### ISSUE TITLE
Time to process

### ISSUE THREAD

**Issue by soltrac** [binance-chain/bsc#103]
Using geth on a local node connected to mainnet, when I call a smart contract, no matter the gas price, it is not validated until 2-3 blocks laters.

Should this work this? I understand is a relay problem or something like that. Same problem happens if I connect via RPC to https://bsc-dataseed.binance.org/ and send the transaction there.

**Comment by guagualvcha** [comment]
hi, it is quite normal to take 6 seconds to be confirmed in the blockchain.  1. The tx propagation needs time. 2. The tx may be not in pool when the validator start mine
