### ISSUE TITLE
Reduce possible fork client not majority warning

### ISSUE THREAD

**Issue by maoueh** [binance-chain/bsc#105]
Would you accept to reduce the amount of time the warning is printed, for example each 10K blocks?

Doing a full sync is annoying when the client is not the majority.

In our fork we added for now

```
	if !snap.isMajorityFork(hex.EncodeToString(nextForkHash[:])) && number%10000 == 0 {
		log.Warn("there is a possible fork, and your client is not the majority. Please check...", "nextForkHash", hex.EncodeToString(nextForkHash[:]))
	}
```

If you agree with such change, I'll provide a PR.

#### System information
BSC 1.0.6

#### Backtrace

````
[backtrace]
````

**Comment by guagualvcha** [comment]
hi, actually the latest code has changed the log level from warning into debug.  Also what you suggest make sense, feel free to submit a pr.
