### ISSUE TITLE
debug_traceCall method not implemented

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [binance-chain/bsc#106]
Why is `debug_traceCall` not implemented? `debug_traceBadBlock`, `debug_traceBlock`, `debug_traceBlockByHash`, `debug_traceBlockByNumber`, `debug_traceTransaction`, etc. are all implemented, quite odd for only this function present within `debug` `namespace` to be excluded? Very important feature to be missing, hopefully this will be added soon.

**Comment by guagualvcha** [comment]
@m-e-r-k-l-e-root  This is a fork of `go-ethereum`, we do not have any plan to implement this in this repo. But we do have a parity version of bsc that carries these APIs, it will be open-sourced soon.
