### ISSUE TITLE
Impossible to get transaction mined on same block in which it was broadcasted

### ISSUE THREAD

**Issue by stephanesanchez** [binance-chain/bsc#107]
Hi there,

I'm broadcasting transactions on BSC but it seems that there is a 2-3 blocks latency between the broadcast and the validation. As an example if I broadcast a transaction on block X it will never be mined before block X+2. I tried very high amount of gas (more than 500gwei) but that doesn't help. 
I allocate 32GB of RAM to GETH and my internet connection is very fast. 

Is that normal behaviour of BSC or am I missing something?

#### System information

Geth version: 1.0.6
OS & Version: OSX

**Comment by guagualvcha** [comment]
Hi, @stephanesanchez  it is not about gas price. Usually, the validator is protected by a sentry node, the transactions need at least two hoops to validators. It is expected behaviors.

**Comment by zhouhaw** [comment]
> Hi, @stephanesanchez it is not about gas price. Usually, the validator is protected by a sentry node, the transactions need at least two hoops to validators. It is expected behaviors.

what's meanings of two hoops?

**Comment by zhouhaw** [comment]
> Hi, @stephanesanchez it is not about gas price. Usually, the validator is protected by a sentry node, the transactions need at least two hoops to validators. It is expected behaviors.

@guagualvcha  what's meanings of two hoops?  under this circumstances, some frontrun tx will failed?
