### ISSUE TITLE
BSC full node running

### ISSUE THREAD

**Issue by gongyaodon** [binance-chain/bsc#108]
hi, folks

after running full node, there's tons of warnning msgs like this:
"
    t=2021-03-10T09:59:29+0800 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=fc3ca6b7
t=2021-03-10T09:59:29+0800 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=fc3ca6b7
t=2021-03-10T09:59:29+0800 lvl=info msg="Imported new chain segment"          blocks=392   txs=2427 mgas=297.032 elapsed=3.902s    mgasps=76.121  number=471635 hash=0x8c50ba4eec4e95a42a5ec841bc245b8c3578cc4686646d31eadf21c238368ccd 
age=5mo3w5d   dirty="16.58 MiB"
t=2021-03-10T09:59:29+0800 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=fc3ca6b7
t=2021-03-10T09:59:29+0800 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=fc3ca6b7
t=2021-03-10T09:59:29+0800 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=fc3ca6b7
t=2021-03-10T09:59:29+0800 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=fc3ca6b7
"

#### System information

Geth version: `1.0.6`
OS & Version: centos
Commit hash : (if `develop`)

````

**Comment by guagualvcha** [comment]
hi @gongyaodon  sorry for the trouble. Just download the latest binary or build from the latest source code, the noisy log won't come up again.
