### ISSUE TITLE
Offline state pruning to reduces disk usage

### ISSUE THREAD

**Issue by barryz** [binance-chain/bsc#109]
Hi team,

Geth 1.10 introduces a new feature, [Offline state pruning](https://blog.ethereum.org/2021/03/03/geth-v1-10-0/#), which significantly reduces disk usage.

Does BSC have any plans to introduce this exciting feature?

**Comment by guagualvcha** [comment]
@barryz  Thanks for the remind.  Geth v1.10.0 does have many features that we are interested in,  we are testing the offline state prune tool, hope can release it a few days later.
