### ISSUE TITLE
Full Node Synced, But Can't Call RPC?

### ISSUE THREAD

**Issue by taschh** [binance-chain/bsc#110]
Hi there,

After days of sync'ing, I was finally able to sync up to the most recent block, but is there something additional that needs to be done before I can call the full node from metamask on a different computer?  I tried to put in the server IP address and it doesn't work.  Looked through Binance's help docs but it doesn't have any additional info on what to do after sync finishes.  Any help would be greatly appreciated!

**Comment by guagualvcha** [comment]
No extra setup is needed to visit the RPC endpoints. Can you test the network connection from your desktop to the VM?

**Comment by taschh** [comment]
Yeah I tried to set the server IP address as the URL in metamask under New RPC URL (i.e. http://244.244.244.1) and it kept throwing an error when trying to save.

I'm starting geth with:

nohup geth --config ./config.toml --datadir ./node --pprofaddr {server_IP_address} --metrics --pprof &

in bsc.log, it keeps importing new chain segment where block height finally caught up to the current block.  Not sure what else to do.

**Comment by jazzandrock** [comment]
Yes, I got the same problem. I followed the tutorial: https://docs.binance.org/smart-chain/developer/fullnode.html and waited till it synchronizes all blocks. When I connect to the RPC, it detects `chainId` correct, but `blockNumber` is zero, and all transactions that I try to call revert (I call only view methods). When I try to hardcode blockNumber in method calls, it laments about missing trie nodes, although trie nodes not missing was the whole point of running a full node myself.

**Comment by sai-voiddev** [comment]
@jazzandrock you should wait until states are fully synced

**Comment by jazzandrock** [comment]
@sai-voiddev Thanks for reply. Indeed, it synced all the blocks but I see a lot of `Imported new block headers` in the logs. I'll leave it syncing for a couple of days or longer, and if it will work, I'll write here how long did I have to wait.

**Comment by jazzandrock** [comment]
Oh my god, it stopped logging `Imported new state entries`, now just `Imported new block headers` with latest block number. But still when connecting to rpc, it gives `blockNumber` 0. What did I do wrong

**Comment by dsbaars** [comment]
What does it say when you attach through the IPC socket?  `./geth attach --datadir node`
Is the response on `eth.syncing` false?

**Comment by jazzandrock** [comment]
@dsbaars no, it says:
```
> eth.syncing
{
  currentBlock: 6101653,
  highestBlock: 6101743,
  knownStates: 66144870,
  pulledStates: 66144457,
  startingBlock: 6091067
}
```
I'm launching it with
```bash
geth --config ./config.toml --datadir ./node -unlock $ADDRESS --password password.txt  --mine --gcmode archive --allow-insecure-unlock  --pprofaddr 0.0.0.0 --metrics --pprof
```

**Comment by edmundhillary** [comment]
+1 on this. Two nodes, with currentBlock's about 100 blocks behind no matter what. Been syncing for over a week. Block 0 makes sense because it's not caught it, but it's 'never' caught up.

**Comment by dsbaars** [comment]
Like for the Ethereum blockchain, it seems you really need a SSD. A traditional Hard Disk is not able to keep with the amount of blocks. The only two systems I got in sync got a NVMe SSD (SAMSUNG 970 EVO PLUS 1TB)
 and sometimes it still gets 2 blocks behind.

**Comment by osizadmin** [comment]
+1 we have used AWS EC2 instance with SSD. 

> eth.syncing;
{
  currentBlock: 7766816,
  highestBlock: 7766915,
  knownStates: 12890150,
  pulledStates: 12880772,
  startingBlock: 7588625
}

Current block showing 100 block difference in highestBlock. Kindly advice us how to resolve this issue.

**Comment by erickcrus** [comment]
Can someone tell how many states we currently have? Mine is on 310474586

**Comment by AlexWD** [comment]
Also seeing this issue.

**Comment by maxilang11** [comment]
> Can someone tell how many states we currently have? Mine is on 310474586

@erickcrus did you get synced after all? If yes, how many state entries was the upper bound for you?

**Comment by francoispqt** [comment]
I had a synced node but I wanted to restart from a fresh node with the 1.10 beta version and it's been syncing for 3 days and it's not able to get fully synced. It's running on a cloud provider VPS with 8vCore 16GB of RAM and 640GB SSD NVMe.

It gets close to highest block but never manages to reach it and it seems it never reaches full sync state.

```> eth.syncing
{
  currentBlock: 7341749,
  highestBlock: 7341843,
  knownStates: 349269732,
  pulledStates: 349159109,
  startingBlock: 7327391
}
> eth.blockNumber
0
```

I tested the disk performance and it can do 20k IOPS and 80 MB/s. Network bandwidth is at 2GB/s.

Does any know how many states there are and if I'm far from it? What could be the bottleneck in my setup?

**Comment by felipecsl** [comment]
Same issue here with an EBS gp2 SSD volume, can only get to about 100 blocks of `highestBlock`

**Comment by DefiDebauchery** [comment]
@felipecsl - From experience (of mine, and others in various threads), this usually means you don't have enough IOPS. A normal SSD doesn't do it anymore, you need speed equivalent to NVMe.

Would be nice to get a specific "minimum IOPS" metric, but I am not sure if anyone has been able to run a fullnode on AWS.

**Comment by felipecsl** [comment]
@DefiDebauchery thanks, yeah that's super helpful. Was kinda my suspicion. I tried initially with a `c1.2xlarge` and failed. Trying now with a `m6g.2xlarge` but I suspect I might run into the same problem.

**Comment by DefiDebauchery** [comment]
@felipecsl

>  Trying now with a `m6g.2xlarge` but I suspect I might run into the same problem.

 Correct. The issue likely isn't the EC2 specs (though I'm not sure what a c1.x2xlarge has), but rather the performance of the EBS. When I was looking at calculators, it seemed prohibitively expensive to match the IOPS of genuine NVMe. You'd be better off owning the hardware at that point.

**Comment by felipecsl** [comment]
Yup, the on demand price for a storage optimized `i3.2xlarge` (8 cores, NVMe SSD) is $0.624 (~$450/month) which is basically prohibitive, as you pointed out. Maybe I should give up on the idea of running this on AWS altogether 😅

**Comment by gongyaodon** [comment]
So.. up to now, approximatively。。。。how many is the known state if fully synced?

**Comment by doplumi** [comment]
I'm having this issue too
Why would it do 800k blocks in 8 hours 100k/hour and then lack behind 100 blocks forever?
Does it switch to a different kind of sync for the latest blocks?

**Comment by sorokousov** [comment]
It took about a day after the node was launched. 
Current block: 8,776,558
Processed state: 431,927,412

I measured the states update rate at the current state, about 2,000,000 per hour.
VPS: 6 vCPU Cores | 16 GB RAM | 400 GB SSD | 400 Mbit/s Port
https://contabo.com/en/vps/vps-m-ssd/?image=ubuntu.267&qty=1&contract=1

While the speed is good, I must catch up)))

**Comment by lovelyrrg51** [comment]
Hi, @sorokousov 
currently, 400GB is enough?
I've tried 2TG but during the 2 weeks, it's full-charged now.
No way to resolve it?
Thanks.

**Comment by guagualvcha** [comment]
closing this issue, please refer to https://github.com/binance-chain/bsc/issues/338
