### ISSUE TITLE
Out of memory (with 64GB RAM)

### ISSUE THREAD

**Issue by koen84** [binance-chain/bsc#122]
#### System information

Geth version: https://github.com/binance-chain/bsc/releases/download/v1.0.6/geth_linux
OS & Version: Ubuntu 18.04 LTS

#### Expected behaviour
BSC completes startup

#### Actual behaviour
BSC crashloops

#### Steps to reproduce the behaviour
On my 2nd server i've got this issue, unlike my primary server.  There's 64GB RAM in this server (128GB in the primary.)

#### Backtrace

See file 
[bsc_outofmemory.txt](https://github.com/binance-chain/bsc/files/6186447/bsc_outofmemery.txt)

**Comment by guagualvcha** [comment]
@koen84  thanks for reporting this. If it is reproducible, can you do `curl -sK -v http://localhost:6060/debug/pprof/heap > heap.out` to get the heap dump? (6060 is the metrics port, please change according to your config)

**Comment by dsbaars** [comment]
Can you show your `config.toml` and the head of your log? Might help us to know how much cache geth is trying to use.

**Comment by koen84** [comment]
I started fresh, using a different backup.  If relevant i can still check those things, but that error state was cleared.

**Comment by guagualvcha** [comment]
fixed in https://github.com/binance-chain/bsc/pull/190, closing this.
