### ISSUE TITLE
cpu spiking 100% 

### ISSUE THREAD

**Issue by eyooooo** [binance-chain/bsc#128]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`

geth@GETH:~$ ./geth_linux version
Geth
Version: 1.0.7
Git Commit: f1d92bef016d2d0bd3aa71b6be417da2ff80400d
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=/usr/lib/golang

OS & Version: Windows/Linux/OSX

geth@GETH:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Commit hash : (if `develop`)

#### Expected behaviour

pulling transactions from getBlocks() and then iterating over them to get transactions receipts should not spike cpu to 100% or take a significantly long time.

#### Actual behaviour

cpu spikes to 100%, all wss connections lag

#### Steps to reproduce the behaviour

get transactions from getBlocks and iterate over those with getTransactionReceipt and cpu goes byebye

#### Backtrace

````
[backtrace]
````

**Comment by guagualvcha** [comment]
hi, @eyooooo I believe the CPU spike is expected, `get receipts` is really CPU consuming. We have done the following improvement to get better performance:
1.  cache the receipts of recent 10000  blocks.  https://github.com/binance-chain/bsc/pull/130
2.  provide batch API for get receipts: https://github.com/binance-chain/bsc/pull/115
You may try the batch API, but if you iterate receipts over all history blocks, I believe the CPU will be still high.
