### ISSUE TITLE
[ERROR] `Block receipts missing, can't freeze` should fix

### ISSUE THREAD

**Issue by jingniao** [binance-chain/bsc#129]
log show 
```
Block receipts missing, can't freeze     number=6104216 hash=42cd3b…38d3e9
```
this is a know issue and is fixed in `geth`
https://github.com/ethereum/go-ethereum/issues/20239
https://github.com/ethereum/go-ethereum/pull/21045

**Comment by lichangshu** [comment]
me too ! docker run Version: 1.11.18-stable
ERROR [04-13|08:15:03.158] Block receipts missing, can't freeze     number=10500842 hash="40591e…ff9907" ,

**Comment by lichangshu** [comment]
> me too ! docker run Version: 1.11.18-stable
> ERROR [04-13|08:15:03.158] Block receipts missing, can't freeze number=10500842 hash="40591e…ff9907" ,

I found that I had synced to the latest block, console prints logs all the time, Is there any underlying problem?

**Comment by z-hao-wang** [comment]
this geth pr (https://github.com/ethereum/go-ethereum/pull/21045/files) doesn't seem to fix this issue

**Comment by longhoangwkm** [comment]
I got a same error too

**Comment by 7-of-9** [comment]
+1

**Comment by guagualvcha** [comment]
On track in release v1.1.8

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
