### ISSUE TITLE
syncing won't start 

### ISSUE THREAD

**Issue by jason12343** [binance-chain/bsc#131]
#### System information
Version: 1.0.7
Git Commit: 46d185b4cfed54436f526b24c47b15ed58a5e1bb
Git Commit Date: 20210403
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.16.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
#### Expected behaviour
start to running 

#### Actual behaviour
got stuck 

#### Steps to reproduce the behaviour
fisrt time to sync
geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof

#### Backtrace

````
[backtrace]
INFO [04-05|13:07:56.464] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [04-05|13:07:56.465] Starting Geth on Ethereum mainnet...
INFO [04-05|13:07:56.465] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [04-05|13:07:56.465] Sanitizing cache to Go's GC limits       provided=4096 updated=2606
INFO [04-05|13:07:56.465] Enabling metrics collection
INFO [04-05|13:07:56.471] Maximum peer count                       ETH=30 LES=0 total=30
INFO [04-05|13:07:56.471] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"



i follow the full node set-up document on bsc site , it got stuck on this , won't start properly . any help would be great.

**Comment by jason12343** [comment]
got it , found old issue related to this .

**Comment by shivhg** [comment]
What was the fix @jason12343 ?

**Comment by jason12343** [comment]
@shivhg delete log config line (last few lines)in the toml file
