### ISSUE TITLE
got checksum mismatch while make geth

### ISSUE THREAD

**Issue by xiaoyu1998** [binance-chain/bsc#132]
go: downloading github.com/btcsuite/btcd v0.20.0-beta
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
	downloaded: h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
	go.sum:     h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=

**Comment by guagualvcha** [comment]
`github.com/btcsuite/btcd` has ever drafted release  `v0.20.0-beta` and then delete it. If you have any repo refer to `github.com/btcsuite/btcd` may have above issue, you can try remove the `github.com/btcsuite/btcd` repo under your `$GOPATH/pkg/mod` to fix this.

**Comment by xiaoyu1998** [comment]
ok thanks! please check line no. 36 in go.sum , I have update this line ,and its ok now.
