### ISSUE TITLE
[Question] What is the payment URI format for BSC?

### ISSUE THREAD

**Issue by gituser** [binance-chain/bsc#134]
Hi there,

I'm wondering what is the payment format URI for BSC is?

For ethereum it's: `ethereum:<address>?amount=XXX`

or there is an integration in metamask to automatically open your wallet with prefilled data (destination address, amount, etc): https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3

Is there the same feature for BSC?

If so how to use it?

Thanks.

**Comment by dsbaars** [comment]
See [EIP-861](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md). The chain ID of BSC is 56 so it should work when you append `@56` to the wallet address, like this:
`ethereum:0x775a694b4bD33bAB2a22C198E56d8aEa502CF067@56`

**Comment by gituser** [comment]
@dsbaars thank you!
