### ISSUE TITLE
Sync block error  NewPendingTransactionFilter

### ISSUE THREAD

**Issue by jin10086** [binance-chain/bsc#135]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth
Version: 1.0.6
Git Commit: e55e9cdd76d3b1716cdc65bec955e829a982a776
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=/usr/lib/golang

#### Sync block error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4879a7]

goroutine 72720662 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter.func1(0xc040441140, 0xc044c3eb40, 0xc0e6d1c5d0, 0xc00452c870)
	/server/bsc/eth/filters/api.go:119 +0x1bd
created by github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewPendingTransactionFilter
	/server/bsc/eth/filters/api.go:115 +0x1bb

**Comment by guagualvcha** [comment]
Hi, this is fixed in latest release.
