### ISSUE TITLE
Error in ganache fork

### ISSUE THREAD

**Issue by rayeaster** [binance-chain/bsc#136]
Hello, could someone shed a light why we get following error in ganache fork for Binance Smart Chain ? 
`Error: Returned error: missing trie node`

Typically the fork would work after a new instance is launched, but after a while (not sure how many blocks/tx mined), the it will start throw this error. We use rpc endpoint as listed in https://docs.binance.org/smart-chain/developer/rpc.html

this is how we launch the local fork: 
`ganache-cli --fork https://bsc-dataseed1.ninicoin.io --chainId 56 -p 8548 --host 0.0.0.0 --defaultBalanceEther 100000 --db /data/bscfork/database`

Really appreciate the insight.

**Comment by dsbaars** [comment]
Did you try other JSON-RPC endpoints? My guess is that BSC mainnet is more different from Ethereum than ganache can handle.

**Comment by guagualvcha** [comment]
`Error: Returned error: missing trie node` from the error, the ganache is query history state, while the public nodes are not running in archive mode.
