### ISSUE TITLE
BSC problems

### ISSUE THREAD

**Issue by vladigor777** [binance-chain/bsc#137]
Hello. Could you help me please. I use this code:
sudo geth --datadir node init genesis.json
sudo geth --config ./config.toml --datadir ./node -pprof.addr 0.0.0.0 --metr
ics --pprof

But i get Fatal: ./config.toml, line 58: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields

If i comment this field, when i start my node i get error 

WARN [04-07|13:29:53.541] Synchronisation failed, dropping peer    peer=301f7717933b021ec4087484c37497ae6665014c3bcd4d02bc795832426cf7a9 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"

Help me please, I don't know how to solve it.

**Comment by dsbaars** [comment]
Please post your full `config.toml` and the version of the `geth` client, your OS and CPU architecture. We have not enough information now to help you. Also, is this the only peer dropping? You can check connected peer count with  `admin.peers.length`

**Comment by vladigor777** [comment]
@dsbaars 

[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000

Lifetime = 10800000000000


[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]
#GraphQLPort = 8557
GraphQLVirtualHosts = ["*"]

[Node.P2P]
MaxPeers = 30
NoDiscovery = false
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

#[Node.LogConfig]
#FilePath = "bsc.log"
#MaxBytesSize = 10485760
#Level = "info"
#FileRoot = ""

 geth VERSION:
   1.10.1-stable-c2d2f4ed
   
    total        used        free      shared  buff/cache   available
Mem:           31Gi       205Mi        30Gi       0.0Ki       683Mi        30Gi

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 2494.080
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes

**Comment by vladigor777** [comment]
> admin.peers.length
2
> admin.nodeInfo

{
  enode: "enode://7124791aaae5396e3861d5437eb39392ac7d601592e247f124590be630c29ca6c36864f0afea781c7f528a453fea7b685823a9684f2721479e317f5e019455f2@138.68.86.198:30311",
  enr: "enr:-J24QDdMnSmF8LdRWUKlceUhxrvmOVJtbKzpCh_51frOuz_ANmQKaWCsDaD3lni3F5Lu6ocYwiOI92YphEE4lYXizp4Ig2V0aMfGhD8umuSAgmlkgnY0gmlwhIpEVsaJc2VjcDI1NmsxoQJxJHkaquU5bjhh1UN-s5OSrH1gFZLiR_EkWQvmMMKcpoRzbmFwwIN0Y3CCdmeDdWRwgnZn",
  id: "6dc53e10d69a5ce5ed85676929cf71d71f5740e0a242fbbb8fed4c8b221f11d9",
  ip: "138.68.86.198",
  listenAddr: "[::]:30311",
  name: "Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16",
  ports: {
    discovery: 30311,
    listener: 30311
  },
  protocols: {
    eth: {
      config: {
        byzantiumBlock: 0,
        chainId: 56,
        constantinopleBlock: 0,
        eip150Block: 0,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0,
        istanbulBlock: 0,
        muirGlacierBlock: 0,
        petersburgBlock: 0
      },
      difficulty: 1,
      genesis: "0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b",
      head: "0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b",
      network: 56
    },
    snap: {}
  }
}

@dsbaars

**Comment by vladigor777** [comment]
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  996K  3.2G   1% /run
/dev/vda1       582G  3.4G  578G   1% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/vda15      105M  9.2M   96M   9% /boot/efi
/dev/loop0       31M   31M     0 100% /snap/snapd/9607
/dev/loop1       56M   56M     0 100% /snap/core18/1885
/dev/loop2       71M   71M     0 100% /snap/lxd/16922
/dev/loop3       33M   33M     0 100% /snap/snapd/11588
/dev/loop4       56M   56M     0 100% /snap/core18/1997
/dev/loop5       71M   71M     0 100% /snap/lxd/19647
tmpfs           3.2G     0  3.2G   0% /run/user/0
/dev/loop6      100M  100M     0 100% /snap/core/10958
/dev/loop7      129M  129M     0 100% /snap/geth/477

**Comment by vladigor777** [comment]
When node works, 
> admin.peers.length
0
> admin.peers.length
2
> admin.peers.length
1
> admin.peers.length
1
> admin.peers.length
0

**Comment by vladigor777** [comment]
WARN [04-13|08:56:58.477] Invalid header encountered               number=1       hash="040553…2ad0f6" parent="0d2184…d57b5b" err="extra-data too long: 97 > 32"
WARN [04-13|08:56:58.478] Synchronisation failed, dropping peer    peer=301f7717933b021ec4087484c37497ae6665014c3bcd4d02bc795832426cf7a9 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
ERROR[04-13|08:56:58.478] Ethereum peer removal failed             peer=301f7717 err="peer not registered"
INFO [04-13|08:57:02.367] Looking for peers                        peercount=1 tried=87  static=23
INFO [04-13|08:57:09.088] Imported new state entries               count=273 elapsed="4.474µs"   processed=62827 pending=4369  trieretry=0 coderetry=0 duplicate=0 unexpected=0
INFO [04-13|08:57:09.126] Imported new state entries               count=384 elapsed="1.78µs"    processed=63211 pending=10499 trieretry=0 coderetry=0 duplicate=0 unexpected=0
WARN [04-13|08:57:09.145] Invalid header encountered               number=1       hash="040553…2ad0f6" parent="0d2184…d57b5b" err="extra-data too long: 97 > 32"
WARN [04-13|08:57:09.145] Synchronisation failed, dropping peer    peer=6c7bc767b533972a12b605c1f086c6503df257cb91296bed6faaae3dcc2ef5a8 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
ERROR[04-13|08:57:09.145] Ethereum peer removal failed             peer=6c7bc767 err="peer not registered"
INFO [04-13|08:57:12.398] Looking for peers

**Comment by vladigor777** [comment]
i solve it

**Comment by zhangyanhuivv** [comment]
> i solve it

same issue, how to salve it?

**Comment by dtx** [comment]
how did you solve this?

**Comment by dtx** [comment]
got it 
```
from web3.middleware import geth_poa_middlewar
from web3 import Web3
my_provider = Web3.HTTPProvider('https://data-seed-prebsc-1-s1.binance.org:8545')
w3 = Web3(my_provider)
w3.middleware_onion.inject(geth_poa_middleware, layer=0)
w3.eth.get_block(8715542) #should now work
```

**Comment by Tushar13kohli** [comment]
Is there a way to get a list of peers I can connect to in BSC?

**Comment by fastener** [comment]
> i solve it

i have same question, can you tell me  how to do

**Comment by WB-Expert5007** [comment]
> Hello. Could you help me please. I use this code: sudo geth --datadir node init genesis.json sudo geth --config ./config.toml --datadir ./node -pprof.addr 0.0.0.0 --metr ics --pprof
> 
> But i get Fatal: ./config.toml, line 58: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields
> 
> If i comment this field, when i start my node i get error
> 
> WARN [04-07|13:29:53.541] Synchronisation failed, dropping peer peer=301f7717933b021ec4087484c37497ae6665014c3bcd4d02bc795832426cf7a9 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
> 
> Help me please, I don't know how to solve it.

Hi, First of all, I hope you are in good health.
I have same error.
Could you tell me how did you solve this problem?
I am looking forward to your reply.
Best Regards.

**Comment by WB-Expert5007** [comment]
> how did you solve this?

Hi, First of all, I hope you are in good health.
I have same error.
Could you tell me how did you solve this problem?
I am looking forward to your reply.
Best Regards.
