### ISSUE TITLE
Connection between BSC and Metamask?

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#141]
Hi,
Trying to connect private network of binance smart chain to metamask.
The given RPC and chain id is: 'http://<ip_address>:30303' & 'chain-id: 1000'
But it results "Could not fetch chain id. Is your RPC URL correct?"

Node information of BSC private chain:
> admin.nodeInfo
{
  enode: "enode://a05c38511321e3977c43eb20fbf303882f8edc813b1fbf61587ce8ee33cf8e81ef82800cd37d0870f563cd1c14720280765382e8e3b7fba1ed8387bd264bbee3@<ip_address>:30303?discport=1690",
  enr: "enr:-KW4QEwGgvJDwwgSfRS0UzdHU9BvJMPlGUp6Tu94TzBq3RVyOPW6SWGBhKhcNAQqiBoIzeqF_wwZ1NDXrkhjCguB9r8Vg2V0aMfGhMpEplKAgmlkgnY0gmlwhHX-vXOJc2VjcDI1NmsxoQOgXDhREyHjl3xD6yD78wOIL47cgTsfv2FYfOjuM8-OgYRzbmFwwIN0Y3CCdl-DdWRwggaahHVkcDaCdl8",
  id: "ebc37fa9ebfd5de3995184dd139982af6bced1cc7c7c0bfaf1247ae7d4101d72",
  ip: "<ip_address>",
  listenAddr: "[::]:30303",
  name: "Geth/v1.10.1-stable-c2d2f4ed/linux-amd64/go1.16",
  ports: {
    discovery: 1690,
    listener: 30303
  },
  protocols: {
    eth: {
      config: {
        chainId: 1000,
        eip150Block: 0,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0
      },
      difficulty: 1642153270,
      genesis: "0xacdfa62d82249dfeaad52d08be1098eeb9d630060e842bfc42b916ff887365e9",
      head: "0x6319e65e13d054c185745b4562dff5c8838b34c8d980fc8655d539f4eafb9881",
      network: 1000
    },
    snap: {}
  }
}

#### System information
Geth version: `1.10.1-stable`
OS & Version: Linux

Any solution?

**Comment by dsbaars** [comment]
It's not port 30303, its 8545 (RPC port). Also chain ID should be 56 for mainnet. Port 30303 is for communication between peers.

**Comment by osiz-blockchainapp** [comment]
> It's not port 30303, its 8545 (RPC port). Also chain ID should be 56 for mainnet. Port 30303 is for communication between peers.

I am connecting private network of BSC and chain ID is 1000.
Chain ID 56 used for mainnet.

**Comment by dsbaars** [comment]
> I am connecting private network of BSC and chain ID is 1000.

Does not change the fact that you are using the wrong port for RPC communication. Execute `geth dumpconfig` and look for `HTTPPort`. If you did not override it, it should be 8545.

**Comment by osiz-blockchainapp** [comment]
> > I am connecting private network of BSC and chain ID is 1000.
> 
> Does not change the fact that you are using the wrong port for RPC communication. Execute `geth dumpconfig` and look for `HTTPPort`. If you did not override it, it should be 8545.

Executed 'geth dumpconfig' command. The HTTPPort is 8545.
But My network id is 1.
Here is my screenshot
![Screenshot from 2021-04-10 19-05-29](https://user-images.githubusercontent.com/48212011/114271669-24b6ce80-9a30-11eb-8a23-287a8d243f94.png)

**Comment by tyntyn1** [comment]
https://github.com/binance-chain/bsc/issues/141#issue-855043618

**Comment by koen84** [comment]
Is the BSC node running on the same computer as where your metamask is ?  Otherwise your URL is incorrect.  And you might need to check access / bind for RPC.
