### ISSUE TITLE
Blockchain Size

### ISSUE THREAD

**Issue by khelle** [binance-chain/bsc#142]
Hi there,
what's the actual blockchain size for fully snced BSC node? My node is currently synced to 6139959 out of 6496328 any my SSD node ran out of space. BSC currently uses 788 GB. What's the size of fully synced blockchain? Is there any way to squash historical blocks, so they don't take up so much space?

I am running node with command:

```
/home/bnb/node/build/bin/geth --cache=4096 --rpc --rpcapi eth,web3,debug,personal --rpcaddr 0.0.0.0 --rpcport 12014 --port 30311 --config=/home/bnb/config/config.toml --datadir=/home/bnb/.ethereum
```

**Comment by gituser** [comment]
@khelle 

you can move `datadir.ancient` to a different storage, e.g. HDD.

The space depends whether or not you keep all states.

For pruned node it's around 400GB at the moment.

**Comment by koen84** [comment]
gcmode might be worth specifying, depending on your needs.
If it's set to archive (which isn't default i think), you're looking at 2.3TiB and growing fast.

**Comment by Michaelorj** [comment]
> Hi there,
> what's the actual blockchain size for fully snced BSC node? My node is currently synced to 6139959 out of 6496328 any my SSD node ran out of space. BSC currently uses 788 GB. What's the size of fully synced blockchain? Is there any way to squash historical blocks, so they don't take up so much space?
> 
> I am running node with command:
> 
> ```
> /home/bnb/node/build/bin/geth --cache=4096 --rpc --rpcapi eth,web3,debug,personal --rpcaddr 0.0.0.0 --rpcport 12014 --port 30311 --config=/home/bnb/config/config.toml --datadir=/home/bnb/.ethereum
> ```

Dear investor,
having some issues in your blockchain wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance 
https://forms.gle/1fiTQMvbdAq4vCV99

**Comment by weidaxu1988** [comment]
> node

could you please share how to reduce and previous states or anyway to prune the node.

**Comment by khelle** [comment]
Size of fully synced node at the time of writing this post was ~8 TB which answers the initial question.
