### ISSUE TITLE
Trying to sync new node and getting bunch of error and warning. 

### ISSUE THREAD

**Issue by safestarme** [binance-chain/bsc#146]
Hi there,

Trying to start new node BSC chain id 56 and not syncing or syncing very slow due to poor connection to peers 

Most common errors:
"peer connected on snap without compatible eth support"
"peer not registered"
"retrieved hash chain is invalid: extra-data too long: 97 > 32"

Did everything like described on https://docs.binance.org/smart-chain/developer/fullnode.html 

Config chain id 56.

Is it normal that it can connect to more than 3-4 peers?

ERROR[04-14|09:23:28.578] Snapshot extension registration failed   peer=3af25a30 err="peer connected on snap without compatible eth support"
WARN [04-14|09:23:32.778] Node data write error                    err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
WARN [04-14|09:23:32.778] Synchronisation failed, retrying         err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:23:38.434] Looking for peers                        peercount=1 tried=64  static=23
ERROR[04-14|09:23:42.285] Snapshot extension registration failed   peer=35ba3061 err="peer connected on snap without compatible eth support"
INFO [04-14|09:23:44.133] Imported new state entries               count=273 elapsed="3.401µs"   processed=2261 pending=4369  trieretry=0 coderetry=0 duplicate=0 unexpected=0
WARN [04-14|09:23:44.201] Invalid header encountered               number=1 hash="040553…2ad0f6" parent="0d2184…d57b5b" err="extra-data too long: 97 > 32"
WARN [04-14|09:23:44.201] Synchronisation failed, dropping peer    peer=301f7717933b021ec4087484c37497ae6665014c3bcd4d02bc795832426cf7a9 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
ERROR[04-14|09:23:44.201] Ethereum peer removal failed             peer=301f7717 err="peer not registered"
INFO [04-14|09:23:49.155] Looking for peers                        peercount=1 tried=103 static=23
WARN [04-14|09:23:56.413] Node data write error                    err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:23:56.413] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=0.00B throttle=8192
WARN [04-14|09:23:56.413] Synchronisation failed, retrying         err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:23:59.203] Looking for peers                        peercount=2 tried=79  static=23
INFO [04-14|09:24:07.040] Imported new state entries               count=273 elapsed="2.835µs"   processed=2534 pending=4369  trieretry=0 coderetry=0 duplicate=0 unexpected=0
INFO [04-14|09:24:07.087] Imported new state entries               count=384 elapsed="1.341µs"   processed=2918 pending=10513 trieretry=0 coderetry=0 duplicate=0 unexpected=0
INFO [04-14|09:24:07.128] Imported new state entries               count=384 elapsed="2.745µs"   processed=3302 pending=16657 trieretry=0 coderetry=0 duplicate=0 unexpected=0
WARN [04-14|09:24:07.158] Invalid header encountered               number=1 hash="040553…2ad0f6" parent="0d2184…d57b5b" err="extra-data too long: 97 > 32"
INFO [04-14|09:24:07.163] Imported new state entries               count=384 elapsed="1.74µs"    processed=3686 pending=21163 trieretry=0 coderetry=0 duplicate=0 unexpected=0
WARN [04-14|09:24:07.164] Synchronisation failed, dropping peer    peer=9e4ade9cf8c478d9d367fd3c43366bb4919ed235b73e3510e41924a3908fe3d5 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
ERROR[04-14|09:24:07.164] Ethereum peer removal failed             peer=9e4ade9c err="peer not registered"
INFO [04-14|09:24:09.331] Looking for peers                        peercount=1 tried=31  static=23
INFO [04-14|09:24:19.341] Looking for peers                        peercount=1 tried=103 static=23
WARN [04-14|09:24:20.303] Node data write error                    err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
WARN [04-14|09:24:20.303] Synchronisation failed, retrying         err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:24:29.486] Looking for peers                        peercount=1 tried=27  static=23
WARN [04-14|09:24:33.358] Node data write error                    err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
WARN [04-14|09:24:33.358] Synchronisation failed, retrying         err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:24:39.917] Looking for peers                        peercount=1 tried=79  static=23
WARN [04-14|09:24:45.574] Node data write error                    err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
WARN [04-14|09:24:45.574] Synchronisation failed, retrying         err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:24:50.452] Looking for peers                        peercount=3 tried=63  static=23
WARN [04-14|09:24:57.878] Node data write error                    err="trie node 15216a…30a83c failed with all peers (1 tries, 1 peers)"
INFO [04-14|09:24:57.878] Downloader queue stats                   receiptTasks=0 blockTasks=0 itemSize=0.00B throttle=8192

Thanks

**Comment by guagualvcha** [comment]
`geth --datadir node init genesis.json` did you do the above step before starting the nodes?

**Comment by safestarme** [comment]
Yes, I had config pointing to chain id 56 
Looks like it is not connecting to more than 2-4 piers and syncing only few blocks

**Comment by Alexei-P** [comment]
Also have the same issue :( All is fine with testnet, but can't sync from 0 in mainnet

**Comment by guagualvcha** [comment]
hi, all node syncing issue redirect to https://github.com/binance-chain/bsc/issues/338. And fast sync from genesis is not suggested now, please download the latest snapshot from. https://github.com/binance-chain/bsc-snapshots
