### ISSUE TITLE
use april chaindata snapshot,an error occurred when I started synchronization

### ISSUE THREAD

**Issue by wemem** [binance-chain/bsc#154]
Hi there,
I download april chaindata snapshot,extract the data,then i start sync
```
./geth --config ./config.toml  --rpcport 9545 --port 30304  --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof
```
logs
![image](https://user-images.githubusercontent.com/11549225/115174265-84317000-a0fb-11eb-89a8-b82b56e26c61.png)
 btw,There's no problem with the March chaindata snapshot

**Comment by huangsuyu** [comment]
hello, @wemem 

The snapshot data is updated now, please try again

https://docs.binance.org/smart-chain/developer/snapshot.html 

Thanks!

**Comment by wemem** [comment]
@huangsuyu 
The latest snapshot  data was used
logs
![image](https://user-images.githubusercontent.com/11549225/115395904-fa76c500-a216-11eb-9650-21d035535c68.png)

Does this synchronize normally?

**Comment by HaoyangLiu** [comment]
Could you try `eth.syncing` for more times? Then check if the returned message is changed?

**Comment by wemem** [comment]
@HaoyangLiu It took a day, and now it's synchronized.

**Comment by maurodelazeri** [comment]
@huangsuyu is this snapshot the achieve data? or just the headers ?

what is the current size of the full archive node?

**Comment by huangsuyu** [comment]
> @huangsuyu is this snapshot the achieve data? or just the headers ?
> 
> what is the current size of the full archive node?

this is a chain data from fast sync

**Comment by wemem** [comment]
today,I find highestBlock backward, knownStates is 0 and pulledStates is 0
![image](https://user-images.githubusercontent.com/11549225/115811373-2619cb00-a422-11eb-9cf2-d3bdc6bb4b31.png)
![image](https://user-images.githubusercontent.com/11549225/115811390-30d46000-a422-11eb-8497-407f06deb205.png)

the highestBlock 500 blocks behind the main network.
