### ISSUE TITLE
How to use ganache-cli to fork the block specified by the main network?

### ISSUE THREAD

**Issue by wemem** [binance-chain/bsc#157]
Hi,I use ganache-cli to fork main network
```
ganache-cli --fork https://bsc-dataseed.binance.org@6727775
```
logs
![image](https://user-images.githubusercontent.com/11549225/115396801-fb5c2680-a217-11eb-94bc-daf0bc27a9cd.png)

**Comment by Wetitpig** [comment]
The block number `6727775` is too old. Only archive nodes would keep the state beyond a certain number of blocks (256? Correct me if I am wrong) Try with a more recent block number to fork.
And by the way this question should be directed to [ganache](https://github.com/trufflesuite/ganache-cli), not this repository.
