### ISSUE TITLE
how configure ssl with binance node

### ISSUE THREAD

**Issue by cryptopapa320** [binance-chain/bsc#166]
how can i setup binance full node with ssl can some one guide

**Comment by DefiDebauchery** [comment]
geth does not have native support for HTTPS. You will need to set up a proxy server - an endpoint that handles your https request and forwards it to geth over the RPC port.

There are various instructions online on how to do it using nginx. Anything you find for "Ethereum" geth will be applicable here.

**Comment by 1b1og-com** [comment]
my wechat is wu4yyy, Let's discuss it together
@DefiDebauchery @cryptopapa320

**Comment by guagualvcha** [comment]
Will closing this, since DefiDebauchery  have answered the question.
