### ISSUE TITLE
config.toml fatal error

### ISSUE THREAD

**Issue by joshuazmiller** [binance-chain/bsc#172]
After following the steps to run a fullnode from [binance.org](https://docs.binance.org/smart-chain/developer/fullnode.html), and compiling everything without problems, I am having an issue with `./config.toml` when trying to start the node on the final step. 

This is my first time attempting to run a node so maybe the documentation is missing a critical step regarding the `config.toml`, or there is something else wrong?

#### System information

Geth version: `1.8.10-stable`
OS & Version: OSX (Big Sur 11.2.3)
Go Version: `go1.10.2`

#### Expected behaviour
Shouldn't crash with fatal error.

#### Actual behaviour
Immediate: 
```
INFO [04-28|12:33:05] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
Fatal: ./config.toml, line 3: field 'NoPruning' is not defined in eth.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth#Config for available fields
```

And with each run I get a different random but similar error, such as the following in the next run:
```
INFO [04-28|12:33:21] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
Fatal: ./config.toml, line 7: field 'TrieTimeout' is not defined in eth.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth#Config for available fields
```

Next run: 
```
INFO [04-28|12:34:10] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
Fatal: ./config.toml, line 20: field 'Locals' is not defined in core.TxPoolConfig, see https://godoc.org/github.com/ethereum/go-ethereum/core#TxPoolConfig for available fields
```

etc.

#### Steps to reproduce the behaviour
Followed the instructions to set up and run a full node from here: [https://docs.binance.org/smart-chain/developer/fullnode.html](https://docs.binance.org/smart-chain/developer/fullnode.html)

Specifically:
1) Build fresh from source code:
```
git clone https://github.com/binance-chain/bsc
# Enter the folder bsc was cloned into
cd bsc
# Compile and install bsc
make geth
```
2) Download config from mainnet: 
```
## mainet
wget   $(curl -s https://api.github.com/repos/binance-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip mainnet.zip
```
3) Write genesis state locally: `geth --datadir node init genesis.json`
4) Try to start the node: `geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof`
5) Encountered fatal error.

#### Other Notes
- Running `geth` command starts geth P2P without issue.
- Solid system and network specs exceeding suggested requirements.

**Comment by guagualvcha** [comment]
The latest version is v1.7.0,  your system info is `1.8.10-stable`, while your go version is `Go Version: go1.10.2`, I know the latest version of geth is `1.10.2`, so is there anything wrong during compile?

**Comment by huangsuyu** [comment]
@joshuazmiller 

the `geth` version is not correct. should be 1.0.7

Did you use the correct binary?

**Comment by koen84** [comment]
The way you've written the start command is sensitive to where you are in you directory structure when running it.  If `ls .` doesn't show `config.toml` and `node` (dir) it'll fail

**Comment by joshuazmiller** [comment]
Thanks guys. I'm sorry I was away for a bit. I will look into getting it to work with your recommendations. I appreciate it. 🙏
