### ISSUE TITLE
On starting full node received: LogConfig' is not defined in node.Config

### ISSUE THREAD

**Issue by zhnedyalkow** [binance-chain/bsc#173]
Hi there,

It seems that there is a change in the config.toml file and it is not documented yet.

#### System information

Geth version: `geth version`
Version: 1.10.2-stable-97d11b01
OS & Version: Windows/Linux/OSX
Ubuntu 18.4
Commit hash : (if `develop`)
97d11b01
#### Expected behaviour

Starting the full node as per steps on documentation

#### Actual behaviour

2 Things:
1) There is an error in the command: geth --config ./config.toml --datadir ./node --**pprofaddr** 0.0.0.0 --metrics --pprof
One of the arguments should be -> 'pprof.addr' instead 'pprofaddr'
2) Throw an error message by executing the aforementioned command: 
Fatal: ./config.toml, line 58: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields

#### Steps to reproduce the behaviour

Go to the official Binance documentation and follow the steps: (https://docs.binance.org/smart-chain/developer/fullnode.html)

#### Backtrace

````
geth --config ./config.toml --datadir ./node --pprof.addr 0.0.0.0 --metrics --pprof
INFO [04-29|09:12:23.478] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [04-29|09:12:23.478] Starting Geth on Ethereum mainnet... 
INFO [04-29|09:12:23.478] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [04-29|09:12:23.478] Enabling metrics collection 
Fatal: ./config.toml, line 58: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields
####:~/Documents/Private-projects/bsc-node$ geth --config ./config.toml --datadir ./node --pprof.addr 0.0.0.0 --metrics --pprof

````

**Comment by huangsuyu** [comment]
the `geth` version is not correct. should be 1.0.7

Did you use the correct binary?

**Comment by guagualvcha** [comment]
Hi, you have to use BSC client, you are using `Ethereum client`, as the version is `1.10.2-stable-97d11b01`

**Comment by zhnedyalkow** [comment]
Hey,

I have follow the documentation steps.

I do not see the reason to close this ticket as it is not solved.

Please have a look here:
https://docs.binance.org/smart-chain/developer/fullnode.html


Br,
Zhi

**Comment by zhnedyalkow** [comment]
Please let me know where it is mentioned that the version should be 1.0.7?

**Comment by havsar** [comment]
Looks like you are using 1.10.x, which is not released yet. The latest version is v1.0.7. It is also written in the official documentation:

```
# Linux
wget  https://github.com/binance-chain/bsc/releases/download/v1.0.7/geth_linux
# MacOS
wget  https://github.com/binance-chain/bsc/releases/download/v1.0.7/geth_mac
```
