### ISSUE TITLE
please help remark the following address as org.com on the explore of bsc

### ISSUE THREAD

**Issue by leverwwz** [binance-chain/bsc#175]
Hi there,
sir, can u help remark the following address as 'biki.com' on the explore named https://bscscan.com/

0x3fdf750fb555583374b26a5ff476abbd7f6e6fb5

just show this address as biki.com on the bsc explore

thank u so much!

**Comment by DefiDebauchery** [comment]
BSCScan has a form used for validating tokens. Please use that; Binance has no control over BSCScan's databases.
