### ISSUE TITLE
How big is the database? Is there any pruning configuration?

### ISSUE THREAD

**Issue by vietthang207** [binance-chain/bsc#176]
Hi bsc team,

I am currently running a full node with --gcmode=full. The database is 1 TB in size, is that expected, or am I doing something wrong? As I have an archive node which only takes 3 TB, and ethereum full node only 600 GB in size.
Is there any pruning configuration, or can I prune it manually?

Thanks in advanced!

**Comment by guagualvcha** [comment]
Hi @vietthang207  we will uprade to v1.10.2, please check https://github.com/binance-chain/bsc/pull/152, after upgrade, we will provide offline prune tools. It will roughly save 200~300G space.

**Comment by Morgon** [comment]
@vietthang207 - Out of curiosity, does that "3 TB" for the archive node include the `ancient` directory? I'm trying to determine whether 2 TB would be sufficient for live data if ancient lived on a different volume

**Comment by DefiDebauchery** [comment]
@vietthang207  - Out of curiosity, does that "3 TB" for the archive node include the ancient directory? I'm trying to determine whether 2 TB would be sufficient for live data if ancient lived on a different volume

**Comment by vietthang207** [comment]
> Hi @vietthang207 we will uprade to v1.10.2, please check #152, after upgrade, we will provide offline prune tools. It will roughly save 200~300G space.

So if my node consumes 1.3 TB, is that normal? The docs said we only need 500GB, so I am doing anything wrong?

**Comment by vietthang207** [comment]
> @vietthang207 - Out of curiosity, does that "3 TB" for the archive node include the ancient directory? I'm trying to determine whether 2 TB would be sufficient for live data if ancient lived on a different volume

Yes, 3 TB include everything, keep in mind that it grows pretty fast.
