### ISSUE TITLE
Transfer BNB on binance smart chain using web3

### ISSUE THREAD

**Issue by shikhars371** [binance-chain/bsc#178]
Hi there,
I am trying to send BNB on binance smart chain using web3, seems like ethereumjs-tx library doesnt support binance smart chain, can you please tell me how to do transaction of BNB over binance smart chain using web3 :

here is my code where i am getting error?

let details = {
                            "to": tokenresp.owner,
                            "value": web3.utils.toHex(Web3.utils.toWei((amtafterfees).toString(), 'ether')),
                            "gasLimit": 21000,
                            "gasPrice": web3.utils.toHex(web3.utils.toWei('10', 'gwei')),
                            "nonce": nonce,
                        }

                        try{

                            //const transaction = new EthereumTx(details,{chain: "chapel"});

                            let privateKey = process.env.TOKENOWNER_PRIVATEKEY.split('0x')
                        console.log("private======key",privateKey);
                        let privKey = Buffer.from(privateKey[0],'hex');
                        transaction.sign(privKey);
                        
                        const serializedTransaction = transaction.serialize();

                        
                        
                        
                        web3.eth.sendSignedTransaction('0x' + serializedTransaction.toString('hex'), (err, id) => {

**Comment by kajeagentspi** [comment]
This issue is not related to this project but I might be able to answer your problem.

value should be in wei not hex afaik.
