### ISSUE TITLE
Peer connection in BSC

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#179]
Hi,
I have setup private node in BSC with rpc addr. 
It connects successful. Block can be mined.
**Command:** geth --datadir ~/node1 --rpc --rpcaddr <ip_addres>  --networkid 1000 --rpcport 8545 --rpccorsdomain "*"  --rpcapi "eth,net,web3,personal,miner" --allow-insecure-unlock console

**Command **: eth.syncing
false

Then i need to connect peer node. It will result 
"WARN [05-03|18:14:20.233] Synchronisation failed, retrying         err="trie node e6f8de…a1b1e9 failed with all peers (1 tries, 1 peers)"
WARN [05-03|18:14:30.238] Node data write error                    err="trie node 38c6c1…8ce929 failed with all peers (1 tries, 1 peers)"
**Peer_ node_command:** geth --datadir ~/node2 --networkid 1000 --port 30304 --nodiscover --rpcaddr <ip_address_in_masternode> --rpccorsdomain "*"  --rpcapi "eth,net,web3,personal,miner" --allow-insecure-unlock console

**Command in peernode**: eth.syncing
{
  currentBlock: 0,
  highestBlock: 833,
  knownStates: 1,
  pulledStates: 0,
  startingBlock: 0
}

#### System information
OS & Version: Linux

#### Expected behaviour
Peer node connected successfully

#### Actual behaviour
Peer node does't sync.

#### Backtrace

````
[backtrace]
````

**Comment by koen84** [comment]
Networkid is 56 for bsc mainnet.

**Comment by osiz-blockchainapp** [comment]
Hi @koen84,
I am connecting private BSC network.
