### ISSUE TITLE
New Binance Smart Chain Full Node Setup

### ISSUE THREAD

**Issue by runfasttoday** [binance-chain/bsc#180]
After following the steps to run a fullnode from binance.org, and compiling everything without problems, I am having an issue with ./config.toml when trying to start the node on the final step.

This is my first time attempting to run a node and I'm also very new to the *nix world.

#### System information

Geth version: Version 1.10.2-stable
OS & Version: Ubuntu 18.0.4.2 LTS
Commit hash : (if `develop`)

#### Actual behaviour
Fatal: ./config.toml, line 57: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields

#### Steps to reproduce the behaviour
Steps to reproduce the behaviour
Followed the instructions to set up and run a full node from here: https://docs.binance.org/smart-chain/developer/fullnode.html

Error occurs on step 4:

Try to start the node: geth --config ./config.toml --datadir ./node --pprof.addr 0.0.0.0 --metrics --pprof

#### Backtrace

My config.toml Node.Config section:
[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = "/usr/chris/bsclogs"

**Comment by EstebanDworak** [comment]
I had the same issue and turns out I was using wrong version of geth. Are you using version 1.0.7?
Try geth --version

**Comment by runfasttoday** [comment]
I was wondering that myself.  I changed to version 1.10.3.-unstable  to see if that would make a difference.  
So I need to be on 1.0.7 ?

**Comment by EstebanDworak** [comment]
Yeah you need to be in 1.0.7

**Comment by runfasttoday** [comment]
resolved
