### ISSUE TITLE
Idea: incremental snapshots.

### ISSUE THREAD

**Issue by manelio** [binance-chain/bsc#198]
Since the time for a BSC node get in sync is being became a problem, what about providing incremental snapshots?

I mean: I see the two latest snapshots are from 2021-04-15 and 2021-04-17, with sizes around 260 GB. The compressed file is a collection of .ldb files.

Why not providing partial compressed files cointaining sequential .ldb files? It could be in a daily, filesize, or number of files basis. This way it could be easy and unexpensive for anyone to retrieve the latest blockchain info.

Or even storing all single files and providing a tool to only retrieve the files needed. I think an object storage like S3 is a perfect use case for this.

That said, I don't know if there's an "official" team behind this, or who they are. I know Amazon S3 storage and transfer have a cost. But IMO this could be a good solution to the problem of bootstraping.

**Comment by koen84** [comment]
The old files get updated / deleted occasionally.
Personally i use btrfs send-receive to create my own incremental backups.
Alternatively something like rsync / rsnapshot could be used.

**Comment by zcrypt0** [comment]
My current strategy is to bring up nodes in the same availability zone and rsync the entire datadir to the new one.

Takes about an hour but much faster than a resync.

With cloud at least, storing/transporting the data out of the cloud is quite expensive if done on a regular interval.

**Comment by koen84** [comment]
Integrated bandwidth definitely a plus here.  In fact, my backups are internal provider traffic and isn't counting.
Took me 14h took copy my archive node entirely, fully saturating GBe across the servers.  Otherwise it's weeks, potentially over a month of syncing.

**Comment by guagualvcha** [comment]
We offered snapshot data in three site https://github.com/binance-chain/bsc-snapshots, you can uncompress during download.  Incremental snapshots are hard to coordinate with all developers.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
