### ISSUE TITLE
Instability syncing rate (archive node)

### ISSUE THREAD

**Issue by koen84** [binance-chain/bsc#199]
#### System information

Geth version: `1.0.7`
OS & Version: Ubuntu 18.04 LTS

Enterprise grade server with :
AMD EPYC 7502P 32-Core Processor
128 GB RAM
4* 4TB NVMe in raid 10

Archive node with max peers 200 & cache 64000.

#### Expected behaviour
Block syncing rate is as constant around 20 blocks per minute (within some 10% variance).

#### Actual behaviour
![BSC_ChainRate_210508_2d](https://user-images.githubusercontent.com/8461454/117549644-d8b17680-b03b-11eb-8005-3e494d54004c.png)

Instead i get wild fluctuations.  And if i check logs, i sometimes notice syncing is behind chainhead as well.
System stats are all green (e.g. disk R/W ~10MBs and iops R/W 250)

I see similar things on my 2nd archive node.

#### Steps to reproduce the behaviour
Run an archive node and observe behaviour over time.

**Comment by koen84** [comment]
Interesting.  A little risky for production nodes imho, especially since it's actively being worked on..

**Comment by zcrypt0** [comment]
Indeed but working is working. I wasn't able to maintain a sync with the 1.0.7 binary at all. You can fix the pull to a certain commit to alleviate the risk that they may just break the branch with a push.

**Comment by DefiDebauchery** [comment]
@koen84 If you don't mind me asking, what's your actual RAM usage on these machines. I know that your cache setting has a lot to do with it, but is >64GB RAM truly being utilized on the archive node?

**Comment by koen84** [comment]
@DefiDebauchery cross-posting from the OOM issue : 

On my 1.0.7 archive node BSC consumes 48GB RAM.
On my 1.1.0-beta archive node BSC was consuming 100GB RAM after approx a day and 3h after restart 78GB.

Both nodes run with `--cache 64000` argument. The 1.1.0-beta node also runs with `--snapshot=false` and `--txlookuplimit=0` arguments.

----

Pretty much all remaining RAM in the server is being used in buffer / cache.  Those machines run only BSC for internal RPC access.

**Comment by koen84** [comment]
For comparistion, my experience with openethereum archive nodes is that cache 48000 is about the limit you can pull on a server with 64GB RAM, any more and you'll start swapping (to the point the server becomes unusable).

**Comment by j75689** [comment]
Hi all.
Thank you for your report.
We have received many report of a sync issue.
You can try the latest version. If you have any probleums, please feedback #338.
We will pay attention to the issue #338 for a long time, and if there are any updates, we will explain it on this issue.

Thanks.
