### ISSUE TITLE
Unable to run v1.1.0-beta

### ISSUE THREAD

**Issue by smartins** [binance-chain/bsc#202]
Just tried to run v1.1.0-beta but I get the error

`Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000
`

Any ideas on how to fix this? Tried the included mainnet.zip files as well (config.toml and genesis.json).

**Comment by guagualvcha** [comment]
hi, looks like the client is working on Ethereum main-net, have you done `geth --datadir node init genesis.json`?

**Comment by smartins** [comment]
> 
> 
> hi, looks like the client is working on Ethereum main-net, have you done `geth --datadir node init genesis.json`?

Doh, totally forgot that step. That "fixed" the issue, thanks!
