### ISSUE TITLE
geth crashing

### ISSUE THREAD

**Issue by gobiyoga** [binance-chain/bsc#203]
Hello,

I have a node setup in a VM, I have 16 vCPU assigned to it and 96GB RAM with a nvme drive passed through from host. I've experienced this crash twice, once when I was running branch upgrade_1.10.2 and again after I compiled the latest release (1.10.2). It has been syncing from genesis

It's been syncing pretty well for 23 hours but it crashed and this is the output I get from the cli:

`panic: expected tx hash 0xd0b94293b98069d6d138fb09a0bcb7a9f4d849cc4312dd067aa226528e064c04, get 0xb1e9299f1261a1d2004c70989ba1c3a073a7d7ba49ecb46b40cb8e88f9aa0789
 
goroutine 785 [running]:
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).Finalize(0xc000205900, 0x1b3b740, 0xc098696000, 0xc1e46bdb00, 0xc0a26021a0, 0xc15f7289c0, 0x2656ba8, 0x0, 0x0, 0xc15f728880, ...)
	github.com/ethereum/go-ethereum/consensus/parlia/parlia.go:708 +0x1153
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc0002f1e60, 0xc13c3be3f0, 0xc0a26021a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/state_processor.go:106 +0xe53
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc098696000, 0xc0d08fd000, 0x572, 0x572, 0xdb42c22c52867501, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:1876 +0x1174
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc098696000, 0xc0d08fd000, 0x572, 0x572, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/core/blockchain.go:1647 +0xcab
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc0ae6b01e0, 0xc0d08fa000, 0x572, 0x572, 0x572, 0x0)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1745 +0x52b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc0ae6b01e0, 0x0, 0xc0b13dad80)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1719 +0x7d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0ae6b01e0, 0xc0b45c5500, 0xc00106f230)
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:595 +0x5b
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	github.com/ethereum/go-ethereum/eth/downloader/downloader.go:595 +0xaf`

**Comment by gobiyoga** [comment]
> Same crash here

I've aligned my ssd and turned snapshot off, I'm now able to hold a proper sync

**Comment by BinanceCash** [comment]
Same issue here, please don't close issues that have not been fixed
