### ISSUE TITLE
Hello, administrator, which version should I use v1.0.7-ht.3 or v1.1.0-beta

### ISSUE THREAD

**Issue by vae520283995** [binance-chain/bsc#204]

**Comment by vae520283995** [comment]
@guagualvcha please help, thank you

**Comment by kryptome** [comment]
@vae520283995, Do you mean that v1.0.7 is not broadcasting transactions over WebSockets?

**Comment by vae520283995** [comment]
> @vae520283995, Do you mean that v1.0.7 is not broadcasting transactions over WebSockets?

I use jsonrpc call eth_sendRawTransaction return (stream is closed), but other api is ok, my version is v1.0.7

**Comment by koen84** [comment]
Depends if you want to run stable or beta version.  Keep in mind 1.1.0-beta is backwards incompatible on your chaindata.

**Comment by seonggwonyoon** [comment]
You cannot downgrade to 1.0.X because the database version changes from the moment you upgrade from 1.0.X to 1.1.0 and use it. It seems that you need to make a careful choice.
