### ISSUE TITLE
bsc blockbook is broken by the upgraded geth v1.10.x

### ISSUE THREAD

**Issue by syrohei** [binance-chain/bsc#206]
Hi. I may put here wrong thread on this repo. but it's related things. 

We are using `master` on https://github.com/binance-chain/blockbook-bsc

that has an issue after we upgraded BSC v1.1.0-beta yesterday. 

I guess it required to merge the latest commits from Trezor: mater repo.

[BSC]
v1.1.0-beta
synced from height 0 with `--syncmode=snap`

[LOG]
```
I0512 03:01:07.219388       7 rocksdb_ethereumtype.go:211] tx 0x425a21faeacb6d2b7b9612fbc0a5d18032663bf6e85d59586d8a1618bf0636e4 create new contract 0x2991cc4aB9286416b7925916aE6bD2Dc5AF7bAcb
I0512 03:01:07.219404       7 rocksdb.go:512] 1 contracts created in block 5958830
E0512 03:01:07.220710       7 blockbook.go:292] resyncIndex execution reverted
I0512 03:01:07.220822       7 rocksdb.go:312] rocksdb: close
2021/05/12 03:01:33 proto: duplicate proto type registered: eth.ProtoCompleteTransaction
2021/05/12 03:01:33 proto: duplicate proto type registered: eth.ProtoCompleteTransaction.TxType
2021/05/12 03:01:33 proto: duplicate proto type registered: eth.ProtoCompleteTransaction.ReceiptType
2021/05/12 03:01:33 proto: duplicate proto type registered: eth.ProtoCompleteTransaction.ReceiptType.LogType
```

**Comment by guagualvcha** [comment]
Hi, @syrohei  the blockbook need an upgrade, I think https://github.com/binance-chain/blockbook-bsc have upgrade for Ethereum, the BSC modification is pending review.

**Comment by guagualvcha** [comment]
https://github.com/binance-chain/blockbook-bsc/commit/a93de7e44152bbe0a164c25f87928162ccc21613 It is fixed in blockbook, you may fetch the latest release and try.
