### ISSUE TITLE
How to speed up sync for bsc full node

### ISSUE THREAD

**Issue by EXPurity** [binance-chain/bsc#207]
My node sync very slowly about 3 blocks every 9 seconds, anybody who meets that problem the same with me. How to speed up sync?

**Comment by joleeee** [comment]
You're gonna wanna read the discussion here: https://github.com/binance-chain/bsc/issues/189
Increase the maxpeers a lot and run only from NVME.

**Comment by j75689** [comment]
Hi all.
Thank you for your report.
We have received many report of a sync issue.
You can try the latest version. If you have any probleums, please feedback #338.
We will pay attention to the issue #338 for a long time, and if there are any updates, we will explain it on this issue.

Thanks.
