### ISSUE TITLE
Validator setup in BSC

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#209]
Hi,
How to setup validator node in BSC?
Is there any document for validator setup?

**Comment by kzadum007** [comment]
https://docs.binance.org/smart-chain/developer/fullnode.html

**Comment by osiz-blockchainapp** [comment]
Hi @kzadum007,
How staking process occur in BSC?
How much voting power need to become an validator?

**Comment by kzadum007** [comment]
https://docs.binance.org/smart-chain/validator/guideline.html

**Comment by osiz-blockchainapp** [comment]
> https://docs.binance.org/smart-chain/validator/guideline.html

Hi,
How to set voting power in BSC?

**Comment by edgeofthegame** [comment]
You need to self stake 10k BNB for possible double sign penalty and attract about 200k BNB more to be elected. This is proof of AUTHORITY.
