### ISSUE TITLE
eth.gasPrice returns 1gwei

### ISSUE THREAD

**Issue by joleeee** [binance-chain/bsc#210]
#### System information
```
# geth version
Geth
Version: 1.1.0-beta
Git Commit: 3ab97c2a8396862b1d23d4dc29d0cff7269c8318
Git Commit Date: 20210510
Architecture: amd64
Go Version: go1.16.4
Operating System: linux
```
Geth version: `1.1.0-beta`, compiled from `upgrade_1.10.2` branch
Commit hash : `3ab97c2a8396862b1d23d4dc29d0cff7269c8318`

OS & Version: Alpine
```
# uname -mrsv
Linux 5.10.29-0-lts #1-Alpine SMP Mon, 12 Apr 2021 15:48:39 UTC x86_64
```

#### Expected behaviour
A reasonable gas price

#### Actual behaviour
1 gwei / 1000000000

#### Steps to reproduce the behaviour
`geth attach geth.ipc --exec 'eth.gasPrice'`

#### Backtrace
no trace

**Comment by zhongfu** [comment]
As a temporary workaround, you may want to try setting `GasPrice` in `config.toml` to a more reasonable value

**Comment by guagualvcha** [comment]
Thanks for reporting this! You need add 
```
[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20
```
to the config.toml or you can fetch the latest config from the release attachment to fix this!
