### ISSUE TITLE
Validators running insufficient hardware not penalized and no longer jailed?

### ISSUE THREAD

**Issue by m-e-r-k-l-e-root** [binance-chain/bsc#212]
There are a few validators clearly running hardware incapable of keeping up with the chain, some were jailed roughly a day ago but now they're back at it again with hardware just as bad as before (if they even changed it)...

Just to name a few, take a look at _Alan Turing_ & _Avengers_ validators... Both of these validators are consistently only including <100 txns per block even though the txns they're including into blocks are only taking up ~15% of the block gas limit...

Here are some of the most recent blocks validated by Alan Turing:

![at](https://user-images.githubusercontent.com/76809797/118063567-38ff2b80-b34e-11eb-8ecb-4c044bd4ad61.png)

Here are some of the most recent blocks validated by Avengers:

![av](https://user-images.githubusercontent.com/76809797/118063600-4ae0ce80-b34e-11eb-9baf-f5f9b2f53ae6.png)

These validators are clearly running hardware incapable of keeping up with the chain, isn't there supposed to be some type of mechanism to penalize validators such as these?

NOTE: If this isn't an issue with the validators hardware, then it is still an issue on their end in which they should have been competent enough to resolve, i.e. being that other validators aren't experiencing the same issues....

**Comment by edgeofthegame** [comment]
If right now we enter **bscscan** we could read
![image](https://user-images.githubusercontent.com/63762555/118111820-e4f75400-b3ec-11eb-876f-37e131dca5fa.png)
Also if we enter its **blocks_forked** section, we can see that bscscan cannot see ~95% of forks happening right now. I guess it mean its node are way off sync, and still bsc scan is an active validator right now.

**Comment by guagualvcha** [comment]
Hi, @edgeofthegame Thanks for reporting this. We are aware of this, the bad performance validator is slow down the blockchain, but the staking mechanism will punish the invalid validators(been slashed with 50 BNB so far and in jail for two days, it will lose thousands of BNB in total), that will be a motivation for those validator to improve their hardware and monitor.

**Comment by edgeofthegame** [comment]
Hi, @guagualvcha Since you are here, could you please update minimal requirements for your software in README?

**Comment by seonggwonyoon** [comment]
@edgeofthegame 
https://docs.binance.org/smart-chain/developer/fullnode.html
You can check the system resource requirements here.

**Comment by edgeofthegame** [comment]
Unfortunately, this article is outdated. Now servers seem to need NVMe to keep up

**Comment by j75689** [comment]
Hi all.
Thank you for your report.
We have received many report of a sync issue.
You can try the latest version. If you have any problems, please feedback #338.
We will pay attention to the issue #338 for a long time, and if there are any updates, we will explain it on this issue.

Thanks.
