### ISSUE TITLE
stuck at init

### ISSUE THREAD

**Issue by junbeomlee** [binance-chain/bsc#213]
#### System information

Geth version: `v1.0.7-ht.3`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Actual behaviour

```
INFO [05-13|02:09:00.253] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [05-13|02:09:00.253] Starting Geth on Ethereum mainnet...
WARN [05-13|02:09:00.253] Sanitizing cache to Go's GC limits       provided=8000 updated=666
INFO [05-13|02:09:00.258] Maximum peer count                       ETH=30 LES=0 total=30
INFO [05-13|02:09:00.258] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
```
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

do i miss something? i run with 
```
./geth_linux --config=./config.toml --datadir=/data --rpc --pprof --pprofaddr=0.0.0.0 --pprof
```

**Comment by junbeomlee** [comment]
v1.0.6 works but v1.0.7 does not start!

**Comment by koen84** [comment]
That log excerpt seems normal.  The smartcard error can be ignored.

There's some differences across version where logs get piped to, for some it's to stdout / journal while for others it's bsc.log in your datadir.  So check for `/data/bsc.log` in your example.

**Comment by guagualvcha** [comment]
Yes, please check $datadir/bsc.log
