### ISSUE TITLE
ERROR[05-13|02:12:27.547] Block receipts missing, can't freeze     number=6410494 hash=698e82…a0a643

### ISSUE THREAD

**Issue by xiaobaiskill** [binance-chain/bsc#214]
releases: v1.0.7-ht.3

log view : ERROR[05-13|02:12:27.547] Block receipts missing, can't freeze     number=6410494 hash=698e82…a0a643

I don't understand why this is happening. Is it normal?

**Comment by guagualvcha** [comment]
@xiaobaiskill  the database is somehow broken, this should be fixed in v1.1.0-beta,  follow https://www.binance.org/en/blog/binance-smart-chain-v1-1-0-fullnode/ to run new client. Please download the snapshot in the blog and run new nodes.
