### ISSUE TITLE
Local highestBlock is higher than Latest Blocks

### ISSUE THREAD

**Issue by 7Ese** [binance-chain/bsc#215]
![image](https://user-images.githubusercontent.com/29915914/118125440-04e84100-b408-11eb-964c-a8c55d305210.png)
![image](https://user-images.githubusercontent.com/29915914/118125911-a7a0bf80-b408-11eb-8ba3-bf923ca3d18d.png)

Local `highestBlock` is higher than Binance Smart Chain Latest Blocks

**Comment by edgeofthegame** [comment]
#212

**Comment by koen84** [comment]
Are you perharps syncing testnet rather than mainnet ?
Current testnet block is 8809714, which seems close enough.

**Comment by 7Ese** [comment]
> Are you perharps syncing testnet rather than mainnet ?
> Current testnet block is 8809714, which seems close enough.

Yes, you're right
I didn't read the document carefully. Thank you for your help
