### ISSUE TITLE
sendTransaction timeout

### ISSUE THREAD

**Issue by erickcrus** [binance-chain/bsc#216]
Sometimes my node just stop sending transactions, I can use most of the commands, but sendTransaction just timeout.

eth.syncing return false
eth.blockNumber return the latest block

htop shows my server is not overloaded (8cores 20gb ram)

It works sometimes, but then it stops and keep bugged for some hours, it was working perfectly about a week ago, no modifications have been made on the server and no updates on the node.

I'm trying to send the transaction from command line for test purposes, like:

eth.sendTransaction({from: "0x46da24dbb9a19dafaf620a363396cecf20c95fed",to: "0x46da24dbb9a19dafaf620a363396cecf20c95fed", value: "0"})

bsc.log don't show anything anormal.

Anyone experienced this issue?

Version: Geth v1.0.7

**Comment by neoromantique** [comment]
+1, We're experiencing this as well with multiple nodes.

**Comment by guagualvcha** [comment]
Hi, what is the version exactly? BSC do not have a version `1.9.6-unstable`

**Comment by erickcrus** [comment]
> +1, We're experiencing this as well with multiple nodes.
> 
> It looks like mempool overload, as node continue to operate normally, obtaining new blocks, as well as responding to any RPC requests that are read only.
> 
> Node 1
> 
> ```
> Geth
> Version: 1.0.7
> Git Commit: f1d92bef016d2d0bd3aa71b6be417da2ff80400d
> ```
> 
> Node 2
> 
> ```
> Geth
> Version: 1.0.6
> Git Commit: e55e9cdd76d3b1716cdc65bec955e829a982a776
> ```

Good to know, please let me know if you discover any workaround.

**Comment by neoromantique** [comment]
> > +1, We're experiencing this as well with multiple nodes.
> > It looks like mempool overload, as node continue to operate normally, obtaining new blocks, as well as responding to any RPC requests that are read only.
> > Node 1
> > ```
> > Geth
> > Version: 1.0.7
> > Git Commit: f1d92bef016d2d0bd3aa71b6be417da2ff80400d
> > ```
> > 
> > 
> >   
> >     
> >     
> > 
> >     
> >     
> > 
> >   
> > 
> > 
> > Node 2
> > ```
> > Geth
> > Version: 1.0.6
> > Git Commit: e55e9cdd76d3b1716cdc65bec955e829a982a776
> > ```
> 
> Good to know, please let me know if you discover any workaround.

We're forced to load balance across multiple nodes + use public nodes as fallback. 

I suspect(but have no proof) that Public nodes are affected as well, as we're seeing 504/499 from those as well, however not that often.

**Comment by liuzhiyangGDM** [comment]
+1, We're experiencing this  with version v1.1.0-beta/

start cmd

geth --config ./config.toml --datadir ./node  --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0

**Comment by vae520283995** [comment]
I have the same problem, but it is resolved by upgrading to v1.0.7-ht.3
https://github.com/binance-chain/bsc/issues/204

**Comment by CantelopePeel** [comment]
Same problem.

**Comment by bug0tree** [comment]
same tbh

**Comment by guagualvcha** [comment]
fixed in  v1.0.7-ht.3
