### ISSUE TITLE
Unable to start a validator node with latest release

### ISSUE THREAD

**Issue by tiagocmachado** [binance-chain/bsc#217]
#### System information

Geth version: latest
OS & Version: Linux

When i run ```./build/bin/geth --config ./config.toml --datadir ./node -unlock {validator-address} --password password.txt  --mine  --allow-insecure-unlock --cache 18000```

Get the following error:

```INFO [05-13|23:02:25.633] Starting Geth on Ethereum mainnet...
WARN [05-13|23:02:25.635] Sanitizing cache to Go's GC limits       provided=18000 updated=2620
Fatal: ./config.toml, line 3: field 'DiscoveryURLs' is not defined in eth.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth#Config for available fields```

**Comment by guagualvcha** [comment]
Hi, @tiagocmachado, you need to fetch the config from the latest release attachment.

**Comment by tiagocmachado** [comment]
Hi @guagualvcha I got the latest, and changed DiscoveryURLs to EthDiscoveryURLs, but after that he complained about another missing config.

**Comment by guagualvcha** [comment]
Fixed already.
