### ISSUE TITLE
suggestGasPrice always 1Gwei

### ISSUE THREAD

**Issue by fwhappy** [binance-chain/bsc#218]
#### System information

Geth version: `v-1.1.0-beta`
OS & Version: OSX
Commit hash : 032970b

```
// getBlockPrices calculates the lowest transaction gas price in a given block
// and sends it to the result channel. If the block is empty or all transactions
// are sent by the miner itself(it doesn't make any sense to include this kind of
// transaction prices for sampling), nil gasprice is returned.
func (gpo *Oracle) getBlockPrices(ctx context.Context, signer types.Signer, blockNum uint64, limit int, result chan getBlockPricesResult, quit chan struct{}) {
```
The method getBlockPrices adds a constant parameter limit, which only fetches 3 transactions from each block,
This will cause the totalTxSamples > gpo.sampleTxThreshold to always be false

```
if len(txPrices) > 0 && totalTxSamples > gpo.sampleTxThreshold {
	sort.Sort(bigIntArray(txPrices))
	price = txPrices[(len(txPrices)-1)*gpo.percentile/100]
} else {
	price = gpo.defaultPrice
}
```
So, suggestGasPrice will only ever return the default value of the GasPrice configuration in config.toml .

**Comment by guagualvcha** [comment]
please refer to https://github.com/binance-chain/bsc/issues/210
