### ISSUE TITLE
bsc node sync aways slowly 

### ISSUE THREAD

**Issue by txsdev** [binance-chain/bsc#219]
### Node run enviroments:
`8 vCPUs/1.5TB SATA SSD / 40GB RAM`

### Version
`v1.1.0-beta`

### Problem
Alwaly behind latest block ~8h

<details>
<summary>bsc.log</summary>
<pre><code>
t=2021-05-14T07:05:17+0000 lvl=info msg="Set global gas cap" cap=25,000,000
t=2021-05-14T07:05:17+0000 lvl=info msg="Allocated trie memory caches" clean="1023.00 MiB" dirty="1024.00 MiB"
t=2021-05-14T07:05:17+0000 lvl=info msg="Allocated cache and file handles" database=/data/geth/chaindata cache="2.00 GiB" handles=524,288
t=2021-05-14T07:05:28+0000 lvl=info msg="Opened ancient database"          database=/data/geth/chaindata/ancient readonly=false
t=2021-05-14T07:05:28+0000 lvl=eror msg="Block receipts missing, can't freeze" number=5,124,297 hash=0xbb4892c29f5fe719aa64214e2238cc94a7a11b3ecb0e6775174c18163d239c01
t=2021-05-14T07:05:28+0000 lvl=info msg="Initialised chain configuration"      config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}"
t=2021-05-14T07:05:28+0000 lvl=info msg="Deep froze chain segment"             blocks=0 elapsed=4.141ms number=5,124,296
t=2021-05-14T07:05:32+0000 lvl=info msg="Initialising Ethereum protocol"       network=56 dbversion=7
t=2021-05-14T07:05:32+0000 lvl=warn msg="Upgrade blockchain database version"  from=7 to=8
t=2021-05-14T07:05:32+0000 lvl=info msg="Loaded most recent local header"      number=7,387,427 hash=0xb02e61ba1f7884564683a2b0ba7b34a6b8690313e8dfcba08302f4ca4d699b1a td=14,722,618 age=7h37m48s
t=2021-05-14T07:05:32+0000 lvl=info msg="Loaded most recent local full block"  number=7,387,427 hash=0xb02e61ba1f7884564683a2b0ba7b34a6b8690313e8dfcba08302f4ca4d699b1a td=14,722,618 age=7h37m48s
t=2021-05-14T07:05:32+0000 lvl=info msg="Loaded most recent local fast block"  number=7,387,427 hash=0xb02e61ba1f7884564683a2b0ba7b34a6b8690313e8dfcba08302f4ca4d699b1a td=14,722,618 age=7h37m48s
t=2021-05-14T07:05:32+0000 lvl=warn msg="Head state missing, repairing"        number=7,387,427 hash=0xb02e61ba1f7884564683a2b0ba7b34a6b8690313e8dfcba08302f4ca4d699b1a
t=2021-05-14T07:05:33+0000 lvl=info msg="Loaded most recent local header"      number=7,387,427 hash=0xb02e61ba1f7884564683a2b0ba7b34a6b8690313e8dfcba08302f4ca4d699b1a td=14,722,618 age=7h37m49s
t=2021-05-14T07:05:33+0000 lvl=info msg="Loaded most recent local full block"  number=7,387,262 hash=0xf0ea73010ff0fbc52187a4090f87d824767a0321faf032a18d85ae87b40f76e2 td=14,722,288 age=7h46m4s
t=2021-05-14T07:05:33+0000 lvl=info msg="Loaded most recent local fast block"  number=7,387,427 hash=0xb02e61ba1f7884564683a2b0ba7b34a6b8690313e8dfcba08302f4ca4d699b1a td=14,722,618 age=7h37m49s
t=2021-05-14T07:05:33+0000 lvl=warn msg="Switch sync mode from fast sync to full sync"
t=2021-05-14T07:05:33+0000 lvl=warn msg="Error reading unclean shutdown markers" error="leveldb: not found"
t=2021-05-14T07:05:33+0000 lvl=info msg="Starting peer-to-peer node"             instance=Geth/v1.1.0-beta-032970b2/linux-amd64/go1.15.5
t=2021-05-14T07:05:34+0000 lvl=info msg="New local node record"                  seq=6234 id=e477736a75b91cac23fc981ebba7a4593402f4a9c672afbe88c0a044e3937a36 ip=127.0.0.1 udp=30311 tcp=30311
t=2021-05-14T07:05:34+0000 lvl=info msg="Started P2P networking"                 self=enode://20d79da327b72729500697ac300d2af7a31d382dcb8eaba30155ca46d4bf4be6c62e0345090d4a1257eb40c0c54f451cbd97868562d69db1435329dadd107213@127.0.0.1:30311
t=2021-05-14T07:05:34+0000 lvl=info msg="IPC endpoint opened"                    url=/data/geth.ipc
t=2021-05-14T07:05:34+0000 lvl=info msg="HTTP server started"                    endpoint=[::]:8545 prefix= cors= vhosts=*
t=2021-05-14T07:05:39+0000 lvl=info msg="New local node record"                  seq=6235 id=e477736a75b91cac23fc981ebba7a4593402f4a9c672afbe88c0a044e3937a36 ip=104.199.129.85 udp=1024  tcp=30311
t=2021-05-14T07:05:49+0000 lvl=info msg="Looking for peers"                      peercount=1 tried=190 static=29
t=2021-05-14T07:05:53+0000 lvl=info msg="Block synchronisation started"
t=2021-05-14T07:05:59+0000 lvl=info msg="Looking for peers"                      peercount=2 tried=86  static=29
t=2021-05-14T07:06:04+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=136 itemSize="13.47 KiB" throttle=4865
t=2021-05-14T07:06:04+0000 lvl=info msg="Importing sidechain segment"            start=7,387,263 end=7,387,429
t=2021-05-14T07:06:13+0000 lvl=info msg="Imported new chain segment"             blocks=3 txs=835 mgas=121.333 elapsed=8.091s  mgasps=14.994 number=7,387,265 hash=0xf12ef5fd5a86f6e8d6fcdf49f12eca1b69b0e7972e95727eadcc0df80b5e5191 age=7h46m35s dirty="10.75 MiB"
t=2021-05-14T07:06:22+0000 lvl=info msg="Imported new chain segment"             blocks=8 txs=1802 mgas=314.489 elapsed=9.126s  mgasps=34.460 number=7,387,273 hash=0xa8a24d848aa4f567f242c8f9e96984f4c205a9376b5033dafd17e83f3723edca age=7h46m20s dirty="36.96 MiB"
t=2021-05-14T07:06:28+0000 lvl=eror msg="Block receipts missing, can't freeze"   number=5,124,297 hash=0xbb4892c29f5fe719aa64214e2238cc94a7a11b3ecb0e6775174c18163d239c01
t=2021-05-14T07:06:28+0000 lvl=info msg="Deep froze chain segment"               blocks=0 elapsed=1.940ms number=5,124,296
t=2021-05-14T07:06:30+0000 lvl=info msg="Imported new chain segment"             blocks=9 txs=2484 mgas=377.828 elapsed=8.613s  mgasps=43.863 number=7,387,282 hash=0x36d60ef20cb9a7edf8fe08610a175bf8f408b5904ff1a3a1a447275fe2062589 age=7h46m1s  dirty="68.38 MiB"
t=2021-05-14T07:06:39+0000 lvl=info msg="Imported new chain segment"             blocks=10 txs=2511 mgas=388.533 elapsed=8.567s  mgasps=45.352 number=7,387,292 hash=0x8a2ed07392e1d1577db77bcb044ea2d3c8ba87f89a212c4e2cee3de8aa2894e7 age=7h45m40s dirty="103.08 MiB"
t=2021-05-14T07:06:47+0000 lvl=info msg="Imported new chain segment"             blocks=11 txs=7166 mgas=553.822 elapsed=8.020s  mgasps=69.054 number=7,387,303 hash=0xc9ce1ff0db4e5e39e51fe7c5053682906493e17ce9e0d8867d13a9d06c2ffc4e age=7h45m15s dirty="144.47 MiB"
t=2021-05-14T07:06:56+0000 lvl=info msg="Imported new chain segment"             blocks=9  txs=3321 mgas=351.181 elapsed=8.636s  mgasps=40.662 number=7,387,312 hash=0xc31a2a88cb248618b338c963fdb2f7fe8730ae89cc7d922190e1ded0caad2872 age=7h44m57s dirty="174.68 MiB"
t=2021-05-14T07:07:04+0000 lvl=info msg="Imported new chain segment"             blocks=14 txs=3609 mgas=486.384 elapsed=8.082s  mgasps=60.178 number=7,387,326 hash=0x423e613032caedf419ff62cedaa4c098d667f154db80a3b2f264bfb62c457ff6 age=7h44m23s dirty="219.07 MiB"
t=2021-05-14T07:07:12+0000 lvl=info msg="Imported new chain segment"             blocks=17 txs=4842 mgas=641.051 elapsed=8.331s  mgasps=76.946 number=7,387,343 hash=0x1d084343f00cfab96c66940ff3c9144c7f6c8960226a15428464eac600507572 age=7h43m40s dirty="271.37 MiB"
t=2021-05-14T07:07:20+0000 lvl=info msg="Imported new chain segment"             blocks=13 txs=4155 mgas=661.512 elapsed=8.092s  mgasps=81.744 number=7,387,356 hash=0xf78d975d2daafeac9d2be99a43010e9871a1203d7c1634adf2443b92b1ae8272 age=7h43m9s  dirty="321.56 MiB"
t=2021-05-14T07:07:28+0000 lvl=eror msg="Block receipts missing, can't freeze"   number=5,124,297 hash=0xbb4892c29f5fe719aa64214e2238cc94a7a11b3ecb0e6775174c18163d239c01
t=2021-05-14T07:07:28+0000 lvl=info msg="Deep froze chain segment"               blocks=0  elapsed=387.012ms number=5,124,296
t=2021-05-14T07:07:28+0000 lvl=info msg="Imported new chain segment"             blocks=16 txs=4478 mgas=548.602 elapsed=8.462s    mgasps=64.830 number=7,387,372 hash=0x591448d0796ad0659307438e3ee9bc2e17124871fe2b134ce04840504ec3a596 age=7h42m30s dirty="371.53 MiB"
t=2021-05-14T07:07:37+0000 lvl=info msg="Imported new chain segment"             blocks=11 txs=9280 mgas=545.644 elapsed=8.228s    mgasps=66.315 number=7,387,383 hash=0xafe7c6df8f5c90df20d08c7ee73bf2381ac5882bb8f136561b6b26e754b06c93 age=7h42m5s  dirty="416.14 MiB"
t=2021-05-14T07:07:45+0000 lvl=info msg="Imported new chain segment"             blocks=17 txs=4880 mgas=569.650 elapsed=8.242s    mgasps=69.111 number=7,387,400 hash=0xeb3fa78aace0db202dfdf1d13adbd54f16664ee79cb409c7a5dfc81aef131d6b age=7h41m22s dirty="453.12 MiB"
t=2021-05-14T07:07:53+0000 lvl=info msg="Imported new chain segment"             blocks=18 txs=5007 mgas=612.213 elapsed=8.016s    mgasps=76.371 number=7,387,418 hash=0x7ee632d300921d9ac54be9696168d53c27377a4bbd4aefdc71c2f64cd9afe2ca age=7h40m36s dirty="469.54 MiB"
t=2021-05-14T07:07:56+0000 lvl=info msg="Persisted trie from memory database"    nodes=125,087 size="39.33 MiB" time=1.905039887s gcnodes=116,617 gcsize="43.20 MiB" gctime=438.880301ms livenodes=971,699 livesize="331.80 MiB"
t=2021-05-14T07:08:02+0000 lvl=info msg="Imported new chain segment"             blocks=11 txs=3445 mgas=380.997 elapsed=9.369s    mgasps=40.662 number=7,387,429 hash=0x27e79c89321a3f153f5aaad9fbb25c96617b3fbfc062fba819becf715606c359 age=7h40m12s dirty="438.55 MiB"
t=2021-05-14T07:08:02+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=4250 itemSize="166.58 KiB" throttle=394
t=2021-05-14T07:08:03+0000 lvl=info msg="Unindexing transactions"                blocks=58377 txs=270  total=5,037,430 elapsed=1.001s
t=2021-05-14T07:08:11+0000 lvl=info msg="Imported new chain segment"             blocks=2     txs=468  mgas=55.962  elapsed=8.919s    mgasps=6.274  number=7,387,431 hash=0x6592ffaee9677081c4335025ac97b246adf4573fc08c78d12710bda381ad70fc age=7h40m15s dirty="440.70 MiB"
t=2021-05-14T07:08:11+0000 lvl=info msg="Unindexing transactions"                blocks=318,207 txs=66486 total=5,037,430 elapsed=9.001s
t=2021-05-14T07:08:19+0000 lvl=info msg="Unindexing transactions"                blocks=431,741 txs=243,695 total=5,037,430 elapsed=17.003s
t=2021-05-14T07:08:20+0000 lvl=info msg="Imported new chain segment"             blocks=2       txs=563     mgas=62.250  elapsed=8.822s    mgasps=7.056  number=7,387,433 hash=0xb8ff809849a35bd673f18f358806e7ec5b25410e10cd18bfd977116ef0b9d1d5 age=7h40m18s dirty="440.97 MiB"
t=2021-05-14T07:08:27+0000 lvl=info msg="Unindexing transactions"                blocks=471,000 txs=480,300 total=5,037,430 elapsed=25.062s
t=2021-05-14T07:08:28+0000 lvl=eror msg="Block receipts missing, can't freeze"   number=5,124,297 hash=0xbb4892c29f5fe719aa64214e2238cc94a7a11b3ecb0e6775174c18163d239c01
t=2021-05-14T07:08:28+0000 lvl=info msg="Deep froze chain segment"               blocks=0       elapsed=1.584ms   number=5,124,296
t=2021-05-14T07:08:35+0000 lvl=info msg="Imported new chain segment"             blocks=3       txs=1742    mgas=131.637 elapsed=14.509s   mgasps=9.073  number=7,387,436 hash=0x0d644044072dee0145e07a946d2f11a1f0a479255c4316876cf4849e9a36a300 age=7h40m24s dirty="446.92 MiB"
t=2021-05-14T07:08:35+0000 lvl=info msg="Unindexing transactions"                blocks=611,000 txs=1,274,744 total=5,037,430 elapsed=33.091s
t=2021-05-14T07:08:43+0000 lvl=info msg="Unindexing transactions"                blocks=813,000 txs=1,910,838 total=5,037,430 elapsed=41.100s
t=2021-05-14T07:08:45+0000 lvl=info msg="Imported new chain segment"             blocks=4       txs=1003      mgas=128.830 elapsed=10.671s   mgasps=12.072 number=7,387,440 hash=0x0e756fe0dccd0ace20814e3e02c401ecbf4f762bff7daf8d2ef47b1ad365d0aa age=7h40m22s dirty="449.41 MiB"
t=2021-05-14T07:08:51+0000 lvl=info msg="Unindexing transactions"                blocks=931,000 txs=2,526,466 total=5,037,430 elapsed=49.117s
t=2021-05-14T07:08:54+0000 lvl=info msg="Imported new chain segment"             blocks=4       txs=801       mgas=110.339 elapsed=8.192s    mgasps=13.468 number=7,387,444 hash=0xaa9af06087e0a3c613e9bb3b68ec16b1909ecdf13a3611ebbe2f7cdccffe0284 age=7h40m19s dirty="450.80 MiB"
t=2021-05-14T07:08:59+0000 lvl=info msg="Unindexing transactions"                blocks=1,060,912 txs=3,198,473 total=5,037,430 elapsed=57.117s
t=2021-05-14T07:09:03+0000 lvl=info msg="Imported new chain segment"             blocks=5         txs=1263      mgas=165.585 elapsed=9.778s    mgasps=16.933 number=7,387,449 hash=0x378e96b816819cecef46e3deb029edbfd00aff54f8b42a6e26f156895ceb15ce age=7h40m13s dirty="453.45 MiB"
t=2021-05-14T07:09:08+0000 lvl=info msg="Unindexing transactions"                blocks=1,166,000 txs=3,867,865 total=5,037,430 elapsed=1m5.170s
t=2021-05-14T07:09:14+0000 lvl=info msg="Imported new chain segment"             blocks=4         txs=1228      mgas=145.251 elapsed=10.198s   mgasps=14.243 number=7,387,453 hash=0x5c12dac2ed62e489856a12cd9da909d0748fd67e98b3fef15717190de75de9c6 age=7h40m12s dirty="456.63 MiB"
t=2021-05-14T07:09:16+0000 lvl=info msg="Unindexing transactions"                blocks=1,254,000 txs=4,481,744 total=5,037,430 elapsed=1m13.175s
t=2021-05-14T07:09:22+0000 lvl=info msg="Imported new chain segment"             blocks=4         txs=760       mgas=101.707 elapsed=8.127s    mgasps=12.514 number=7,387,457 hash=0x6809a44a08dff87023ee1abde15afbd9012a355ed54383c44e74f9c330c1dce2 age=7h40m8s  dirty="457.73 MiB"
t=2021-05-14T07:09:24+0000 lvl=info msg="Unindexing transactions"                blocks=1,355,000 txs=5,090,663 total=5,037,430 elapsed=1m21.203s
t=2021-05-14T07:09:28+0000 lvl=eror msg="Block receipts missing, can't freeze"   number=5,124,297 hash=0xbb4892c29f5fe719aa64214e2238cc94a7a11b3ecb0e6775174c18163d239c01
t=2021-05-14T07:09:28+0000 lvl=info msg="Deep froze chain segment"               blocks=0         elapsed=1.967ms   number=5,124,296</code></pre>
</details>

<details>
<summary>config.toml</summary>
<pre><code>

[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
DatabaseCache = 12000

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
BootstrapNodes = ["enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311","enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311","enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"]
StaticNodes = ["enode://f3cfd69f2808ef64838abd8786342c0b22fdd28268703c8d6812e26e109f9a7cb2b37bd49724ebb46c233289f22da82991c87345eb9a2dadeddb8f37eeb259ac@18.180.28.21:30311","enode://ae74385270d4afeb953561603fcedc4a0e755a241ffdea31c3f751dc8be5bf29c03bf46e3051d1c8d997c45479a92632020c9a84b96dcb63b2259ec09b4fde38@54.178.30.104:30311","enode://d1cabe083d5fc1da9b510889188f06dab891935294e4569df759fc2c4d684b3b4982051b84a9a078512202ad947f9240adc5b6abea5320fb9a736d2f6751c52e@54.238.28.14:30311","enode://f420209bac5324326c116d38d83edfa2256c4101a27cd3e7f9b8287dc8526900f4137e915df6806986b28bc79b1e66679b544a1c515a95ede86f4d809bd65dab@54.178.62.117:30311","enode://c0e8d1abd27c3c13ca879e16f34c12ffee936a7e5d7b7fb6f1af5cc75c6fad704e5667c7bbf7826fcb200d22b9bf86395271b0f76c21e63ad9a388ed548d4c90@54.65.247.12:30311","enode://f1b49b1cf536e36f9a56730f7a0ece899e5efb344eec2fdca3a335465bc4f619b98121f4a5032a1218fa8b69a5488d1ec48afe2abda073280beec296b104db31@13.114.199.41:30311","enode://4924583cfb262b6e333969c86eab8da009b3f7d165cc9ad326914f576c575741e71dc6e64a830e833c25e8c45b906364e58e70cdf043651fd583082ea7db5e3b@18.180.17.171:30311","enode://4d041250eb4f05ab55af184a01aed1a71d241a94a03a5b86f4e32659e1ab1e144be919890682d4afb5e7afd837146ce584d61a38837553d95a7de1f28ea4513a@54.178.99.222:30311","enode://b5772a14fdaeebf4c1924e73c923bdf11c35240a6da7b9e5ec0e6cbb95e78327690b90e8ab0ea5270debc8834454b98eca34cc2a19817f5972498648a6959a3a@54.170.158.102:30311","enode://f329176b187cec87b327f82e78b6ece3102a0f7c89b92a5312e1674062c6e89f785f55fb1b167e369d71c66b0548994c6035c6d85849eccb434d4d9e0c489cdd@34.253.94.130:30311","enode://cbfd1219940d4e312ad94108e7fa3bc34c4c22081d6f334a2e7b36bb28928b56879924cf0353ad85fa5b2f3d5033bbe8ad5371feae9c2088214184be301ed658@54.75.11.3:30311","enode://c64b0a0c619c03c220ea0d7cac754931f967665f9e148b92d2e46761ad9180f5eb5aaef48dfc230d8db8f8c16d2265a3d5407b06bedcd5f0f5a22c2f51c2e69f@54.216.208.163:30311","enode://352a361a9240d4d23bb6fab19cc6dc5a5fc6921abf19de65afe13f1802780aecd67c8c09d8c89043ff86947f171d98ab06906ef616d58e718067e02abea0dda9@79.125.105.65:30311","enode://bb683ef5d03db7d945d6f84b88e5b98920b70aecc22abed8c00d6db621f784e4280e5813d12694c7a091543064456ad9789980766f3f1feb38906cf7255c33d6@54.195.127.237:30311","enode://11dc6fea50630b68a9289055d6b0fb0e22fb5048a3f4e4efd741a7ab09dd79e78d383efc052089e516f0a0f3eacdd5d3ffbe5279b36ecc42ad7cd1f2767fdbdb@46.137.182.25:30311","enode://21530e423b42aed17d7eef67882ebb23357db4f8b10c94d4c71191f52955d97dc13eec03cfeff0fe3a1c89c955e81a6970c09689d21ecbec2142b26b7e759c45@54.216.119.18:30311","enode://d61a31410c365e7fcd50e24d56a77d2d9741d4a57b295cc5070189ad90d0ec749d113b4b0432c6d795eb36597efce88d12ca45e645ec51b3a2144e1c1c41b66a@34.204.129.242:30311","enode://bb91215b1d77c892897048dd58f709f02aacb5355aa8f50f00b67c879c3dffd7eef5b5a152ac46cdfb255295bec4d06701a8032456703c6b604a4686d388ea8f@75.101.197.198:30311","enode://786acbdf5a3cf91b99047a0fd8305e11e54d96ea3a72b1527050d3d6f8c9fc0278ff9ef56f3e56b3b70a283d97c309065506ea2fc3eb9b62477fd014a3ec1a96@107.23.90.162:30311","enode://4653bc7c235c3480968e5e81d91123bc67626f35c207ae4acab89347db675a627784c5982431300c02f547a7d33558718f7795e848d547a327abb111eac73636@54.144.170.236:30311","enode://c6ffd994c4ef130f90f8ee2fc08c1b0f02a6e9b12152092bf5a03dd7af9fd33597d4b2e2000a271cc0648d5e55242aeadd6d5061bb2e596372655ba0722cc704@54.147.151.108:30311","enode://99b07e9dc5f204263b87243146743399b2bd60c98f68d1239a3461d09087e6c417e40f1106fa606ccf54159feabdddb4e7f367559b349a6511e66e525de4906e@54.81.225.170:30311","enode://1479af5ea7bda822e8747d0b967309bced22cad5083b93bc6f4e1d7da7be067cd8495dc4c5a71579f2da8d9068f0c43ad6933d2b335a545b4ae49a846122b261@52.7.247.132:30311","enode://42deadff5ff5d97ea4245128952335969fafea6c4ddd05146b3cac125099e1b2d1ea42c8d02c11ee8b5272a75d4f4b9f51a99244fd6daf1c6a1d5017242a3d43@101.36.120.67:30311","enode://905f585c09b8eed66afdf8a99acdab7487185357f33d5c9fe40332e4aa4a661382b159ffb300b20fbc12e81505505944ac3bfc7e6673b352d01e09f2df8af5bc@152.32.131.34:30311","enode://e585bafb7ab5a187534d69e84531165e5d4b0ee4f76b21641fe778c53770cd72e1850d44b48ad00c08ca4dc860cd5c5afa04b23a5061303f61d2658b1c48b9b2@152.32.132.171:30311","enode://b2ed83944f4c0e18d6b2f5f6c2e86b0320c10b8a96f897a535b43f25dc625ae739f449765ad86f38a393472638fcef69f30d7af53b02c3545722b1dd6f18f606@34.194.252.9:30311","enode://7cf68af17a83f925f34eeced2a139b1d11bac03fd2635707e459a821965b5e6016021a43379f24dc428ebcb84b8fb377517dee6ae484cd276a2f9360dac9c183@52.86.7.102:30311","enode://8fb5dd1259e0672efb8c141434bf0c24c73b338f7c2da15efc2def7403b952d453814230eeb97f555aaed46ee0b0b6e2a8568b518f88bd328729031746114dd2@3.0.236.154:30311","enode://8fb5dd1259e0672efb8c141434bf0c24c73b338f7c2da15efc2def7403b952d453814230eeb97f555aaed46ee0b0b6e2a8568b518f88bd328729031746114dd2@3.0.236.154:30311"]
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
</code></pre>
</details>

**Comment by vietthang207** [comment]
My guess is that SATA is not enough for the current bsc workload. I use nvme on google cloud, and it just barely be able to catch up.

**Comment by zhongfu** [comment]
My SATA SSD (Micron 5100 ECO) is able to keep up just fine; perhaps you're experiencing resource contention (maybe the SSD is shared) or some other bottleneck (e.g. if the SSD on the network)?

You may also want to consider dropping the `MaxPeers` value -- 200 peers means that you'd probably have to keep serving things like old block headers and receipts, and state trie entries from disk to quite a few of those peers. I generally use 30 or so on my nodes; having more peers (above 100?) causes my SSDs to start struggling to keep up.

**Comment by j75689** [comment]
Hi all.
Thank you for your report.
We have received many report of a sync issue.
You can try the latest version. If you have any probleums, please feedback #338.
We will pay attention to the issue #338 for a long time, and if there are any updates, we will explain it on this issue.

Thanks.
