### ISSUE TITLE
geth not work

### ISSUE THREAD

**Issue by MarlikAlmighty** [binance-chain/bsc#221]
#### System information

Geth
Version: 1.1.0-beta
Git Commit: 032970b2deeffe3b7f87703753d7be9a09906758
Git Commit Date: 20210510
Architecture: amd64
Go Version: go1.16.3
Operating System: linux
GOPATH=/home/marlik/go
GOROOT=go

#### Expected behaviour

work app

#### Actual behaviour

Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

#### Steps to reproduce the behaviour

git clone https://github.com/binance-chain/bsc
cd bsc
go get -u ./cmd/..
make geth
./build/bin/geth

#### Backtrace

marlik@noutbook:~/go/src/bsc$ ./build/bin/geth
INFO [05-14|23:19:47.761] Starting Geth on Ethereum mainnet... 
INFO [05-14|23:19:47.766] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [05-14|23:19:47.774] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-14|23:19:47.774] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [05-14|23:19:47.841] Sanitizing cache to Go's GC limits       provided=4096 updated=1805
INFO [05-14|23:19:47.842] Set global gas cap                       cap=25,000,000
INFO [05-14|23:19:47.843] Allocated trie memory caches             clean=270.00MiB dirty=451.00MiB
INFO [05-14|23:19:47.852] Allocated cache and file handles         database=/home/marlik/.ethereum/geth/chaindata cache=901.00MiB handles=48908
INFO [05-14|23:19:57.156] Opened ancient database                  database=/home/marlik/.ethereum/geth/chaindata/ancient readonly=false
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

**Comment by koen84** [comment]
You missed running `geth --datadir $datadir init genesis.json`
Your startup command needs `geth --datadir "$datadir" --config $HOME/config.toml` (in particular the config.toml spec).

You're currently trying to run ETH mainnet with the bsc modified geth.

**Comment by MarlikAlmighty** [comment]
Many thanks. Have a nice day.

**Comment by MarlikAlmighty** [comment]
Made a new genesis.json via puppeth, but the error persists, here: 

Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0

**Comment by MarlikAlmighty** [comment]
If you look at the code  https://github.com/binance-chain/bsc/blob/master/params/config.go, then there is a BerlinBlock in the code, but puppeth does not generate it in json.

**Comment by billyriantono** [comment]
are you sure when you run the geth startup you already point to correct genesis json file ?

**Comment by MarlikAlmighty** [comment]
> are you sure when you run the geth startup you already point to correct genesis json file ?

Excuse me, I don't understand you?

**Comment by james-ray** [comment]
I have the same error as you, have you solved this?

**Comment by MarlikAlmighty** [comment]
> I have the same error as you, have you solved this?
> 
> ```
> Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0
> ```
> 
> I have added mirrorSyncBlock into genesis.json and execute geth init.

No, I didn't. Can you show your genesis.json? Did it work for you?

**Comment by MarlikAlmighty** [comment]
> I have the same error as you, have you solved this?
> 
> ```
> Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0
> ```
> 
> I have added mirrorSyncBlock into genesis.json and execute geth init.

I did this, it will then ask for other blocks, and still will not work. 

Fatal: Failed to write genesis block: unsupported fork ordering: ramanujanBlock not enabled, but mirrorSyncBlock enabled at 0

**Comment by james-ray** [comment]
Yes, so I add the two lines:
```
{
  "config": {
    "chainId": 156,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "ramanujanBlock": 0,
    "mirrorSyncBlock": 0,
    "clique": {
      "period": 5,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "8000000",
  "extradata": "0x0000000000000000000000000000000000000000000000000000000000000000bad98f2e06ca412f73ca36aa96f7edcec3ad08ab00000000000000000000000000000000000000
```
but it did not work, still
```
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0
```

**Comment by MarlikAlmighty** [comment]
>  "ramanujanBlock": 0,
>     "mirrorSyncBlock": 0,

https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/testnet.zip 

Here you can take the config. Later:

./build/bin/geth init --datadir ./testnet/node ./testnet/genesis.json

  ./build/bin/geth --datadir ./testnet/node ./testnet/config.toml

**Comment by koen84** [comment]
`./build/bin/geth --config config.toml console`
(not sure about the order of config flag and console)

If you're getting errors about Berlin block, you're trying to run ETH, not BSC.

**Comment by james-ray** [comment]
> > "ramanujanBlock": 0,
> > "mirrorSyncBlock": 0,
> 
> https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/testnet.zip
> 
> Here you can take the config. Later:
> 
> ./build/bin/geth init --datadir ./testnet/node ./testnet/genesis.json
> 
> ./build/bin/geth --datadir ./testnet/node ./testnet/config.toml

You download that config and follow the steps and solve the problem?

**Comment by koen84** [comment]
@james-ray your last command is wrong, you need to specify the --config flag, like i mentioned a few times.

`./build/bin/geth --datadir ./testnet/node --config ./testnet/config.toml`

**Comment by MarlikAlmighty** [comment]
> > > "ramanujanBlock": 0,
> > > "mirrorSyncBlock": 0,
> > 
> > 
> > https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/testnet.zip
> > Here you can take the config. Later:
> > ./build/bin/geth init --datadir ./testnet/node ./testnet/genesis.json
> > ./build/bin/geth --datadir ./testnet/node ./testnet/config.toml
> 
> You download that config and follow the steps and solve the problem?

No, because I suspect this is a testnet. But it works, yes.

**Comment by MarlikAlmighty** [comment]
> `./build/bin/geth --config config.toml console`
> (not sure about the order of config flag and console)
> 
> If you're getting errors about Berlin block, you're trying to run ETH, not BSC.

Yes, the console is not needed there. But unfortunately it does not work as before. If you noticed, I did not run ethereum, but bsc, you can see from the paths.

But thanks anyway for your support.

**Comment by koen84** [comment]
You can choose any path you like.  What matters is if you did the init beforehand and specify --config at startup.

**Comment by MarlikAlmighty** [comment]
> You can choose any path you like. What matters is if you did the init beforehand and specify --config at startup.

You do not understand, I run the build from ./build/bin/geth, I show it step by step: 

```
git clone https://github.com/binance-chain/bsc
cd bsc
go get -u ./cmd/...
make all
./build/bin/puppeth
This is where I create a new genesis.json ^
./build/bin/geth init genesis.json
INFO [05-19|19:04:11.148] Successfully wrote genesis state         database=lightchaindata                        hash=af5a85..64f1ec
./build/bin/geth dumpconfig > config.toml
Here I create a new config.toml  ^
./build/bin/geth --config config.toml
And got

marlik@noutbook:~/go/src/bsc$ ./build/bin/geth --config config.toml
INFO [05-19|19:06:02.477] Starting Geth on Ethereum mainnet... 
INFO [05-19|19:06:02.477] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [05-19|19:06:02.483] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-19|19:06:02.484] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [05-19|19:06:02.484] Sanitizing cache to Go's GC limits       provided=4096 updated=1805
INFO [05-19|19:06:02.490] Set global gas cap                       cap=25,000,000
INFO [05-19|19:06:02.491] Allocated trie memory caches             clean=270.00MiB dirty=451.00MiB
INFO [05-19|19:06:02.491] Allocated cache and file handles         database=/home/marlik/.ethereum/geth/chaindata cache=901.00MiB handles=48908
INFO [05-19|19:06:02.910] Opened ancient database                  database=/home/marlik/.ethereum/geth/chaindata/ancient readonly=false
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0

```

**Comment by koen84** [comment]
Try with genesis.json and config.toml from the [release](https://github.com/binance-chain/bsc/releases/) section.  I'm not sure it works like you're trying to, seeing your log mentions ethereum mainnet and berlin fork, it probably doesn't.

**Comment by MarlikAlmighty** [comment]
> Try with genesis.json and config.toml from the [release](https://github.com/binance-chain/bsc/releases/) section. I'm not sure it works like you're trying to, seeing your log mentions ethereum mainnet and berlin fork, it probably doesn't.

Thanks for the support, it seems to work. Have a nice day.
