### ISSUE TITLE
Not reaching the tip: Is it nvme absolutely required to do a fast sync?

### ISSUE THREAD

**Issue by maldo-ctrl** [binance-chain/bsc#223]
I already have succesfully synced a node in fast mode with a `i3.2xlarge`  but now I'm tryng to do it in a cheaper home server and I'm probably having difficulties to reach the tip of the chain after 15 hours running a fast sync.

After reading all the issues, specially the comments https://github.com/binance-chain/bsc/issues/189. It seems that my ssd could be the problem as it's not `nvme`.  Is there here indicative of a bottleneck in the ssd?

Here are the specs and information about the system:
- Intel Core i5-8600K 3.6GHz
- 16 GB DDR4 2400 
- WD 1TB Blue 3D NAND M.2 SATA SSD/Solid State Drive (Read 560MB/s, Write 530MB/s, 95k/84k IOPS) **===>probably the weakest point**
- OS: `Red Hat Enterprise Linux 8.3 (Ootpa)` Filesystem `xfs`
- broadband 200 mbps

Branch: `v1.1.0-beta`
Running: `bsc --config /config.toml --datadir /root/.ethereum --syncmode fast --cache "10000" --maxpeers "2000" --snapshot=false --txlookuplimit=0`

```
eth.syncing:
{
  currentBlock: 7454087,
  highestBlock: 7454213,
  knownStates: 281343054,
  pulledStates: 281090552,
  startingBlock: 5507387
}
```

`admin.peers.length: 376`

CPU & memory usage:
![image](https://user-images.githubusercontent.com/53186719/118390576-bdd89680-b627-11eb-9245-24239e3da185.png)

Iostat:
![image](https://user-images.githubusercontent.com/53186719/118390520-6fc39300-b627-11eb-8ae2-762369aca199.png)

**Comment by afanasy** [comment]
Have you tried to reduce peers to 50? Large amount of peers is needed for sync, but after that they induce additional load on the node.

**Comment by maldo-ctrl** [comment]
Thanks, I have tried reducing different peers 30, 20, 10 but the bottleneck of the sata drive is very obvious right now:
![image](https://user-images.githubusercontent.com/53186719/118406934-29495500-b676-11eb-8ffe-e11e31ace361.png)

So I gues it confirms that a nvme is required. 

I will close the issue.

Thank you

**Comment by jmouvill** [comment]
> Have you tried to reduce peers to 50? Large amount of peers is needed for sync, but after that they induce additional load on the node.

out of curiosity, what would be the benefits (if any) of running a node with a large amount of peers once the node is synced ? Broadcast speed ?

**Comment by 0xprotobunny** [comment]
> > Have you tried to reduce peers to 50? Large amount of peers is needed for sync, but after that they induce additional load on the node.
> 
> out of curiosity, what would be the benefits (if any) of running a node with a large amount of peers once the node is synced ? Broadcast speed ?

More txns in mempool since you get them from more nodes. With 10 peers you will get like ~20% of all pending txns and with 50 nodes it will be close to 95-99%.
