### ISSUE TITLE
How do I get to the correct version of Geth? (BSC Full Node setup)

### ISSUE THREAD

**Issue by Arranua** [binance-chain/bsc#225]
**System information**

Ubuntu 20.04.2 LTS
Geth version: 1.9.6-unstable

**Problem**
I am having trouble setting up a fullnode and from reading through posts here, I am seeing that the Geth version I should be on is either 1.0.7 or 1.1.0.
However, I follow the [Binance Docs Guide](https://docs.binance.org/smart-chain/developer/fullnode.html) to installing Geth and setting up the node, and it seems to give me Geth 1.9.6-unstable.

I am checking my Geth version with the command "`geth version`". The command "`geth --version`" gives me the error "`Flag not found`".

It seems this geth version that I have installed is creating a host of problems for me while setting up the node, such as:

`Fatal: ./config.toml, line 57: field 'LogConfig' is not defined in node.Config` when I try to start the node.
If I remove LogConfig from my config.toml, I get an infinite loop of "searching for peers" 

How can I resolve this? I have tried `sudo apt-get remove geth` and it does not remove geth from my system.

**Backtrace**
`$ geth version

Geth

Version: 1.9.6-unstable

Architecture: amd64

Protocol Versions: [63]

Network Id: 1

Go Version: go1.11.13

Operating System: linux

GOPATH=

GOROOT=/home/travis/.gimme/versions/go1.11.13.linux.amd64
`

**Comment by DamCzech** [comment]
Download: https://github.com/binance-chain/bsc/releases/tag/v1.1.0-beta (mainnet + geth_linux)
Rename geth_linux to geth

sudo cp geth /usr/local/bin
sudo chmod u+x /usr/local/bin/geth

go back to mainnet directory

geth --datadir node init genesis.json

**Comment by Arranua** [comment]
> Your hardware requirements?

using a linux PC with 4 cores, 1tb ssd, 16gb ram

Thanks for the help, I think the node is syncing now. bsc.log is opening correctly and adding new entries.
I'm wondering though, why are these commands not listed in the documentation?

**Comment by DamCzech** [comment]
I don't know, documentation like documentation. You have a bigger problem - you need NVMe SSD. On Remember to Download Snapshot - https://docs.binance.org/smart-chain/developer/snapshot.html (2021-05-13 snapshot (Size: 203G)

Look: https://github.com/binance-chain/bsc/issues/207

**Comment by Arranua** [comment]
Absolutely necessary? I had heard that it would be fine with my setup, and also to not use the snapshot as it could have trouble finding peers (and just let it sync for days or a week). Not from the best source though, so I'll take your word for it.

**Comment by Arranua** [comment]
> I don't know, documentation like documentation. You have a bigger problem - you need SSD NVMe. Remember to Download Snapshot - https://docs.binance.org/smart-chain/developer/snapshot.html (2021-05-13 snapshot (Size: 203G)
> 
> Look: #207

Hey, quick question. How can I monitor the block that my node reached while syncing? I'm aware of the eth.syncing command to see what block was reached, but don't know where or how to run it and be able to view the output.

**Comment by DamCzech** [comment]
mainnet directory

geth attach node/geth.ipc --exec "eth.syncing"
geth attach node/geth.ipc --exec "eth.syncing.highestBlock - eth.syncing.currentBlock"
geth attach node/geth.ipc --exec "admin.peers.length"

Worth adding to the startup command (geth --config...)  --maxpeers 300
