### ISSUE TITLE
v1.0.7-ht.3 kill pid,Don't take effect

### ISSUE THREAD

**Issue by gaiyaa** [binance-chain/bsc#226]
v1.0.7-ht.3 kill pid,Don't take effect

**Comment by koen84** [comment]
Try `kill -9 pid`

**Comment by gaiyaa** [comment]
> Try `kill -9 pid`

Not normal use

**Comment by guagualvcha** [comment]
fixed in https://github.com/binance-chain/bsc/pull/227
