### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by gaiyaa** [binance-chain/bsc#230]
My max memory: 16G
out of memory : 16G Memory in use，then the process die
version: 1.1.0-beta-032970b2

**Comment by koen84** [comment]
Please lower your BSC `--cache` setting.
Alternatively install more RAM if possible.

**Comment by gaiyaa** [comment]
Why ETH chain don't need so many memory than BSC chain?

> Please lower your BSC `--cache` setting.
> Alternatively install more RAM if possible.

Okay,but  why ETH chain don't need so many memory than BSC chain?

**Comment by koen84** [comment]
Lower blocktime, higher gas limit, etc.

**Comment by voronindev** [comment]
Hello there! Have the same issue. It's a bug obviously. Using 32 G
`Starting peer-to-peer node               instance=Geth/v1.1.0-beta-032970b2/linux-amd64/go1.16.4`

**Comment by koen84** [comment]
No, it's likely using incompatible --cache setting compared to you're RAM size.  Try `--cache 16000` and see if it fixes.

**Comment by gaiyaa** [comment]
> No, it's likely using incompatible --cache setting compared to you're RAM size. Try `--cache 16000` and see if it fixes.

I try --cache 1000 ,for a while, still die

**Comment by guagualvcha** [comment]
usually,  1/4 of the system RAM is suggested to be the cache size.
