### ISSUE TITLE
Local private network how to

### ISSUE THREAD

**Issue by logrusorgru** [binance-chain/bsc#231]
Hello.

Extremely not clear how to start with local private network.

On the releases page there is config.toml and genesis.json for the mainnet and for the testnet. But there is no for private. This https://docs.binance.org/smart-chain/developer/deploy/local.html doesn't work with errors (eip150Block, berlinBlock, etc). 

Thanks.

Expected: have a detailed doc that works.
Have: outdated doc that doesn't work.

**Comment by shvmjn** [comment]
did you find any solution? i'm also stuck with the similar problem

**Comment by logrusorgru** [comment]
@shvmjn , hello. No, I'm not. I've switched to Ethereum local private network, because for me (work with smartcontracts and ABI) there's no difference. And Ethereum is better documented.
