### ISSUE TITLE
Sync hangs after 

### ISSUE THREAD

**Issue by nmeyersdeakin** [binance-chain/bsc#234]
#### System information

Geth version: `1.1.0-beta`
OS & Version: Ubuntu 18.04 LTS
Commit hash : (032970b2deeffe3b7f87703753d7be9a09906758)

#### Expected behaviour
Attempt to connect to peers

#### Actual behaviour
OUTPUT:
INFO [05-18|19:19:47.030] Starting Geth on Ethereum mainnet...
INFO [05-18|19:19:47.035] Maximum peer count                       ETH=300 LES=0 total=300
INFO [05-18|19:19:47.035] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Then hangs here

#### Steps to reproduce the behaviour
https://docs.binance.org/smart-chain/developer/fullnode.html

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by DefiDebauchery** [comment]
Are you sure it's hung? geth forks to the background; further logs are in `node/bsc.log`

**Comment by nmeyersdeakin** [comment]
Ah yes you're quite right. I checked the logs and it looks like I'm having problems getting peers now. I've talked to someone and he thinks I might have misdone the genesis step. My output for the genesis step is 

INFO [05-18|20:15:59.082] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-18|20:15:59.082] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [05-18|20:15:59.083] Set global gas cap                       cap=25,000,000
INFO [05-18|20:15:59.083] Allocated cache and file handles         database=/usr/local/go/bsc/node/geth/chaindata cache=16.00MiB handles=16
INFO [05-18|20:15:59.094] Persisted trie from memory database      nodes=15 size=2.32KiB time="114.41µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [05-18|20:15:59.128] Successfully wrote genesis state         database=chaindata                             hash=0d2184..d57b5b
INFO [05-18|20:15:59.128] Allocated cache and file handles         database=/usr/local/go/bsc/node/geth/lightchaindata cache=16.00MiB handles=16
INFO [05-18|20:15:59.134] Persisted trie from memory database      nodes=15 size=2.32KiB time="55.91µs"  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [05-18|20:15:59.135] Successfully wrote genesis state         database=lightchaindata                        hash=0d2184..d57b5b

Which seems to be quite different to the one posted on the link I gave in steps. I got it from 1.1.0 release.

**Comment by nmeyersdeakin** [comment]
Wow I think it finally worked. Syncing slowly but surely.

**Comment by gaiyaa** [comment]
> Wow I think it finally worked. Syncing slowly but surely.

`t=2021-05-19T10:00:22+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=6b263d819b701b00431742813af73c6a90baa2a35304588a121e8490728f3c20 err=timeout
t=2021-05-19T10:00:22+0800 lvl=eror msg="Ethereum peer removal failed"          peer=6b263d81 err="peer not registered"
t=2021-05-19T10:00:32+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:01:07+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:01:42+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:02:07+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=6b263d819b701b00431742813af73c6a90baa2a35304588a121e8490728f3c20 err=timeout
t=2021-05-19T10:02:07+0800 lvl=eror msg="Ethereum peer removal failed"          peer=6b263d81 err="peer not registered"
t=2021-05-19T10:02:17+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:02:52+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:03:27+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:04:02+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:04:37+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:05:02+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=6b263d819b701b00431742813af73c6a90baa2a35304588a121e8490728f3c20 err=timeout
t=2021-05-19T10:05:02+0800 lvl=eror msg="Ethereum peer removal failed"          peer=6b263d81 err="peer not registered"
t=2021-05-19T10:05:12+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:05:47+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:05:47+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2021-05-19T10:06:22+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:06:57+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:07:22+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=6b263d819b701b00431742813af73c6a90baa2a35304588a121e8490728f3c20 err=timeout
t=2021-05-19T10:07:22+0800 lvl=eror msg="Ethereum peer removal failed"          peer=6b263d81 err="peer not registered"
t=2021-05-19T10:07:32+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:08:07+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:08:42+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:09:07+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=6b263d819b701b00431742813af73c6a90baa2a35304588a121e8490728f3c20 err=timeout
t=2021-05-19T10:09:07+0800 lvl=eror msg="Ethereum peer removal failed"          peer=6b263d81 err="peer not registered"
t=2021-05-19T10:09:17+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:09:17+0800 lvl=warn msg="Synchronisation failed, retrying"      err="peer is unknown or unhealthy"
t=2021-05-19T10:09:29+0800 lvl=info msg="Downloader queue stats"                receiptTasks=0 blockTasks=358 itemSize="26.03 KiB" throttle=2518
t=2021-05-19T10:09:30+0800 lvl=info msg="Importing sidechain segment"           start=7,517,563 end=7,517,748
`
Why  peercount=0  a long time?

**Comment by guagualvcha** [comment]
@nmeyersdeakin I will close this issue seems you have solved it.
