### ISSUE TITLE
Can your snapshot run the BSC ARCH node directly ？

### ISSUE THREAD

**Issue by pangintama** [binance-chain/bsc#235]
Can your snapshot run the BSC ARCH node directly  ?
snap link [https://docs.binance.org/smart-chain/developer/snapshot.html](url)
v1.1.0 snapshot

**Comment by koen84** [comment]
Archive node ?  That's 6.0 TiB, so no.

**Comment by j75689** [comment]
This snapshot does not contain the entire block data, so it cannot be used for archive nodes.
