### ISSUE TITLE
Why "peercount=0" for a long time(about an hour)?

### ISSUE THREAD

**Issue by gaiyaa** [binance-chain/bsc#236]
_**Version:v1.1.0-beta-032970b2**_

t=2021-05-19T10:35:31+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=26 static=23
t=2021-05-19T10:35:55+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=23
t=2021-05-19T10:36:30+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:37:05+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:37:40+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:37:40+0800 lvl=info msg="Block synchronisation started"
t=2021-05-19T10:38:15+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:38:40+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=6b263d819b701b00431742813af73c6a90baa2a35304588a121e8490728f3c20 err=timeout
t=2021-05-19T10:38:40+0800 lvl=eror msg="Ethereum peer removal failed"          peer=6b263d81 err="peer not registered"
t=2021-05-19T10:38:50+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:39:25+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:39:51+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=b166d029f4853769f8e054576d9e042f22f52fdf3f6a97c69c03657defcd1d2a err=timeout
t=2021-05-19T10:39:51+0800 lvl=eror msg="Ethereum peer removal failed"          peer=b166d029 err="peer not registered"
t=2021-05-19T10:40:00+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:40:35+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23
t=2021-05-19T10:41:01+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=b166d029f4853769f8e054576d9e042f22f52fdf3f6a97c69c03657defcd1d2a err=timeout
t=2021-05-19T10:41:01+0800 lvl=eror msg="Ethereum peer removal failed"          peer=b166d029 err="peer not registered"
t=2021-05-19T10:41:10+0800 lvl=info msg="Looking for peers"                     peercount=0 tried=23 static=23

**Comment by soltrac** [comment]
Have u generated the genesis like explained in docs?

**Comment by gaiyaa** [comment]
> Have u generated the genesis like explained in docs?
generated the genesis????
I deploy it by "https://docs.binance.org/smart-chain/developer/snapshot.html"

**Comment by soltrac** [comment]
https://docs.binance.org/smart-chain/developer/fullnode.html 

First this, after that, try the snapshot.

**Comment by gaiyaa** [comment]
> https://docs.binance.org/smart-chain/developer/fullnode.html
> 
> First this, after that, try the snapshot.

Okay,I hava a try,tks bro.

**Comment by guagualvcha** [comment]
closing this. @soltrac  feel free to open new ones if any questions.
