### ISSUE TITLE
The method signatures defined in 4byte.go, where is the source code of the contract?

### ISSUE THREAD

**Issue by james-ray** [binance-chain/bsc#237]
Hi, I am new to BSC chain, and I see from the doc, the validator can undelegate and get its reward,
but I can't find where the logic is, seems like it is defined as solidity method, where is the related contract code?
```
"090cebff": "unDelegate(uint8,bytes32,bytes32)",
"090cfb04": "DiamondscoinToken()",
"090d23b9": "setBank(address)",
"090d5386": "GDOAdv(uint256,string,string)",
"090d94cc": "WithdrawalsOpen(address)",
"090d993a": "updateParticipantCapTier1(uint256)",
"090e5465": "trainFee()",
"090e871f": "createNewSubtoken(uint256,address,uint256)",
"090ea6f3": "setProxyManagementAddress(address)",
"090f4465": "payoutDate()",
```

**Comment by kyrie-yl** [comment]
> unDelegate



> Hi, I am new to BSC chain, and I see from the doc, the validator can undelegate and get its reward,
> but I can't find where the logic is, seems like it is defined as solidity method, where is the related contract code?
> 
> ```
> "090cebff": "unDelegate(uint8,bytes32,bytes32)",
> "090cfb04": "DiamondscoinToken()",
> "090d23b9": "setBank(address)",
> "090d5386": "GDOAdv(uint256,string,string)",
> "090d94cc": "WithdrawalsOpen(address)",
> "090d993a": "updateParticipantCapTier1(uint256)",
> "090e5465": "trainFee()",
> "090e871f": "createNewSubtoken(uint256,address,uint256)",
> "090ea6f3": "setProxyManagementAddress(address)",
> "090f4465": "payoutDate()",
> ```

**Comment by kyrie-yl** [comment]
> Hi, I am new to BSC chain, and I see from the doc, the validator can undelegate and get its reward,
> but I can't find where the logic is, seems like it is defined as solidity method, where is the related contract code?
> 
> ```
> "090cebff": "unDelegate(uint8,bytes32,bytes32)",
> "090cfb04": "DiamondscoinToken()",
> "090d23b9": "setBank(address)",
> "090d5386": "GDOAdv(uint256,string,string)",
> "090d94cc": "WithdrawalsOpen(address)",
> "090d993a": "updateParticipantCapTier1(uint256)",
> "090e5465": "trainFee()",
> "090e871f": "createNewSubtoken(uint256,address,uint256)",
> "090ea6f3": "setProxyManagementAddress(address)",
> "090f4465": "payoutDate()",
> ```

Delegate and undelegate are not done on BSC but on BC. So, they are not a contract.

**Comment by james-ray** [comment]
thanks.
