### ISSUE TITLE
Why is transations always packed after T+2 blocks

### ISSUE THREAD

**Issue by skyh24** [binance-chain/bsc#239]
I am a dapp developer. I want to send transations after the event just from last block. But I try several ways, my block was  always packed in block after T+2 block. It take too long to be packed. Can I packed my txn in the next block? Is there any ways to improve my latency? Or is  the validator using proxy or block ordering?

**Comment by soltrac** [comment]
No, you can't. This has been explained several times on this github. Always 2 blocks.

**Comment by skyh24** [comment]
> No, you can't. This has been explained several times on this github. Always 2 blocks.

Do you have any ref for explain why?

**Comment by skyh24** [comment]
@fjl @atoulme @reds Does Is there any particular design for bsc ?

**Comment by skyh24** [comment]
@guagualvcha @yutianwu

**Comment by skyh24** [comment]
Why does some txns can be packed in next block? Does the official have some validator endpoint? and is there any service to pack on chain faster? @guagualvcha @yutianwu

**Comment by lvzhenxin2006** [comment]
I can't find anything code about this logic,  it  maybe  controled by the miners,  that's unfair and be careful.

**Comment by zhouhaw** [comment]
i have same question, pls help

**Comment by cryptobrokering** [comment]
Would also be interested to learn more. Some months earlier, I tried sending Txs fast and it was possible to get in the same block as a new pending Tx from the mempool and about 0.3-0.5s latency between seeing a tx in the mempool and seeing an own one sent afterwards. Now this latency is > 2s every time and it is nearly impossible to get in the same block. Did they change something in the system?

**Comment by guagualvcha** [comment]
@skyh24 this has been discussed several times, how fast your transaction can be validated on-chain depends on network, topology, location, and the a lot of things we can not explain in this repo.
