### ISSUE TITLE
Connecting to websocket causes memory leak

### ISSUE THREAD

**Issue by tculig** [binance-chain/bsc#240]
#### System information

Geth version: `geth version 1.10.-beta`
OS & Version: Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
No memory leak

#### Actual behaviour
Starting node with 'sudo geth --config ./config.toml --datadir ./node --syncmode snap

config.toml changes I made:
WSHost = "127.0.0.1"
WSOrigins = ["*"]
WSExposeAll = true

When I connect to the websocket, even locally, and then disconnect right after with unsubscribe, the memory leak starts.
After about 20 minutes it takes up 64Gb or RAM and crashes geth. 

#### Steps to reproduce the behaviour
My very basic piece of code that I run:
`
const Web3 = require("web3");

let web3;
async function initialize() {
    web3 = new Web3("ws://localhost:8546");
}

let subscription;
async function startTracking() {
  subscription = web3.eth.subscribe("logs", { fromBlock: "0x0" })
      .on("data", async (log) => {
          subscription.unsubscribe(function(error, success){
            if(success)
              console.log('Successfully unsubscribed!');
            if(error){
               console.log('Cannot unsubscribe!');
               console.log(error);
            }
      });
  });
  console.log("Listening...");
}

async function run() {
  await initialize();
  startTracking();
}

run();`

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by soltrac** [comment]
Im not experiencing that memory leak and I'm connecting to my node with WS.

Anyway, I have snapshot disabled, it crashes me, don't sure why

**Comment by tculig** [comment]
The issue was caused by the web3 library, version 1.3.6. No idea how or why, but connecting with "ws": "^7.4.5" doesn't cause the same issue.

**Comment by tculig** [comment]
Its happening with older versions of web3 as well...there is some really weird interactions between web3 and geth....
