### ISSUE TITLE
Validator locations

### ISSUE THREAD

**Issue by Arranua** [binance-chain/bsc#243]
Does anyone know where the BSC validators are located? Trying to find the best place to set up a full node. Or, is it better to just run the node close to where you yourself are operating from?

**Comment by zhongfu** [comment]
I guess it depends on what you're planning on using it for -- if you're planning to interact with e.g. web3 sites, then the latter would be better since those sites can end up making a ton of read contract calls. Some don't even do it in parallel, so latency becomes even more important

**Comment by patllc** [comment]
It depends on what you are going to do.
If you plan to do some arbitraging, I recommend you reading the issue below. Current version I think it is not possible to be profitable. Winner takes all.

https://github.com/binance-chain/bsc/issues/269

**Comment by aenima1** [comment]
Does anyone actually know? Im assuming most are in the US and Europe?

**Comment by guagualvcha** [comment]
@Arranua  it is not within the scope of this repo, you can find validators in https://www.binance.org/en/staking. some of them are maintained by organization, better ask them.  Aome are anonymous, no answer here.
