### ISSUE TITLE
Full node RPC html url

### ISSUE THREAD

**Issue by Arranua** [binance-chain/bsc#248]
Hello, I have synced a BSC full node. How could I connect it to RPC and generate an html url? Does anyone have a good guide for doing this?

**Comment by DefiDebauchery** [comment]
Adding the command line option `--http` when you start geth enables the RPC port for you to connect your personal Metamask (or other web3 software) to. You can also adjust the port it listens on with `--http.port`.

Note that if you're using 1.1.0 beta, you may need to change or remove the `HTTPHost` entry in config.toml, as its configuration to `localhost` seems to take precedence over the `--http.addr` command line flag.

**Comment by Arranua** [comment]
Didn't add --http when I started - do I have to stop the node and resync with the new command?

**Comment by DefiDebauchery** [comment]
You will need to stop the node, but if you do a controlled shutdown (CTRL-C if you have an active window, otherwise `kill -2 $PID_OF_GETH`), it should resync pretty quickly.

**Comment by Arranua** [comment]
Thanks. Then, rpc url I can put in metamask or whatever, is just http:/<ip of node>, correct?

**Comment by DefiDebauchery** [comment]
That's right. As a note, if you're intending to access this over the internet (vs within your internal home network), I would recommend using a reverse proxy (such as nginx) to be your https endpoint, which forwards to the insecure RPC port.

**Comment by Arranua** [comment]
> 
> 
> That's right. As a note, if you're intending to access this over the internet (vs within your internal home network), I would recommend using a reverse proxy (such as nginx) to be your https endpoint, forwarding to the insecure RPC port.

Heard of this, couldn't find a good guide on how to get it done. Do you have any resources I can check?

**Comment by Arranua** [comment]
doesnt seem to be working. I put http://xxx.xx.xx.xx as "new rpc url" in metamask. and it says Could not fetch chain ID. Is your RPC URL correct?

Node looks like it is synced properly, command "eth.syncing" returns false

**Comment by DefiDebauchery** [comment]
Chain ID should be `0x38` for BSC.

By default, the port is 8545; so the RPC URL should be http://12.34.56.78:8545 - but you'd have to check whether you can telnet to that port, as you may need to open it up through any firewall that may be configured.

**Comment by Smoosh195** [comment]
> Chain ID should be `0x38` for BSC.
> 
> By default, the port is 8545; so the RPC URL should be http://12.34.56.78:8545 - but you'd have to check whether you can telnet to that port, as you may need to open it up through any firewall that may be configured.

Would you be interested in taking payment (bnb) to help me set up a full node? Currently have debian with ssh, 10 core @ 5.2ghz , 4tb ssd and 64gb Ram with 1gb internet connection

**Comment by Arranua** [comment]
still says could not fetch chain ID

I did " telnet 12.34.56.78 8545 " and it says "Connected to <ip>". Looks like port works. Not sure what to do now

**Comment by stnho** [comment]
> 
> 
> doesnt seem to be working. I put http://xxx.xx.xx.xx as "new rpc url" in metamask. and it says Could not fetch chain ID. Is your RPC URL correct?
> 
> Node looks like it is synced properly, command "eth.syncing" returns false
> 
> My geth starting commnd:
> 
> `geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 300`
> 
> and i removed HTTPhost entry from config.toml
> 
> im using VPS not local so I think that could be the problem, how do I do this properly?

I have mine, Im using 
./geth_linux --config config.toml --maxpeers 200 --datadir bscdata --cache 36000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --http.addr <ipaddress> --http.port <port> 

neither http or rpc command is working. geth log always shows endpoint create on local 127.0.0.1 but somehow port command is working, it connects to my pointed port.

**Comment by Patrollia** [comment]
> That's right. As a note, if you're intending to access this over the internet (vs within your internal home network), I would recommend using a reverse proxy (such as nginx) to be your https endpoint, forwarding to the insecure RPC port.

Hi, this is my first time talking here. First of all, thank you guys, I'm learning a lot.

I had/have the same question as OP, I mean, his post itself and the one where he is asking you if there is a guide or something to configure NGINX for this kind of things.

Is there a guide or something? Thanks!

**Comment by KeefeL** [comment]
> > That's right. As a note, if you're intending to access this over the internet (vs within your internal home network), I would recommend using a reverse proxy (such as nginx) to be your https endpoint, forwarding to the insecure RPC port.
> 
> Hi, this is my first time talking here. First of all, thank you guys, I'm learning a lot.
> 
> I had/have the same question as OP, I mean, his post itself and the one where he is asking you if there is a guide or something to configure NGINX for this kind of things.
> 
> Is there a guide or something? Thanks!

Hope this will help you https://linuxiac.com/reverse-proxy-with-nginx/
