### ISSUE TITLE
Light client block speed up

### ISSUE THREAD

**Issue by DamCzech** [binance-chain/bsc#250]
Hey

How will it speed up block downloads in Light Client? The average is 3 seconds. Can you change to lower values? 

t=DATA:8:00:0 "Imported new block headers"
t=DATA:8:00:3 "Imported new block headers.
t=DATA:8:00:6 "Imported new block headers"
...

// edit:
Are 30-32 peers a good result? Can you get more? I set  max. 300.

**Comment by guagualvcha** [comment]
It only needs few hours to set up a full synced Light client, although you seeing the log every second, but it download a lot of header every 3 seconds.

**Comment by DamCzech** [comment]
> Wystarczy kilka godzin, aby skonfigurować w pełni zsynchronizowanego klienta Light, chociaż dziennik jest wyświetlany co sekundę, ale co 3 sekundy pobiera dużo nagłówków.

How can you get more peers? Is there any list besides the configuration file? Max 32...

**Comment by deltapulse** [comment]
How do you even set up a light node on bsc, I thought you can't do that.

**Comment by guagualvcha** [comment]
Will close this. Since more peers(more than 30) won't speed up light client syncing.
