### ISSUE TITLE
Transactions stay in "secondary node" forever

### ISSUE THREAD

**Issue by wmsouza** [binance-chain/bsc#254]
#### System information

Geth version: 1.0.7ht3 and 1.10.0
OS & Version: Linux

#### Expected behaviour
Transactions to get submitted correctly

#### Actual behaviour
Transactions appear to be submitted, but never shows up, BSCScan shows them as "picked up by a secondary node" but never change state

#### Steps to reproduce the behaviour
Send any transaction

On versions prior to 1.0.7, the sendTransaction rpc method would time out and never return, and transactions would stay in a "Queued" state until the geth node gets shut down, during the shutdown process geth would try to send all of the stuck transactions.

**Comment by wmsouza** [comment]
Fixed.. firewall was blocking inbound connections on port 30303

**Comment by rainwater11** [comment]
Hey, I unblocked that port and it worked for a little bit but now its back to the issue you described: transactions just appear submitted but never complete. 

Anyone have any idea how to fix this?
