### ISSUE TITLE
OracleThreshold is not defined in gasprice.Config

### ISSUE THREAD

**Issue by unsphere** [binance-chain/bsc#255]
I'm struggling with starting the full node on Linux. Everything is set up like pointed out in the tutorial, but I get the following error when starting the node:

```
(NFO` [05-25|18:39:04.850] Starting Geth on Ethereum mainnet... 
Fatal: ./config.toml, line 35: field 'OracleThreshold' is not defined in gasprice.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/gasprice#Config for available fields)
```

OracleThreshold is defined in the config.toml:

```
...
[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20
...
```

Can someone help me out?

**Comment by guagualvcha** [comment]
hi, can you do `geth version` and paste the version info here?

**Comment by unsphere** [comment]
> hi, can you do `geth version` and paste the version info here?

```
Version: 1.10.4-unstable
Git Commit: 017cf71fbd51ede510dd0e40e02f89b5340eea93
Git Commit Date: 20210525
Architecture: amd64
Go Version: go1.14.12
Operating System: linux
GOPATH=
GOROOT=go
```

**Comment by unsphere** [comment]
I solved it with a fresh new installation and following the tutorial again.
