### ISSUE TITLE
Offline pruning not working

### ISSUE THREAD

**Issue by edgybtc** [binance-chain/bsc#256]
#### System information

Geth version: `Version: 1.1.0-beta`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Should be able to prune and reduce occupied space

#### Actual behaviour
Displaying error when I try to prune using the command  ./build/bin/geth --datadir ./node snapshot prune-state

#### Steps to reproduce the behaviour
I have synced the node from a snapshot, which I downloaded from this resp. 
Once my node was synced to latest block, I saw that it's occupying 580 GB of space and wanted to prune.
I stopped geth with force and killed any ongoing process of geth. Then I ran the command  ./build/bin/geth --datadir ./node snapshot prune-state

#### Backtrace

````
[root@vultr:/home/bsc# ./build/bin/geth --datadir ./node snapshot prune-state
INFO [05-25|22:45:48.857] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-25|22:45:48.857] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [05-25|22:45:48.858] Set global gas cap                       cap=25,000,000
INFO [05-25|22:45:48.858] Allocated cache and file handles         database=/home/bsc/node/geth/chaindata cache=512.00MiB handles=524,288
INFO [05-25|22:45:49.107] Opened ancient database                  database=/home/bsc/node/geth/chaindata/ancient readonly=false
WARN [05-25|22:45:49.111] Loaded snapshot journal                  diskroot=d874fe..f6d49a diffs=missing
ERROR[05-25|22:45:49.111] Failed to open snapshot tree             err="head doesn't match snapshot: have 0xd874febe4ce234f75682461fc1fa2a199a102d7d99d4da3827c738b2e1f6d49a, want 0xbef52f95df13568feabff9422bbd6f577f3c29dd065e148cb4e5ca38a71c9063"
ERROR[05-25|22:45:49.111] Failed to append ancient body            number=7,638,196 hash="[248 135 221 218 4 131 240 87 120 18 82 130 32 8 26 180 97 253 250 202 10 239 1 228 56 177 136 163 22 54 202 219]" err=closed
CRIT [05-25|22:45:49.111] Failed to repair freezer                 err="invalid argument"]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by guagualvcha** [comment]
hi, please do not force kill the process, it need gracefully shutdown

**Comment by DefiDebauchery** [comment]
If it's forked to the background, you cann kill it with signal 2 instead of 9, which will shut it down gracefully.

`kill -2 $pid_of_geth`

**Comment by edgybtc** [comment]
Even after stopping geth gracefully, I am still getting the same error while pruning.

**Comment by edgybtc** [comment]
Used space has increased to 608 GB, any input will be appreciated.

**Comment by dudebing99** [comment]
Came across the same problem, I tried this and that worked for me.

0. stop the node.
1. re-sync with snap mode for a while.
```
./geth --syncmode=snap <other options not listed ...>
```
2. stop the node.
3. start to prune.
```bash
geth snapshot prune-state
```

**Comment by guagualvcha** [comment]
> Came across the same problem, I tried this and that worked for me.
> 
> 0. stop the node gracefully.
> 1. re-sync with snap mode for a while.
> 
> ```
> ./geth --syncmode=snap <other options not listed ...>
> ```
> 
> 2. stop the node gracefully.
> 3. start to prune.
> 
> ```shell
> geth snapshot prune-state
> ```

Closing this. This is the solution.

**Comment by hanik244** [comment]
WIN10 如何處理?
