### ISSUE TITLE
Txpool

### ISSUE THREAD

**Issue by atrinitytv** [binance-chain/bsc#259]
I see that I have anywhere from 30,000-40,000 txns in the mempool, is there anyway I can set these to expire off my node quicker using Lifetime? If so, how would I make it less than 30 minutes or an hour?

**Comment by atrinitytv** [comment]
And what is that value 10800000000000 convert into?

**Comment by guagualvcha** [comment]
It is `10800000000000 /1e9 = 10800 second`

**Comment by guagualvcha** [comment]
Will kindly close this @atrinitytv. Thanks
