### ISSUE TITLE
Geth on localhost gives wrong pending and queued data

### ISSUE THREAD

**Issue by KDawid** [binance-chain/bsc#261]
#### System information

Geth version: `geth version` 
1.10.1-stable-c2d2f4ed

OS & Version: Windows/Linux/OSX
Linux

#### Expected behaviour
Get pending transactions from local binance node, match the result I get from https://bsc-dataseed1.binance.org
Get real pending transaction list

#### Actual behaviour
Number of pending transactions is more less than expected (~2000), number of queued transactions is much more than expected (~13000). 
Example: local node does not give back new token listings on pancakeswap but data from https://bsc-dataseed1.binance.org seems valid.
Local node seems to be synchronized.
How can I force to synchronize?

#### Steps to reproduce the behaviour
using web3 in python3.8
getting pending transaction filter id with 'eth_newPendingTransactionFilter' method (POST to local node or https://bsc-dataseed1.binance.org)
using 'eth_getFilterChanges' method with the pending filter id (POST to local node or https://bsc-dataseed1.binance.org)

node has been started using the following command:
`nohup ./build/bin/geth --config ./config.toml --syncmode fast --datadir ./node --metrics --pprof --rpc --rpcaddr 127.0.0.1 --rpcapi="db,eth,net,web3,personal,txpool"   --allow-insecure-unlock  > bscnodeout.log 2> bscnodeerr.log </dev/null &`

**Comment by ilyasELBANI** [comment]
I'm not sure, but did you try updating config.toml  ?
`[Eth.TxPool]
GlobalSlots = $SizeOfPool
GlobalQueue = $SizeOfQueue
Lifetime = 10800000000000
`

**Comment by ggalgoczi** [comment]
> I'm not sure, but did you try updating config.toml ?
> 
> ```toml
> [Eth.TxPool]
> GlobalSlots = $SizeOfPool
> GlobalQueue = $SizeOfQueue
> Lifetime = 10800000000000
> ```

What is the value of the $SizeOfPool and $SizeOfQueue variables?

We are facing the same problem. Pending and queued tx number is OK in the first few minutes of running the node but then somehow queued keeps increasing and pending tx stays around 200.

**Comment by ggalgoczi** [comment]
> I'm not sure, but did you try updating config.toml ?
> 
> ```toml
> [Eth.TxPool]
> GlobalSlots = $SizeOfPool
> GlobalQueue = $SizeOfQueue
> Lifetime = 10800000000000
> ```

What should be the values of SizeOfPool and SizeOfQueue?

The first few minutes the number of pending and queued txs seem OK.

After few minutes queued TX number starts to go up and pending goes down to 100-200. We are not getting a lot of pending TXs as well...

**Comment by ilyasELBANI** [comment]
SizeOfPool is the max number of pendings transactions you want, and SizeOfQueue is the max size of queud transactions.

Could it be related to a slow disk ? What's your storage type, people here say it must be a physical NVME ssd, they say even normal ssds are not enough. ( I can't confirm that this is correct though )

**Comment by KeefeL** [comment]
The transactions are propagated among the P2P network, I think it is hard to get the same results between your own node and the https://bsc-dataseed1.binance.org node all the time.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8

**Comment by francesco-clementi-92** [comment]
@KDawid did you fix the issue?
