### ISSUE TITLE
What am I supposed to do first: unzip geth or create genesis?

### ISSUE THREAD

**Issue by gajus** [binance-chain/bsc#265]
It is not clear from reading the [documentation](https://docs.binance.org/smart-chain/developer/fullnode.html) in which order should these commands be executed:

```bash
geth --datadir /srv/node init genesis.json
unzip geth.zip -d /srv/node/
```

or

```bash
unzip geth.zip -d /srv/node/
geth --datadir /srv/node init genesis.json
```

It is also not clear if there are any special attributes that should be used when syncing node using snapshot.

This is what I am using at the moment:

```bash
./build/bin/geth \
  --syncmode snap \
  --config ./config.toml \
  --datadir /srv/node \
  --cache 18000 \
  # https://blog.ethereum.org/2021/03/03/geth-v1-10-0/
  --rpc.allow-unprotected-txs \
  --txlookuplimit 0 \
  --ipcpath /srv/geth.ipc
```

**Comment by koen84** [comment]
The snapshot should include the init, otherwise they wouldn't have been able to sync.  So when you use a snapshot, you don't need to init.  Keep in mind, people reported problems when running with snapshot data.

**Comment by gajus** [comment]
For what it is worth, I didn't have problems running with Snapshot data once I figured out the correct directory structure.

**Comment by doplumi** [comment]
@gajus what is the correct directory structure? I'm currently unpacking w/

`unzip snap.zip -d bsc/node/geth` as indicated in the docs, the structure doesn't seem to match
