### ISSUE TITLE
Publish Different Messages to Kafka

### ISSUE THREAD

**Issue by namlt3820** [binance-chain/bsc#267]
I want to use the feature Publish Different Messages to Kafka in binance smart chain node. But from the docs it seems like it's binance chain node feature only. Can someone clarify it? Thank you.

**Comment by guagualvcha** [comment]
https://docs.binance.org/guides/node/extra-info.html

**Comment by pthor11** [comment]
@guagualvcha: does this method can apply for bsc node as well? As I can see from the docs, it's supposed to work for bnb node only. Please correct me if I'm wrong, thanks in advanced!
