### ISSUE TITLE
BSC Full Node (Archive) Size

### ISSUE THREAD

**Issue by seonggwonyoon** [binance-chain/bsc#268]
Hi I am trying to build a bsc full node archive node.
However, I tried to check the disk requirements before server building, but the data (disk usage) is not displayed normally. If someone is running an archive node, can anybody tell me the current disk usage and disk growth per day?

The site I referenced is here, but the data does not appear.
https://bscscan.com/chartsync/chainarchive

**Comment by pr0logas** [comment]
5.7 TB of data 

![Selection_637](https://user-images.githubusercontent.com/44883794/120281476-abb25580-c2c1-11eb-8246-666d087a4023.png)

**Comment by seonggwonyoon** [comment]
@pr0logas Thank you ! Could you please tell me how you configured the disk raid? 
What disk did you use (nvme ssd or something)?

**Comment by pr0logas** [comment]
You need at least Enterprise NVMe disk storage. The SSD's cannot handle the load. Plus the CPUs are spiking very hard from time to time. Even if you have a 32C server beast. 
The cheapest approach would be RAID0 (if you are aware of the risks) but if you want flexibility - RAID5. It lets you add more storage later.

**Comment by seonggwonyoon** [comment]
@pr0logas Thanks for the detailed info!
I have one additional question.
You said that the CPU spiking frequently. In what cases does spiking occur frequently?
