### ISSUE TITLE
Is it possible to get into the very next block?

### ISSUE THREAD

**Issue by ntegrals** [binance-chain/bsc#271]
I am currently trying to get into the very next block, but I end up always being one block late.

Current setup:
- Receive block header of block 1 with my full node
- Do all my calcs and send tx (takes 11ms right now)

I want to end up in block 2, but always end up in block 3

Is this even possible with ~3s block times?

**Comment by m-e-r-k-l-e-root** [comment]
This questions has been asked and answered a plethora of times (i.e. answered here [https://github.com/binance-chain/bsc/issues/107](https://github.com/binance-chain/bsc/issues/107))... Try overviewing the closed issues tab next time before opening a new issue...
