### ISSUE TITLE
transactions.rlp

### ISSUE THREAD

**Issue by soltrac** [binance-chain/bsc#272]
Hi,

Since I updated my node to 1.10, I cannot find transactions.rlp file in any place. Is this a normal behaviour? I would like to be able to clear the queue pool and the only way I know to do it is clearing that file.

Any suggestions?

**Comment by FomoApe** [comment]
Same here, I can't find that file as well

**Comment by guagualvcha** [comment]
What you need to do is change the `NoLocals = true` to `NoLocals = false`
