### ISSUE TITLE
Voting power in BSC

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#274]
Hi everyone,
In BSC, How to get voting power?
Is there any api for voting power?

Kindly guide me to solve this issue asap.

**Comment by osiz-blockchainapp** [comment]
> Hi everyone,
> In BSC, How to get voting power?
> Is there any api for voting power?
> 
> Kindly guide me to solve this issue asap.

How to setup voting power in BSC?

**Comment by guagualvcha** [comment]
You can ready from genesis contract:
![image](https://user-images.githubusercontent.com/7310198/126962004-91aea9c8-6f0d-47b8-9b1f-50c6ea6a1559.png)

**Comment by osiz-blockchainapp** [comment]
> You can ready from genesis contract:
> ![image](https://user-images.githubusercontent.com/7310198/126962004-91aea9c8-6f0d-47b8-9b1f-50c6ea6a1559.png)

Can we get voting power in contract?
