### ISSUE TITLE
Contract calling in geth

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#275]
Hi everyone,
Contract can be deployed in geth private network using web3. Try to call that function using web3 but it shows error.
"Error: Returned error: invalid opcode: SHR" 

**genesis file:**
{
     "config": {
       "chainId": 99,
       "homesteadBlock": 0,
       "eip150Block": 0,
       "eip155Block": 0,
       "eip158Block": 0
                },
     "nonce": "0x0000000000000061",
     "timestamp": "0x0",
     "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
     "gasLimit": "0x8000000",
     "difficulty": "0x100",
     "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
     "coinbase": "0x3333333333333333333333333333333333333333",
     "byzantiumBlock": 0,
     "constantinopleBlock": 0,
     "istanbulBlock": 0,
}

How to overcome this error?

**Comment by guagualvcha** [comment]
You may follow https://github.com/binance-chain/bsc-docker; The `truffle-test` shows how to deploy contracts on private chain.
