### ISSUE TITLE
unable to import account created by geth account new

### ISSUE THREAD

**Issue by ravinayag** [binance-chain/bsc#279]
Im unable to import the account from the secret key file generated by geth. 
**Reproduce the problem :**
```
$ geth account new --datadir some-safe-folder-path
$ geth account import some-safe-folder-path/keystore/UTC--2021-06-08T16-48-04.166326199Z--34xxxxxxxx
```
this import not working and ended with 
```
Fatal: Failed to load the private key: invalid character '"' at end of key file
```

**Comment by guagualvcha** [comment]
![image](https://user-images.githubusercontent.com/7310198/125056575-f30add80-e0da-11eb-947b-48f8d0e03dce.png)
The keyfile is expected to contain unencrypted private key, obviously the newly generated keystore file does not meet the requirement.
