### ISSUE TITLE
make geth failed

### ISSUE THREAD

**Issue by songning4** [binance-chain/bsc#281]
added GOPATH to PATH environment

```
export GOPATH=/usr/local/go/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
```
`source /etc/profile`

`git clone https://github.com/binance-chain/bsc`
`cd bsc`
`make geth`

```

env GO111MODULE=on go run build/ci.go install ./cmd/geth
go: github.com/btcsuite/btcd@v0.20.1-beta requires
	github.com/davecgh/go-spew@v0.0.0-20171005155431-ecdeabc65495: invalid version: git fetch --unshallow -f origin in /usr/local/go/go/pkg/mod/cache/vcs/d9a489aa71aa9542aea8f66dfdd8c20fc0c90a8f7154b9b36206e404c9b1551e: exit status 128:
	fatal: git fetch-pack: expected shallow list
make: *** [geth] Error 1


```

Compilation failed, please help me, thanks!

**Comment by guagualvcha** [comment]
hi, @songning4, what is the version of golang are you using?

**Comment by songning4** [comment]
> hi, @songning4, what is the version of golang are you using?

The golang version is 1.15

**Comment by guagualvcha** [comment]
`github.com/btcsuite/btcd@v0.20.1-beta` have ever released twice.. so cause a lot of issues, you can clean the `$GOPATH/pkg` first and try again

**Comment by guagualvcha** [comment]
Close the issue, since it is not occur in latest release
