### ISSUE TITLE
How to know current number of known states ?

### ISSUE THREAD

**Issue by JosephInGithub** [binance-chain/bsc#284]
Hello there,

I have been trying to sync my node for a bit more than two weeks.
This is what I get when I use the eth.syncing function:

 eth.syncing
{
  currentBlock: 8184676,
  highestBlock: 8184795,
  knownStates: 2142912973,
  pulledStates: 2142628040,
  startingBlock: 0
}

It seems like it keeps going on forever. I think I had already seen people sync with way less known states.

So I was wondering if you had any idea what could be wrong and if there was a way to know the current number of known states somewhere ?

Best regards,

Joseph

**Comment by n8twj** [comment]
Hi - Unfortunately, that means your server is not capable of syncing up.
You need a current, multi-core server with an NVMe drive to be able to
catch up to the head of the blockchain.

>

**Comment by ravinayag** [comment]
Do [refer #245](https://github.com/binance-chain/bsc/issues/245) this conversation

**Comment by guagualvcha** [comment]
close due to duplicate issue.
