### ISSUE TITLE
eth_getBlockByHash returning undefined for `result.response.transactions`

### ISSUE THREAD

**Issue by redred77** [binance-chain/bsc#286]
#### System information

Used host in `bsc-dataseed1.binance.org`

#### Expected behaviour
`eth_getBlockByHash` should return correct result when the result is succeeded

#### Actual behaviour
The returned `response.transactions` property is undefined sometimes even the result says it's succeeded

#### Steps to reproduce the behaviour
call eth_getBlockByHash several times for each block. It happens within few hours.

#### Another note
Seems like it also happens on `eth_blockByNumber` call too.
the `error` field is not filled, which means it succeded but the response.hash is not valid.

**Comment by kyrie-yl** [comment]
i can't reproduce this problem, can you show your response when the undefined happened?

**Comment by kyrie-yl** [comment]
> #### System information
> Used host in `bsc-dataseed1.binance.org`
> 
> #### Expected behaviour
> `eth_getBlockByHash` should return correct result when the result is succeeded
> 
> #### Actual behaviour
> The returned `response.transactions` property is undefined sometimes even the result says it's succeeded
> 
> #### Steps to reproduce the behaviour
> call eth_getBlockByHash several times for each block. It happens within few hours.
> 
> #### Another note
> Seems like it also happens on `eth_blockByNumber` call too.
> the `error` field is not filled, which means it succeded but the response.hash is not valid.

which sdk did you use? And can you show some detail , for example, the panic stack when the undefined happended.
