### ISSUE TITLE
Nodes monitoring system

### ISSUE THREAD

**Issue by phu-tang-tiki** [binance-chain/bsc#287]
Hi guys,

I cloned and built full nodes then joined bsc network (testnet). But I have a question, do we have any tool to monitor node (network, pending pool, connection, syncing status on web. I used ethstats on Ethereum but can't find something similar on bsc. Could you guys can help?

**Comment by barryz** [comment]
Section `Montoring` in document: https://blog.ethereum.org/2019/07/10/geth-v1-9-0/   

I hope it can help you.

**Comment by phu-tang-tiki** [comment]
thanks, let me check

**Comment by phu-tang-tiki** [comment]
thanks, seem it's working
