### ISSUE TITLE
No response from eth_subscribe on newHeads and newPendingTransactions

### ISSUE THREAD

**Issue by chenyuejie** [binance-chain/bsc#292]
I have setup a full node and it sync successfully. But when I make subscriptions through websocket, there are no response for newHeads and newPendingTransacitons. Subscription on logs and syncing works fine.

Did I missed some configuration?

**Comment by VenkatTeja** [comment]
+1

**Comment by guagualvcha** [comment]
I can help check if you can upload the example code.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
