### ISSUE TITLE
Geth crashes at startup w/ no error messages

### ISSUE THREAD

**Issue by doplumi** [binance-chain/bsc#300]
Just setting up a new node, I run geth via 
`geth --config ./config.toml --datadir ./node  --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0`, get logs:

```
INFO [06-21|11:00:04.366] Starting Geth on Ethereum mainnet...
INFO [06-21|11:00:04.370] Maximum peer count                       ETH=30 LES=0 total=30
INFO [06-21|11:00:04.370] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [06-21|11:00:04.370] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
```

*./node/bsc.log* contains:

```
t=2021-06-21T11:06:36+0200 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=18000 updated=10705
t=2021-06-21T11:06:36+0200 lvl=info msg="Set global gas cap"                 cap=25,000,000
t=2021-06-21T11:06:36+0200 lvl=info msg="Allocated trie memory caches"       clean="2.61 GiB" dirty="2.61 GiB"
t=2021-06-21T11:06:36+0200 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/bsc/node/geth/chaindata cache="5.23 GiB" handles=524,288
t=2021-06-21T11:06:36+0200 lvl=info msg="Opened ancient database"            database=/home/ubuntu/bsc/node/geth/chaindata/ancient readonly=false
t=2021-06-21T11:06:36+0200 lvl=warn msg="Found genesis block without chain config"
```

Any idea on what to do? Is the last warning here causing the crash?

**Comment by ares0x** [comment]
> Just setting up a new node, I run geth via
> `geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0`, get logs:
> 
> ```
> INFO [06-21|11:00:04.366] Starting Geth on Ethereum mainnet...
> INFO [06-21|11:00:04.370] Maximum peer count                       ETH=30 LES=0 total=30
> INFO [06-21|11:00:04.370] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> WARN [06-21|11:00:04.370] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
> ```
> 
> _./node/bsc.log_ contains:
> 
> ```
> t=2021-06-21T11:06:36+0200 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=18000 updated=10705
> t=2021-06-21T11:06:36+0200 lvl=info msg="Set global gas cap"                 cap=25,000,000
> t=2021-06-21T11:06:36+0200 lvl=info msg="Allocated trie memory caches"       clean="2.61 GiB" dirty="2.61 GiB"
> t=2021-06-21T11:06:36+0200 lvl=info msg="Allocated cache and file handles"   database=/home/ubuntu/bsc/node/geth/chaindata cache="5.23 GiB" handles=524,288
> t=2021-06-21T11:06:36+0200 lvl=info msg="Opened ancient database"            database=/home/ubuntu/bsc/node/geth/chaindata/ancient readonly=false
> t=2021-06-21T11:06:36+0200 lvl=warn msg="Found genesis block without chain config"
> ```
> 
> Any idea on what to do? Is the last warning here causing the crash?

Are you sure that your machine has enough configuration?
