### ISSUE TITLE
Verbose and useful log output during the initial sync

### ISSUE THREAD

**Issue by miohtama** [binance-chain/bsc#301]
The normal `geth` writes some information about the sync state to the stdout.

E.g.

```
INFO [06-22|15:04:16.569] Imported new block receipts              count=299  elapsed=949.848ms   number=5,133,062  hash=befc64..8fa05f age=3y4mo2w   size=11.12MiB
```

Is there any way to have Binance Smart Chain geth to do the same? Looks like `--verbosity 5` does not add any more useful messages.

**Comment by zhongfu** [comment]
the default `config.toml` causes geth to log to a file instead of to stdout

try checking `node/bsc.log`, or removing the logging configuration directive(s) if you want the output to go to stdout instead

**Comment by guagualvcha** [comment]
@zhongfu have given the correct advise, will close this issue.
