### ISSUE TITLE
Can not start geth ?

### ISSUE THREAD

**Issue by mkroxm** [binance-chain/bsc#303]
./geth --config ./config.toml --datadir ./node  --syncmode light --ws --http --cache 378 --light.maxpeers 50
INFO [06-28|23:50:59.003] Starting Geth on Ethereum mainnet...
INFO [06-28|23:50:59.006] Maximum peer count                       ETH=0 LES=50 total=50
INFO [06-28|23:50:59.006] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [06-28|23:50:59.006] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

Please help me to fix this

**Comment by zhongfu** [comment]
did you remember to init geth with the genesis file? see steps 2 and 3 from [here](https://docs.binance.org/smart-chain/developer/fullnode.html#steps-to-run-a-fullnode):

```
wget https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/mainnet.zip
unzip mainnet.zip

geth --datadir ./node init genesis.json
```

**Comment by rainwater11** [comment]
> did you remember to init geth with the genesis file? see steps 2 and 3 from [here](https://docs.binance.org/smart-chain/developer/fullnode.html#steps-to-run-a-fullnode):
> 
> ```
> wget https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/mainnet.zip
> unzip mainnet.zip
> 
> geth --datadir ./node init genesis.json
> ```

I am having the same issue and yes I did do those steps.

**Comment by mkroxm** [comment]
> did you remember to init geth with the genesis file? see steps 2 and 3 from [here](https://docs.binance.org/smart-chain/developer/fullnode.html#steps-to-run-a-fullnode):
> 
> ```
> wget https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/mainnet.zip
> unzip mainnet.zip
> 
> geth --datadir ./node init genesis.json
> ```

geth --datadir ./node init genesis.json was sucessfull but getting error on 
./geth --config ./config.toml --datadir ./node --syncmode light --ws --http --cache 378 --light.maxpeers 50 

Wants to run light node is there any changes needed for light node
