### ISSUE TITLE
light Node install failed 

### ISSUE THREAD

**Issue by mkroxm** [binance-chain/bsc#306]
Is there any documentations available for install light node using command   

git clone https://github.com/binance-chain/bsc
cd bsc
make geth
wget https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/mainnet.zip
unzip mainnet.zip
geth --datadir node init genesis.json
./geth --config ./config.toml --datadir ./node --syncmode light --ws --http --cache 378 --light.maxpeers 50

Getting output 

INFO [06-28|23:50:59.003] Starting Geth on Ethereum mainnet...
INFO [06-28|23:50:59.006] Maximum peer count ETH=0 LES=50 total=50
INFO [06-28|23:50:59.006] Smartcard socket not found, disabling err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [06-28|23:50:59.006] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

Please help me to fix this

**Comment by guagualvcha** [comment]
hi, there. Here is what I did to start a light node and it works fine:
![image](https://user-images.githubusercontent.com/7310198/124913496-c3e46580-e021-11eb-876d-0667689a0658.png)

What is suspicious  is the log `Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000`,  can you double check the version of the used `geth`?

**Comment by osizadmin** [comment]
If we use the syncmode light withdraw function not working. showing this kind of transaction.

https://bscscan.com/tx/0x4057029493d4301a5e40e4c83ff1f8ed1038b87ee539e9f9842f2b08dc854c2e

How to resolve this issue.

**Comment by kyrie-yl** [comment]
> If we use the syncmode light withdraw function not working. showing this kind of transaction.
> 
> https://bscscan.com/tx/0x4057029493d4301a5e40e4c83ff1f8ed1038b87ee539e9f9842f2b08dc854c2e
> 
> How to resolve this issue.

this link can't open
