### ISSUE TITLE
pcie 3.0 ?or, nvme ssd pcie 4.0 is a must ？？ 

### ISSUE THREAD

**Issue by gongyaodon** [binance-chain/bsc#307]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

**Comment by zhongfu** [comment]
a mid- to high-end PCIe 3.0 NVMe SSD should be enough. preferably TLC with DRAM, or something like that

(anecdotally, I've managed to fast sync and run a node on an **enterprise** SATA SSD, but I'd still recommend that you go with a good NVMe SSD. I'm using a mix of Hynix P31s and Samsung PM981/PM981a/970 Evo etc. on my NVMe nodes)

**Comment by guagualvcha** [comment]
The fast sync may have a high requirement to SSD,  I recommend that you download the latest snapshot from here: https://github.com/binance-chain/bsc-snapshots

**Comment by guagualvcha** [comment]
Will close this issue cause it is only enquire.
