### ISSUE TITLE
Stake Wars Rewards Claim

### ISSUE THREAD

**Issue by huangsuyu** [binance-chain/bsc#31]

**Comment by tigdar** [comment]
{
  "address": "0x0af7d8b7d4eb50fa0eddd643d11120c94ad61248",
  "msg": "bnb149m2zlvnn223yk28wjjxwurlmu5nmeg7ew4us0",
  "sig": "0x956c73f435450df67a8d3c8719ebd0e061c3060bbba689d13df39bfa9b048a4d531374b407b722179ab56ab160dba3482ec68130629cc05a29cfd201c8cae0f01c",
  "version": "3",
  "signer": "MEW"
}

**Comment by Metas-taz** [comment]
{
  "address": "0xbc93f0661a49822b66b07e0727848ed3598551e0",
  "msg": "bnb1rydsekq4283qfcudfkzevsge9u7kl7xfke68p7",
  "sig": "0x51df018cddf18fd011929b397e3208dc4a1e054dd836d8322093ca2ad526d5c0790dbc50a0936f10d6ba7aa4f13dad4dce0bdd26fe229c9f7e0323fed7c295811c",
  "version": "3",
  "signer": "MEW"
}

**Comment by utkarsssh17** [comment]
{
  "address": "0xa2e5f9e8db4b38ac8529f79c4f3b582952b3d3dc",
  "msg": "bnb16nwsuwgqzwaxljufw7u4zt3vqs6l6fxjwrd9wh",
  "sig": "0xb6697e14bfc3cb4b2ff579e30042437691c10ab65e8ae386c5188e423d00b7180de59bb403c41ac3d21e0c34e2c6a001f14ecf263ca55dacb6ef71abd389bd971c",
  "version": "3",
  "signer": "MEW"
}

**Comment by zzzTheWinner** [comment]
{
  "address": "0x3efb67b34a9b69b54d4027e044954f483dc31678",
  "msg": "bnb10sem3qt9hrm45cmdh9w6h7ulllp5u2m0ylqjkz",
  "sig": "0x3c7eb87bafa0e44b7c0d88d8159318146589ef5c452bd281a566e2c61a136a1e14eed74ec385f44c1e82d8922f2037b8f9f45e5a4ec277cfacb7e65ee02b5fdc1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by redredemptionmark** [comment]
{
  "address": "0x4083dcf5ba3d1506e3d43067cdbe262124adbf8f",
  "msg": "bnb1znctahduy0v35l9qg2vj9d3cj2z0kxw3g6q07t",
  "sig": "0xfb460106737d66fc769cc1a007089e0310869f0b6308c0be32e881df2d997df01c6bd5477c98666ffbd42875e6295903d750ef0a92c595a2fb9523390c47ec1d1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by vallenheim** [comment]
{
  "address": "0x36e45ae758af73e12af7629e04223ad8e18852df",
  "msg": "bnb19af5x08zrscq2zk2ln7qln0dpe39cm240uu6m0",
  "sig": "0x7880f54ef88a282cde75804bd20679695b94d857765b8a466c4e39287963cacd1a7f62dca2342434df957a507a94b4e2d8d5df68631634175b1686e5fffb8cca1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by akash-akatsuki** [comment]
{
  "address": "0x93f1e5cb95fbb4e1a76b1bbd16ff57a4fe470e2e",
  "msg": "bnb1gccnu0nqc0jf7qdde2qjzfat2gsg2cvanhsnd7",
  "sig": "0x712999d0b9d20f84e96e6e2a4ae677984c3876a2f110240b22bf808a45d97514694bd2b24ce8203d77168179606490845de9a17e362a8b98fbf55b5fd22f79071b",
  "version": "3",
  "signer": "MEW"
}

**Comment by baliant-balina** [comment]
{
  "address": "0x1580bdf1405d094d24a40115ac4ca7bf68d95d2c",
  "msg": "bnb1e4j8fvutdueghedjqjyfpstqysszjvcm2p4ldl",
  "sig": "0xeffbefb496aa7251fa2f8c15d84e19e204609bd390f03705d54af1b96cf2fead0255068437786139ce17212e36eefd7f6c98f9eb8c40bc49b10e7725c08c1c851b",
  "version": "3",
  "signer": "MEW"
}

**Comment by veryclerkbedroom** [comment]
{
  "address": "0x4d40e48c34e6c9b6ba7a62ab6adde570aeca8ce5",
  "msg": "bnb18mx90rsdnd4nx9m8kkvmuvtd4hhcnxgzmzwpqe",
  "sig": "0xbf7b11a7233695c347d22dd6e621fd8529e6efa696ec533dff71b31c130db0954bf411abc0eb960d2c494b08649f8a24518f18dcd4589578f42a9a870a104d6d1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by eigen-eisen** [comment]
{
  "address": "0x977ecef7de795cd248d77fd0d080ce3a35dec013",
  "msg": "bnb1vag023d83hw0m6fskkwufgacclu52ctu4jjrst",
  "sig": "0xa210edcba6109f6543d9ad32c5e9a9f003a16afc6fd120ca50c17406778c6a8a47c8821e2813da76507148a0770a574884386432565b1521b78cd6a4946ed4a61b",
  "version": "3",
  "signer": "MEW"
}

**Comment by dare-dandelion** [comment]
{
  "address": "0x2780f0adc57f9f3c49d11adf1ab0e49b519a9728",
  "msg": "bnb1p7j3rssxx69wxccrdh58nxyx9lvmcl3gxr6cye",
  "sig": "0x8c5be5b9b6400dbe78a8d50d06213ee8ded3d2d31b59b46410a7bdd1660d7b7861afb19a09a8e4bdf32b9eabae74d41ccaf2db120e2a01db7d12205157b96f541b",
  "version": "3",
  "signer": "MEW"
}

**Comment by chrono-chavez** [comment]
{
  "address": "0xe657961fc9775db22c70d9f0f4330acab7a931d1",
  "msg": "bnb1mwa433k6wqamzccp73accrhsp4qheff606lup5",
  "sig": "0x75bd9a828bd476f01a9b56db7f76704dc5c3f3fd91221bf9cce8b19c0ed0c09b0a9b35d1a581be71f7f0f8b8e01606d19dcbd0af2a145ed4746403bb0f7800ac1b",
  "version": "3",
  "signer": "MEW"
}

**Comment by jaygaga** [comment]
{
  "address": "0xcdd7de033e5b313ef95a4492903656d2d0276d1e",
  "msg": "bnb1g85fpa2fwactsv2jj2gf2vt5kz65vp4zuzh8ns",
  "sig": "0xa6296a34b793b8ec176f82aaec2d9723f1a96e1f97546697a781e81773d3504e303a4dd2456866c403ddf886891474d191137f9d6876ba8bf02bf9fc38dfcd741b",
  "version": "3",
  "signer": "MEW"
}

**Comment by huobicapital** [comment]
{
  "address": "0x23f8c9e58035c830bd5d3a782f50e36be47991a4",
  "msg": "bnb1yx06tcpzv0lxg4kr7ewqr0tu7d6mt9gzdr8s27",
  "sig": "0x21a2be4434069a92a5cf3730f5e5d03d4026b1ef3aea3ac19d81b1dd355fb0687cd85710b6eb83ff3be36064836254fa5b49160a54ad44a10a2b67557aa274201c",
  "version": "3",
  "signer": "MEW"
}

**Comment by verycoon** [comment]
{
  "address": "0x2a08b1fe372860a22c70cc7285aff985ded624c6",
  "msg": "bnb19ylksz8x40xa88229cr0n9hjcnpz0l2qk58hns",
  "sig": "0xa7a3a2a5c359872fbae0f51422186cd088ee5d563d6e60befc811aabf1784fb6383e0fede69d4cbd93a96489adeff6d142019d5d44505cf83b8515ade0f55ee41b",
  "version": "3",
  "signer": "MEW"
}

**Comment by BNB48ClubSirIan** [comment]
> {
> "address": "0x3efb67b34a9b69b54d4027e044954f483dc31678",
> "msg": "bnb10sem3qt9hrm45cmdh9w6h7ulllp5u2m0ylqjkz",
> "sig": "0x3c7eb87bafa0e44b7c0d88d8159318146589ef5c452bd281a566e2c61a136a1e14eed74ec385f44c1e82d8922f2037b8f9f45e5a4ec277cfacb7e65ee02b5fdc1c",
> "version": "3",
> "signer": "MEW"
> }

Hello, zzz
Can you please contact me ? sirian@bnb48.club

**Comment by pedraoooo** [comment]
{
  "address": "0x9b51d5c0dc20b732fe6ae831f9b5c1574c545364",
  "msg": "bnb1fscukcpwnxnl0lqsl99hjsaw4kre55qqcusdpn",
  "sig": "0x411e8e5126a92a2584a6dd998bc962cdaeb4070ee55dbd201b0ffc83e474c4a306bd03cffb15ec390f482ed9f0de332226e9779b047b7f67aa08ffbdb9cb44241b",
  "version": "3",
  "signer": "MEW"
}

**Comment by generousity** [comment]
{
  "address": "0x441795acc9183cacf0b69083770ab0c627bf4ee1",
  "msg": "bnb1qqlg4r0dffkaqy52stj3hte6s582s77vgde3gy",
  "sig": "0x089224d10e2f2391486927e5fd39ed771f1f98913604e0141158350385f3a9b60571b4f29b827685a9d914711bbd777c4c4528994d587332da5d924584138abb1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by punjabishaw** [comment]
{
  "address": "0x03073aedceaeeae639c465a009ee1012272d20b4",
  "msg": "tbnb1eku43p7pzpc03glm7g4knmedm665l9tpq92s9h",
  "sig": "0x5f31d16a4f5aaeac32e058cf8a996ea04e6c7756e55ba466b99939ef9103f3d9794a5e07cb8b5d03729c6b701e0a1082c08006ddb94b45ee74a1a654d57987d71b",
  "version": "3",
  "signer": "MEW"
}

**Comment by punjabishaw** [comment]
{
  "address": "0x03073aedceaeeae639c465a009ee1012272d20b4",
  "msg": "bnb1nezy5z7v067fpdm0u5snskdu4e5z5n282h69vm",
  "sig": "0x6ad4ac880710887d831b7b8169babaf8c31784f98ce38e0f79ef48bf4b3964b52ba76b081ba0c6395bdaad958d8e157d6f2e3a32b802f7899218b75296200f081b",
  "version": "3",
  "signer": "MEW"
}

**Comment by punjabishaw** [comment]
{
  "address": "0xf9de5e94fda4c861fced1b1ef3eb77c0aacb1611",
  "msg": "bnb1nezy5z7v067fpdm0u5snskdu4e5z5n282h69vm",
  "sig": "0x7c6fa464eaf25f4254c1e88ba8ad3d3196cb0d9dbd4552fb40733d302d85fcb10c0f061c6bc2be791c43a8504fd3229543b94b8551c3f218fad88279c689f3531c",
  "version": "3",
  "signer": "MEW"
}

**Comment by shacklertr** [comment]
{
  "address": "0x5ac1e500a5e2f4b67241e2986baf4383ee9debfe",
  "msg": "bnb18x64edglf5m0d962lmccjsdq8t3288zuzwwvxt",
  "sig": "0x8b1db32332a2f4e748240a1a94908ed13e8252f66ac626d7bcc1421e261979dc26a75d21f00a228fc3097ad18faea48fb54dcb790d7a180a9a83bd509727e12d1b",
  "version": "3",
  "signer": "MEW"
}

**Comment by duduzhu** [comment]
{
  "address": "0x3efb67b34a9b69b54d4027e044954f483dc31678",
  "msg": "bnb10sem3qt9hrm45cmdh9w6h7ulllp5u2m0ylqjkz",
  "sig": "0x3c7eb87bafa0e44b7c0d88d8159318146589ef5c452bd281a566e2c61a136a1e14eed74ec385f44c1e82d8922f2037b8f9f45e5a4ec277cfacb7e65ee02b5fdc1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by BNB48ClubSirIan** [comment]
{
  "address": "0x23f8c9e58035c830bd5d3a782f50e36be47991a4",
  "msg": "bnb1yx06tcpzv0lxg4kr7ewqr0tu7d6mt9gzdr8s27",
  "sig": "0x21a2be4434069a92a5cf3730f5e5d03d4026b1ef3aea3ac19d81b1dd355fb0687cd85710b6eb83ff3be36064836254fa5b49160a54ad44a10a2b67557aa274201c",
  "version": "3",
  "signer": "MEW"
}

**Comment by BNB48ClubSirIan** [comment]
{
  "address": "0x2a08b1fe372860a22c70cc7285aff985ded624c6",
  "msg": "bnb19ylksz8x40xa88229cr0n9hjcnpz0l2qk58hns",
  "sig": "0xa7a3a2a5c359872fbae0f51422186cd088ee5d563d6e60befc811aabf1784fb6383e0fede69d4cbd93a96489adeff6d142019d5d44505cf83b8515ade0f55ee41b",
  "version": "3",
  "signer": "MEW"
}

**Comment by duduzhu** [comment]
{
  "address": "0x4083dcf5ba3d1506e3d43067cdbe262124adbf8f",
  "msg": "bnb1znctahduy0v35l9qg2vj9d3cj2z0kxw3g6q07t",
  "sig": "0xfb460106737d66fc769cc1a007089e0310869f0b6308c0be32e881df2d997df01c6bd5477c98666ffbd42875e6295903d750ef0a92c595a2fb9523390c47ec1d1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by duduzhu** [comment]
{
  "address": "0x4d40e48c34e6c9b6ba7a62ab6adde570aeca8ce5",
  "msg": "bnb18mx90rsdnd4nx9m8kkvmuvtd4hhcnxgzmzwpqe",
  "sig": "0xbf7b11a7233695c347d22dd6e621fd8529e6efa696ec533dff71b31c130db0954bf411abc0eb960d2c494b08649f8a24518f18dcd4589578f42a9a870a104d6d1c",
  "version": "3",
  "signer": "MEW"
}

**Comment by suattavsan** [comment]
{
  "address": "0x8c24ecc5bca58df83cf2a8bd6a2adfc053c9c854",
  "msg": "bnb1g7jnjyk94xld9sxnmg2aqz8e2d5q6u7lnehtcy",
  "sig": "0x7217b43fd2b6e94081a6dd4cde278b0b616d51782618f766236ee780bc36460d5ce375813c233af74bf2851dec3a6d011e00a884f1fa48934be7ae59f9942df51c",
  "version": "3",
  "signer": "MEW"
}

**Comment by w1sej** [comment]
{
  "address": "0x58195c07561efc5572555533cac00496f7ade196",
  "msg": "bnb1xvq2zqtj8m0sfqggzjnksv66r7vysufp7kcegc",
  "sig": "0x72c4109eb2a8c3ec889ddcd6b12bda25d5c0058cb2af1195ef482eb5732e08193f9c6ad6ee2f0efca8fccfd51b96296626d13a05c622b8e37c9a02dcad9879f21b",
  "version": "3",
  "signer": "MEW"
}
