### ISSUE TITLE
debug.traceBlockByNumber is brocken via IPC but works via RPC

### ISSUE THREAD

**Issue by vlads123** [binance-chain/bsc#311]
#### System information

Geth version: 
````
Geth
Version: 1.1.0-beta
Git Commit: 032970b2deeffe3b7f87703753d7be9a09906758
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=go
````

OS & Version: Linux 
Commit hash : Official release, installed  from binaries
#### Expected behaviour
I can get tracesByBlockNumber of the last `latest-128` via RPC and IPC interfaces

#### Actual behaviour
debug_tracesByBlockNumber via RPC works fine
if I request debug.tracesByBlockNumber in IPC it just locks up on the command(I waited about 1 hour and still no reply). 

#### Steps to reproduce the behaviour
````
$ geth attach ./geth.ipc 
> eth.blockNumber
XXXXXX
> debug.traceBlockByNumber(XXXXXX)
````
last command just lock up
#### Backtrace

No any output in logs or terminal

![image](https://user-images.githubusercontent.com/84506373/124673514-0bc59880-df0d-11eb-9907-3a80dd927db0.png)

**Comment by guagualvcha** [comment]
Hi, the usage of console maybe wrong, I just tried following command and it works:
```
debug.traceBlockByNumber("0x100", {"tracer": "callTracer"})
```

**Comment by guagualvcha** [comment]
Seems not a valid issue here, will close first. Feel free to reopen the issue.
