### ISSUE TITLE
command to start the bsc full mainnet node in linux.

### ISSUE THREAD

**Issue by lokeshratnam09** [binance-chain/bsc#313]
Please give me a command to start the bsc full mainnet node in linux.

I already run this command -    sudo ./geth_linux  --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0

and gets this error - 
INFO [07-09|15:32:59.541] Starting Geth on Ethereum mainnet...
INFO [07-09|15:32:59.545] Maximum peer count                       ETH=30 LES=0 total=30
INFO [07-09|15:32:59.545] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [07-09|15:32:59.545] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

kindly help me to give any suggestions to i proper run bsc mainnet node.
Thank you

**Comment by 0fuz** [comment]
hello, I doesn't saw this error but was faced with wrong file system which can't create IPC sockets

**Comment by lokeshratnam09** [comment]
@0fuz  if you successfully install BSC Mainnet node , then kindly share the commands or documents  that you have used during install bsc mainnet node through linux.

**Comment by Dondudu** [comment]
Is your config.toml in the correct directory?

**Comment by zhongfu** [comment]
did you write the genesis state to your local chaindata

```
geth --datadir node init genesis.json
```

**Comment by lokeshratnam09** [comment]
> Is your config.toml in the correct directory?

@Dondudu  config.toml i put in /home/ubuntu directory in linux.  then after run the above command i already mention on the top but was getting the same error.
so if you run sucessfully bsc mainnet node  kindly share the steps. because i stuck now why i getting this kind of error again and again.
Thank you

**Comment by lokeshratnam09** [comment]
> did you write the genesis state to your local chaindata
> 
> ```
> geth --datadir node init genesis.json
> ```

@zhongfu ya i already run this command before run this -  sudo ./geth_linux --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0
But  i getting same error.

**Comment by guagualvcha** [comment]
you may remove the datadir and run `geth --datadir node init genesis.json` again.   Please refer to https://github.com/binance-chain/bsc/issues/338, just download the snapshot rather than start from genesis.
