### ISSUE TITLE
debug_standardTraceBlockToFile returns error -32000

### ISSUE THREAD

**Issue by maxogden** [binance-chain/bsc#314]
#### System information

Geth version: `1.1.0-beta`
OS & Version: Linux

#### Expected behaviour

I'm trying to call debug_standardTraceBlockToFile as soon as block is mined (to index internal transactions). I'd like to use debug_standardTraceBlockToFile over debug_traceBlock because debug_traceBlock requires a *lot* of CPU due to the ~3s block time. It should return the list of files in `/tmp` that the traces were written to.

#### Actual behaviour

For most blocks I get an error like this as a response:

```
{"code":-32000,"message":"insufficient funds for transfer: address 0x2D4C407BBe49438ED859fe965b140dcF1aaB71a9"}
```

#### Steps to reproduce the behaviour

First grab the latest block:

```
{
  jsonrpc: '2.0',
  method: 'eth_getBlockByNumber',
  params: [ 'latest', false ],
  id: 1
}
```

Then grab `result.hash` from the response and try to trace that block:

```
{
  jsonrpc: '2.0',
  method: 'debug_standardTraceBlockToFile',
  params: [
    '0xc93407012e1a758d0dad966e65878a1ce4ec2f8ebfc72dea0ecc83985a2b0c1b',
    {
      disableMemory: true,
      disableStorage: true,
      disableStack: true,
      tracer: 'callTracer',
      reexec: 6000000
    }
  ],
  id: 1
}
```

I also experimented with removing all the options in the param and I still got the high error rate, but each trace call took longer

**Comment by voronindev** [comment]
I have the same issue

**Comment by voronindev** [comment]
I have the same issue!

**Comment by voronindev** [comment]
I have the same issue!!

**Comment by kozhevnikov-peter** [comment]
I have the same issue!!

**Comment by voronindev** [comment]
I have the same issue

**Comment by guagualvcha** [comment]
fixed in https://github.com/binance-chain/bsc/pull/374
