### ISSUE TITLE
Nodes can no longer submit transactions

### ISSUE THREAD

**Issue by rainwater11** [binance-chain/bsc#318]
#### System information

Geth version: `v1.1.0-beta`
OS & Version: Ubuntu 20.04

#### Expected behaviour
My node used to be able to submit transactions normally just fine without being stuck "pending". Now, it doesn't work. I have even tried a new server and a new node on several different hosts. None of them work! I have even opened port 30303 which actually worked for a short time but then for some reason, regressed back to the original problem.

I have even tried different nodes from different blockchains on the exact same server and submitting transactions works perfectly. However, this is not the case on the bsc node.

#### Actual behaviour
When submitting a transaction to pancakeswap, the geth log shows "Submitted transaction". After pasting the hash into bscscan.com, it shows as "pending" and stays as such and never actually finishes. 

#### Steps to reproduce the behaviour
Try spinning up a new node on a new server and then submit a transaction. Specifically a transaction through Pancakeswap.

**Comment by Undead8** [comment]
If you see it pending on bscscan.com, it means that the node did send it properly. If it is not validated, you most likely have a gas price or nonce issue. The bsc node is not the problem.

**Comment by guagualvcha** [comment]
I don't think BSC has such issue. Can you check whether your node is lagged?
