### ISSUE TITLE
fast sync takes more than three weeks.

### ISSUE THREAD

**Issue by CNLHC** [binance-chain/bsc#319]
I am trying to set up a full node by following the instructions in the [BSC-Doc](https://docs.binance.org/smart-chain/developer/fullnode.html). Without any extra configuration, i believe that i am using the "fast sync" mode.

I totally understand that downloading the state is a slow process. But i think it is abnormal for this process to take more than 3 weeks.

My machine has 32GiB RAM and 8 cores, equipped with 1TiB SSD driver , which meets the suggested requirements in the BSC website.

Currently the `knownStates` field from `eth.syncing` is `1605196693`, and it is increasing by about 4000-10000 every seconds.

```
> eth.syncing
{
  currentBlock: 9253432,
  highestBlock: 9253496,
  knownStates: 1605196693,
  pulledStates: 1605191168,
  startingBlock: 9227812
}
```

Do you have any suggestions?

**Comment by n8twj** [comment]
if it takes more than 48 hours, get faster hardware

**Comment by zhongfu** [comment]
> I am trying to set up a full node by following the instructions in the [BSC-Doc](https://docs.binance.org/smart-chain/developer/fullnode.html). Without any extra configuration, i believe that i am using the "fast sync" mode.
> 
> I totally understand that downloading the state is a slow process. But i think it is abnormal for this process to take more than 3 weeks.
> 
> My machine has 32GiB RAM and 8 cores, equipped with 1TiB SSD driver , which meets the suggested requirements in the BSC website.
> 
> Currently the `knownStates` field from `eth.syncing` is `1605196693`, and it is increasing by about 4000-10000 every seconds.
> 
> ```
> > eth.syncing
> {
>   currentBlock: 9253432,
>   highestBlock: 9253496,
>   knownStates: 1605196693,
>   pulledStates: 1605191168,
>   startingBlock: 9227812
> }
> ```
> 
> Do you have any suggestions?

is your SSD directly attached to the node hardware (e.g. **not** AWS EBS, etc), and is it being shared by other people or otherwise bottlenecked

are you using a suitable fs (zfs with large recordsize will probably wreck your sync performance)

**Comment by j75689** [comment]
Hi all.
Thank you for your report.
We have received many report of a sync issue.
You can try the latest version. If you have any problems, please feedback #338.
We will pay attention to the issue #338 for a long time, and if there are any updates, we will explain it on this issue.

Thanks.
