### ISSUE TITLE
Storage issue in Binance Smart Chain

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#320]
#### System information

Geth version: `1.10.3-stable`
OS & Version: Linux

Setup private network of BSC node in AWS server. It runs maximum 1 day then it will produce **"Runtime out of memory error"**
 How much memory it will take?
 How to solve this issue?

**Comment by j75689** [comment]
Modify your `--cache` size to be less than 1/3 of the total memory may help.

**Comment by guagualvcha** [comment]
Actually 1/4 is more safe.
