### ISSUE TITLE
Web3.js connection local geth cannot be accessed

### ISSUE THREAD

**Issue by pennchester** [binance-chain/bsc#321]
startup code
`geth --datadir ./nodeTest --config ./config.toml --ws --ws.port 5476 --ws.api eth,net,web3 --syncmode light`

js:
`let web3 = new Web3('ws://localhost:8576');`
console:
WebSocket connection to 'ws://localhost:8576/' failed:

**Comment by kyrie-yl** [comment]
you start the geth at port 5476, but connect to port 8576
