### ISSUE TITLE
Node synchronization slow

### ISSUE THREAD

**Issue by yqZhang711** [binance-chain/bsc#325]
Node synchronization is slow, always more than 2000 blocks away from the block browser, what is the solution?

**Comment by yqZhang711** [comment]
@fjl @guagualvcha @j75689 Node synchronization is slow, always more than 2000 blocks away from the block browser, what is the solution?

**Comment by wenchaopeng** [comment]
@yqZhang711 me too,how is going of your side?

**Comment by vae520283995** [comment]
In the past two days, it is often found that the synchronization cannot catch up with the block generation

**Comment by vietthang207** [comment]
Me too, I am using v1.0.7-ht.3-deploy

**Comment by yqZhang711** [comment]
> @yqZhang711 me too,how is going of your side?

I'm using the latest node (V1.1.0), but it's still unresolved！

**Comment by yqZhang711** [comment]
> In the past two days, it is often found that the synchronization cannot catch up with the block generation

Me too, I started yesterday, node synchronization speed is slower than block speed! Resulting in more and more block height difference

**Comment by vae520283995** [comment]
@guagualvcha need your help

**Comment by luoxiandong** [comment]
me too,  I am using v1.1.0

**Comment by wo4zhuzi** [comment]
Me too. I need the minimum conditions to catch up with the block.

such as:
cpu
disk
Memory

**Comment by wenchaopeng** [comment]
my node is still 1237 blocks behind, and the synchronization speed cannot keep up with the block generation speed

**Comment by jun0tpyrc** [comment]
> Me too. I need the minimum conditions to catch up with the block.
> 
> such as:
> cpu
> disk
> Memory

full mode: (with heavy rpc, 4 cores won't suffice) 8-core-cpu + nvme

archive mode: no idea, bottleneck seems on p2p for head blocks,  raid0 on aws gp3 ssd can catch up for old blocks but not from last day, running 16-core-cpu  machiness

**Comment by zhouhaw** [comment]
Me two, still can't catch the latest height with about 100 blocks. With 8-core + 32g + 640G nvme

**Comment by zhouhaw** [comment]
Still can't catch the latest height with about 100 blocks.  my node With 8-core + 32g + 640G nvme

**Comment by vshybalov** [comment]
Has the same issue after update to the 1.1.0-7822e9e26, the resolution  was to add the --txlookuplimit=0 option while starting the daemon. Seems like after update, it tried to do some unindexing job which, slowed down the sync.

Once I added the option, after approximately  one hour the sync started to run faster and was able to complete it.

**Comment by dracmic** [comment]
Taking in consideration that I have similar issue even with latest 1.1.0 release by using  --txlookuplimit=0 ... I still have the issue with 100 blocks behind in fast syncmode ... I don't know what happen but this is happening from last week. I tried 2-3 different server providers all with NVME and a lot of RAM and different location same issue: eth.blockNumber on 0 and pivot getting stalled so I get the issue with 3 minutes back blocks (~100blocks).

**Comment by vae520283995** [comment]
I am already 5,000 blocks behind

**Comment by LiZhengyan** [comment]
from 1.0.6 update to 1.1.0   but   5719 blocks behind
--txlookuplimit=0 is default  and syncmode  full  and fast  has try    but nothing

**Comment by j75689** [comment]
In the past few days, TPS has grown very fast, and the original hardware performance may not be able to meet the current speed.

We have also increased GasLimit to increase TPS, which may cause the block size to become larger, resulting in synchronization difficulties.

We provide several operations for reference:
1. Use the latest binary version.
2. Prune the data to reduce the amount of data or download the snapshot we provide.
3. Use the recommended AWS m5zn.3xlarge.

We will discuss how to improve synchronization performance asap.
If the community has any good ideas, you are welcome to submit your ideas.

Thanks all

**Comment by dracmic** [comment]
@j75689  I am using: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz with 18000 cache on running command (32 GB ram total ram), 2 x NVME Samsung put in raid0 ( to increase space) still no luck .... to get synced ... Also I've used a VPS with 10 core of  AMD EPYC 7282 16-Core Processor with 60GB of total system RAM and same cache setting I suppose NVME SSD which worked ... I have enough bandwithd. So can you suggest some settings ...

**Comment by dwjpeng** [comment]
> In the past few days, TPS has grown very fast, and the original hardware performance may not be able to meet the current speed.
> 
> We have also increased GasLimit to increase TPS, which may cause the block size to become larger, resulting in synchronization difficulties.
> 
> We provide several operations for reference:
> 
> 1. Use the latest binary version.
> 2. Prune the data to reduce the amount of data or download the snapshot we provide.
> 3. Use the recommended AWS m5zn.3xlarge.
> 
> We will discuss how to improve synchronization performance asap.
> If the community has any good ideas, you are welcome to submit your ideas.
> 
> Thanks all

Geth
Version: 1.1.0
Git Commit: 7822e9e2a1c11e5e9f989b740ba0166a9cd96db1
Architecture: amd64
Go Version: go1.16.3
Operating System: ubuntu 18.04(alyun), 
storage: essd  2.0T
net: 100M/S
cpu: 16C

syncing slower three days ago, I tried different syncmodes like snap and fast, it didn't work. now 9000 blocks behind.

**Comment by seonggwonyoon** [comment]
https://github.com/binance-chain/docs-site/commit/db2b4be7a7c784ff3c19f3e3679f1f0cb0b5a42e

The recommended specifications for BSC nodes have been updated today.
see this commit

**Comment by jun0tpyrc** [comment]
> [binance-chain/docs-site@db2b4be](https://github.com/binance-chain/docs-site/commit/db2b4be7a7c784ff3c19f3e3679f1f0cb0b5a42e)
> 
> The recommended system requirements for BSC nodes have been updated today.
> see this commit

could we add suggestion/estimation for `archive node` requirement too?  thanks

**Comment by jun0tpyrc** [comment]
seems won't be enough to let aws gp3 catch up gap using full node full syncmode as in doc, it's finalising slower than new blcok
```
c5.4xlarge
--syncmode=full --gcmode=full --snapshot=false --txlookuplimit=0 --cache.preimages
ebs gp3 2200GB  10000 iops 1000 MB/s
```
any tunings at filesystem / os level?

**Comment by dracmic** [comment]
@j75689  Hey I have suggestion to talk with the guys from CryptoBlades (SKILL) guys which are doing nft fights and transactions on blockchain maybe they can move the fight calls :) https://explorer.bitquery.io/bsc/calls

**Comment by kgcdream2019** [comment]
I have same issue, blocks are behind now 51750 ( 1 days 22hr)

**Comment by kgcdream2019** [comment]
my vps is   CPU 36 RAM 72  gp3 10000 IOPS 500 MB/S

**Comment by seonggwonyoon** [comment]
I am running 2 BSC Full Nodes.
Prerequisite is only running bsc
One is running on a dedicated server, and the other is running on AWS.

Here is my system resource and running script.
Please note

### Dedicated Server
- CPU: i7-9700
- RAM: 64GB
- DISK: RAID 0 (Samsung SSD 870, Samsung SSD 860)
- 1Gbps Network Speed

### AWS EC2
- Instance:  c5.x4large
- GP3 1800GB 6000/IOPS 500/Mbps(Throughput)
- Use seoul region (ap-northeast-2)

**No tunings at filesystem or os level.**

And my start script is

### Dedicated Server (geth version: 1.1.0 beta)
`$ ./geth_linux --config ./config.toml --datadit ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0`

### AWS EC2 (geth version: 1.1.0)
`$ ./geth_linux --config ./config.toml --datadit ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0`

**Comment by jun0tpyrc** [comment]
We run like 15 bsc nodes, my observations being

- p2p is slower for cold start, taking around 1 hour to resume efficiency for finalising block at comparable speed before restart , even for old blocks 
- maybe you need to have fast and quality peer list which are in sync to catch up fast  
- node slow down when serving heavy rpc requests

the result is , we run some syncmode=fast/full mode on `i3en.2xlarge  8C 64GB nvme`, seeing some of them failing to catch up the gap, not shortening

**Comment by jayboy-mabushi** [comment]
did anyone manage to sync?

**Comment by j75689** [comment]
Hi everyone, could you please move to #338 to discuss this issue?

The recent large number of transactions have caused a lot of problems, and we are also working hard to improve performance.

We will continue to follow issue #338.
