### ISSUE TITLE
Release 1.1.0 stable cannot full sync on fast mode

### ISSUE THREAD

**Issue by dracmic** [binance-chain/bsc#329]
#### System information

Geth version:  
geth version
Geth
Version: 1.1.0
Git Commit: 7822e9e2a1c11e5e9f989b740ba0166a9cd96db1
Architecture: amd64
Go Version: go1.16.3
Operating System: linux
GOPATH=
GOROOT=go

OS & Version: Linux Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
To be fully synced and to not be behind with 100 blocks 

#### Actual behaviour
Pivot Stale, receipts behind with ~100 blocks and the issue was also in 1.1.0-beta and actually the issue started to happen about 1 week and half ago after I saw that my node gets behind I did restart it and started this behaviour. Deleted and resynced same issue. I tried 2-3 different server providers all with NVME and a lot of RAM and different location same issue: eth.blockNumber on 0 and pivot getting stalled so I get the issue with 3 minutes back blocks (~100blocks).

#### Steps to reproduce the behaviour
Start a full sync ( personally I've used servers from EU countries) by using fast as syncmode

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by dwjpeng** [comment]
same problem， I tried different syncmodes（snap and fast） but it didn't work；now  more than 8,000 blocks behind；

**Comment by maldiva** [comment]
Having the same issue. Has anyone solved this problem? My hardware specs are more than enough to run a node, so it's not the problem. Changing sync modes didn't help, txlookuplimit didn't help as well

**Comment by Crypto2** [comment]
I'm having this problem with snap sync, it's fully caught up on blocks but syncing won't end.

INFO [07-28|10:23:22.535] Downloader queue stats                   receiptTasks=0     blockTasks=0     itemSize=696.76KiB  throttle=95
WARN [07-28|10:23:22.535] Pivot became stale, moving               old=9,549,567 new=9,549,631
INFO [07-28|10:23:23.012] Imported new block receipts              count=64   elapsed=475.749ms   number=9,549,630 hash=f1ba4a..79446e age=3m22s      size=19.06MiB
INFO [07-28|10:23:23.012] State heal in progress                   accounts=1,336,240@66.72MiB   slots=10,615,893@741.15MiB codes=1649@14.33MiB      nodes=31,544,661@6.05GiB   pending=9232
INFO [07-28|10:23:25.891] Imported new block headers               count=1    elapsed=1.221ms     number=9,549,694 hash=ac0434..51228c
INFO [07-28|10:23:29.422] Imported new block headers               count=2    elapsed=1.062ms     number=9,549,696 hash=dd897f..2ad02e
INFO [07-28|10:23:31.031] State heal in progress                   accounts=1,336,245@66.72MiB   slots=10,615,893@741.15MiB codes=1649@14.33MiB      nodes=31,551,163@6.06GiB   pending=18434

**Comment by cctanfujun** [comment]
Having the same issue. knownStates and pulledStates increase but not sync finish

**Comment by flonussi** [comment]
Same here, synced fine before, now after the update I cannot get the node to sync. Hardware is more than enough: 12 core cpu, nvme ssd 980 pro, 128gb memory.

**Comment by dracmic** [comment]
@flonussi @cctanfujun @dwjpeng  @Crypto2  I have a look here https://explorer.bitquery.io/bsc/calls maybe we can help does CryptoBlades (SKILL) to not do transactions for fights on blockchain :)

**Comment by cctanfujun** [comment]
> Having the same issue. knownStates and pulledStates increase but not sync finish

![image](https://user-images.githubusercontent.com/7422247/127454124-138c3836-0873-4ba9-8ef7-169f44f36055.png)

**Comment by cctanfujun** [comment]
i ask some people, they said because of nft games,their are too many transcation,just wait about 48hours,if you are use nvme ssd

**Comment by lovelyrrg51** [comment]
![image](https://user-images.githubusercontent.com/56916797/127548272-2ecaac3f-2488-4488-8c82-de66973b4fb3.png)
Same problems here.

**Comment by lovelyrrg51** [comment]
when they can fix it?

**Comment by dracmic** [comment]
@lovelyrrg51  @cctanfujun  they've released 1.1.1-beta which personally I am running and got synced. So give it a try :)

**Comment by lovelyrrg51** [comment]
Really?
@dracmic so only update geth with 1.1.1?

**Comment by dracmic** [comment]
@lovelyrrg51  I have a full node started with snapshot ... which was almost synced ... I did a safe stop like crtl+c and replace the exec waited a bit ... but it got synced.

**Comment by lovelyrrg51** [comment]
Ah, okay, got it.
Thanks for your advice.
@dracmic

**Comment by Crypto2** [comment]
Is 1.1.1 working for everyone? Unfortunately no luck here with it :(

**Comment by lovelyrrg51** [comment]
Yes
still syncing in 10 hours.

**Comment by litebarb** [comment]
@lovelyrrg51 do you mean your syncing has completed?

**Comment by dracmic** [comment]
problem with fast syncing persists in 1.1.1-beta .... 
t=2021-07-30T07:12:55+0200 lvl=warn msg="Pivot became stale, moving"             old=9,593,429 new=9,593,493
t=2021-07-30T07:16:07+0200 lvl=warn msg="Pivot became stale, moving"             old=9,593,493 new=9,593,557
t=2021-07-30T07:19:20+0200 lvl=warn msg="Pivot became stale, moving"             old=9,593,557 new=9,593,621

**Comment by lovelyrrg51** [comment]
not completed.

**Comment by litebarb** [comment]
@lovelyrrg51 alrights let us know how it goes. I am on 1.1.0, stable. Around 11hours into syncing, not completed yet.

**Comment by lovelyrrg51** [comment]
Yes, of course.
1.1.1-beta is still syncing, not completed too.
@litebarb

**Comment by lovelyrrg51** [comment]
not sure which version should be use.

**Comment by litebarb** [comment]
@lovelyrrg51 is this your first time setting up a node? Were you successful in previous versions before? Seems like some ppl are able to sync on 1.1.0 beta and 1.0.7

**Comment by lovelyrrg51** [comment]
Not first time.
About few days ago, it works well with 1.1.0 beta.
but not work well now.
Probably, because of CryptoBlades, too many transactions. :)

**Comment by litebarb** [comment]
> problem with fast syncing persists in 1.1.1-beta ....
> t=2021-07-30T07:12:55+0200 lvl=warn msg="Pivot became stale, moving" old=9,593,429 new=9,593,493
> t=2021-07-30T07:16:07+0200 lvl=warn msg="Pivot became stale, moving" old=9,593,493 new=9,593,557
> t=2021-07-30T07:19:20+0200 lvl=warn msg="Pivot became stale, moving" old=9,593,557 new=9,593,621

@dracmic I thought you managed to sync up? When you said you replace the exec file, what do you mean exactly? Do you mean you only replaced the geth_linux file from https://github.com/binance-chain/bsc/releases/download/v1.1.1-beta/geth_linux?

**Comment by lovelyrrg51** [comment]
All of third parties including quicknode&getblock not sync complete too.

**Comment by litebarb** [comment]
> Not first time.
> About few days ago, it works well with 1.1.0 beta.
> but not work well now.
> Probably, because of CryptoBlades, too many transactions. :)

Oooo I see. Any reason you are upgrading to 1.1.0 stable? I thought the beta version I was good enough>

**Comment by litebarb** [comment]
@lovelyrrg51 and how long did your 1.1.0 beta version took before sync completed?

**Comment by lovelyrrg51** [comment]
not to 1.1.0 stable
updated geth to 1.1.1 beta.
but not working too.

**Comment by lovelyrrg51** [comment]
> @lovelyrrg51 and how long did your 1.1.0 beta version took before sync completed?

about 2 month

**Comment by litebarb** [comment]
> > @lovelyrrg51 and how long did your 1.1.0 beta version took before sync completed?
> 
> about 2 month

I mean how long did your server took from scratch to achieve full sync state? 10hours?

**Comment by lovelyrrg51** [comment]
Ah, no
about 3 days

**Comment by dracmic** [comment]
> > problem with fast syncing persists in 1.1.1-beta ....
> > t=2021-07-30T07:12:55+0200 lvl=warn msg="Pivot became stale, moving" old=9,593,429 new=9,593,493
> > t=2021-07-30T07:16:07+0200 lvl=warn msg="Pivot became stale, moving" old=9,593,493 new=9,593,557
> > t=2021-07-30T07:19:20+0200 lvl=warn msg="Pivot became stale, moving" old=9,593,557 new=9,593,621
> 
> @dracmic I thought you managed to sync up? When you said you replaced the exec file, what do you mean exactly? Do you mean you only replaced the geth_linux file from https://github.com/binance-chain/bsc/releases/download/v1.1.1-beta/geth_linux? Also how many hours did it take for your node to be fully synced?

Yes ... But I tried on other server for fast sync ... without the snapshot ... just to test out the sync

**Comment by litebarb** [comment]
@dracmic So in sumamry, your node with snapshot synced, and the other node without snapshot did not sync? Can you share with us the link you used for snapshot? Is this the one? https://github.com/binance-chain/bsc-snapshots/blob/main/README.md

**Comment by dracmic** [comment]
@litebarb  in which area you have your server maybe I can share a faster way from the server which I build ... Yes I used the the snapshot from there with syncmode="snap" ...

**Comment by litebarb** [comment]
@dracmic It's a custom server I have at home, I am in South East Asia

**Comment by dracmic** [comment]
@litebarb  then that s3 link from there I think is faster to download from what I have in Europe.

**Comment by litebarb** [comment]
@dracmic Man I have a good connection (1 gbps) but the speed it's giving me takes me another 9hours to complete. Lol. Where can I find alternative links?

**Comment by j75689** [comment]
At present, fast/snap sync is very unstable, a large number of transactions will cause more state changes, and it will become very difficult to catch up with the current state with the current implementation.

We recommend that you download the [snapshot](https://github.com/binance-chain/bsc-snapshots/blob/main/README.md) we provide and run a full sync.

If there is a sync issue, please report it at #338 and we will continue to update.

**Comment by seiyria** [comment]
> [...] I have a look here [explorer.bitquery.io/bsc/calls](https://explorer.bitquery.io/bsc/calls) maybe we can help does CryptoBlades (SKILL) to not do transactions for fights on blockchain :) 

CryptoBlades is intended to be entirely on chain with minimal external services. We don't really plan to do stuff like this off-chain because our users prefer us to be entirely on-chain.
