### ISSUE TITLE
v1.1.0-beta -> v1.1.1-beta need resync block or not？

### ISSUE THREAD

**Issue by huahuayu** [binance-chain/bsc#336]
hi, I noticed that v1.1.1-beta is released, if I upgrade from v1.1.0-beta to v1.1.1-beta, I just replace the `geth` binary file or need resync block to take advantage of the performance improve as claimed？

@guagualvcha

**Comment by dracmic** [comment]
@huahuayu  replace just the executable ... with the new version ... I am using  it from about 3 hours and works.

**Comment by lovelyrrg51** [comment]
Hello everyone.
I've synced the v 1.1.0-beta last 3 days but not sync yet.
How can I resolve this?
Thanks.

**Comment by dracmic** [comment]
@lovelyrrg51  try 1.1.1-beta ...

**Comment by diogoagra** [comment]
> Hello everyone.
> I've synced the v 1.1.0-beta last 3 days but not sync yet.
> How can I resolve this?
> Thanks.

same problem here

```
{
  currentBlock: 9583373,
  highestBlock: 9583478,
  knownStates: 287873085,
  pulledStates: 287816257,
  startingBlock: 9573432
}

```

**Comment by huahuayu** [comment]
> @huahuayu replace just the executable ... with the new version ... I am using it from about 3 hours and works.

did you up upgraded from v1.1.0-beta or v1.1.0?

**Comment by kgcdream2019** [comment]
I upgraded to 1.1.0-beta and updated again to 1.1.1-beta.
 archive node is behind about 1.5 days, but not sync.
the block increase speed is very low.
How can I solve this?

**Comment by LiZhengyan** [comment]
I update 1.0.6 to 1.1.0  and to 1.1.1   16CPU32GMEN  3T RSSD 240wIOPS
now: Fri Jul 30 11:28:43 HKT 2021
CHAIN [BSC]
The highest:9583209 The current:9545113
difference:38096
sync slow slow slow

**Comment by j75689** [comment]
You can directly upgrade v1.1.1-beta, that is no problem.

If you have any sync issues, please reply in #338 or discuss.
We will continue to pay attention to this issue.

Thanks all.
