### ISSUE TITLE
Synced, stopped working and now has 0 peers

### ISSUE THREAD

**Issue by Arranua** [binance-chain/bsc#339]
I synced a full node a few days ago and it was operational. however suddenly it has stopped working, and it displays peerCount as 0.

```
> eth.syncing
false
> net.peerCount
0
```

However it still shows synced status with eth.syncing returning false. Im unable to fix this by simply stopping the node and restarting it, it just shows the same status when I try to start it again (0 peers, eth.syncing false)

One time I restarted it, and it seemed to actually regain peers, got up to 22 peers before showing this error

```
>net.peerCount
4
>net.peerCount
6
>net.peerCount
22
>net.peerCount
Error: io: read/write on closed pipe
at web3.js:6405:37(47)
at get (web3.js:6305:66(14))
```
as of now, not sure how to fix this, not sure if the correct move is to just wipe everything and resync (because it might break again, and resync takes half a day)

previously when it had worked it was showing 300+ peers and working fine. i have opened firewall ports for the node already and restarted firewall, didnt fix it

**Comment by guagualvcha** [comment]
```
>net.peerCount
Error: io: read/write on closed pipe
at web3.js:6405:37(47)
at get (web3.js:6305:66(14))
```
 This is quite suspicious,  is the node keeping restart? can you check whether is there any panic logs ?

**Comment by guagualvcha** [comment]
I will close this issue, feel free to open new one if any further question
