### ISSUE TITLE
archive bsc node not synced

### ISSUE THREAD

**Issue by kgcdream2019** [binance-chain/bsc#340]
suddenly my archive node stopped syncing from  3 days ago.
I upgrade my node as follows:
    cpu 36    ram 72G hard EBS gp3 IOPS 10000, throughput 1000MB/s,network  10Gbps
   aws c5.9xlarge
I updated geth to version 1.1.1-beta
geth command as follows:
./build/bin/geth --config ./config.toml --datadir ./node --gcmode archive --syncmode=full --snapshot=false --http.vhosts=* --cache=18000 --cache.preimages --rpc.allow-unprotected-txs --txlookuplimit 0 console

maxPeerCount = 200

block syncing speed is 2\~3 blocks/ 10\~12 seconds.
but this archive node is not synced yet.
are there any person who can fix this archive node syncing issue?

**Comment by koen84** [comment]
Is it doing "database compaction" ?  That halts chain syncing until it finishes, though rpc remains available.
See issue #229

**Comment by jcaffet** [comment]
I recently faced this kind of problem with c5/m5 instances. Upgrading to i3.2xlarge with directly attached NVME fixed the issue.

**Comment by koen84** [comment]
Yeah, IOPS are critical for bsc.  Some months ago already most github respondents suggested local NVMe's is the way to go.

**Comment by kgcdream2019** [comment]
> I recently faced this kind of problem with c5/m5 instances. Upgrading to i3.2xlarge with directly attached NVME fixed the issue.
Thanks for your reply..
Now all blockchain data is stored in 16T EBS , can I upgrade it to i3.2xlarge with keeping the blockchain data or should I sync from scratch?

**Comment by jun0tpyrc** [comment]
when data is on ebs now you can 
- gracefully stop geth 
- stop instance 
- change instance type
- start instance
- mount ebs in new instance type, maybe actually you need i3en.6xlarge, a few month later i3en.12xlarge ...... $$$$$
- no single nvme suffice, just 7.5TB each on aws instance <= you need to use something to "join" disks together ( lvm / zfs  etc..)  
- `rsync -avhP XXXXX YYYYY`   <= it takes day 
- start geth again in data dir backed by nvme 
- Never stop you instance again without backup to ebs (you will lose all data)

**Comment by kgcdream2019** [comment]
Hi, @jun0tpyrc , Thanks for your reply.
I have some question about your answer.
i3en.6xlarge have 2 x 7,500 GB local NVMe SSD.
so shall I join these two NVMe SSD and move blockchain data from EBS to this joined local SSD?
if I stop instance, why all data will be lose?

**Comment by jun0tpyrc** [comment]
> Hi, @jun0tpyrc , Thanks for your reply.
> I have some question about your answer.
> i3en.6xlarge have 2 x 7,500 GB local NVMe SSD.
> so shall I join these two NVMe SSD and move blockchain data from EBS to this joined local SSD?
> if I stop instance, why all data will be lose?

those are instance store 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage-optimized-instances.html#storage-instances-hardware
```
Instance store volumes persist only for the life of the instance. When you stop, hibernate, or terminate an instance, the applications and data in its instance store volumes are erased. We recommend that you regularly back up or replicate important data in your instance store volumes. For more information, see Amazon EC2 instance store and SSD instance store volumes.
```
rebooting is ok  , `stop instance` at aws level not , when you start again , you get another instance

**Comment by kgcdream2019** [comment]
Got it, thanks @jun0tpyrc.

**Comment by kgcdream2019** [comment]
Hi, @jun0tpyrc. I could successfully migrate archive node to new i3en.6xlarge instance. Thank you so much for your support.
now the blockchain syncing speed is 6\~8 blocks/8\~10 second.
