### ISSUE TITLE
Pending Block is null after upgrade to Latest Version (1.1.1-beta)

### ISSUE THREAD

**Issue by zcrypt0** [binance-chain/bsc#341]
#### System information

Geth version: `1.1.1-beta`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour

`eth.getBlock('pending')` returns the pending block when `--mine` is specified on the command line.

#### Actual behaviour

`eth.getBlock('pending')` returns null.

#### Backtrace

N/A

### More Details

I upgraded from 1.10.2 (https://github.com/binance-chain/bsc/commit/032970b2deeffe3b7f87703753d7be9a09906758) to 1.1.1-beta and now the node no longer generates pending blocks.

I resynced the node entirely using `--syncmode=snap` with version 1.1.1-beta to see if it would solve the issue. The pending block is still null. 

Snapshot generation is on and the snapshot is completely generated (if applicable).

I downgraded back to 1.10.2 (with the same db synced on 1.1.1-beta) and confirmed that pending blocks are generated, so this is definitely some type of issue with 1.1.1-beta. Note I am specifying the same command line in both versions which includes `--mine`.

**Comment by guagualvcha** [comment]
hi, @zcrypt0 Thanks for reporting this issue. It is introduced in release v1.1.1-beta, we will fix it in v1.1.1 stable release

**Comment by zcrypt0** [comment]
Thanks @guagualvcha 

This is becoming somewhat of a priority for my use case, and I expect others who depend on timely generation of pending blocks. Given the number of transactions on the blockchain right now, I cannot generate pending blocks in a timely manner even on relatively high end hardware. 

I will probably attempt an interim hacky patch myself. I wonder if you might point out relevant sections in the code to help accelerate this, since I am not familiar with the geth codebase.

Alternatively, a dev branch that could be built manually would be helpful as well if you are already making progress on it.

**Comment by guagualvcha** [comment]
> Hi, @guagualvcha
> When v1.1.1 stable will be release?

It will be done within this week.

**Comment by lovelyrrg51** [comment]
Great
So at that time, will only update geth on Node?
@guagualvcha

**Comment by lovelyrrg51** [comment]
And I've another question.
Currently, BSC Node size is fullfilled 100GB every day.
Is this normal?
@guagualvcha

**Comment by Undead8** [comment]
I think that this issue should be reopened because it has been only partially fixed, as mentioned [here](https://github.com/binance-chain/bsc/pull/358#issuecomment-898466311).
