### ISSUE TITLE
[Question] Transaction's Execution Block

### ISSUE THREAD

**Issue by mentalrob** [binance-chain/bsc#342]
Hey guys i'am trying something like this and i noticed something weird 

```js
provider.on('block', (blockNumber) => {
    console.log(blockNumber)
    provider.sendTransaction(...)
})
```

when i do that transaction gets executed on `blockNumber + 2` not `blockNumber + 1` why is this happening ?
I'm using ethers.js for interacting with bsc.

**Comment by m-e-r-k-l-e-root** [comment]
Check the closed issues tab prior to opening new issues...

This questions been asked and answered numerous times: [answer](https://github.com/binance-chain/bsc/issues/107)

**Comment by guagualvcha** [comment]
Will close due to duplicated issue.
