### ISSUE TITLE
sync speed is slow or not?

### ISSUE THREAD

**Issue by sonhn1988** [binance-chain/bsc#343]
Hi there,
I run a bsc full node on my pc
i would like  to ask your guy, this sync speed is slow or fast?
because i see sometime elapsed is milisecond and sometime it comes to second as attachment.
i try to use my local node to verify my transaction and it often slowly than post via public RPC node.
my PC:
CPU intel core i9 10900 2.8Ghz, 10C 20T
Ram 64 gb
ssd 1T m2 

INFO [08-02|16:07:32.013] Imported new chain segment               blocks=1  txs=371  mgas=60.262  elapsed=829.284ms   mgasps=72.667  number=9,682,283 hash=b3dff1..34c856 dirty=805.33MiB
INFO [08-02|16:07:32.895] Chain reorg detected                     number=9,682,282 hash=e325b9..b963f9 drop=1 dropfrom=b3dff1..34c856 add=1 addfrom=636717..50985b
INFO [08-02|16:07:32.900] Imported new chain segment               blocks=1  txs=438  mgas=70.666  elapsed=530.229ms   mgasps=133.274 number=9,682,283 hash=636717..50985b dirty=804.19MiB
INFO [08-02|16:07:34.945] Imported new chain segment               blocks=1  txs=249  mgas=39.256  elapsed=513.857ms   mgasps=76.395  number=9,682,284 hash=285146..3540a5 dirty=808.02MiB
INFO [08-02|16:07:38.337] Imported new chain segment               blocks=1  txs=456  mgas=74.761  elapsed=992.172ms   mgasps=75.351  number=9,682,285 hash=77142f..8ae0f1 dirty=809.36MiB
INFO [08-02|16:07:38.772] Imported new chain segment               blocks=1  txs=3    mgas=0.119   elapsed=4.552ms     mgasps=26.190  number=9,682,283 hash=330f57..b89a02 dirty=804.48MiB
INFO [08-02|16:07:38.845] Imported new chain segment               blocks=1  txs=0    mgas=0.000   elapsed="372.954µs" mgasps=0.000   number=9,682,284 hash=fa4e13..4dae4e dirty=804.48MiB
INFO [08-02|16:07:39.065] Imported new chain segment               blocks=1  txs=0    mgas=0.000   elapsed="405.801µs" mgasps=0.000   number=9,682,284 hash=154d9a..99db69 dirty=804.48MiB
INFO [08-02|16:07:42.014] Imported new chain segment               blocks=1  txs=420  mgas=65.657  elapsed=1.736s      mgasps=37.803  number=9,682,286 hash=ac6b61..c43068 dirty=810.07MiB
INFO [08-02|16:07:45.107] Imported new chain segment               blocks=1  txs=316  mgas=47.010  elapsed=1.877s      mgasps=25.039  number=9,682,287 hash=f043e6..9f8e2e dirty=810.95MiB
INFO [08-02|16:07:46.987] Imported new chain segment               blocks=1  txs=321  mgas=49.937  elapsed=670.547ms   mgasps=74.472  number=9,682,288 hash=dccba1..f08d4c dirty=812.12MiB
INFO [08-02|16:07:48.272] Imported new chain segment               blocks=1  txs=381  mgas=59.952  elapsed=456.716ms   mgasps=131.267 number=9,682,288 hash=f62dc8..fafc86 dirty=811.10MiB
INFO [08-02|16:07:54.452] Imported new chain segment               blocks=1  txs=373  mgas=63.094  elapsed=774.562ms   mgasps=81.458  number=9,682,289 hash=589800..9ba5d9 dirty=815.95MiB
INFO [08-02|16:07:54.975] Imported new chain segment               blocks=1  txs=412  mgas=68.954  elapsed=426.921ms   mgasps=161.514 number=9,682,289 hash=5f1f03..3c84e3 dirty=813.92MiB
INFO [08-02|16:07:55.870] Chain reorg detected                     number=9,682,288 hash=dccba1..f08d4c drop=1 dropfrom=589800..9ba5d9 add=1 addfrom=17b4cb..c08a33
INFO [08-02|16:07:55.874] Imported new chain segment               blocks=1  txs=306  mgas=48.482  elapsed=517.815ms   mgasps=93.628  number=9,682,289 hash=17b4cb..c08a33 dirty=814.81MiB
INFO [08-02|16:07:57.368] Deep froze chain segment                 blocks=18 elapsed=49.761ms    number=9,592,289 hash=c1e155..8313cb
INFO [08-02|16:07:58.280] Chain reorg detected                     number=9,682,288 hash=dccba1..f08d4c drop=1 dropfrom=17b4cb..c08a33 add=2 addfrom=433358..92b6c3
INFO [08-02|16:07:58.290] Imported new chain segment               blocks=1  txs=440  mgas=74.843  elapsed=955.630ms   mgasps=78.317  number=9,682,290 hash=433358..92b6c3 dirty=820.98MiB
INFO [08-02|16:08:00.127] Imported new chain segment               blocks=1  txs=300  mgas=48.040  elapsed=1.436s      mgasps=33.443  number=9,682,289 hash=8e366a..94b719 dirty=816.76MiB
INFO [08-02|16:08:01.419] Imported new chain segment               blocks=1  txs=483  mgas=74.565  elapsed=1.076s      mgasps=69.235  number=9,682,291 hash=3e5fcd..f27e51 dirty=823.37MiB
INFO [08-02|16:08:01.907] Persisted trie from memory database      nodes=0       size=0.00B     time="2.752µs"     gcnodes=699,386 gcsize=273.73MiB gctime=3.155314576s livenodes=1,910,629 livesize=642.09MiB
INFO [08-02|16:08:01.908] Imported new chain segment               blocks=1  txs=487
thank you for your help

**Comment by guagualvcha** [comment]
Hi, the speed is a bit slow, as you can see from logs `mgas=74.843`, it means your node can execute 74.843G gas per second, it can catch up with the chain, but not fast, it is better larger than 100.

**Comment by sonhn1988** [comment]
hi, 
thank you so much for your answer, 
give me 1 flavor, how could i improve the speed of bsc node?

thanks,
Henry

**Comment by JetQe** [comment]
how to improve?
