### ISSUE TITLE
Data explosion when run bsc node

### ISSUE THREAD

**Issue by thanhnv2303** [binance-chain/bsc#344]
I have a machine : 16 core, 32G RAM, 2T SSD.

When I build bsc node with geth config "--cache 16000 --syncmode snap --gcmode full ", I see that the capacity of the directory containing node **increases 1.8G/h**. That means I lose approx **43G per day** or **320G per week.**

Now (2/8/2021) the capacity of the directory containing node is 724.6G. With this data explosion i think i just can maintain my node for a month.

**I wonder if there is any solution for me to reduce the increasing data size and maintain my node for a longer time?**

**Comment by perfectcircle2020** [comment]
You can prune the geth database using this command appended after geth:

snapshot prune-state

Credits: https://gist.github.com/yorickdowne/3323759b4cbf2022e191ab058a4276b2

**Comment by perfectcircle2020** [comment]
Yesterday it took me about 4 hours and reduced the size of the chain to about 500 GB. mercoledì, 04 agosto 2021, 05:53PM +02:00 da thanhnv  ***@***.*** :

**Comment by thanhnv2303** [comment]
> Yesterday it took me about 4 hours and reduced the size of the chain to about 500 GB. mercoledì, 04 agosto 2021, 05:53PM +02:00 da thanhnv ***@***.*** :
> […](#)
> >You can prune the geth database using this command appended after geth: >snapshot prune-state >Credits: https://gist.github.com/yorickdowne/3323759b4cbf2022e191ab058a4276b2 Do you know how long it takes to run snapshot prune-state with my config like above (it just keeps the latest 128 tries)? — You are receiving this because you commented. Reply to this email directly, view it on GitHub , or unsubscribe . Triage notifications on the go with GitHub Mobile for iOS or Android .

yep. Thank you so much!
