### ISSUE TITLE
How to run an archive node?

### ISSUE THREAD

**Issue by jason-w0** [binance-chain/bsc#346]
I want to run an archive node.But I'm not sure the command and config.toml for it.Please give me a command and config.toml to start an archive node. Thank you.

**Comment by koen84** [comment]
You need syncmode full and gcmode archive.

**Comment by jason-w0** [comment]
> You need syncmode full and gcmode archive.

Thank you.I have another question.Can I use syncmode=snap with an archive node.

**Comment by yutianwu** [comment]
no, you can not

**Comment by jason-w0** [comment]
My archive node sync speed is like this.
<img width="1615" alt="image" src="https://user-images.githubusercontent.com/87351703/128601357-c7e2f350-bf71-4f2f-bddb-64c6d9f4a03d.png">
It cannot sync to last blockNumber.
