### ISSUE TITLE
transaction too slow

### ISSUE THREAD

**Issue by SatanBtc** [binance-chain/bsc#349]
Sending the transaction is too slow. It takes 2 blocks. Even if the gas is increased, is there any way or parameter to speed up the transaction?

Can anyone help me？Or who knows the geolocation of the validator
thanks~

**Comment by cryptobrokering** [comment]
Have the same issue, does anybody know if they changed something causing this behaviour during the last months?

**Comment by perfectcircle2020** [comment]
The reason is the high volume there is lately in the network take a look here:

https://bscscan.com/chart/tx

**Comment by m-e-r-k-l-e-root** [comment]
Check the closed issues tab prior to opening new issues...

This question has been asked and answered numerous times: [answer](https://github.com/binance-chain/bsc/issues/107)

**Comment by cryptobrokering** [comment]
@perfectcircle2020 I understand that a higher number of transactions may require higher gas prices to get in the next block but does a high number of transactions also slow down the broadcasting process in the network? Could see my own transactions in the mempool about an order of magnitude faster (~300ms vs. > 2s) about 2 months ago with exactly the same setting.

@m-e-r-k-l-e-root Have read this issues as well but it was possible to send Tx much faster some months ago.

**Comment by guagualvcha** [comment]
The network does not guarantee to include transactions in the next block.  It is impacted by p2p network and when the validator starts to mine the next block.  Please refer to https://github.com/binance-chain/bsc/issues/107
