### ISSUE TITLE
always Looking fo peers and not sync data

### ISSUE THREAD

**Issue by WorldDogs** [binance-chain/bsc#351]
#### System information

Geth version: `1.0.0-alpha.0`
OS & Version: OSX(MacBook Pro (13-inch, M1, 2020)) BigSur 11.4
Commit hash : (if `develop`)

#### Expected behaviour
Can pull data normally

#### Actual behaviour

The data cannot be pulled normally, and the balance of my test network cannot be found.

#### Steps to reproduce the behaviour

1. get testnet release file
2. download geth on https://github.com/binance-chain/bsc.
3. boot node with `./geth --syncmode "light"  --datadir ./data --ws --rpc --wsorigins "*" --rpccorsdomain "*"   --allow-insecure-unlock console`
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by psdlt** [comment]
For `testnet` it sometimes takes a lot of time to find good peers, that sometimes can be hours to start syncing. My suggestion is wait a little more, once it starts syncing, do this:
attach to console `./geth attach --datadir ./data`
get a list of peers `admin.peers`
copy some of those peers `enode` value to `config.toml` `BootstrapNodes` section.
next time you launch your `geth` it should start syncing faster.

**Comment by guagualvcha** [comment]
hi, @WorldDogs  as the command start as `--syncmode "light"`, only headers will be pulled, no blocks will be pulled.

**Comment by guagualvcha** [comment]
@WorldDogs  will kindly close this. Feel free to open new one if any concern
