### ISSUE TITLE
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

### ISSUE THREAD

**Issue by worldofibra** [binance-chain/bsc#353]
Running into the following error when trying to enable geth http link and geth ws link.

Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

Geth 1.1.10 
OS: Linux
Cmd to get result 

> geth_linux --http

or 

> geth_linux --ws

I've allowed the correct ports and i use the following cmd to run geth_linux:

> geth --config ./config.toml --datadir ./node  --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http.api --ws.api

Genesis.json (i think something may be wrong with this
> {
  "config": {
    "chainId": 56,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,    "petersburgBlock": 0,    "istanbulBlock": 0,    "muirGlacierBlock": 0,    "ramanujanBlock": 0,    "nielsBlock": 0,    "parlia": {      "period": 3,      "epoch": 200    }  },  "nonce": "0x0",  "timestamp": "0x5e9da7ce",  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000002a7cdd959bfe8d9487b2a43b33565295a698f7e26488aa4d1955ee33403f8ccb1d4de5fb97c7ade29ef9f4360c606c7ab4db26b016007d3ad0ab86a0ee01c3b1283aa067c58eab4709f85e99d46de5fe685b1ded8013785d6623cc18d214320b6bb6475978f3adfc719c99674c072166708589033e2d9afec2be4ec20253b8642161bc3f444f53679c1f3d472f7be8361c80a4c1e7e9aaf001d0877f1cfde218ce2fd7544e0b2cc94692d4a704debef7bcb61328b8f7166496996a7da21cf1f1b04d9b3e26a3d0772d4c407bbe49438ed859fe965b140dcf1aab71a96bbad7cf34b5fa511d8e963dbba288b1960e75d64430b3230294d12c6ab2aac5c2cd68e80b16b581ea0a6e3c511bbd10f4519ece37dc24887e11b55d7ae2f5b9e386cd1b50a4550696d957cb4900f03a82012708dafc9e1b880fd083b32182b869be8e0922b81f8e175ffde54d797fe11eb03f9e3bf75f1d68bf0b8b6fb4e317a0f9d6f03eaf8ce6675bc60d8c4d90829ce8f72d0163c1d5cf348a862d55063035e7a025f4da968de7e4d7e4004197917f4070f1d6caa02bbebaebb5d7e581e4b66559e635f805ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x2625a00",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0xffffFFFfFFffffffffffffffFfFFFfffFFFfFFfE",
  "alloc": {
    "0xffffFFFfFFffffffffffffffFfFFFfffFFFfFFfE": {
      "balance": "0x0"
    },

terminal log
> geth_linux --http
INFO [08-08|07:06:52.343] Starting Geth on Ethereum mainnet...
INFO [08-08|07:06:52.343] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-08|07:06:52.345] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-08|07:06:52.345] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-08|07:06:52.347] Set global gas cap                       cap=25,000,000
INFO [08-08|07:06:52.347] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [08-08|07:06:52.348] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=2.00GiB handles=32767
INFO [08-08|07:06:52.480] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient readonly=false
INFO [08-08|07:06:52.483] Writing default main-net genesis block
INFO [08-08|07:06:52.796] Persisted trie from memory database      nodes=12356 size=1.78MiB time=72.047807ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000
[root@iZ0xi93demjbbhowo7hj6vZ ~]# geth_linux --http
INFO [08-08|08:33:36.455] Starting Geth on Ethereum mainnet...
INFO [08-08|08:33:36.455] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-08|08:33:36.457] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-08|08:33:36.457] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-08|08:33:36.458] Set global gas cap                       cap=25,000,000
INFO [08-08|08:33:36.466] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [08-08|08:33:36.468] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=2.00GiB handles=32767
INFO [08-08|08:33:36.608] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient readonly=false
INFO [08-08|08:33:36.616] Writing default main-net genesis block
INFO [08-08|08:33:36.883] Persisted trie from memory database      nodes=12356 size=1.78MiB time=73.699768ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000
[root@iZ0xi93demjbbhowo7hj6vZ ~]# geth_linux --ws
INFO [08-08|08:37:38.743] Starting Geth on Ethereum mainnet...
INFO [08-08|08:37:38.743] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-08|08:37:38.745] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-08|08:37:38.745] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-08|08:37:38.746] Set global gas cap                       cap=25,000,000
INFO [08-08|08:37:38.746] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [08-08|08:37:38.746] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=2.00GiB handles=32767
INFO [08-08|08:37:38.904] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient readonly=false
INFO [08-08|08:37:38.904] Writing default main-net genesis block
INFO [08-08|08:37:39.302] Persisted trie from memory database      nodes=12356 size=1.78MiB time=83.317398ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000
[root@iZ0xi93demjbbhowo7hj6vZ ~]# geth_linux --http --http.port 8545
INFO [08-08|08:44:59.988] Starting Geth on Ethereum mainnet...
INFO [08-08|08:44:59.988] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [08-08|08:44:59.990] Maximum peer count                       ETH=50 LES=0 total=50
INFO [08-08|08:44:59.990] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [08-08|08:44:59.991] Set global gas cap                       cap=25,000,000
INFO [08-08|08:44:59.991] Allocated trie memory caches             clean=614.00MiB dirty=1024.00MiB
INFO [08-08|08:44:59.991] Allocated cache and file handles         database=/root/.ethereum/geth/chaindata cache=2.00GiB handles=32767
INFO [08-08|08:45:00.148] Opened ancient database                  database=/root/.ethereum/geth/chaindata/ancient readonly=false
INFO [08-08|08:45:00.148] Writing default main-net genesis block
INFO [08-08|08:45:00.486] Persisted trie from memory database      nodes=12356 size=1.78MiB time=84.060094ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000
[root@iZ0xi93demjbbhowo7hj6vZ ~]#  

And my config

> [Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

> [Eth.Miner]

> GasFloor= 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

> [Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

> [Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

> [Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

> [Node.P2P]
MaxPeers = 30
NoDiscovery = false
BootstrapNodes = ["enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311","enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311","enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"]
StaticNodes = ["enode://f3cfd69f2808ef64838abd8786342c0b22fdd28268703c8d6812e26e109f9a7cb2b37bd49724ebb46c233289f22da82991c87345eb9a2dadeddb8f37eeb259ac@18.180.28.21:30311","enode://ae74385270d4afeb953561603fcedc4a0e755a241ffdea31c3f751dc8be5bf29c03bf46e3051d1c8d997c45479a92632020c9a84b96dcb63b2259ec09b4fde38@54.178.30.104:30311","enode://d1cabe083d5fc1da9b510889188f06dab891935294e4569df759fc2c4d684b3b4982051b84a9a078512202ad947f9240adc5b6abea5320fb9a736d2f6751c52e@54.238.28.14:30311","enode://f420209bac5324326c116d38d83edfa2256c4101a27cd3e7f9b8287dc8526900f4137e915df6806986b28bc79b1e66679b544a1c515a95ede86f4d809bd65dab@54.178.62.117:30311","enode://c0e8d1abd27c3c13ca879e16f34c12ffee936a7e5d7b7fb6f1af5cc75c6fad704e5667c7bbf7826fcb200d22b9bf86395271b0f76c21e63ad9a388ed548d4c90@54.65.247.12:30311","enode://f1b49b1cf536e36f9a56730f7a0ece899e5efb344eec2fdca3a335465bc4f619b98121f4a5032a1218fa8b69a5488d1ec48afe2abda073280beec296b104db31@13.114.199.41:30311","enode://4924583cfb262b6e333969c86eab8da009b3f7d165cc9ad326914f576c575741e71dc6e64a830e833c25e8c45b906364e58e70cdf043651fd583082ea7db5e3b@18.180.17.171:30311","enode://4d041250eb4f05ab55af184a01aed1a71d241a94a03a5b86f4e32659e1ab1e144be919890682d4afb5e7afd837146ce584d61a38837553d95a7de1f28ea4513a@54.178.99.222:30311","enode://b5772a14fdaeebf4c1924e73c923bdf11c35240a6da7b9e5ec0e6cbb95e78327690b90e8ab0ea5270debc8834454b98eca34cc2a19817f5972498648a6959a3a@54.170.158.102:30311","enode://f329176b187cec87b327f82e78b6ece3102a0f7c89b92a5312e1674062c6e89f785f55fb1b167e369d71c66b0548994c6035c6d85849eccb434d4d9e0c489cdd@34.253.94.130:30311","enode://cbfd1219940d4e312ad94108e7fa3bc34c4c22081d6f334a2e7b36bb28928b56879924cf0353ad85fa5b2f3d5033bbe8ad5371feae9c2088214184be301ed658@54.75.11.3:30311","enode://c64b0a0c619c03c220ea0d7cac754931f967665f9e148b92d2e46761ad9180f5eb5aaef48dfc230d8db8f8c16d2265a3d5407b06bedcd5f0f5a22c2f51c2e69f@54.216.208.163:30311","enode://352a361a9240d4d23bb6fab19cc6dc5a5fc6921abf19de65afe13f1802780aecd67c8c09d8c89043ff86947f171d98ab06906ef616d58e718067e02abea0dda9@79.125.105.65:30311","enode://bb683ef5d03db7d945d6f84b88e5b98920b70aecc22abed8c00d6db621f784e4280e5813d12694c7a091543064456ad9789980766f3f1feb38906cf7255c33d6@54.195.127.237:30311","enode://11dc6fea50630b68a9289055d6b0fb0e22fb5048a3f4e4efd741a7ab09dd79e78d383efc052089e516f0a0f3eacdd5d3ffbe5279b36ecc42ad7cd1f2767fdbdb@46.137.182.25:30311","enode://21530e423b42aed17d7eef67882ebb23357db4f8b10c94d4c71191f52955d97dc13eec03cfeff0fe3a1c89c955e81a6970c09689d21ecbec2142b26b7e759c45@54.216.119.18:30311","enode://d61a31410c365e7fcd50e24d56a77d2d9741d4a57b295cc5070189ad90d0ec749d113b4b0432c6d795eb36597efce88d12ca45e645ec51b3a2144e1c1c41b66a@34.204.129.242:30311","enode://bb91215b1d77c892897048dd58f709f02aacb5355aa8f50f00b67c879c3dffd7eef5b5a152ac46cdfb255295bec4d06701a8032456703c6b604a4686d388ea8f@75.101.197.198:30311","enode://786acbdf5a3cf91b99047a0fd8305e11e54d96ea3a72b1527050d3d6f8c9fc0278ff9ef56f3e56b3b70a283d97c309065506ea2fc3eb9b62477fd014a3ec1a96@107.23.90.162:30311","enode://4653bc7c235c3480968e5e81d91123bc67626f35c207ae4acab89347db675a627784c5982431300c02f547a7d33558718f7795e848d547a327abb111eac73636@54.144.170.236:30311","enode://c6ffd994c4ef130f90f8ee2fc08c1b0f02a6e9b12152092bf5a03dd7af9fd33597d4b2e2000a271cc0648d5e55242aeadd6d5061bb2e596372655ba0722cc704@54.147.151.108:30311","enode://99b07e9dc5f204263b87243146743399b2bd60c98f68d1239a3461d09087e6c417e40f1106fa606ccf54159feabdddb4e7f367559b349a6511e66e525de4906e@54.81.225.170:30311","enode://1479af5ea7bda822e8747d0b967309bced22cad5083b93bc6f4e1d7da7be067cd8495dc4c5a71579f2da8d9068f0c43ad6933d2b335a545b4ae49a846122b261@52.7.247.132:30311","enode://43562d35f274d9e93f5ccac484c7cb185eabc746dbc9f3a56c36dc5a9ef05a3282695de7694a71c0bf4600651f49395b2ee7a6aaef857db2ac896e0fcbe6b518@35.73.15.198:30311","enode://08867e57849456fc9b0b00771f53e87ca6f2dd618c23b34a35d0c851cd484a4b7137905c5b357795025b368e4f8fe4c841b752b0c28cc2dbbf41a03d048e0e24@35.74.39.234:30311"]
ListenAddr = ":30311"
EnableMsgEvents = false

> [Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

> [Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 1048576000
Level = "info"
FileRoot = ""

**Comment by guagualvcha** [comment]
The version is wrong `Geth 1.1.10`, bsc do not release such version , I think it is a go-ethereum release.

**Comment by worldofibra** [comment]
> The version is wrong `Geth 1.1.10`, bsc do not release such version , I think it is a go-ethereum release.

I meant Geth 1.1.0-beta is that correct for bsc? I pulled geth from here https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/geth_linux
