### ISSUE TITLE
Block not found while send amount in CLI

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#356]
Hi,
Running BSC local network. It will mine block and connected with metamask. Transaction made in metamask is successfull, but in Command line it results an error as "block not found"

**Command for running BSC**
./geth --datadir <datadir>/node --rpc --rpcaddr 0.0.0.0  --networkid 30 --rpcport 8545 --rpccorsdomain "*"  --rpcapi "eth,net,web3,personal,miner" --allow-insecure-unlock --rpc.txfeecap 0 console

**Send amount command**
eth.sendTransaction({from: "<from_address>", to: "<to_address>", value: web3.toWei(2, "ether")})

**GETH**
Version: 1.1.1-beta
Git Commit: 4e254782246f09f42b4fee13ad7bd9eed7b9387a
Git Commit Date: 20210803
Architecture: amd64

How to overcome this error?

**Comment by guagualvcha** [comment]
This is case by case, hard to find whether you miss any steps. But you can follow https://github.com/binance-chain/bsc-docker to setup private network, and follow the `truffle-test` to send transactions.

**Comment by guagualvcha** [comment]
close the issue. Feel free to open new ones if any further concern
