### ISSUE TITLE
BSC sync problem on the AWS

### ISSUE THREAD

**Issue by pmmasterpm** [binance-chain/bsc#364]
Hello.

I have 2 absolutely identical AWS servers (c5.9xlarge, SSD gp3, Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz, CPU(s): 36, RAM 72G). BSC version 1.1.1 (fast mode). On one server the node was synchronized in about 14 hours. On the second, it has not been able to synchronize for several days. The node always showing 100 blocks behind.

I've tried copying the geth/chaindata folder from the synced node. And this helps to synchronize the second node. But I want to understand what the problem is.

What could be the problem?

Thank You!

**Comment by guagualvcha** [comment]
if your node starts without downloading the snapshot, it will require NVMe SSD.
