### ISSUE TITLE
"Failed to write unclean-shutdown marker" err="leveldb/table: corruption on data-block (pos=1911514): checksum mismatch, want=0x535b6c69 got=0x871597ee [file=682254.ldb]"

### ISSUE THREAD

**Issue by jayboy-mabushi** [binance-chain/bsc#368]
#### System information

Geth version: `1.1.1-beta`
OS & Version: ubuntu 20.4
Commit hash : (if `develop`)

#### Expected behaviour
geth 

#### Actual behaviour
I just synced and geth is reporting unclean database shutdown even though I did not shut it down and it is giving some errors. I believe because of this error, I sometimes get an error when I try to connect to my node

#### Steps to reproduce the behaviour
sync geth 

#### Backtrace
t=2021-08-13T03:21:43+0000 lvl=info msg="New local node record"               seq=1389 id=9accfe10a547850615098d3037f2990926ca7f3267d8f4c8f22bd92ec8a2d6d1 ip=127.0.0.1 udp=30311 tcp=30311
t=2021-08-13T03:21:43+0000 lvl=eror msg="Section processing failed"           type=bloombits error="leveldb/table: corruption on data-block (pos=1911514): checksum mismatch, want=0x535b6c69 got=0x871597ee [file=682254.ldb]"
t=2021-08-13T03:21:43+0000 lvl=info msg="IPC endpoint opened"                 url=/nvme/geth/mainnet/geth.ipc
t=2021-08-13T03:21:43+0000 lvl=info msg="Started P2P networking"              self=enode://155868d1bd15624da81a1a83bc840dcf4018da4c9c4d0de70b737acae8ad96174429844a40420bb5a70170f9b77bcd3584b33429412ab36728bf850469a5a613@127.0.0.1:30311
t=2021-08-13T03:21:43+0000 lvl=info msg="HTTP server started"                 endpoint=127.0.0.1:9545 prefix= cors= vhosts=localhost
t=2021-08-13T03:21:43+0000 lvl=info msg="WebSocket enabled"                   url=ws://127.0.0.1:9546
t=2021-08-13T03:21:59+0000 lvl=info msg="Snap sync requested, enabling --snapshot"
t=2021-08-13T03:21:59+0000 lvl=info msg="Set global gas cap" cap=25,000,000
t=2021-08-13T03:21:59+0000 lvl=info msg="Allocated trie memory caches" clean="2.64 GiB" dirty="4.39 GiB"
t=2021-08-13T03:21:59+0000 lvl=info msg="Allocated cache and file handles" database=/nvme/geth/mainnet/geth/chaindata cache="7.03 GiB" handles=262,144
t=2021-08-13T03:21:59+0000 lvl=info msg="Opened ancient database"          database=/nvme/geth/mainnet/geth/chaindata/ancient readonly=false
t=2021-08-13T03:21:59+0000 lvl=info msg="Initialised chain configuration"  config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}"
t=2021-08-13T03:21:59+0000 lvl=info msg="Unprotected transactions allowed"
t=2021-08-13T03:21:59+0000 lvl=info msg="Initialising Ethereum protocol"   network=56 dbversion=8
t=2021-08-13T03:21:59+0000 lvl=info msg="Loaded most recent local header"  number=9,977,897 hash=0x41535ec6b9ee4ebad1d45ae6ca734dee980a9597924d4b28430bba34e6165f79 td=19,861,062 age=4h13s
t=2021-08-13T03:21:59+0000 lvl=info msg="Loaded most recent local full block" number=0         hash=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b td=1          age=1y3mo4w
t=2021-08-13T03:21:59+0000 lvl=info msg="Loaded most recent local fast block" number=9,977,825 hash=0x434f5877e9f8237771d24af8a34b5d0ac0407b958a911ad9717e058723ff06a7 td=19,860,918 age=4h3m51s
t=2021-08-13T03:21:59+0000 lvl=info msg="Loaded last fast-sync pivot marker"  number=9,977,826
t=2021-08-13T03:21:59+0000 lvl=warn msg="Snapshot maintenance disabled (syncing)"
t=2021-08-13T03:21:59+0000 lvl=info msg="Upgrading chain index"               type=bloombits percentage=38
t=2021-08-13T03:21:59+0000 lvl=warn msg="Sanitizing invalid gasprice oracle price cap" provided=<nil> updated=500,000,000,000
t=2021-08-13T03:21:59+0000 lvl=warn msg="Failed to write unclean-shutdown marker" err="leveldb/table: corruption on data-block (pos=1911514): checksum mismatch, want=0x535b6c69 got=0x871597ee [file=682254.ldb]"
t=2021-08-13T03:21:59+0000 lvl=eror msg="Could not update unclean-shutdown-marker list" error="leveldb/table: corruption on data-block (pos=1911514): checksum mismatch, want=0x535b6c69 got=0x871597ee [file=682254.ldb]"
t=2021-08-13T03:21:59+0000 lvl=info msg="Starting peer-to-peer node"          instance=Geth/v1.1.1-beta-69ce7f1e/linux-amd64/go1.15.5
t=2021-08-13T03:21:59+0000 lvl=info msg="New local node record"               seq=1390 id=9accfe10a547850615098d3037f2990926ca7f3267d8f4c8f22bd92ec8a2d6d1 ip=127.0.0.1 udp=30311 tcp=30311
t=2021-08-13T03:21:59+0000 lvl=eror msg="Section processing failed"           type=bloombits error="leveldb/table: corruption on data-block (pos=1911514): checksum mismatch, want=0x535b6c69 got=0x871597ee [file=682254.ldb]"
t=2021-08-13T03:21:59+0000 lvl=info msg="Started P2P networking"              self=enode://155868d1bd15624da81a1a83bc840dcf4018da4c9c4d0de70b737acae8ad96174429844a40420bb5a70170f9b77bcd3584b33429412ab36728bf850469a5a613@127.0.0.1:30311
t=2021-08-13T03:21:59+0000 lvl=info msg="IPC endpoint opened"                 url=/nvme/geth/mainnet/geth.ipc
t=2021-08-13T03:21:59+0000 lvl=info msg="HTTP server started"                 endpoint=127.0.0.1:9545 prefix= cors= vhosts=localhost
t=2021-08-13T03:21:59+0000 lvl=info msg="WebSocket enabled"                   url=ws://127.0.0.1:9546

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by guagualvcha** [comment]
It is very hard to trouble shoot the data corruption.  You may download latest snapshot https://github.com/binance-chain/bsc-snapshots

**Comment by jayboy-mabushi** [comment]
@guagualvcha  I am getting this error when I try to sync using the snapshot  Fatal: Failed to register the Ethereum service: database contains incompatible genesis (have 0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b, new d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3)

**Comment by guagualvcha** [comment]
Did you exactly follow the guide here https://github.com/binance-chain/bsc-snapshots

It needs to replace your origin data.

**Comment by perfectcircle2020** [comment]
How about implementing this feature as they did here:

https://github.com/ethereum/go-ethereum/issues/20858

It's a flag in geth called '--repairtire'

**Comment by guagualvcha** [comment]
Will kindly close this. Feel free to open new ones.
