### ISSUE TITLE
Imported new state entries

### ISSUE THREAD

**Issue by blockchen-admin** [binance-chain/bsc#369]
t=2021-08-13T02:59:59+0000 lvl=info msg="Imported new state entries"             count=1147 elapsed=5.079ms     processed=769,622,080 pending=11995 trieretry=3   coderetry=0 duplicate=333 unexpected=49
t=2021-08-13T02:59:59+0000 lvl=info msg="Imported new state entries"             count=1113 elapsed=5.274ms     processed=769,623,193 pending=11220 trieretry=16  coderetry=0 duplicate=333 unexpected=49
t=2021-08-13T03:00:00+0000 lvl=info msg="Imported new state entries"             count=1468 elapsed=6.448ms     processed=769,624,661 pending=9996  trieretry=25  coderetry=0 duplicate=333 unexpected=49

Synchronization is not completed on the 2nd day now.

Imported new state entries are
About 120,000 pieces are processed per minute.

Synchronization is complete when the number of processed is equal to the total number of transactions???

**Comment by guagualvcha** [comment]
Fast sync needs NVMe disk. I think your hardware can not do fast sync or snap sync. I will suggest you download snap from this [page](https://github.com/binance-chain/bsc-snapshots)

Please refer to https://github.com/binance-chain/bsc/issues/338
