### ISSUE TITLE
启动节点报错

### ISSUE THREAD

**Issue by jiazechen** [binance-chain/bsc#37]
0|geth     | INFO [09-14|16:13:31.014] Starting Geth on Ethereum mainnet...
0|geth     | INFO [09-14|16:13:31.015] Bumping default cache on mainnet         provided=1024 updated=4096
0|geth     | INFO [09-14|16:13:31.019] Maximum peer count                       ETH=200 LES=0 total=200
0|geth     | INFO [09-14|16:13:31.019] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"

**Comment by guagualvcha** [comment]
This err log is fine, it affect nothing.
