### ISSUE TITLE
Node stays 60-100 blocks away from current block

### ISSUE THREAD

**Issue by worldofibra** [binance-chain/bsc#372]
#### System information

Geth version: 1.1.1- Stable
OS & Version: Linux
CPU- 8 core Intel Xeon(Skylake) Platinum 8163
Ram- 64 gb
Ssd- Nvme SSD with 240k max IOPs  1.7 TB

Not sure if i just haven't downloaded the correct amount of states or if i have something wrong with my files. Been running the node for 3 days in a row now with it being 100 ish blocks away. First couple of days node was processing atleast 1-3 million blocks a day then slowed down. This was a fresh sync but then tried to use the snapshot but that also couldn't sync so went back to my original files. 

#### Actual behaviour

> currentBlock: 10027854,
  highestBlock: 10027966,
  knownStates: 479406624,
  pulledStates: 479385410,
  startingBlock: 10013365

Peer count usually around 20.

#### Steps to reproduce the behaviour
Use geth_linux --config ./config.toml --cache 18000 --http --ws --rpc.allow-unprotected-txs  --datadir ./node  to start up node.
Computer was processing around a 1200 blocks every few seconds but after getting current with known states it can't sync up properly.

I don't get any errors on startup. 

> geth_linux --config ./config.toml --cache 18000 --http --ws --rpc.allow-unprotected-txs  --datadir ./node
INFO [08-14|15:12:05.036] Starting Geth on Ethereum mainnet...
INFO [08-14|15:12:05.041] Maximum peer count                       ETH=300 LES=0 total=300
INFO [08-14|15:12:05.041] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [08-14|15:12:05.041] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 

Here is my bot logs:

> lvl=info msg="Imported new state entries"             count=1152 elapsed=13.038ms    processed=479,340,208 pending=7105  trieretry=5    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:03+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=8.024ms     processed=479,340,976 pending=6878  trieretry=2    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:03+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=4.682ms     processed=479,341,744 pending=7347  trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:04+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=7.539ms     processed=479,342,512 pending=7137  trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:04+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=1.024ms     processed=479,342,896 pending=7541  trieretry=5    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:04+0800 lvl=warn msg="Stalling state sync, dropping peer"     peer=686c6ce96ec256c1e6c502f52e794dff43e32df5d7a38b778a2cc9a92328c9d6
t=2021-08-15T01:45:04+0800 lvl=eror msg="Ethereum peer removal failed"           peer=686c6ce9 err="peer not registered"
t=2021-08-15T01:45:04+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=5.184ms     processed=479,343,280 pending=7291  trieretry=6    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:05+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=4.001ms     processed=479,343,664 pending=7150  trieretry=8    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:06+0800 lvl=info msg="Imported new block headers"             count=1    elapsed="625.401µs" number=10,027,940 hash=0xfbdc0e131be373c4cffd16f6ead5b469ac2bd6ccd17e82f265ae74b6ed513b23
t=2021-08-15T01:45:06+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=2.314ms     processed=479,344,048 pending=7254  trieretry=11   coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:07+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=9.055ms     processed=479,344,816 pending=6789  trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:07+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=5.003ms     processed=479,345,200 pending=6611  trieretry=7    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:07+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=10.385ms    processed=479,345,968 pending=6070  trieretry=0    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:08+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=6.611ms     processed=479,346,736 pending=6538  trieretry=2    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:08+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=3.220ms     processed=479,347,120 pending=8070  trieretry=2    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:08+0800 lvl=info msg="Imported new state entries"             count=384  elapsed="641.299µs" processed=479,347,504 pending=13290 trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:09+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=2.978ms     processed=479,348,272 pending=16955 trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:09+0800 lvl=info msg="Imported new block headers"             count=2    elapsed="967.896µs" number=10,027,942 hash=0xc8c13a8dd8daf7446c5c46dae60af2bed7cea5d48f4614b27dcf865e622e9e35
t=2021-08-15T01:45:10+0800 lvl=info msg="Imported new state entries"             count=383  elapsed=4.567ms     processed=479,348,655 pending=17289 trieretry=8    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:10+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=2.069ms     processed=479,349,039 pending=17812 trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:11+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=4.322ms     processed=479,349,423 pending=20618 trieretry=11   coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:11+0800 lvl=info msg="Downloader queue stats"                 receiptTasks=0    blockTasks=0    itemSize="305.56 KiB" throttle=215
t=2021-08-15T01:45:11+0800 lvl=info msg="Imported new state entries"             count=384  elapsed="116.483µs" processed=479,349,807 pending=23670 trieretry=9    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:12+0800 lvl=info msg="Imported new state entries"             count=777  elapsed=5.489ms     processed=479,350,584 pending=25135 trieretry=7    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:12+0800 lvl=info msg="Imported new state entries"             count=382  elapsed=3.633ms     processed=479,350,966 pending=26331 trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:13+0800 lvl=info msg="Imported new state entries"             count=400  elapsed=3.717ms     processed=479,351,366 pending=26748 trieretry=30   coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:13+0800 lvl=info msg="Imported new block headers"             count=1    elapsed="463.906µs" number=10,027,943 hash=0x8683ddcdf1ca3303a64b1e37d2420a35ce68fabcd9dad8b954566cda1d82f039
t=2021-08-15T01:45:13+0800 lvl=eror msg="Snapshot extension registration failed" peer=3af25a30 err="peer connected on snap without compatible eth support"
t=2021-08-15T01:45:14+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=1.585ms     processed=479,352,134 pending=28213 trieretry=9    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:15+0800 lvl=info msg="Imported new state entries"             count=384  elapsed="206.005µs" processed=479,352,518 pending=28650 trieretry=7    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:16+0800 lvl=info msg="Imported new state entries"             count=384  elapsed="133.786µs" processed=479,352,902 pending=29027 trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:16+0800 lvl=info msg="Imported new state entries"             count=762  elapsed=7.888ms     processed=479,353,664 pending=29186 trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:16+0800 lvl=info msg="Imported new state entries"             count=384  elapsed=3.760ms     processed=479,354,048 pending=29201 trieretry=2    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:16+0800 lvl=info msg="Imported new block headers"             count=1    elapsed="456.118µs" number=10,027,944 hash=0x6c8065d89474d6bf4212d349dbbbda3113c0c61a8a45428a264acec048141a7e
t=2021-08-15T01:45:17+0800 lvl=info msg="Imported new state entries"             count=384  elapsed="298.298µs" processed=479,354,432 pending=29572 trieretry=0    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:17+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=1.946ms     processed=479,355,200 pending=30195 trieretry=2    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:18+0800 lvl=info msg="Imported new state entries"             count=746  elapsed=3.942ms     processed=479,355,946 pending=30470 trieretry=0    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:18+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=9.731ms     processed=479,356,714 pending=30023 trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:19+0800 lvl=info msg="Imported new state entries"             count=768  elapsed=11.323ms    processed=479,357,482 pending=29055 trieretry=4    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:19+0800 lvl=info msg="Imported new state entries"             count=763  elapsed=11.646ms    processed=479,358,245 pending=28296 trieretry=5    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:19+0800 lvl=info msg="Imported new state entries"             count=1155 elapsed=18.418ms    processed=479,359,400 pending=26477 trieretry=0    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:20+0800 lvl=info msg="Imported new block headers"             count=1    elapsed="490.866µs" number=10,027,945 hash=0x379b71cab199205e5f6672a22655ff8a78e44b502a118c0b8aa4003ff30bd3a1
t=2021-08-15T01:45:20+0800 lvl=info msg="Imported new state entries"             count=810  elapsed=5.634ms     processed=479,360,210 pending=26457 trieretry=5    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:20+0800 lvl=info msg="Imported new state entries"             count=811  elapsed=9.916ms     processed=479,361,021 pending=26352 trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:20+0800 lvl=info msg="Imported new state entries"             count=826  elapsed=8.256ms     processed=479,361,847 pending=26584 trieretry=5    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:20+0800 lvl=info msg="Imported new state entries"             count=879  elapsed=8.638ms     processed=479,362,726 pending=25969 trieretry=1    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:21+0800 lvl=info msg="Imported new state entries"             count=805  elapsed=9.873ms     processed=479,363,531 pending=25476 trieretry=5    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:22+0800 lvl=info msg="Imported new state entries"             count=1365 elapsed=15.302ms    processed=479,364,896 pending=24440 trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:22+0800 lvl=info msg="Imported new state entries"             count=810  elapsed=9.758ms     processed=479,365,706 pending=23990 trieretry=3    coderetry=0  duplicate=398,511 unexpected=687,883
t=2021-08-15T01:45:23+0800 lvl=info msg="Imported new block headers"             count=1    elapsed="565.74µs"  number=10,027,946 hash=0x63259f23b3cf21bc66feec441635d2d1b89fdcf5320d2d50a461a1a2fc4742fd
t=2021-08-15T01:45:26+0800 lvl=info msg="Imported new block headers"             count=1    elapsed="613.284µs" number=10,027,947 hash=0xbf1dddca8eb47e104f3192ced1bad2771f76e1b513e5ea3efa9941dc283ce7d8
t=2021-08-15T01:45:26+0800 lvl=info msg="Imported new state entries"             count=1145 elapsed=8.530ms     processed=479,366,851 pending=24371 trieretry=2    coderetry=0  duplicate=398,511 unexpected=687,883

Here is my config.toml:

> [Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 2000000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

>[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

>[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

>[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

>[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

>[Node.P2P]
MaxPeers = 300
NoDiscovery = false
BootstrapNodes = ["enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311","enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311","enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"]
StaticNodes = ["enode://f3cfd69f2808ef64838abd8786342c0b22fdd28268703c8d6812e26e109f9a7cb2b37bd49724ebb46c233289f22da82991c87345eb9a2dadeddb8f37eeb259ac@18.180.28.21:30311","enode://ae74385270d4afeb953561603fcedc4a0e755a241ffdea31c3f751dc8be5bf29c03bf46e3051d1c8d997c45479a92632020c9a84b96dcb63b2259ec09b4fde38@54.178.30.104:30311","enode://d1cabe083d5fc1da9b510889188f06dab891935294e4569df759fc2c4d684b3b4982051b84a9a078512202ad947f9240adc5b6abea5320fb9a736d2f6751c52e@54.238.28.14:30311","enode://f420209bac5324326c116d38d83edfa2256c4101a27cd3e7f9b8287dc8526900f4137e915df6806986b28bc79b1e66679b544a1c515a95ede86f4d809bd65dab@54.178.62.117:30311","enode://c0e8d1abd27c3c13ca879e16f34c12ffee936a7e5d7b7fb6f1af5cc75c6fad704e5667c7bbf7826fcb200d22b9bf86395271b0f76c21e63ad9a388ed548d4c90@54.65.247.12:30311","enode://f1b49b1cf536e36f9a56730f7a0ece899e5efb344eec2fdca3a335465bc4f619b98121f4a5032a1218fa8b69a5488d1ec48afe2abda073280beec296b104db31@13.114.199.41:30311","enode://4924583cfb262b6e333969c86eab8da009b3f7d165cc9ad326914f576c575741e71dc6e64a830e833c25e8c45b906364e58e70cdf043651fd583082ea7db5e3b@18.180.17.171:30311","enode://4d041250eb4f05ab55af184a01aed1a71d241a94a03a5b86f4e32659e1ab1e144be919890682d4afb5e7afd837146ce584d61a38837553d95a7de1f28ea4513a@54.178.99.222:30311","enode://b5772a14fdaeebf4c1924e73c923bdf11c35240a6da7b9e5ec0e6cbb95e78327690b90e8ab0ea5270debc8834454b98eca34cc2a19817f5972498648a6959a3a@54.170.158.102:30311","enode://f329176b187cec87b327f82e78b6ece3102a0f7c89b92a5312e1674062c6e89f785f55fb1b167e369d71c66b0548994c6035c6d85849eccb434d4d9e0c489cdd@34.253.94.130:30311","enode://cbfd1219940d4e312ad94108e7fa3bc34c4c22081d6f334a2e7b36bb28928b56879924cf0353ad85fa5b2f3d5033bbe8ad5371feae9c2088214184be301ed658@54.75.11.3:30311","enode://c64b0a0c619c03c220ea0d7cac754931f967665f9e148b92d2e46761ad9180f5eb5aaef48dfc230d8db8f8c16d2265a3d5407b06bedcd5f0f5a22c2f51c2e69f@54.216.208.163:30311","enode://352a361a9240d4d23bb6fab19cc6dc5a5fc6921abf19de65afe13f1802780aecd67c8c09d8c89043ff86947f171d98ab06906ef616d58e718067e02abea0dda9@79.125.105.65:30311","enode://bb683ef5d03db7d945d6f84b88e5b98920b70aecc22abed8c00d6db621f784e4280e5813d12694c7a091543064456ad9789980766f3f1feb38906cf7255c33d6@54.195.127.237:30311","enode://11dc6fea50630b68a9289055d6b0fb0e22fb5048a3f4e4efd741a7ab09dd79e78d383efc052089e516f0a0f3eacdd5d3ffbe5279b36ecc42ad7cd1f2767fdbdb@46.137.182.25:30311","enode://21530e423b42aed17d7eef67882ebb23357db4f8b10c94d4c71191f52955d97dc13eec03cfeff0fe3a1c89c955e81a6970c09689d21ecbec2142b26b7e759c45@54.216.119.18:30311","enode://d61a31410c365e7fcd50e24d56a77d2d9741d4a57b295cc5070189ad90d0ec749d113b4b0432c6d795eb36597efce88d12ca45e645ec51b3a2144e1c1c41b66a@34.204.129.242:30311","enode://bb91215b1d77c892897048dd58f709f02aacb5355aa8f50f00b67c879c3dffd7eef5b5a152ac46cdfb255295bec4d06701a8032456703c6b604a4686d388ea8f@75.101.197.198:30311","enode://786acbdf5a3cf91b99047a0fd8305e11e54d96ea3a72b1527050d3d6f8c9fc0278ff9ef56f3e56b3b70a283d97c309065506ea2fc3eb9b62477fd014a3ec1a96@107.23.90.162:30311","enode://4653bc7c235c3480968e5e81d91123bc67626f35c207ae4acab89347db675a627784c5982431300c02f547a7d33558718f7795e848d547a327abb111eac73636@54.144.170.236:30311","enode://c6ffd994c4ef130f90f8ee2fc08c1b0f02a6e9b12152092bf5a03dd7af9fd33597d4b2e2000a271cc0648d5e55242aeadd6d5061bb2e596372655ba0722cc704@54.147.151.108:30311","enode://99b07e9dc5f204263b87243146743399b2bd60c98f68d1239a3461d09087e6c417e40f1106fa606ccf54159feabdddb4e7f367559b349a6511e66e525de4906e@54.81.225.170:30311","enode://1479af5ea7bda822e8747d0b967309bced22cad5083b93bc6f4e1d7da7be067cd8495dc4c5a71579f2da8d9068f0c43ad6933d2b335a545b4ae49a846122b261@52.7.247.132:30311","enode://43562d35f274d9e93f5ccac484c7cb185eabc746dbc9f3a56c36dc5a9ef05a3282695de7694a71c0bf4600651f49395b2ee7a6aaef857db2ac896e0fcbe6b518@35.73.15.198:30311","enode://08867e57849456fc9b0b00771f53e87ca6f2dd618c23b34a35d0c851cd484a4b7137905c5b357795025b368e4f8fe4c841b752b0c28cc2dbbf41a03d048e0e24@35.74.39.234:30311"]
ListenAddr = ":30311"
EnableMsgEvents = false

>[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

>[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""

i followed this exactly:
https://docs.binance.org/smart-chain/developer/fullnode.html

And I used the latest geth download from here:

https://github.com/binance-chain/bsc/releases/tag/v1.1.1

**Comment by guagualvcha** [comment]
fast sync or snap sync need NVMe ssd, please refer to https://github.com/binance-chain/bsc/issues/338

**Comment by worldofibra** [comment]
> fast sync or snap sync need NVMe ssd, please refer to #338

I said i have a NVME at the top of the post....

**Comment by czarly** [comment]
same problem here

Ryzen 5950x 
2 NVMe in Raid0
128 GB RAM

**Comment by worldofibra** [comment]
> same problem here
> 
> Ryzen 5950x
> 2 NVMe in Raid0
> 128 GB RAM

I got synced by using snapshot from
https://github.com/binance-chain/bsc-snapshots

Just replace chaindata and triecache folders in your data directory with the ones from the snapshot.
