### ISSUE TITLE
How is the `cache` value set for `writeBuffer` calculated?

### ISSUE THREAD

**Issue by fomotrader** [binance-chain/bsc#375]
`cache` calculation of my node and the write buffer size is confusing.

`CacheFlag.Name` on my node is 42931
`CacheDatabaseFlag.Name` is 50 (even though I set `DatabaseCache` to 9k in config.toml file) because I'm learning by trial and error

So the value calculated for the cache is 21465. That value is used to set my levelDB write buffer to 5626658816

I have several questions;
1.) Is the writeBuffer in levelDB MiB or bytes?
2.) What flag does the DatabaseCache in config.toml represent?
3.) What sets the CacheFlag.name value to 42931?
4.) Are all these units Bytes or MiB and how can I find out?
5.) What directory can I find the leveldb files in? Is it the datadir and are they the log files in that datadir?

**Comment by FomoCoder** [comment]
cc @guagualvcha

**Comment by guagualvcha** [comment]
Hi, @FomoCoder 
1.)  It is Mbi.
2.) It is the cache used for level DB.
3.) I don't quite get the question
4.) It is MiB. https://github.com/binance-chain/bsc/blob/c4f931212903b3ee8495c36ac374340aec4ac269/ethdb/leveldb/leveldb.go#L45
5.) It is under `${Your geth data dir}/chaindata`

**Comment by guagualvcha** [comment]
close this.
