### ISSUE TITLE
Failed to connect to nodes due to out-of-date genesis.json

### ISSUE THREAD

**Issue by wellttllew** [binance-chain/bsc#378]
#### System information

Geth version: `geth v1.1.1`
OS & Version: Linux

#### Expected behaviour

I am trying to setup an archive node and try to sync from genesis block rather than use your provided [snapshot](https://github.com/binance-chain/bsc-snapshots). I downloaded the latest `genesis.json` from [here](https://github.com/binance-chain/bsc/releases/tag/v1.1.1). After `geth init` with the `genesis.json` and I started my node. 

I expected my node to be able to connect with at least one of the `bootstrap/static nodes`.  

#### Actual behaviour

After waiting for around 15min, my node connected to the first node :  

```
enr=enode://16cdbe6d29362f5e91101f43b36ccf45edef7a3562ff61339b0fed8dd124d26fc54a3eafda2d0959ceef740fa2a31b9553a6ab8f3db7b687b41cf97dd6735d6c@94.130.131.79:30311
``` 

And after waiting for around 24h more, my node still cannot connect to any of the `bootstrap/static nodes` provided in your `toml file`, and the `node` mentioned above is still the only connected node.  

#### Solution 

After digging into the `devp2p` a little bit, I found out your `genesis.json` file is out-of-date. With the out-of-date `gengesis.json`,  my node failed to handshake with all the `bootstrap/static nodes` due to a failure in `fork id filter check`. 

The solution is simple, just insert one line (include the `mirrorSyncBlock` ) to your out-of-date `genesis.json`: 

```diff
*** 7,12 ****
--- 7,13 ----
      "eip155Block": 0,
      "eip158Block": 0,
      "byzantiumBlock": 0,
+     "mirrorSyncBlock":5184000,
      "constantinopleBlock": 0,    "petersburgBlock": 0,    "istanbulBlock": 0,    "muirGlacierBlock": 0,    "ramanujanBlock": 0,    "nielsBlock": 0,    "parlia": {      "period": 3,      "epoch": 200    }  },  "nonce": "0x0",  "timestamp": "0x5e9da7ce",  "extraData": "0x00000000000000000000000000000000000000000000000000000000000000002a7cdd959bfe8d9487b2a43b33565295a698f7e26488aa4d1955ee33403f8ccb1d4de5fb97c7ade29ef9f4360c606c7ab4db26b016007d3ad0ab86a0ee01c3b1283aa067c58eab4709f85e99d46de5fe685b1ded8013785d6623cc18d214320b6bb6475978f3adfc719c99674c072166708589033e2d9afec2be4ec20253b8642161bc3f444f53679c1f3d472f7be8361c80a4c1e7e9aaf001d0877f1cfde218ce2fd7544e0b2cc94692d4a704debef7bcb61328b8f7166496996a7da21cf1f1b04d9b3e26a3d0772d4c407bbe49438ed859fe965b140dcf1aab71a96bbad7cf34b5fa511d8e963dbba288b1960e75d64430b3230294d12c6ab2aac5c2cd68e80b16b581ea0a6e3c511bbd10f4519ece37dc24887e11b55d7ae2f5b9e386cd1b50a4550696d957cb4900f03a82012708dafc9e1b880fd083b32182b869be8e0922b81f8e175ffde54d797fe11eb03f9e3bf75f1d68bf0b8b6fb4e317a0f9d6f03eaf8ce6675bc60d8c4d90829ce8f72d0163c1d5cf348a862d55063035e7a025f4da968de7e4d7e4004197917f4070f1d6caa02bbebaebb5d7e581e4b66559e635f805ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "gasLimit": "0x2625a00",
    "difficulty": "0x1",

```

**Comment by guagualvcha** [comment]
Thanks a lot for the report, we will verify it ASAP

**Comment by teroneko** [comment]
Maybe this correlates to this error:
> Fatal: Failed to write genesis block: mismatching mirrorSync fork block in database (have 5184000, want <nil>, rewindto 5183999)
Happens when unpacking mainnet.zip and executing the first time `geth --datadir node init genesis.json`. I will check now, but first unzip 400 gb again. >.>

**Comment by teroneko** [comment]
Okay, after 3 hours I can confirm, that the error is gone, when adding the provided line from @wellttllew. :)

**Comment by guagualvcha** [comment]
will kindly close this.  thanks @wellttllew
