### ISSUE TITLE
geth dump don't works

### ISSUE THREAD

**Issue by gr8den** [binance-chain/bsc#382]
#### System information

Geth version: `Geth/v1.1.2-c4f93121/linux-amd64/go1.15.5`
OS & Version: `Ubuntu 18.04.1`

#### Expected behaviour
Geth dump works

#### Actual behaviour
Geth dump failed with error "Fatal: could not create new state: missing trie node"

#### Steps to reproduce the behaviour
Node fully synced (default configuration). Then node stopped. Then run following commands:

~ ./bsc-geth --config ./config.toml --datadir $BSC_DATA dump 10342382 > bsc-dump-10342382.json
\>
> INFO [08-26|01:02:23.769] Maximum peer count                       ETH=30 LES=0 total=30
INFO [08-26|01:02:23.769] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [08-26|01:02:23.769] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
Fatal: could not create new state: missing trie node 5495c9bb4321f66344773743f712aa3e0836b9e4d2f8e763542696b895e4b1c6 (path )

~ cat bsc-dump-10342382.json
> Fatal: could not create new state: missing trie node 5495c9bb4321f66344773743f712aa3e0836b9e4d2f8e763542696b895e4b1c6 (path )

**Comment by wellttllew** [comment]
`Geth dump` will dump not only the specified block but also the snapshot of the state (includes eth balance of each address, codes of each contract, storage of each contract etc. ) at the time of that block.  

If you are not running your node with  `--gcmode=archive`,   `geth` will not flush all the trie nodes to database (actually, it will skip some intermediate states, flush only after a fixed interval or reaching a dirty size limit).

**Comment by guagualvcha** [comment]
@wellttllew  is right, you need running an archvive node to get a dump of a specified height.
