### ISSUE TITLE
Anyone successfully run a full node on M1 Mac mini?

### ISSUE THREAD

**Issue by nikingstore** [binance-chain/bsc#383]
I tried few weeks try to run a full node on google clouds, but I think it's the IOPS issue, can't really get it synced after a lot of attemps. Local SSD on google cloud is extremely expensive, so I want to try to build the node on a new m1 mac mini?
But don't want to waste my money? Anybody know if it's possible to run the node on a M1 mac mini?

**Comment by fastener** [comment]
Of course, you just need to download the geth client and BSC configuration files. https://github.com/binance-chain/bsc/releases/
。
After downloading, enter the directory.
Execute the command geth first_ mac -- dataDir node init genesis.json for initialization,
Then execute geth_ mac -- dataDir node -- config.toml client

**Comment by fastener** [comment]
If you want to put the node data into the mobile hard disk, you can initialize it in the mobile hard disk and then start it. Note: IPC cannot be used when starting in the mobile hard disk. You can modify the IPCPath in config.toml to the directory in your computer hard disk to run normally

**Comment by nikingstore** [comment]
> If you want to put the node data into the mobile hard disk, you can initialize it in the mobile hard disk and then start it. Note: IPC cannot be used when starting in the mobile hard disk. You can modify the IPCPath in config.toml to the directory in your computer hard disk to run normally

wow...thank you, i'll give it a shot. :)
