### ISSUE TITLE
Node stop syncing at Block: 10394607

### ISSUE THREAD

**Issue by FeurJak** [binance-chain/bsc#387]
My node has stopped syncing at at Block: 10394607 and now i'm getting these things continuously printed on the console without my input: 

`> {"balance":"62526386212277327","nonce":140,"root":"56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":
"c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","address":"0x4be1d21e20f7a80e179909f499df28b3b27341e3"}        
{"balance":"0","nonce":1,"root":"1f9be30e5468e6dd3ca9da6b3b88312ae01b8d317a541ab61e15299b0a52bb55","codeHash":"fc1ea81db44e2de921b
958dc92da921a18968ff3f3465bd475fb86dd1af03986","address":"0x8cfdbdb84a75cbe149c9a7c44fc911f2c33ce6a4"}                            
{"balance":"978967218409158395","nonce":69,"root":"56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"c
5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","address":"0x2a349361a141a7a3e8f9f01917085b570ba166b1"}          
{"balance":"0","nonce":1,"root":"d90e50233f8377e481775e19645b8867fee8db38c13eed99ef523087fc9825ac","codeHash":"02d664941017f4390cb
c78017c0428570a2228b60f745688d479336fa561be3c","address":"0x83a76ff60aeff493832ae1d254b24248190f85d6"}                            
{"balance":"0","nonce":1,"root":"e298b37305d94d52351dcefcefa10bc20c84f670724f4bb7fbb597951d2d88f0","codeHash":"3b631ac9376e7309b1d
3154e97f957bb4afa1f4fb04f6cd9ffaa3b7d5aa8264d","address":"0xe34653265484200a4b791851f7c37e25aab8d4a3"}                            
{"balance":"0","nonce":1,"root":"7120306b5251b54fb484b50b2916f1099f72bd0d4639d785eef5364c2634a3f7","codeHash":"90fa393552d1a496927
0fd34a4a5f47d8287c1cd9ced318b943ab2a5290429f4","address":"0x03b6b7cc6b933961f18b1708892f298cb0824ce2"}                            
{"balance":"37124672845416782","nonce":3,"root":"56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","codeHash":"c5d
2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","address":"0x5d9744f45636f3477d774c13a535844b4aeb8b6f"}            
{"balance":"0","nonce":1,"root":"858e702420cad355b684f10d5a6d976e8dad69d5d23e95099c91b2cbf6304708","codeHash":"60e4bcb14447615ab7c
14fda2c2d70ca4191570e8841c75618e627c8f72662f8","address":"0xad1bfa8b34e6f6e63972d47667712f36061d955b"}    `

Can anyone explain what's going on?

**Comment by kenshou** [comment]
same issue for me too.I'll try  1.1.2

**Comment by Nilotaviano** [comment]
I'm still getting this issue on 1.1.12

**Comment by FeurJak** [comment]
> I'm still getting this issue on 1.1.12

try to use the latest snapshot which should allready have that block
