### ISSUE TITLE
The test network cannot query the bep20 transaction, and the account balance is incorrect

### ISSUE THREAD

**Issue by fastener** [binance-chain/bsc#391]
I use this website（ https://testnet.binance.org/faucet-smart ）Click give me BNB, the amount in the account will increase, but when I send transactions to my account with Peggy tokens, the amount in the account does not increase. I don't quite understand this. Why?
In bsccan testnet, there are BNB transactions in transition, but the transactions sent by Peggy tokens are in bep20 token txns. But I can't synchronize Peggy tokens in my local geth. How can I query and display this transaction?
Transaction inquiry address: https://testnet.bscscan.com/address/0x9FA04d6f30039bd0798c1A7AB1361aDB918B57a3#tokentxns

**Comment by guagualvcha** [comment]
Hi, @fastener, I guess the problem is your local geth, is it syncing?

**Comment by SL1825** [comment]
Is it possible that the token I bought is fake?

**Comment by 0fuz** [comment]
Is it chain id mistake?

**Comment by guagualvcha** [comment]
closing this since no response.
