### ISSUE TITLE
block.basefee

### ISSUE THREAD

**Issue by DEntwickler** [binance-chain/bsc#392]
im testing the usecase of block.basefee on bsc and got this error: { "code": -32000, "message": "invalid opcode: opcode 0x48 not defined" }
isnt it support yet?
thanks!

**Comment by wellttllew** [comment]
EIP-1559 (in London fork ) has not be implemented in BSC yet:

- [BSC Chain Config](https://github.com/binance-chain/bsc/blob/c4f931212903b3ee8495c36ac374340aec4ac269/params/config.go#L412)    
- [go-ethereum](https://github.com/ethereum/go-ethereum/blob/26675454bf93bf904be7a43cce6b3f550115ff90/params/config.go#L315)

**Comment by guagualvcha** [comment]
BSC won't enable EIP1559.
