### ISSUE TITLE
how to improve node mgasps

### ISSUE THREAD

**Issue by scream7** [binance-chain/bsc#403]
My node is AWS c5.4xlarge, 2T NVME. run with full sync mode.
Usually, the mgasps can catch up new blocks, likes:

> t=2021-09-01T03:38:58+0000 lvl=info msg="Imported new chain segment"            blocks=1   txs=231   mgas=36.365  elapsed=2.279s      mgasps=15.955  number=10,525,232 hash=0x237ade0f30357a847d5648ad96da55e8c4f95ce4a4efbd109aac7f8389920428 dirty="2.08 GiB"

But if a block mags increased rapiddly, like 100 mgas, it can hardly catch up.

My question is how to increase the mgasps, any config recomanded or node requirement? thanks.

**Comment by PanJ** [comment]
For me, v1.1.2 is slower to process transactions too. The sync process is significantly slower than v1.1.1

**Comment by souilh** [comment]
Hello @PanJ PanJ

I run on same Issue i'm having good NVME but my Mgasps is not stable going from 20 to 80 , can you please share how you solve any any config tunnig ?

Thanks

**Comment by guagualvcha** [comment]
Please refer to https://github.com/binance-chain/bsc/issues/502. Will close this issue since duplicated.
