### ISSUE TITLE
Full node disk is about 10 TB

### ISSUE THREAD

**Issue by Scumwong** [binance-chain/bsc#414]
my full node disk is about 10 TB ,does anyone know how i can  purne the date? thanks

**Comment by pefka** [comment]
the node took 2 terrabytes, what is so much? are there any solutions?

**Comment by perfectcircle2020** [comment]
You can prune the database regularly with this command: `geth --datadir /my/data/dir snapshot prune-state`

At the moment my node size is about 600 GB

**Comment by Scumwong** [comment]
> You can prune the database regularly with this command: `geth --datadir /my/data/dir snapshot prune-state`
> 
> At the moment my node size is about 600 GB
 
Thanks you and does it need to stop bsc sevrice before command `geth --datadir /my/data/dir snapshot prune-state`?

**Comment by perfectcircle2020** [comment]
> 
> 
> > You can prune the database regularly with this command: `geth --datadir /my/data/dir snapshot prune-state`
> > At the moment my node size is about 600 GB
> 
> Thanks you and does it need to stop bsc sevrice before command `geth --datadir /my/data/dir snapshot prune-state`?

Yeah you need to stop it

**Comment by Scumwong** [comment]
> > > You can prune the database regularly with this command: `geth --datadir /my/data/dir snapshot prune-state`
> > > At the moment my node size is about 600 GB
> > 
> > 
> > Thanks you and does it need to stop bsc sevrice before command `geth --datadir /my/data/dir snapshot prune-state`?
> 
> Yeah you need to stop it

OK，i will try it later.. Thank you ~

**Comment by nilampatel-engineer** [comment]
> > > You can prune the database regularly with this command: `geth --datadir /my/data/dir snapshot prune-state`
> > > At the moment my node size is about 600 GB
> > 
> > 
> > Thanks you and does it need to stop bsc sevrice before command `geth --datadir /my/data/dir snapshot prune-state`?
> 
> Yeah you need to stop it

How will you stop bsc from syncing? and then add this flag to commands to prune the data?
