### ISSUE TITLE
How local get uses websocket？

### ISSUE THREAD

**Issue by fastener** [binance-chain/bsc#416]
I modified WSOrigins=['*'] in config.toml, but I still can't use WebSockets to link to geth.

. /geth_linux attach ws://127.0.0.1:8576
Fatal: Unable to attach to remote geth: dial TCP 127.0.0.1:8576: connect: connection refused。

Ask me how to connect to geth using webscoket

**Comment by 0fuz** [comment]
Hello, important part for me about ws were add `--ws` to geth command line. something like `./geth --config ... --datadir ... --ws`
at config toml I has only this ws-linked lines:
`WSPort = 8546`
`WSModules = ["net", "web3", "eth", "txpool"]`

after that I can connect to ws from nodejs 127.0.0.1:8546

**Comment by guagualvcha** [comment]
@fastener will close this, and thanks @0fuz for answering this
