### ISSUE TITLE
Anyone knows how to resycn current block from the stopping?

### ISSUE THREAD

**Issue by daron4ever** [binance-chain/bsc#417]
Hi,

The block suddenly stopped and i tried to reconnect using the following snippet and it seems it doesnt work.
`screen`
`./build/bin/geth --syncmode=fast --config ./config.toml --datadir ./node --metrics --cache 128000 -verbosity 5 --ws --rpc.allow-unprotected-txs --txlookuplimit 0 --pprof.addr 0.0.0.0 --ws.origins "*" --ws.addr 0.0.0.0 --maxpeers 500`

i want to continue syncing from the latest block I have.
Plz any help?

**Comment by emadami3060** [comment]
Hi

**Comment by daron4ever** [comment]
I resolved it. 
I removed the existing screen detached and it seems working with new screen command.
