### ISSUE TITLE
Light mode of BSC node?

### ISSUE THREAD

**Issue by RickCastle2018** [binance-chain/bsc#420]
Is it possible to run BSC node geth -—syncmode light mode?

This is what i get following steps https://github.com/binance-chain/bsc only using -—syncmode light

```
t=2021-05-08T11:56:12+0300 lvl=info msg="Block synchronisation started"
t=2021-05-08T11:56:47+0300 lvl=info msg="Looking for peers"                   peercount=0 tried=26 static=26
t=2021-05-08T11:56:57+0300 lvl=info msg="Looking for peers"                   peercount=0 tried=26 static=26
t=2021-05-08T11:57:12+0300 lvl=warn msg="Synchronisation failed, dropping peer" peer=0e8faf860dce288213e055a2c3efee9b3db5190465d6bdc9333b9a8178ffebda err=timeout
t=2021-05-08T11:57:22+0300 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=26
t=2021-05-08T11:57:57+0300 lvl=info msg="Looking for peers"                     peercount=0 tried=26 static=26
t=2021-05-08T11:58:22+0300 lvl=warn msg="Synchronisation failed, dropping peer" peer=0e8faf860dce288213e055a2c3efee9b3db5190465d6bdc9333b9a8178ffebda err=timeout
t=2021-05-08T11:58:32+0300 lvl=info msg="Looking for peers"                     peercount=0 tried=26 static=26
t=2021-05-08T11:58:42+0300 lvl=info msg="Looking for peers"                     peercount=0 tried=26 static=26
t=2021-05-08T11:59:07+0300 lvl=info msg="Looking for peers"                     peercount=0 tried=0  static=26
t=2021-05-08T11:59:42+0300 lvl=info msg="Looking for peers"                     peercount=0 tried=26 static=26
```

and so on without syncing any blocks

https://ethereum.stackexchange.com/questions/98558/running-bsc-node-in-light-mode

Can I use node, but without using 1TB of space?

**Comment by 0fuz** [comment]
Light mode means you are ready to send queries to other nodes. They might be slow and small amount which support light mode peers. If your tasks don't rely from critical fast query processing then u can look for light mode or any provider like bscfree(https://docs.binance.org/smart-chain/developer/rpc.html)/bscscan(need apikey)/quicknode(pay for usage)/etc

1TB is recommended size but bcs-snapshot size ~560GB and it growths to 700-800GB in 2weeks then make state-prune and size reduces to ~560GB

**Comment by RickCastle2018** [comment]
@0fuz, thank you, now it became clearer. 

I was interested in this question because my service needs websockets for web3.js subscriptions, so I was looking for something like Binance Chain light client (https://docs.binance.org/light-client.html), but for Binance Smart Chain, because there's no free nodes for testnet with Websockets enabled. I wanted to set up my own light node and get websockets API without storing 560GB of data. Could you suggest something, please?

**Comment by psdlt** [comment]
@RickCastle2018 BSC *testnet* is 35-40GB, don't need any special hardware to catch-up to network. For *mainnet* there _are_ free WS nodes available (see URL to Binance docs posted above). Stability is not guaranteed, but they're free.

**Comment by guagualvcha** [comment]
```
wss://data-seed-prebsc-2-s1.binance.org:8545
wss://data-seed-prebsc-1-s2.binance.org:8545
wss://data-seed-prebsc-2-s2.binance.org:8545
wss://data-seed-prebsc-1-s3.binance.org:8545
wss://data-seed-prebsc-2-s3.binance.org:8545
```
All the above nodes support wss on testnet.  @RickCastle2018

**Comment by RickCastle2018** [comment]
@guagualvcha Thank you very much! These are new?

**Comment by KeefeL** [comment]
Yes, these are free nodes for testnet.

> ```
> wss://data-seed-prebsc-2-s1.binance.org:8545
> wss://data-seed-prebsc-1-s2.binance.org:8545
> wss://data-seed-prebsc-2-s2.binance.org:8545
> wss://data-seed-prebsc-1-s3.binance.org:8545
> wss://data-seed-prebsc-2-s3.binance.org:8545
> ```
> 
> All the above nodes support wss on testnet. @RickCastle2018

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by Thankgod20** [comment]
Light client node not working. It’s giving out errors stating it’s temporarily unavailable

**Comment by Thankgod20** [comment]
panic: Error initializing DB: resource temporarily unavailable
