### ISSUE TITLE
AWS node from aws-snapshot slow sync.

### ISSUE THREAD

**Issue by 0fuz** [binance-chain/bsc#422]
Steps I made:
1. download snapshot
2. make full sync with geth-1.1.2 (its fast enough, 5-10k blocks in a hour)
3. stop geth
4. make volume snapshot
5. create new instance with volume from snapshot
6. start geth sync
7. geth syncing going really slow (30 peers at config.toml), check logs below. 

I tried leave folders like bsc-snapshot has, but this not helped

<details>
  <summary>Logs after geth opened ipc and enode url</summary>
  
t=2021-09-16T07:55:12+0000 lvl=info msg="Block synchronisation started"
t=2021-09-16T07:55:22+0000 lvl=eror msg="Snapshot extension registration failed" peer=3af25a30 err="peer connected on snap without compatible eth support"
t=2021-09-16T07:56:12+0000 lvl=warn msg="Synchronisation failed, dropping peer"  peer=5ca1112f60ff345dbc91cb0869fb88272a5b3bebc9d0ab7134a869b47ba77cfc err=timeout
t=2021-09-16T07:56:12+0000 lvl=eror msg="Ethereum peer removal failed"           peer=5ca1112f err="peer not registered"
t=2021-09-16T07:56:15+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0 itemSize="15.62 KiB" throttle=4196
t=2021-09-16T07:56:19+0000 lvl=eror msg="Snapshot extension registration failed" peer=98998f1a err="peer connected on snap without compatible eth support"
t=2021-09-16T07:56:20+0000 lvl=eror msg="Snapshot extension registration failed" peer=98ea4397 err="peer connected on snap without compatible eth support"
t=2021-09-16T07:56:20+0000 lvl=eror msg="Snapshot extension registration failed" peer=9803e139 err="peer connected on snap without compatible eth support"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=7886bf55 err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=756113fb err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=16fa31e9 err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=75f7ca91 err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=aab7a154 err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=49226b01 err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=75c58a4f err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=76937f51 err="peer not registered"
t=2021-09-16T07:56:55+0000 lvl=eror msg="Ethereum peer removal failed"           peer=758aaba4 err="peer not registered"
t=2021-09-16T07:57:17+0000 lvl=eror msg="Snapshot extension registration failed" peer=20dcc090 err="peer connected on snap without compatible eth support"
t=2021-09-16T07:57:25+0000 lvl=eror msg="Ethereum peer removal failed"           peer=76abce4d err="peer not registered"
t=2021-09-16T07:57:25+0000 lvl=eror msg="Ethereum peer removal failed"           peer=990239ec err="peer not registered"
t=2021-09-16T07:57:25+0000 lvl=eror msg="Ethereum peer removal failed"           peer=10804668 err="peer not registered"
t=2021-09-16T07:57:25+0000 lvl=eror msg="Ethereum peer removal failed"           peer=9865634c err="peer not registered"
t=2021-09-16T07:57:42+0000 lvl=eror msg="Snapshot extension registration failed" peer=1125cc47 err="peer connected on snap without compatible eth support"
t=2021-09-16T07:57:45+0000 lvl=eror msg="Ethereum peer removal failed"           peer=0cf6e060 err="peer not registered"
t=2021-09-16T08:02:10+0000 lvl=info msg="Imported new chain segment"             blocks=1 txs=348 mgas=36.337 elapsed=5m54.759s mgasps=0.102 number=10,854,786 hash=0xd64918107fd768f8bd42a02c17519725c92c8972aff55a1e4eccbad2d9b0b878 age=3d15h2m  dirty="3.36 MiB"
t=2021-09-16T08:05:25+0000 lvl=info msg="Persisted trie from memory database"    nodes=0 size="0.00 B" time="2.441µs" gcnodes=0 gcsize="0.00 B" gctime=0s livenodes=15758 livesize="5.53 MiB"
t=2021-09-16T08:05:25+0000 lvl=info msg="Imported new chain segment"             blocks=1 txs=253 mgas=31.293 elapsed=3m15.291s mgasps=0.160 number=10,854,787 hash=0xf05861f3a03715d44186eb6946d1b2d81b2c0ce214a4a9bcc239d7414482e688 age=3d15h5m  dirty="7.00 MiB"
t=2021-09-16T08:05:25+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=33818 itemSize="48.59 KiB" throttle=1349
t=2021-09-16T08:05:26+0000 lvl=info msg="Unindexing transactions"                blocks=81573 txs=620 total=8,504,788 elapsed=1.000s
t=2021-09-16T08:05:34+0000 lvl=info msg="Unindexing transactions"                blocks=400,000 txs=127,397 total=8,504,788 elapsed=9.000s
t=2021-09-16T08:05:42+0000 lvl=info msg="Unindexing transactions"                blocks=448,266 txs=334,482 total=8,504,788 elapsed=17.038s
t=2021-09-16T08:05:50+0000 lvl=info msg="Unindexing transactions"                blocks=476,283 txs=568,181 total=8,504,788 elapsed=25.120s
t=2021-09-16T08:05:58+0000 lvl=info msg="Deep froze chain segment"               blocks=2       elapsed=916.087ms number=10,764,787 hash=0x9e9c3ab414150a75bcab03c8abcc3c2a7860b2d4b998afa6e75370213a3b1d45
t=2021-09-16T08:05:58+0000 lvl=info msg="Unindexing transactions"                blocks=492,300 txs=829,312 total=8,504,788 elapsed=33.189s
t=2021-09-16T08:06:06+0000 lvl=info msg="Unindexing transactions"                blocks=558,279 txs=1,072,296 total=8,504,788 elapsed=41.310s
t=2021-09-16T08:06:15+0000 lvl=info msg="Unindexing transactions"                blocks=640,496 txs=1,318,234 total=8,504,788 elapsed=49.369s
t=2021-09-16T08:06:23+0000 lvl=info msg="Unindexing transactions"                blocks=718,087 txs=1,564,413 total=8,504,788 elapsed=57.406s
t=2021-09-16T08:06:31+0000 lvl=info msg="Unindexing transactions"                blocks=775,788 txs=1,781,712 total=8,504,788 elapsed=1m5.421s
t=2021-09-16T08:06:39+0000 lvl=info msg="Unindexing transactions"                blocks=841,740 txs=2,010,347 total=8,504,788 elapsed=1m13.489s
t=2021-09-16T08:06:47+0000 lvl=info msg="Unindexing transactions"                blocks=888,189 txs=2,234,722 total=8,504,788 elapsed=1m21.513s
t=2021-09-16T08:06:55+0000 lvl=info msg="Unindexing transactions"                blocks=923,454 txs=2,458,701 total=8,504,788 elapsed=1m29.584s
t=2021-09-16T08:07:03+0000 lvl=info msg="Unindexing transactions"                blocks=956,998 txs=2,686,879 total=8,504,788 elapsed=1m37.653s
t=2021-09-16T08:07:11+0000 lvl=info msg="Unindexing transactions"                blocks=997,696 txs=2,887,126 total=8,504,788 elapsed=1m45.748s
t=2021-09-16T08:07:19+0000 lvl=info msg="Unindexing transactions"                blocks=1,037,271 txs=3,087,924 total=8,504,788 elapsed=1m53.842s
t=2021-09-16T08:07:27+0000 lvl=info msg="Unindexing transactions"                blocks=1,081,000 txs=3,304,425 total=8,504,788 elapsed=2m1.848s
t=2021-09-16T08:07:35+0000 lvl=info msg="Unindexing transactions"                blocks=1,120,415 txs=3,523,902 total=8,504,788 elapsed=2m9.864s
t=2021-09-16T08:07:40+0000 lvl=info msg="Imported new chain segment"             blocks=1         txs=166       mgas=20.903 elapsed=2m15.208s mgasps=0.155 number=10,854,788 hash=0xd8c82c3e39e63db79fb54c1639d4ca8f438d8b9354028f125c9f4da6d815c267 age=3d15h7m  dirty="9.39 MiB"
t=2021-09-16T08:07:43+0000 lvl=info msg="Unindexing transactions"                blocks=1,151,703 txs=3,738,166 total=8,504,788 elapsed=2m17.938s
t=2021-09-16T08:07:51+0000 lvl=info msg="Unindexing transactions"                blocks=1,181,834 txs=3,961,589 total=8,504,788 elapsed=2m25.968s
t=2021-09-16T08:07:59+0000 lvl=info msg="Unindexing transactions"                blocks=1,212,912 txs=4,185,554 total=8,504,788 elapsed=2m33.992s
t=2021-09-16T08:08:07+0000 lvl=info msg="Unindexing transactions"                blocks=1,242,725 txs=4,402,492 total=8,504,788 elapsed=2m42.019s
t=2021-09-16T08:08:15+0000 lvl=info msg="Unindexing transactions"                blocks=1,277,085 txs=4,617,745 total=8,504,788 elapsed=2m50.099s
t=2021-09-16T08:08:23+0000 lvl=info msg="Unindexing transactions"                blocks=1,309,244 txs=4,833,413 total=8,504,788 elapsed=2m58.104s
t=2021-09-16T08:08:31+0000 lvl=info msg="Unindexing transactions"                blocks=1,348,000 txs=5,054,145 total=8,504,788 elapsed=3m6.126s
t=2021-09-16T08:08:39+0000 lvl=info msg="Unindexing transactions"                blocks=1,373,511 txs=5,294,628 total=8,504,788 elapsed=3m14.178s
t=2021-09-16T08:08:47+0000 lvl=info msg="Unindexing transactions"                blocks=1,407,203 txs=5,514,094 total=8,504,788 elapsed=3m22.223s
t=2021-09-16T08:08:55+0000 lvl=info msg="Unindexing transactions"                blocks=1,433,673 txs=5,732,025 total=8,504,788 elapsed=3m30.233s
t=2021-09-16T08:09:03+0000 lvl=info msg="Unindexing transactions"                blocks=1,463,517 txs=5,946,059 total=8,504,788 elapsed=3m38.236s
t=2021-09-16T08:09:11+0000 lvl=info msg="Unindexing transactions"                blocks=1,491,049 txs=6,191,922 total=8,504,788 elapsed=3m46.290s
t=2021-09-16T08:09:15+0000 lvl=info msg="Persisted trie from memory database"    nodes=0 size="0.00 B" time="1.79µs"  gcnodes=0 gcsize="0.00 B" gctime=0s livenodes=26994 livesize="9.47 MiB"
t=2021-09-16T08:09:15+0000 lvl=info msg="Imported new chain segment"             blocks=1         txs=171       mgas=24.705 elapsed=1m34.880s mgasps=0.260 number=10,854,789 hash=0x94ce0780a265773a5a4819d5aea71b2c09c6740a154938cb3ec77fa07d99b021 age=3d15h9m  dirty="12.00 MiB"
t=2021-09-16T08:09:19+0000 lvl=info msg="Unindexing transactions"                blocks=1,515,450 txs=6,432,669 total=8,504,788 elapsed=3m54.300s
t=2021-09-16T08:09:27+0000 lvl=info msg="Unindexing transactions"                blocks=1,545,000 txs=6,644,121 total=8,504,788 elapsed=4m2.319s
t=2021-09-16T08:09:36+0000 lvl=info msg="Unindexing transactions"                blocks=1,581,603 txs=6,859,027 total=8,504,788 elapsed=4m10.356s
t=2021-09-16T08:09:44+0000 lvl=info msg="Unindexing transactions"                blocks=1,609,521 txs=7,061,285 total=8,504,788 elapsed=4m18.391s
t=2021-09-16T08:09:52+0000 lvl=info msg="Unindexing transactions"                blocks=1,644,915 txs=7,269,327 total=8,504,788 elapsed=4m26.457s
t=2021-09-16T08:09:58+0000 lvl=info msg="Deep froze chain segment"               blocks=2         elapsed=96.454ms  number=10,764,789 hash=0x7230f877f465f796c35f3db507007cc9ec39952701b9a4e700b949defbfe2dc4
t=2021-09-16T08:10:00+0000 lvl=info msg="Unindexing transactions"                blocks=1,673,547 txs=7,475,631 total=8,504,788 elapsed=4m34.499s
t=2021-09-16T08:10:08+0000 lvl=info msg="Unindexing transactions"                blocks=1,701,682 txs=7,674,563 total=8,504,788 elapsed=4m42.509s
t=2021-09-16T08:10:16+0000 lvl=info msg="Unindexing transactions"                blocks=1,732,951 txs=7,870,740 total=8,504,788 elapsed=4m50.551s
t=2021-09-16T08:10:24+0000 lvl=info msg="Unindexing transactions"                blocks=1,766,425 txs=8,074,471 total=8,504,788 elapsed=4m58.634s
t=2021-09-16T08:10:32+0000 lvl=info msg="Unindexing transactions"                blocks=1,800,377 txs=8,271,507 total=8,504,788 elapsed=5m6.702s
t=2021-09-16T08:10:40+0000 lvl=info msg="Unindexing transactions"                blocks=1,845,837 txs=8,491,984 total=8,504,788 elapsed=5m14.739s
t=2021-09-16T08:10:48+0000 lvl=info msg="Unindexing transactions"                blocks=1,887,684 txs=8,694,869 total=8,504,788 elapsed=5m22.775s
t=2021-09-16T08:10:56+0000 lvl=info msg="Unindexing transactions"                blocks=1,925,921 txs=8,911,152 total=8,504,788 elapsed=5m30.775s
t=2021-09-16T08:11:02+0000 lvl=info msg="Imported new chain segment"             blocks=1         txs=220       mgas=32.914 elapsed=1m46.648s mgasps=0.309 number=10,854,790 hash=0x7d55af685e6de95937156795dab8ae1ca49356a539d8528d4ac97ba691dbcdc5 age=3d15h10m dirty="15.30 MiB"
t=2021-09-16T08:11:04+0000 lvl=info msg="Unindexing transactions"                blocks=1,967,519 txs=9,119,983 total=8,504,788 elapsed=5m38.775s
t=2021-09-16T08:11:12+0000 lvl=info msg="Unindexing transactions"                blocks=2,009,575 txs=9,329,358 total=8,504,788 elapsed=5m46.831s
t=2021-09-16T08:11:20+0000 lvl=info msg="Unindexing transactions"                blocks=2,054,756 txs=9,529,634 total=8,504,788 elapsed=5m54.921s
t=2021-09-16T08:11:28+0000 lvl=info msg="Unindexing transactions"                blocks=2,106,586 txs=9,750,809 total=8,504,788 elapsed=6m2.966s
t=2021-09-16T08:11:36+0000 lvl=info msg="Unindexing transactions"                blocks=2,148,958 txs=9,952,430 total=8,504,788 elapsed=6m11.032s
t=2021-09-16T08:11:44+0000 lvl=info msg="Unindexing transactions"                blocks=2,203,879 txs=10,170,912 total=8,504,788 elapsed=6m19.112s
t=2021-09-16T08:11:52+0000 lvl=info msg="Unindexing transactions"                blocks=2,260,184 txs=10,371,037 total=8,504,788 elapsed=6m27.135s
t=2021-09-16T08:12:00+0000 lvl=info msg="Unindexing transactions"                blocks=2,316,484 txs=10,580,951 total=8,504,788 elapsed=6m35.217s
t=2021-09-16T08:12:08+0000 lvl=info msg="Unindexing transactions"                blocks=2,360,287 txs=10,780,580 total=8,504,788 elapsed=6m43.261s
t=2021-09-16T08:12:16+0000 lvl=info msg="Unindexing transactions"                blocks=2,401,443 txs=10,986,143 total=8,504,788 elapsed=6m51.306s
t=2021-09-16T08:12:20+0000 lvl=info msg="Persisted trie from memory database"    nodes=0 size="0.00 B" time="2.242µs" gcnodes=0 gcsize="0.00 B" gctime=0s livenodes=41252 livesize="14.47 MiB"
t=2021-09-16T08:12:20+0000 lvl=info msg="Imported new chain segment"             blocks=1         txs=221        mgas=25.998 elapsed=1m17.751s mgasps=0.334 number=10,854,791 hash=0x3da82fccf1f35df7725b3f5dbb0f2c2797af3bdc0375a49381d9898887ac6a75 age=3d15h12m dirty="18.34 MiB"
t=2021-09-16T08:12:24+0000 lvl=info msg="Unindexing transactions"                blocks=2,450,024 txs=11,200,892 total=8,504,788 elapsed=6m59.307s
t=2021-09-16T08:12:32+0000 lvl=info msg="Unindexing transactions"                blocks=2,504,630 txs=11,421,117 total=8,504,788 elapsed=7m7.309s
t=2021-09-16T08:12:41+0000 lvl=info msg="Unindexing transactions"                blocks=2,540,244 txs=11,633,514 total=8,504,788 elapsed=7m15.326s
t=2021-09-16T08:12:49+0000 lvl=info msg="Unindexing transactions"                blocks=2,577,000 txs=11,842,861 total=8,504,788 elapsed=7m23.502s
t=2021-09-16T08:12:57+0000 lvl=info msg="Unindexing transactions"                blocks=2,614,380 txs=12,045,544 total=8,504,788 elapsed=7m31.595s
t=2021-09-16T08:12:58+0000 lvl=info msg="Deep froze chain segment"               blocks=2         elapsed=121.331ms number=10,764,791 hash=0x920a46b682219ce9f6d71f371ad019ee5aaceb272da604cc78a3d209d64e0965
t=2021-09-16T08:13:05+0000 lvl=info msg="Unindexing transactions"                blocks=2,642,192 txs=12,236,930 total=8,504,788 elapsed=7m39.596s
t=2021-09-16T08:13:13+0000 lvl=info msg="Unindexing transactions"                blocks=2,674,703 txs=12,449,223 total=8,504,788 elapsed=7m47.679s
t=2021-09-16T08:13:21+0000 lvl=info msg="Unindexing transactions"                blocks=2,709,598 txs=12,678,926 total=8,504,788 elapsed=7m55.784s
t=2021-09-16T08:13:29+0000 lvl=info msg="Unindexing transactions"                blocks=2,741,732 txs=12,870,757 total=8,504,788 elapsed=8m3.787s
t=2021-09-16T08:13:37+0000 lvl=info msg="Unindexing transactions"                blocks=2,773,349 txs=13,091,437 total=8,504,788 elapsed=8m11.787s
t=2021-09-16T08:13:45+0000 lvl=info msg="Unindexing transactions"                blocks=2,797,418 txs=13,302,616 total=8,504,788 elapsed=8m19.823s
t=2021-09-16T08:13:53+0000 lvl=info msg="Unindexing transactions"                blocks=2,824,501 txs=13,504,034 total=8,504,788 elapsed=8m27.875s
t=2021-09-16T08:14:01+0000 lvl=info msg="Unindexing transactions"                blocks=2,856,095 txs=13,701,132 total=8,504,788 elapsed=8m35.875s
t=2021-09-16T08:14:08+0000 lvl=info msg="Imported new chain segment"             blocks=1         txs=266        mgas=33.493 elapsed=1m48.778s mgasps=0.308 number=10,854,792 hash=0x7ad788947d80304da014e004595446c89c2e4bbaae89c47f91c4d391c5341499 age=3d15h13m dirty="21.90 MiB"
t=2021-09-16T08:14:09+0000 lvl=info msg="Unindexing transactions"                blocks=2,894,015 txs=13,925,659 total=8,504,788 elapsed=8m43.911s
t=2021-09-16T08:14:17+0000 lvl=info msg="Unindexing transactions"                blocks=2,925,421 txs=14,127,928 total=8,504,788 elapsed=8m51.926s
  
</details>

**Comment by urkishan** [comment]
I am facing the same, as bsc is not syncing.

**Comment by 0fuz** [comment]
> I am facing the same, as bsc is not syncing.

only one temporary solution is: keep zipped snapshot as volume and unzip once needed to other volume. Its ~2hr to unzip instead of 12hr to download snapshot

**Comment by guagualvcha** [comment]
Please refer to https://github.com/binance-chain/bsc/issues/502. Will close this since duplicated issue
