### ISSUE TITLE
Huge NVMe disks are obligatory?

### ISSUE THREAD

**Issue by edgeofthegame** [binance-chain/bsc#425]
Hello, 
node admins and developers.

Right now I am managing two full bsc nodes on 2TB NVMe disks. Both bsc folders are 1.4TB right now. And my 2TB NVMe disks gonna be not large enough in a few months or so.

Is it an OK size, or maybe I'm doing something wrong?
Is there a way to reduce bsc folder size? 

And if this is all expected behavior, and there is nothing we can do with bsc size, 
maybe you could share some information about datacenters with 10TB NVMe disk servers for reasonable price? 

Thank you.

**Comment by psdlt** [comment]
Hi @edgeofthegame 
you can prune your data (https://gist.github.com/yorickdowne/3323759b4cbf2022e191ab058a4276b2):
`geth --datadir /my/data/dir snapshot prune-state`
this should reduce your data dir size about in half.
but... you have to stop your node to do this and prune might take several hours to complete.

**Comment by brian-man** [comment]
My understanding is that pruning requires a sync'd node and I haven't managed a successful sync in a couple weeks. :|

No code changes in the repo in 16 days, so not optimistic I'll ever have a viable node again.

**Comment by 0fuz** [comment]
@brian-man ensure that your geth process don't use 100% of RAM. I were faced with problem when 100% RAM + swap file used and really slow sync. And knownStates keep growth 700mil+. Need reduce RAM limits

**Comment by edgeofthegame** [comment]
Prune worked fine:
**before**
![image](https://user-images.githubusercontent.com/63762555/134956366-af193b17-e1a5-476e-99a1-f3e8fea40490.png)
**after**
![image](https://user-images.githubusercontent.com/63762555/134956402-b795e1a9-33d4-4bd3-b7c3-069f8ef44b14.png)
