### ISSUE TITLE
1 tx in block. How thats possible?

### ISSUE THREAD

**Issue by ctanbern** [binance-chain/bsc#428]
https://bscscan.com/block/11138706
Hello everyone. Im just wonder how that can be possible ? Whole network was down for a all blocktime so they proceed only 1 tx?
Im stilll reread code and can't fine answer.

**Comment by 0fuz** [comment]
Really interesting case. Have you read transactions?
position 0. swap https://bscscan.com/tx/0x6e1327386af0f7fc436f6eeb7ec3b2792065d66aa18943a963d1ce1357c39ea6
with 200 000 gasPrice !!! 9k$ fee

I think its the reason like validator can put into block so many texts (0..700) but it has fees limits to share other fee for next validators

**Comment by guagualvcha** [comment]
@ctanbern for those validators whos performance is not good(failed to validate transaction as much as possible), they need broadcast transactions as fast as possible, so that is why you can see even some empty blocks on mainnet.

**Comment by guagualvcha** [comment]
closing this.
