### ISSUE TITLE
Curious about the PoSA

### ISSUE THREAD

**Issue by freefacefly** [binance-chain/bsc#43]
As far as i can read from the [BSC whitepaper](https://dex-bin-1259603563.file.myqcloud.com/static/Whitepaper_%20Binance%20Smart%20Chain.pdf),

the the block finality time is  > 5s * (1/2 * 21), because we are using clique like algorithm for consensus,

my question is, why not using a variant of PBFT to reach a better finality time?

**Comment by HaoyangLiu** [comment]
`PBFT` is more suitable for alliance chain. BSC assumes that validator might change frequently and validators rewards is counter by the produced blocks quantity. However, in `PBFT`, usually only one validator is in charge of block producing while other validators just vote the blocks. In additon, finality time is not the key point for BSC.
