### ISSUE TITLE
BSC node can't sync

### ISSUE THREAD

**Issue by nav1d** [binance-chain/bsc#433]
#### System information

Geth version: `geth v1.1.2`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Full sync on nvm disks.

#### Actual behaviour
It never sync complete, always a few blocks behind.
my node has 32gb ram + 3T nvm disk.

> eth.syncing
{
  currentBlock: 11332290,
  highestBlock: 11332357,
  knownStates: 326395741,
  pulledStates: 326332549,
  startingBlock: 11330116
}

#### Steps to reproduce the behaviour
./geth --config ./config.toml --datadir ./node  --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by gogopro-dev** [comment]
+1

**Comment by 0fuz** [comment]
@nav1d @gogopro-dev is this issue appears with sync from genesis.json or snapshot?

**Comment by northwestnodes** [comment]
We are having the same issue in Azure. 8 cores, 32GB RAM, Premium SSD disks with 7500 IOPS and 250MB/sec throughput. Metrics show not even half of the capacity is actually being used. So it can't be the (allocated) hardware.

**Comment by gogopro-dev** [comment]
> @nav1d @gogopro-dev is this issue appears with sync from genesis.json or snapshot?

This issue appears with fast or span sync from genesis.json in my case. But now i tested it on bare metal nvme and got synced.

**Comment by 0fuz** [comment]
I haven't success with syncing via genesis.json but always success from snapshot.zip. One more issue is don't pass --cache more than RAM, because geth could start using swap file and really slow down work

**Comment by northwestnodes** [comment]
We found disabling or limiting swap on Linux (`vm.swappiness = 1` or `sudo swapoff -a` for session) did the trick for performance. But, syncing from genesis.json is still an issue. We are trying syncing from the latest snapshot now.

**Comment by DryDragon10** [comment]
I've had the same issue. Could sync before but after I reinstalled the OS no longer able to sync.

**Comment by LyyDandelion** [comment]
same problem

**Comment by Thyoity** [comment]
@0fuz Are you using an EC2 server?

**Comment by KeefeL** [comment]
It is recommended to use the latest snapshot as @overload-ak said, maybe we can forward this discuss to #338

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
