### ISSUE TITLE
Latest Block is always 0

### ISSUE THREAD

**Issue by northwestnodes** [binance-chain/bsc#434]
#### System information

Geth version: 
```
Geth
Version: 1.1.2
Git Commit: c4f931212903b3ee8495c36ac374340aec4ac269
Git Commit Date: 20210825
Architecture: amd64
Go Version: go1.15.14
Operating System: linux
GOPATH=
GOROOT=go
```
OS & Version: Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
Latest block to be equal to "latest header" or "latest receipt"

#### Actual behaviour
Latest block is always 0. Not only is this visible through InfluxDB metrics, but when hooking up a ChainLink node, the CL node also starts complaining about the fact that there's only a 0 block.
![wtfguys](https://user-images.githubusercontent.com/91630022/135541936-9d1b016c-a868-4ccf-879d-b7c074bb0ad7.PNG)

#### Steps to reproduce the behaviour
Run the node. Please see attached screenshot.

When submitting logs: please submit them as text and not screenshots.

**Comment by KeefeL** [comment]
It is so weird, could you follow this https://docs.binance.org/smart-chain/developer/fullnode.html and try again?

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
