### ISSUE TITLE
About build

### ISSUE THREAD

**Issue by leonOyo** [binance-chain/bsc#437]
I use 
make geth
make all
and build out in bsc/build/bin,where is bnbchaind? Is something wrong?

**Comment by leonOyo** [comment]
How can I build a bnbchaind? I use bsc of master branch

**Comment by 0fuz** [comment]
default bnb chain ids are:
main net: 56
testnet: 97. 

You can ensure this by checking .zips ->config.toml there https://github.com/binance-chain/bsc/releases/tag/v1.1.2

Am I get question right?

**Comment by KeefeL** [comment]
It is recommended to use the latest snapshots as @0fuz mentioned, I am going to close this issue, for synchronization issues we can visit #338
