### ISSUE TITLE
Error while decode transaction with Web3

### ISSUE THREAD

**Issue by fonov** [binance-chain/bsc#44]
I tried decode transaction from block but got a error 

```
Number can only safely store up to 53 bits
	at assert ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
	at BN.toNumber ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506
	at Object.hexToNumber ./node_modules/web3-core-helpers/node_modules/web3-utils/lib/utils.js:208
	at Method.outputTransactionFormatter [as outputFormatter] ./node_modules/web3-core-helpers/lib/formatters.js:204
	at Method.formatOutput ./node_modules/web3-core-method/lib/index.js:147
	at sendTxCallback ./node_modules/web3-core-method/lib/index.js:523
	at ./node_modules/web3-core-requestmanager/lib/index.js:293
	at XMLHttpRequest.request.onreadystatechange ./node_modules/web3-providers-http/lib/index.js:98
	at XMLHttpRequestEventTarget.dispatchEvent ./node_modules/xhr2-cookies/xml-http-request-event-target.ts:44
	at XMLHttpRequest._setReadyState ./node_modules/xhr2-cookies/xml-http-request.ts:219
	at XMLHttpRequest._onHttpResponseEnd ./node_modules/xhr2-cookies/xml-http-request.ts:345
	at IncomingMessage.<anonymous> ./node_modules/xhr2-cookies/xml-http-request.ts:311
	at IncomingMessage.emit events.js:326
	at endReadableNT _stream_readable.js:1252
	at processTicksAndRejections internal/process/task_queues.js:80
```

error occur with tx id `0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9`

if look closely on https://bscscan.com/tx/0xe0db32759810271eec05326a4c96fbb42a185139134e16b4581f77456df226a9

we can see that gas equal `9,223,372,036,854,775,807`, so web3 js can't convert this string to number 

Anyone has idea how resolve this problem? 

```
import Web3 from 'web3';

async function main() {
  const web3 = new Web3('https://bsc-dataseed1.binance.org:443');

  const res = await web3.eth.getBlock(1365710);

  await Promise.all(
    res.transactions.map(async (txId) => {
      try {
        const tx = await web3.eth.getTransaction(txId);

        console.log(`decode ${txId}`);
      } catch (error) {
        console.error(`error decode ${txId}`);
      }
    }),
  );
}

main();
```

**Comment by guagualvcha** [comment]
What's the version are you using of web3.js? Upgrade to latest version may works.
As I have tried, it works on latest version:
![image](https://user-images.githubusercontent.com/7310198/100064839-fc0dae00-2e6d-11eb-8d1b-679f1d3dae58.png)

**Comment by fonov** [comment]
i use latest version

```
"web3": "1.3.0",
    "web3-core": "1.3.0",
    "web3-core-helpers": "1.3.0",
    "web3-eth": "1.3.0",
    "web3-eth-contract": "1.3.0",
    "web3-utils": "1.3.0",
```
And i still get a error

<img width="1103" alt="Screenshot 2020-11-24 at 11 30 09" src="https://user-images.githubusercontent.com/17071211/100068309-6a3f7a00-2e48-11eb-95e8-c0ba341c762c.png">

**Comment by fonov** [comment]
but i found a how fixed issue and already created pull request in web3 repo https://github.com/ethereum/web3.js/pull/3789/files

**Comment by sergey-pylypiv** [comment]
Hello everyone ! I have too this problem ! Try to combine versions of web3js, not helped.

**Comment by guagualvcha** [comment]
It is the problem that BSC have system tx like this one: https://bscscan.com/tx/0xc35fed5ba462e2ec9c1131ea80ba30a5b82312ca37c6c75d3b990bc4a86eae96
The gas limit of system tx is `9,223,372,036,854,775,807`, which beyond what the BN lib of node js can handle.

**Comment by fonov** [comment]
Why it close? Problem steel exist

**Comment by BuyOwnEx** [comment]
For those who cannot decode transaction with Web3

Use web3 with version >= 1.9.0

And use optional `hexFormat` param to `getTransaction` and `getBlock` that accepts the value `'hex'`

Example:

`let transactions = await web3.eth.getBlock(block_number, true, 'hex')`
