### ISSUE TITLE
BSC node won't sync more than 1 block every 13 seconds

### ISSUE THREAD

**Issue by northwestnodes** [binance-chain/bsc#440]
#### System information

Geth version:
```
Geth
Version: 1.1.2
Git Commit: c4f931212903b3ee8495c36ac374340aec4ac269
Git Commit Date: 20210825
Architecture: amd64
Go Version: go1.15.14
Operating System: linux
GOPATH=
GOROOT=go
```
OS & Version: Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
That the node catches up to the latest block asap.

#### Actual behaviour
A few days ago we finally got this damn node to sync up. Then slowly but surely, over 48 hours, it slipped away further and further from the mainnet's head. We are now 4,000 blocks behind. We reset the server, increased the maxpeers to 60 and it still won't sync quickly:
```
Oct 05 20:47:11 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:47:11.082] Imported new chain segment               blocks=1   txs=385 mgas=59.357  elapsed=11.700s mgasps=5.073 number=11,510,932 hash=d8d3db..8101c6 age=5h41m48s dirty=277.55MiB
Oct 05 20:47:20 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:47:20.061] Imported new chain segment               blocks=1   txs=284 mgas=39.603  elapsed=8.979s  mgasps=4.410 number=11,510,933 hash=f8714f..0b9e87 age=5h41m54s dirty=281.00MiB
Oct 05 20:47:38 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:47:38.550] Imported new chain segment               blocks=2   txs=863 mgas=116.128 elapsed=18.488s mgasps=6.281 number=11,510,935 hash=83d3f0..129c36 age=5h42m6s  dirty=291.34MiB
Oct 05 20:47:47 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:47:47.463] Imported new chain segment               blocks=1   txs=404 mgas=52.582  elapsed=8.913s  mgasps=5.899 number=11,510,936 hash=f8009b..c576c4 age=5h42m12s dirty=296.31MiB
Oct 05 20:48:00 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:48:00.492] Imported new chain segment               blocks=2   txs=774 mgas=96.199  elapsed=13.028s mgasps=7.384 number=11,510,938 hash=da9fc4..ac3d0f age=5h42m19s dirty=305.84MiB
Oct 05 20:48:13 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:48:13.539] Imported new chain segment               blocks=1   txs=534 mgas=73.360  elapsed=13.047s mgasps=5.623 number=11,510,939 hash=14f545..baf6ee age=5h42m29s dirty=311.92MiB
Oct 05 20:48:26 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:48:26.430] Imported new chain segment               blocks=2   txs=797 mgas=98.233  elapsed=12.891s mgasps=7.620 number=11,510,941 hash=ae71b1..b15101 age=5h42m36s dirty=320.93MiB
Oct 05 20:48:35 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:48:35.426] Imported new chain segment               blocks=1   txs=431 mgas=60.271  elapsed=8.995s  mgasps=6.700 number=11,510,942 hash=632a57..91adfd age=5h42m42s dirty=326.48MiB
Oct 05 20:48:46 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:48:46.375] Imported new chain segment               blocks=2   txs=695 mgas=89.692  elapsed=10.948s mgasps=8.192 number=11,510,944 hash=c71e8c..452d42 age=5h42m47s dirty=334.96MiB
Oct 05 20:48:57 vm-prod-westeu-binance-01 geth[4737]: INFO [10-05|20:48:57.752] Imported new chain segment               blocks=2   txs=786 mgas=97.804  elapsed=11.377s mgasps=8.597 number=11,510,946 hash=6e5f6b..158ac5 age=5h42m52s dirty=343.99MiB
```

### Before you start about NeEd MoRe DiSk IoPs........
.....we have a Premium SSD for both OS and Data in Azure, with 7,500 IOPS and a 250MB/sec DEDICATED throughput. 8 CPU, 32GB RAM running Ubuntu 20.04 x64. The metrics in Azure show that the data disk NEVER goes above 60MB/sec and is steady at 2MB/sec. Nor do the IOPS go above 3,000 of the 7,500.

Our systemd runs the following:
```
/usr/bin/geth --config /bsc/config.toml --datadir <dir> --ethash.dagdir <dir> --cache 24000 --nocompaction --syncmode full --port 30311 --maxpeers 60 --networkid 56
```

Sync worked just fine and fast. Sometimes even 2048 blocks per 13 seconds. Then it caught up, and then started lagging behind. What gives?

#### Steps to reproduce the behaviour
Turn on the node.

When submitting logs: please submit them as text and not screenshots.

**Comment by DryDragon10** [comment]
same issue here. Was fine a few days ago

**Comment by urkishan** [comment]
I am facing the same issue https://github.com/binance-chain/bsc/issues/439

**Comment by 0fuz** [comment]
@northwestnodes 
1. how much size of your node folder? I saw it is 500-600gb, if its more then might be needed prune-state
2. in my practice config.toml maxPeers = 90 will give admin.peers=30
3. don't forget do graceful shutdown
4. You can put higher --cache like 80% of RAM

**Comment by KeefeL** [comment]
Hope what @0fuz mentioned will help you. At the same time, as your RAM is 32GB, I will recommend you to specify cache value to 8000 other than 24000.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
