### ISSUE TITLE
Syncing more than 3 weeks

### ISSUE THREAD

**Issue by schukevich** [binance-chain/bsc#448]
My node configuration
16 cpu x 2.4ghz, 16 ram, 1 TB nvme (samsung 960), ESXI hypervisor and nvme in pci passtrough mode
I started fullnode sync three weeks ago, now i see these log entries
`processed=1,402,938,136 pending=138,445`
It pulles 386-1024 entries every second and about 64-128 blocks behind in sync
Is it normal that i have so much states to sync? Or i am wrong with config.toml or start parameters?

```
> eth.syncing
  currentBlock: 11713183
  highestBlock: 11713246
  knownStates: 1403247487
  pulledStates: 1403198340
  startingBlock: 11709887
```

```
[root@bsc ~]# cat /mnt/storage1/bsc/config/config.toml
[Eth]
SyncMode = "full"
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Node]
IPCPath = "geth.ipc"
NoUSB = true
InsecureUnlockAllowed = false

[Node.P2P]
MaxPeers = 1000
NoDiscovery = false


[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "debug"
FileRoot = ""

```

```
[root@bsc ~]# cat /var/bsc.sh
#!/bin/bash
geth \
        --config /mnt/storage1/bsc/config/config.toml \
        --datadir /mnt/storage1/bsc/mainnet \
        --cache 8196 \
        --maxpeers 10000 \
        --verbosity 6 \
        --log.json
```

**Comment by DryDragon10** [comment]
try snap mode. Lots of people had issues with fast or full mode

**Comment by nlandeker** [comment]
Yes.

**Comment by nlandeker** [comment]
Hi, any news on resolving this issue? Thanks

**Comment by KeefeL** [comment]
Maybe you can upgrade to latest binary and use latest snapshot follow https://docs.binance.org/smart-chain/developer/fullnode.html, and there are some tips you can get from #502

Hope this will help you.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8

**Comment by echoof** [comment]
same problem +1
<img width="274" alt="image" src="https://user-images.githubusercontent.com/54647766/195103560-09ed12e3-2bd1-4bd3-9cb7-e0a6a51c154c.png">
