### ISSUE TITLE
Problem with peers

### ISSUE THREAD

**Issue by sl4mmer** [binance-chain/bsc#45]
Hi, i reproduced steps described at
https://docs.binance.org/smart-chain/developer/fullnode.html
and i have trouble trying to run full sync

`t=2020-10-28T10:55:13+0100 lvl=info msg="Looking for peers"                      peercount=0 tried=110 static=8
t=2020-10-28T10:55:23+0100 lvl=info msg="Looking for peers"                      peercount=1 tried=63  static=8
t=2020-10-28T10:55:33+0100 lvl=info msg="Looking for peers"                      peercount=1 tried=159 static=8
t=2020-10-28T10:55:43+0100 lvl=info msg="Looking for peers"                      peercount=1 tried=90  static=8
t=2020-10-28T10:55:46+0100 lvl=info msg="Updated mining threads"                 threads=48
t=2020-10-28T10:55:46+0100 lvl=info msg="Updated mining threads"                 threads=8
t=2020-10-28T10:55:47+0100 lvl=info msg="Updated mining threads"                 threads=4
t=2020-10-28T10:55:47+0100 lvl=info msg="Updated mining threads"                 threads=2
t=2020-10-28T10:55:47+0100 lvl=info msg="Updated mining threads"                 threads=1`

that is what i get last few days. Any solutions?

**Comment by guagualvcha** [comment]
Would upload the whole log file? 
Maybe just work on a different network, have you executed `geth --datadir node init genesis.json`?
