### ISSUE TITLE
BSC Light client peers -  What is going on?

### ISSUE THREAD

**Issue by DamCzech** [binance-chain/bsc#452]
Have other people noticed a decrease in the number of peers
light customer node? For the last two days I have a max of 5-13, where the norm is 25-36 peers. I noted this on 3 servers in different locations around the world. I tested on all releases 1.0.0 - 1.1.2

I use according needs: 

--light.maxpeers 300 
--ulc.onlyannounce 
--light.nopruning 
--light.nosyncserve

**Comment by patoshii** [comment]
Can someone respond if they got this working or not? 

I'm trying to setup a fresh new BSC light node setup. What get setup commands did you use and what is the connection config to connect to BSC in light mode?

thanks!

**Comment by DamCzech** [comment]
He continues to lose peers. In addition, blocks jump in every 5-10 sec... Unresolved issue in 1.4
Where is dev?!

Run BSC LCN:
--syncmode=light

**Comment by patoshii** [comment]
ok from the looks of it. BSC in light mode is unusable.

Is everyone really running a BSC full node? Isn't that 1TB+ space requirement and the need of a SSD?

**Comment by Crypto2** [comment]
I've never tried light mode but you'd want 2TB + NVMe if possible for a full node. It will need 1.5TB just to download and extract the snapshot. (You get half that back after you delete the snapshot file.)

**Comment by DamCzech** [comment]
Normally, the light node worked very well until version 1.1.2. From 1.1.3 problems began and in fact this form is useless.

**Comment by ttodua** [comment]
any news?

**Comment by KeefeL** [comment]
I will recommend to use small --light.maxpeers, such as 30 not 300. One p2p node's max connected peer is fixed, the larger peers you have connected, means others can't get connected anymore.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
