### ISSUE TITLE
The same codebase (version) and files, sync / subscriptions are slower on better hardware

### ISSUE THREAD

**Issue by adapt7** [binance-chain/bsc#453]
Node 1: Dedicated server, 32GB RAM, XFS file system
Recently created Node 2: Dedicated server, 128GB RAM, XFS system, more CPU cores than Node 1, set higher cache and peers values than Node 1

The Node 2 is a 1:1 files copy of Node 1.

Both servers have the same network speed.

The same operating system.

Most of the time both nodes are connected to similar amount of peers.

After few days I noticed that Node 1 works quicker. The same subscription for pending transactions finds and filters the same transaction quicker on Node 1 (difference ~10-300ms). Also sometimes Node 2 misses some transactions from the pool that are filtered / found in subscription on Node 1.

How is this possible with better hardware?

Factors I can thing about:

1. Node 1 is in different country than Node 2.
2. Node 2 has started just recently and for some reason is not "trusted" by others?
3. Node 2 has bigger cache and higher peers set up.

Is there anything else I'm missing that could explain this? What else I can try to get as much as I can from better hardware?

**Comment by DryDragon10** [comment]
> Node 1: Dedicated server, 32GB RAM, XFS file system Recently created Node 2: Dedicated server, 128GB RAM, XFS system, more CPU cores than Node 1, set higher cache and peers values than Node 1
> 
> The Node 2 is a 1:1 files copy of Node 1.
> 
> Both servers have the same network speed.
> 
> The same operating system.
> 
> Most of the time both nodes are connected to similar amount of peers.
> 
> After few days I noticed that Node 1 works quicker. The same subscription for pending transactions finds and filters the same transaction quicker on Node 1 (difference ~10-300ms). Also sometimes Node 2 misses some transactions from the pool that are filtered / found in subscription on Node 1.
> 
> How is this possible with better hardware?
> 
> Factors I can thing about:
> 
> 1. Node 1 is in different country than Node 2.
> 2. Node 2 has started just recently and for some reason is not "trusted" by others?
> 3. Node 2 has bigger cache and higher peers set up.
> 
> Is there anything else I'm missing that could explain this? What else I can try to get as much as I can from better hardware?

might be the number of peers. I set my peer to 1000 and it seems to be slower than when it was 250

**Comment by KeefeL** [comment]
Is there any difference between the two nodes's storage, the storage performance is quite important. And as you mentioned, the different country may cause the differences.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
