### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by wo4zhuzi** [binance-chain/bsc#46]
Hi, The configuration is 1.03, but the running error is as follows:

```
t=2020-11-10T14:19:28+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=8c391a82c7f6be45 err="retrieved hash chain is invalid"
```

**Comment by guagualvcha** [comment]
We are trying to reproduce this issue.

**Comment by alberentsen** [comment]
I get a similar  running error
Synchronisation failed, dropping peer    peer=74c2d4019efb660a err="retrieved hash chain is invalid: extra-data too long: 97 > 32"

**Comment by heipacker** [comment]
I get a similar running error

t=2020-12-19T13:20:36+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=5c5798865ba89277 err=timeout
t=2020-12-19T13:21:01+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=d58941fd4b983fc4 err=timeout
t=2020-12-19T13:21:30+0800 lvl=warn msg="Synchronisation failed, dropping peer" peer=acfcfb046811caac err="action from bad peer ignored"

**Comment by guagualvcha** [comment]
> I get a similar running error
> Synchronisation failed, dropping peer peer=74c2d4019efb660a err="retrieved hash chain is invalid: extra-data too long: 97 > 32"

This could be `geth --datadir node init genesis.json` not executed. Please do this before start the node.

**Comment by heipacker** [comment]
> > I get a similar running error
> > Synchronisation failed, dropping peer peer=74c2d4019efb660a err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
> 
> This could be `geth --datadir node init genesis.json` not executed. Please do this before start the node.

It should not be that our node still synchronizes the latest block 10 minutes before the problem

**Comment by riccardope** [comment]
> > I get a similar running error
> > Synchronisation failed, dropping peer peer=74c2d4019efb660a err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
> 
> This could be `geth --datadir node init genesis.json` not executed. Please do this before start the node.

This does not work. Could you please work on a solution? Thanks.

**Comment by tebayoso** [comment]
@guagualvcha this is happening consistently for me, in 3 different syncs in a week. Can't get my node to the head of the chain.

**Comment by guagualvcha** [comment]
hi @tebayoso  

> extra-data too long

![image](https://user-images.githubusercontent.com/7310198/109818861-6b195080-7c6e-11eb-93c8-4dc965da9492.png)
Can you double check:
1. you are using bsc geth;
2. you have done the init work.
Since the error log comes from `ethash` consensus engine, while bsc use `parilia` consensus engine.

**Comment by guagualvcha** [comment]
> @guagualvcha this is happening consistently for me, in 3 different syncs in a week. Can't get my node to the head of the chain.

@tebayoso  can you open another issue to give details of your problem?
