### ISSUE TITLE
Fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by fwhappy** [binance-chain/bsc#463]
#### System information

Geth version: 1.1.2
OS & Version: AWS EC2

28432242 fatal error: concurrent map read and map write
28432243
28432244 goroutine 1315367488 [running]:
28432245 runtime.throw(0x16b35f2, 0x21)
28432246         runtime/panic.go:1117 +0x72 fp=0xc0564eb550 sp=0xc0564eb520 pc=0x44f1f2
28432247 runtime.mapaccess2(0x1490a60, 0xc000efe210, 0xc0564eb5e8, 0xc2d65e1080, 0x1ad9b90)
28432248         runtime/map.go:469 +0x255 fp=0xc0564eb590 sp=0xc0564eb550 pc=0x4262d5
28432249 github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc016792000, 0x79afd4283b257435, 0xa4601acd9e1b91fd, 0x53621db625770d47         , 0x70978bdb4cc72fe4, 0x1af1750, 0xc049bb5e60, 0xc4727e4430, 0x0, 0x0, ...)
28432250         github.com/ethereum/go-ethereum/trie/database.go:769 +0x74 fp=0xc0564eb678 sp=0xc0564eb590 pc=0x7c1e34
28432251 github.com/ethereum/go-ethereum/trie.(*Database).commit.func1(0x79afd4283b257435, 0xa4601acd9e1b91fd, 0x53621db625770d47, 0x7097         8bdb4cc72fe4)
28432252         github.com/ethereum/go-ethereum/trie/database.go:776 +0x85 fp=0xc0564eb6e8 sp=0xc0564eb678 pc=0x7dd065
28432253 github.com/ethereum/go-ethereum/trie.forGatherChildren(0x1ad9b90, 0xc2d65e13c8, 0xc0564ebb58)
28432254         github.com/ethereum/go-ethereum/trie/database.go:211 +0x258 fp=0xc0564eb878 sp=0xc0564eb6e8 pc=0x7bce18
28432255 github.com/ethereum/go-ethereum/trie.forGatherChildren(0x1ad9bb8, 0xc06a76c6c0, 0xc0564ebb58)
28432256         github.com/ethereum/go-ethereum/trie/database.go:208 +0xe5 fp=0xc0564eba08 sp=0xc0564eb878 pc=0x7bcca5
28432257 github.com/ethereum/go-ethereum/trie.(*cachedNode).forChilds(0xc4d0500060, 0xc0564ebb58)
28432258         github.com/ethereum/go-ethereum/trie/database.go:196 +0x110 fp=0xc0564ebab8 sp=0xc0564eba08 pc=0x7bcbb0
28432259 github.com/ethereum/go-ethereum/trie.(*Database).commit(0xc016792000, 0x454b13da67f80514, 0x858332558a0c1256, 0x2aed269a5791d930         , 0xe80fc0b2f1e38768, 0x1af1750, 0xc049bb5e60, 0xc4727e4430, 0x0, 0x0, ...)

**Comment by kyrie-yl** [comment]
This is a same issue with go ethereum #22892[#22892](https://github.com/ethereum/go-ethereum/issues/22892).
