### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#482]
Does anyone know what is causing this problem？
![image](https://user-images.githubusercontent.com/65291464/138982399-cbd56058-5096-4f27-be23-8a1cf35acc48.png)

**Comment by KeefeL** [comment]
How can we reproduce this issue?

**Comment by masayil** [comment]
Now the problem does not appear.

**Comment by masayil** [comment]
Querying for blocks which are not present. This behavior can cause this issue
