### ISSUE TITLE
My node always ~100 blocks behind mainnet

### ISSUE THREAD

**Issue by mutobui** [binance-chain/bsc#483]
#### System information

Geth version:  1.1.2
OS & Version: i3. xlarge

I follow this document: https://docs.binance.org/smart-chain/developer/fullnode.html
BSC Testnet node runs fine but mainnet node always ~100 block behind.

<img width="459" alt="geth-attach" src="https://user-images.githubusercontent.com/67900234/138993073-0a129503-ae20-43bc-a4a2-cd0f734183f1.png">

<img width="1649" alt="logs" src="https://user-images.githubusercontent.com/67900234/138993079-d0bb0e34-c980-4f71-a73d-be8b9debf4bf.png">

**Comment by KyloYang888** [comment]
> > > "You can use snapshots for synchronization" - can you please point to an URL showing any kind of instructions how to do that?
> > 
> > 
> > https://github.com/binance-chain/bsc-snapshots
> 
> I have tried to download the snapshot. The snapshot file size is nearly 700GB, and the download speed is always between 50KB/s ~ 500KB/s.

This is the problem of your slow network, you need to upgrade the network.

**Comment by nining** [comment]
> > > > "You can use snapshots for synchronization" - can you please point to an URL showing any kind of instructions how to do that?
> > > 
> > > 
> > > https://github.com/binance-chain/bsc-snapshots
> > 
> > 
> > I have tried to download the snapshot. The snapshot file size is nearly 700GB, and the download speed is always between 50KB/s ~ 500KB/s.
> 
> This is the problem of your slow network, you need to upgrade the network.

I can download any other file using up my full bandwidth 1000Mb/s.  Is there any bandwidth limitation on the snapshot file?

**Comment by KyloYang888** [comment]
Your download speed depends on your network environment, such as the region
or country you are in.

**Comment by mutobui** [comment]
Solve this issue by snap mode!

**Comment by mutobui** [comment]
/usr/local/bin/geth --config /home/ubuntu/work/mainnet/config.toml --datadir /home/ubuntu/work/mainnet/node --syncmode snap --rpc --rpcaddr "127.0.0.1" --rpccorsdomain "*" --rpcport "8545" --rpcapi "db, eth, net, web3, personal" --ws --ws.port "8546" --ws.addr "127.0.0.1" --ws.origins "*" --ws.api "web3, eth" --cache 72000 --maxpeers=100 --rpc.allow-unprotected-txs --txlookuplimit 0 --rpcvhosts=*

**Comment by DeepBorys** [comment]
I have tried the snap mode, and the state heal takes forever.

t=2021-11-01T11:17:04+0100 lvl=info msg="State heal in progress"                 accounts=3,139,108@177.14MiB slots=11,013,704@820.90MiB  codes=1458@11.57MiB   nodes=52,192,295@13.68GiB  pending=13770

Any idea how long it should take?

**Comment by nining** [comment]
> I have tried the snap mode, and the state heal takes forever.
> 
> t=2021-11-01T11:17:04+0100 lvl=info msg="State heal in progress" accounts=3,139,[108@177.14MiB](mailto:108@177.14MiB) slots=11,013,[704@820.90MiB](mailto:704@820.90MiB) codes=[1458@11.57MiB](mailto:1458@11.57MiB) nodes=52,192,[295@13.68GiB](mailto:295@13.68GiB) pending=13770
> 
> Any idea how long it should take?

i have 2 nodes: 1 for snap and 1 for fast, and they both are in syncing forever （over 1 month).
> eth.syncing
{
  currentBlock: 12278213,
  highestBlock: 12278325,
  knownStates: 381745959,
  pulledStates: 381626029,
  startingBlock: 12269987
}

**Comment by echoof** [comment]
same problem +1
<img width="274" alt="image" src="https://user-images.githubusercontent.com/54647766/195102519-bc3797dd-aa1f-4326-ae7b-eab03a6c263d.png">
