### ISSUE TITLE
Block sync got interrupted 20s when "Persisted trie from memory database" appears every time

### ISSUE THREAD

**Issue by jhaigcg** [binance-chain/bsc#484]
#### System information

Geth version: `geth version`: 1.1.3
OS & Version: Windows/Linux/OSX: Linux
Commit hash : (if `develop`)

#### Expected behaviour
elapsed time is less than 3s

#### Actual behaviour
elapsed time is more than 20s

#### Log
t=2021-10-27T05:04:36+0000 lvl=info msg="Imported new chain segment"             blocks=1    txs=230     mgas=32.544  elapsed=849.707ms   mgasps=38.301  number=12,126,657 hash=0x8f26cb47a4dc85fcde37e72d3b3ada2670429e3b38b5225c2b5cfaa84afa092b dirty="1.19 GiB"
t=2021-10-27T05:04:36+0000 lvl=info msg="Unindexed transactions"                 blocks=1    txs=260     tail=9,776,658 elapsed=2.984ms
t=2021-10-27T05:04:40+0000 lvl=info msg="Imported new chain segment"             blocks=1    txs=322     mgas=43.774  elapsed=2.481s      mgasps=17.640  number=12,126,658 hash=0xc4f9a2c640be975488adcbb5c2597b8afa10041940b97b093e100c250acd8a85 dirty="1.19 GiB"
t=2021-10-27T05:04:40+0000 lvl=info msg="Unindexed transactions"                 blocks=1    txs=180     tail=9,776,659 elapsed=8.612ms
t=2021-10-27T05:04:44+0000 lvl=info msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0    itemSize="104.77 KiB" throttle=626
t=2021-10-27T05:04:49+0000 lvl=info msg="Deep froze chain segment"               blocks=17   elapsed=58.442ms    number=12,036,658 hash=0x4895c0f4e775ebb2b67c4927383fd34e9aa0e9e6024809db91fde7bb161cab32
t=2021-10-27T05:04:56+0000 lvl=eror msg="Snapshot extension registration failed" peer=35ba3061 err="peer connected on snap without compatible eth support"
t=2021-10-27T05:05:03+0000 lvl=info msg="Persisted trie from memory database"    nodes=1,561,884 size="434.33 MiB" time=20.892181555s gcnodes=3,712,915 gcsize="1.40 GiB"   gctime=17.488942858s livenodes=1,428,273 livesize="492.46 MiB"
t=2021-10-27T05:05:03+0000 lvl=info msg="Imported new chain segment"             blocks=1    txs=293     mgas=49.818  elapsed=21.971s     mgasps=2.267   number=12,126,659 hash=0x7c0ee37c3e219ac7e11037d3f5d08242c190c07093ae56444dfc2159725cbac9 dirty="1.19 GiB"
t=2021-10-27T05:05:03+0000 lvl=info msg="Unindexed transactions"                 blocks=1    txs=225     tail=9,776,660 elapsed=6.887ms
t=2021-10-27T05:05:03+0000 lvl=info msg="do light process success at block"      num=12,126,660
t=2021-10-27T05:05:03+0000 lvl=info msg="Imported new chain segment"             blocks=1    txs=340     mgas=40.392  elapsed=628.021ms   mgasps=64.316  number=12,126,660 hash=0xfba62d013bccdf2156fe2ed948c118865db2ba9027ca58f9731c28f0f1e4af33 dirty="641.61 MiB"
t=2021-10-27T05:05:03+0000 lvl=info msg="Unindexed transactions"                 blocks=1    txs=224     tail=9,776,661 elapsed=3.153ms
t=2021-10-27T05:05:04+0000 lvl=eror msg="Snapshot extension registration failed" peer=3af25a30 err="peer connected on snap without compatible eth support"
t=2021-10-27T05:05:05+0000 lvl=info msg="do light process success at block"      num=12,126,662
t=2021-10-27T05:05:06+0000 lvl=info msg="Imported new chain segment"             blocks=2    txs=1465    mgas=110.271 elapsed=2.349s      mgasps=46.935  number=12,126,662 hash=0x4e05ddd57877484441af89e741aa34411df73445ad037c619b01b8b85a531887 dirty="651.09 MiB"  ignored=2
t=2021-10-27T05:05:06+0000 lvl=info msg="Unindexed transactions"                 blocks=2    txs=512     tail=9,776,663 elapsed=5.348ms

#### Steps to reproduce the behaviour
Continue to watch the bsc.log. Everytime "Persisted trie from memory database" apears, the elapsed time is over 20s.

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by KeefeL** [comment]
It is may caused by pool storage performance, could you share your hardware parameters?

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8

**Comment by etan-status** [comment]
Same problem repeatedly observed on a Rock 5B running Rocketpool.

Every couple days, there is `Persisted trie from memory database` from Geth, and after that comes a crazy lagspike >30s spanning several slots.

⚠️ During this lagspike, attached beacon node validator duties cannot be reliably performed, as the beacon node relies on EL (Geth) to determine whether a block is valid.

Note that the spec defines an 8s timeout to both `engine_newPayload` and `engine_forkchoiceUpdated`: https://github.com/ethereum/execution-apis/blob/main/src/engine/shanghai.md#engine_newpayloadv2

It would be great if Geth would reply with `SYNCING / ACCEPTED` in case the timeout is about to be reached, instead of replying with nothing. This way, the BN knows what's going on instead of degrading the EL connection.

Even better would be if Geth could still process `engine_newPayload` and `engine_forkchoiceUpdated` messages during this persist operation. As in, process them far enough to issue a final validity verdict. Or, obviously fixing the lag spike altogether :-)

```
rocketpool_eth1        | DEBUG[08-23|03:24:58.578] Served eth_syncing                       conn=172.18.0.3:45478 reqid=78090  duration="92.747µs"
rocketpool_eth1        | DEBUG[08-23|03:24:58.580] Served eth_getBlockByNumber              conn=172.18.0.3:45478 reqid=78091  duration="313.533µs"
rocketpool_eth1        | DEBUG[08-23|03:24:59.406] Served eth_getBlockByNumber              conn=172.18.0.5:35040 reqid=142469 duration="760.936µs"
rocketpool_eth1        | INFO [08-23|03:25:00.792] Persisted trie from memory database      nodes=14,979,155 size=3.65GiB time=2m39.181582629s gcnodes=69,672,895 gcsize=26.10GiB gctime=10m2.499724637s livenodes=422,719 livesize=152.62MiB
rocketpool_eth1        | INFO [08-23|03:25:00.792] Imported new potential chain segment     number=17,974,704 hash=708dda..a6a0fe blocks=1 txs=340 mgas=29.650 elapsed=35.021s      mgasps=0.847   dirty=194.91MiB
rocketpool_eth1        | DEBUG[08-23|03:25:00.792] Served engine_newPayloadV2               conn=172.18.0.5:34896 reqid=142461 duration=35.03378824s
rocketpool_eth1        | INFO [08-23|03:25:00.822] Chain head was updated                   number=17,974,704 hash=708dda..a6a0fe root=51c8e9..e06d7e elapsed=29.994708ms
rocketpool_eth1        | DEBUG[08-23|03:25:00.823] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:34914 reqid=142463 duration=26.49394218s
rocketpool_eth1        | WARN [08-23|03:25:00.824] Forkchoice requested unknown head        hash=a90265..533878
rocketpool_eth1        | DEBUG[08-23|03:25:00.824] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:35000 reqid=142467 duration=10.012106712s
rocketpool_eth1        | INFO [08-23|03:25:01.035] Imported new potential chain segment     number=17,974,705 hash=a90265..533878 blocks=1 txs=134 mgas=13.443 elapsed=211.658ms    mgasps=63.514  dirty=195.87MiB
rocketpool_eth1        | DEBUG[08-23|03:25:01.035] Served engine_newPayloadV2               conn=172.18.0.5:34954 reqid=142464 duration=18.604207122s
rocketpool_eth1        | INFO [08-23|03:25:01.317] Imported new potential chain segment     number=17,974,706 hash=22b056..a2c717 blocks=1 txs=128 mgas=12.818 elapsed=271.097ms    mgasps=47.284  dirty=196.85MiB
rocketpool_eth1        | DEBUG[08-23|03:25:01.317] Served engine_newPayloadV2               conn=172.18.0.5:35024 reqid=142468 duration=2.474562299s
rocketpool_eth1        | INFO [08-23|03:25:01.891] Extend chain                             add=2 number=17,974,706 hash=22b056..a2c717
rocketpool_eth1        | INFO [08-23|03:25:01.922] Chain head was updated                   number=17,974,706 hash=22b056..a2c717 root=58a9a0..842221 elapsed=31.173883ms
rocketpool_eth1        | DEBUG[08-23|03:25:01.923] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:35046 reqid=142470 duration=34.686905ms
rocketpool_eth1        | INFO [08-23|03:25:02.261] Imported new potential chain segment     number=17,974,707 hash=4a5745..f78aea blocks=1 txs=109 mgas=11.774 elapsed=143.834ms    mgasps=81.861  dirty=197.63MiB
rocketpool_eth1        | DEBUG[08-23|03:25:02.261] Served engine_newPayloadV2               conn=172.18.0.5:35048 reqid=142471 duration=154.582618ms
rocketpool_eth1        | INFO [08-23|03:25:02.885] Chain head was updated                   number=17,974,707 hash=4a5745..f78aea root=9f7e75..e871cf elapsed=14.687322ms
rocketpool_eth1        | DEBUG[08-23|03:25:02.885] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:35052 reqid=142472 duration=18.510668ms
```

```
rocketpool_eth1        | DEBUG[08-26|20:04:09.947] Served eth_call                          conn=172.18.0.3:56666 reqid=131651 duration="638.148µs"
rocketpool_eth1        | DEBUG[08-26|20:04:14.648] Served eth_getBlockByNumber              conn=172.18.0.5:46502 reqid=34950  duration="793.31µs"
rocketpool_eth1        | DEBUG[08-26|20:04:16.949] Served engine_exchangeTransitionConfigurationV1 conn=172.18.0.5:46510 reqid=34951  duration="185.494µs"
rocketpool_eth1        | DEBUG[08-26|20:04:19.948] Served eth_getBlockByNumber              conn=172.18.0.3:56666 reqid=131652 duration="539.86µs"
rocketpool_eth1        | INFO [08-26|20:04:22.343] Persisted trie from memory database      nodes=15,522,470 size=3.77GiB time=2m41.777937169s gcnodes=73,094,369 gcsize=27.43GiB gctime=10m44.159144046s livenodes=437,477 livesize=158.12MiB
rocketpool_eth1        | INFO [08-26|20:04:22.343] Imported new potential chain segment     number=18,001,105 hash=5c33e5..2b8433 blocks=1 txs=121 mgas=15.993 elapsed=32.698s      mgasps=0.489   dirty=201.88MiB
rocketpool_eth1        | DEBUG[08-26|20:04:22.344] Served engine_newPayloadV2               conn=172.18.0.5:46316 reqid=34945  duration=32.720688896s
rocketpool_eth1        | INFO [08-26|20:04:22.360] Chain head was updated                   number=18,001,105 hash=5c33e5..2b8433 root=9a9eb3..d29892 elapsed=16.840341ms
rocketpool_eth1        | DEBUG[08-26|20:04:22.361] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:46374 reqid=34946  duration=24.281695782s
rocketpool_eth1        | WARN [08-26|20:04:22.362] Forkchoice requested unknown head        hash=73fd7c..2ba967
rocketpool_eth1        | DEBUG[08-26|20:04:22.362] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:46500 reqid=34949  duration=7.739647994s
rocketpool_eth1        | INFO [08-26|20:04:22.643] Imported new potential chain segment     number=18,001,106 hash=73fd7c..2ba967 blocks=1 txs=154 mgas=22.393 elapsed=282.763ms    mgasps=79.195  dirty=203.69MiB
rocketpool_eth1        | DEBUG[08-26|20:04:22.644] Served engine_newPayloadV2               conn=172.18.0.5:46424 reqid=34948  duration=16.461765452s
rocketpool_eth1        | INFO [08-26|20:04:22.802] Imported new potential chain segment     number=18,001,107 hash=19a72c..6ceeac blocks=1 txs=113 mgas=9.892  elapsed=155.892ms    mgasps=63.457  dirty=204.38MiB
rocketpool_eth1        | DEBUG[08-26|20:04:22.803] Served engine_newPayloadV2               conn=172.18.0.5:46520 reqid=34952  duration=366.493227ms
rocketpool_eth1        | INFO [08-26|20:04:23.270] Extend chain                             add=2 number=18,001,107 hash=19a72c..6ceeac
rocketpool_eth1        | INFO [08-26|20:04:23.283] Chain head was updated                   number=18,001,107 hash=19a72c..6ceeac root=af5147..21c9b1 elapsed=13.26957ms
rocketpool_eth1        | DEBUG[08-26|20:04:23.283] Served engine_forkchoiceUpdatedV2        conn=172.18.0.5:46532 reqid=34953  duration=16.74526ms
```

**Comment by etan-status** [comment]
Ah, just realized this is the BSC fork. But, the issue doesn't seem to be BSC specific, at least.

**Comment by etan-status** [comment]
Reported upstream: https://github.com/ethereum/go-ethereum/issues/28015
