### ISSUE TITLE
v1.1.3 nodes lag behind the main network after reboot

### ISSUE THREAD

**Issue by KyloYang888** [binance-chain/bsc#488]
**Operating Environment**
Geth version: 1.1.2/1.1.3
OS & Version: c5a.4xlarge
mem: 32G
16 cores

**Start command**
sudo nohup geth --config=./config.toml --datadir=/data --cache=18000 --rpc.allow-unprotected-txs --ws --txlookuplimit=0 --diffsync --persistdiff  >> nohup.out &

**Current operating status**

> eth.syncing
{
  currentBlock: 12156690,
  highestBlock: 12157013,
  knownStates: 297473485,
  pulledStates: 297473485,
  startingBlock: 12153507
}

> eth.syncing.highestBlock - eth.syncing.currentBlock
322

$ top
![image](https://user-images.githubusercontent.com/88371425/139204792-0495b579-14e3-40be-a06d-9ded01fe758b.png)
    

$ sudo iostat
![image](https://user-images.githubusercontent.com/88371425/139204617-c661550a-cf9d-49e0-a74b-274987d80360.png)

**My question**
The node has not been able to keep up with the main network.What else can I do to make a difference? I hope to get a reply from you. Thank you very much~

**Comment by KyloYang888** [comment]
Use the following configuration to solve this problem:
c5a.8xlarge, 
32vCP, 
64GiB ram,
8K iops

**Comment by Undead8** [comment]
I will try a c5a.8xlarge and compare with another m5.4xlarge and see if it makes a difference. What's your maxpeers setting?
