### ISSUE TITLE
diff layers too new from current??

### ISSUE THREAD

**Issue by arayalways** [binance-chain/bsc#490]
#### System information

Geth version: `v1.1.3`
OS & Version: Linux ubuntu 18
Commit hash : (if `develop`)

#### Expected behaviour
sync normal

#### Actual behaviour
Lag behind more than 1 hour, and then get error message "diff layers too new from current". The whole node hang.

#### Steps to reproduce the behaviour
geth --cache 8192 --rpc.allow-unprotected-txs --config ./config.toml --datadir ./node --metrics --pprof --syncmode snap --snapshot=false --diffsync

**Comment by guagualvcha** [comment]
The node is not been gracefully shutdown, it is a bug in latest release, the dev is trying to fix it.

**Comment by voron** [comment]
>The node is not been gracefully shutdown

WIll graceful shutdown prevent this issue?

> it is a bug in latest release, the dev is trying to fix it.

Is it fixed in the latest  1.1.4 as of today ?

**Comment by KeefeL** [comment]
> 

I think so, it is fixed by #509
