### ISSUE TITLE
NEED HELP! NEED HELP! NEED HELP! NEED HELP! NEED HELP!

### ISSUE THREAD

**Issue by urkishan** [binance-chain/bsc#494]
I've started 3 more nodes to sync from last 1 week and still nothing, it still not fully synced. At least give us an update there are other people who are also facing the same. At least let me know what should I have to do. I've increased CPU, IOPS, RAM anything I've found on the internet but didn't work.

https://github.com/binance-chain/bsc/issues/439

**Comment by dklibz** [comment]
Facing the same issue. Whenever I receive 1 peer, it resets back to 0 in a sec. What's going on?

**Comment by de-ltd** [comment]
I have a node synced a few months ago and it took 12 hours to sync fully from scratch, that node is still running. 5 days ago i started syncing a new node on the SAME hardware and it just will not sync. I think currently it isn't possible to sync for some reason from scratch.

**Comment by psdlt** [comment]
I have just started a new node a couple of days ago and it synced up from scratch in about 16 hours.
```
Intel E-2288G
128GB RAM
2x2TB NVMe (RAID 0)
Debian 11
```
standard `config.toml` except for slightly increased peer count.

**Comment by de-ltd** [comment]
Did you use a snapshot ?

**Comment by psdlt** [comment]
@de-ltd no, cold/empty start.

**Comment by KeefeL** [comment]
Maybe you can use the latest binary and snapshot try again, you can visit #338 for detailed suggestions.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
