### ISSUE TITLE
BSC WS Light client node.

### ISSUE THREAD

**Issue by DamCzech** [binance-chain/bsc#496]
Hi,

How to run WebSocket correctly in the case of light client node?

RUN:
> geth --config ./config.toml --datadir ./node --ws --ws.rpcprefix /ws --metrics --syncmode=light 

LOG
> "WebSocket enable" url=ws://127.0.0.1:8546/ws
> "Block synch... started"

Everything seems to be correct. When I paste a link to .cfg APPS, it returns a messag:
> dial tcp 127.0.0.1:8546: connect: connection refused

CFG:
> WS_RPC:ws://127.0.0.1:8546/ws 
or 
> WS_RPC:wss://127.0.0.1:8546/ws 

For example, moralis.io works properly.

**Comment by DamCzech** [comment]
UP

**Comment by algobotishere** [comment]
> UP

Did u figured it out maybe?

**Comment by DamCzech** [comment]
No. It starts, but the application returns no connection.

**Comment by kyrie-yl** [comment]
> Hi,
> 
> How to run WebSocket correctly in the case of light client node?
> 
> RUN:
> 
> > geth --config ./config.toml --datadir ./node --ws --ws.rpcprefix /ws --metrics --syncmode=light
> 
> LOG
> 
> > "WebSocket enable" url=ws://127.0.0.1:8546/ws
> > "Block synch... started"
> 
> Everything seems to be correct. When I paste a link to .cfg APPS, it returns a messag:
> 
> > dial tcp 127.0.0.1:8546: connect: connection refused
> 
> CFG:
> 
> > WS_RPC:ws://127.0.0.1:8546/ws
> > or
> > WS_RPC:wss://127.0.0.1:8546/ws
> 
> For example, moralis.io works properly.

what's the dial command in your 'dial tcp 127.0.0.1:8546' command line? I can curl this websocket port.

**Comment by kyrie-yl** [comment]
Please check your config file to make sure your websocket is running on port 8546, and then dial url ws://127.0.0.1:8546/ws. I have run it on my server, it works.

**Comment by DamCzech** [comment]
START:
`geth --config ./config.toml --datadir ./node --ws --ws.rpcprefix /ws --metrics --syncmode=light`

**Comment by DamCzech** [comment]
> Sprawdź plik konfiguracyjny, aby upewnić się, że Twój websocket działa na porcie 8546, a następnie wybierz adres URL ws://127.0.0.1:8546/ws. Uruchomiłem go na moim serwerze, działa. Poniżej znajduje się mój kod i wynik testu: `c, _:=ethclient.Dial("ws://localhost:8546")`
> 
> ```
> ch := make(chan *types.Header, 16)
> sub, err := c.SubscribeNewHead(context.Background(), ch)
> if err != nil {
> 	fmt.Printf("Failed to subscribe to head events: %v\n", err)
> 	panic(err)
> }
> defer sub.Unsubscribe()
> for h := range ch {
> 	hstr, err := json.Marshal(h)
> 	if err != nil {
> 		fmt.Printf("failed to marshal head %s, err: %v\n", h.Root, err)
> 	}
> 	fmt.Printf("%s\n", hstr)
> }
> ```
> 
> ![obraz](https://user-images.githubusercontent.com/83150977/147460746-d0f5a70a-ee14-4166-b789-c41497d204b1.png)

START:
`geth --config ./config.toml --datadir ./node --ws  --metrics --syncmode=light`

CONFIG:
`WSPort = 8546, WSModules =["net","web3","ETH"]`

RETURN:
`2021/12/27 xx:xx:xx dial tcp 127.0.0.1:8546: connect: connection refused`

I have no idea how to fix it...

**Comment by kyrie-yl** [comment]
> > Sprawdź plik konfiguracyjny, aby upewnić się, że Twój websocket działa na porcie 8546, a następnie wybierz adres URL ws://127.0.0.1:8546/ws. Uruchomiłem go na moim serwerze, działa. Poniżej znajduje się mój kod i wynik testu: `c, _:=ethclient.Dial("ws://localhost:8546")`
> > ```
> > ch := make(chan *types.Header, 16)
> > sub, err := c.SubscribeNewHead(context.Background(), ch)
> > if err != nil {
> > 	fmt.Printf("Failed to subscribe to head events: %v\n", err)
> > 	panic(err)
> > }
> > defer sub.Unsubscribe()
> > for h := range ch {
> > 	hstr, err := json.Marshal(h)
> > 	if err != nil {
> > 		fmt.Printf("failed to marshal head %s, err: %v\n", h.Root, err)
> > 	}
> > 	fmt.Printf("%s\n", hstr)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![obraz](https://user-images.githubusercontent.com/83150977/147460746-d0f5a70a-ee14-4166-b789-c41497d204b1.png)
> 
> START: `geth --config ./config.toml --datadir ./node --ws --metrics --syncmode=light`
> 
> CONFIG: `WSPort = 8546, WSModules =["net","web3","ETH"]`
> 
> RETURN: `2021/12/27 xx:xx:xx dial tcp 127.0.0.1:8546: connect: connection refused`
> 
> `ws://localhost:8546`
> 
> I have no idea how to fix it...

I followed your steps and tried again, and it didn't have errors. I checked the config, the only difference is my config is :
WSPort = 8546
WSModules = ["net", "web3", "eth"].
So, you can change the ETH to eth in WSModules config item.

![image](https://user-images.githubusercontent.com/83150977/147624074-c13b7fe2-958f-4153-b0dc-c87906e71790.png)

After that, if it still don't work, my advice is：
first : make sure you are using the latest bsc code.
second: make sure your wbsocket is running at localhost:8546 port.
![image](https://user-images.githubusercontent.com/83150977/147624293-3f512074-0d44-4442-a8e4-a6914cb71f8d.png)
