### ISSUE TITLE
BSC CPU utilization

### ISSUE THREAD

**Issue by AliakseiMalyshau** [binance-chain/bsc#497]
Hello team! Hope you're doing great! Sorry for bothering in GitHub - have a question about CPU high percentage.

I configured BSC full node went through this guide - https://docs.binance.org/smart-chain/developer/fullnode.html.

Node configured in GCP (c2-standard-8 type), additional NVMe SSD disk (2TB).

I decided configure node via Docker container (ethereum/client-go image, bind volume with chain data).

After configuration I see that my CPU each 2 - 3 hours is over 70%. It's normal behaviour for full node or not? (pinned screen below)

Also I turned on `debug` level info for more details but didn't see any strange error, just "some_node can't join to chain", etc.

![image](https://user-images.githubusercontent.com/91066845/139584517-baae0f8f-6256-4347-8437-6c8e03244e27.png)

Thanks for your help!

**Comment by KeefeL** [comment]
It is normal now, the node will do compact sometimes, the cpu utilization will be high sometimes.

**Comment by AliakseiMalyshau** [comment]
@KeefeL hello! We could close this card cause we destroyed our node.
