### ISSUE TITLE
How to subscribe to Internal Txns

### ISSUE THREAD

**Issue by KyloYang888** [binance-chain/bsc#498]
Hi partner, how to subscribe and parse Internal Txns when getting transaction data from bsc？thanks

**Comment by KyloYang888** [comment]
![image](https://user-images.githubusercontent.com/88371425/139624238-b6294343-c160-4362-94bd-4dd08b72e580.png)

**Comment by guagualvcha** [comment]
You have to use trace API of geth, it will print every details of the transaction execution, include the internal txs.

**Comment by KyloYang888** [comment]
Thanks! I have solved this problem. The solution is https://geth.ethereum.org/docs/dapp/tracing

To start the node use the parameter --syncmode=full --gcmode=archive. 

Here is an example of the request

![image](https://user-images.githubusercontent.com/88371425/140022667-5d8e803e-a354-426b-b82f-7333ddf79071.png)

**Comment by KyloYang888** [comment]
In Config.toml you also need to add support for debug.

![image](https://user-images.githubusercontent.com/88371425/140023351-e494d35a-0b70-40f8-9edb-a6a60b1d27bc.png)
