### ISSUE TITLE
Node lag Synchronization

### ISSUE THREAD

**Issue by acswap** [binance-chain/bsc#500]
#### System information

Geth version: `v1.1.3`
OS & Version: CentOS 7
Commit hash :  b6035c1afaf03bbffbde5c83cc57b7e57325a7a1

#### Expected behaviour
Complete synchronization with the master node

#### Actual behaviour
Node synchronization is always ten or twenty blocks behind

#### Steps to reproduce the behaviour
This has been the case since v1.1.3

t=2021-11-01T14:48:44+0800 lvl=info msg="Imported new chain segment"             blocks=2  txs=401  mgas=81.051  elapsed=9.734s      mgasps=8.326   number=12,270,123 hash=0xf599ba079c455c1ef96e85e7982307349e7d584c1759a86817640a19de53d601 age=2m59s    dirty="618.28 MiB"
t=2021-11-01T14:48:56+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=1146 mgas=170.626 elapsed=11.274s     mgasps=15.134  number=12,270,126 hash=0xfe755e7f725be1c47e070cb7423b9a3ba51e897d4caa00ecaa65241f20426d76 age=3m       dirty="630.68 MiB"
t=2021-11-01T14:49:04+0800 lvl=info msg="Imported new chain segment"             blocks=2  txs=602  mgas=111.222 elapsed=8.555s      mgasps=12.999  number=12,270,128 hash=0x52ba2307fcc846a87b90b257125d61bda1701a6acd517d42e3ec4eb396123039 age=3m2s     dirty="638.25 MiB"
t=2021-11-01T14:49:17+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=1110 mgas=193.631 elapsed=12.880s     mgasps=15.032  number=12,270,131 hash=0x26fd5f7bde2d4c2d5d0858da1d513b84a73aca182270bee7d7456a9f6bfe5fd4 age=3m       dirty="651.50 MiB"
t=2021-11-01T14:49:30+0800 lvl=info msg="Imported new chain segment"             blocks=2  txs=1060 mgas=169.708 elapsed=12.509s     mgasps=13.566  number=12,270,133 hash=0xbdde377677ca4f0d70372def93399069403f10e7befb67a43ff00ac9edd9cf6a age=3m6s     dirty="663.73 MiB"
t=2021-11-01T14:49:41+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=722  mgas=129.100 elapsed=11.221s     mgasps=11.505  number=12,270,136 hash=0xf21ecb00e5b51e68223df24f610d7e8fe0ca98412dc3ba1f40527633b6ccc784 age=3m8s     dirty="670.88 MiB"
t=2021-11-01T14:49:53+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=776  mgas=154.559 elapsed=11.799s     mgasps=13.098  number=12,270,139 hash=0x1bd6155ef9b7ae0b33e0455730beced14d5ddfb580a7139045a230750e151df2 age=3m11s    dirty="680.14 MiB"
t=2021-11-01T14:50:01+0800 lvl=info msg="Imported new chain segment"             blocks=2  txs=726  mgas=137.006 elapsed=8.872s      mgasps=15.442  number=12,270,141 hash=0x8b255273711d63cf776f87af9f2375ef8f58512e761c11c671c7e75e47279792 age=3m6s     dirty="689.13 MiB"
t=2021-11-01T14:50:11+0800 lvl=info msg="Imported new chain segment"             blocks=2  txs=1023 mgas=167.613 elapsed=9.519s      mgasps=17.607  number=12,270,143 hash=0xef0d4cabf9683a8b327dfcdc0b25c78260869831af0b9c5aa467778cb401bbd7 age=3m10s    dirty="700.20 MiB"
t=2021-11-01T14:50:23+0800 lvl=info msg="Imported new chain segment"             blocks=4  txs=1058 mgas=166.811 elapsed=11.687s     mgasps=14.272  number=12,270,147 hash=0x5988ff8ebba27492929d9015e4abd7efd2e189b57bb0f00988de7e7e48d179d2 age=3m9s     dirty="646.63 MiB"
t=2021-11-01T14:50:28+0800 lvl=info msg="Imported new chain segment"             blocks=2  txs=688  mgas=99.010  elapsed=5.120s      mgasps=19.334  number=12,270,149 hash=0xe8b86ee9bc1c916d1c4e34dc22e4e185a4b1d09fd80cc009f0e64f1ee3da0743 age=3m7s     dirty="654.97 MiB"
t=2021-11-01T14:50:55+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=969  mgas=179.191 elapsed=9.894s      mgasps=18.110  number=12,270,152 hash=0x03d4f443af3dad465cc0c2b7b1f5055bbd3780a78d977017e0ef3eae5804eaf0 age=3m25s    dirty="668.04 MiB"
t=2021-11-01T14:51:04+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=754  mgas=157.363 elapsed=8.821s      mgasps=17.839  number=12,270,155 hash=0x27a70216870d3f4a8fce377eb11e072fbf55089ff6b6b273165aba6db225bdb6 age=3m25s    dirty="678.91 MiB"
t=2021-11-01T14:51:14+0800 lvl=info msg="Imported new chain segment"             blocks=3  txs=963  mgas=181.809 elapsed=10.328s     mgasps=17.603  number=12,270,158 hash=0xfc36ac4d3eed4dec232413b4a5da80ea13c23bc06588059aba1ac7f4173b1eb1 age=3m24s    dirty="690.22 MiB"
t=2021-11-01T14:51:17+0800 lvl=info msg="Imported new chain segment"             blocks=1  txs=264  mgas=44.008  elapsed=2.452s      mgasps=17.948  number=12,270,159 hash=0xf49a77a3d1f775f59fa769c0509bf96efd1f5fa054b6c29d50533946b364564c age=3m24s    dirty="692.45 MiB"

**Comment by seonggwonyoon** [comment]
I had the same problem, changed the instance type from c5.4xlarge to c5d.4xlarge and increased disk iops from 3000 to 6000 and it was solved.

**Comment by guagualvcha** [comment]
Please refer to https://github.com/binance-chain/bsc/issues/502

**Comment by hellodword** [comment]
> I had the same problem, changed the instance type from c5.4xlarge to c5d.4xlarge and increased disk iops from 3000 to 6000 and it was solved.

I think [c5d.4xlarge](https://aws.amazon.com/cn/blogs/aws/ec2-instance-update-c5-instances-with-local-nvme-storage-c5d/) is c5.4xlarge with a 450 GB NVMe SSD, and the iops cannot be changed.

Can you tell me more about your solution?

Thank you!
