### ISSUE TITLE
what is the bnb get new address command in bsc mainnet node in linux

### ISSUE THREAD

**Issue by lokeshratnam09** [binance-chain/bsc#501]
After entered  a bsc mainnet node through geth command  , not able to generate new address in bnb through command .

> personal.NewAccount("123");
TypeError: 'NewAccount' is not a function
    at <anonymous>:1:1

> ; -- function is not working here.
so how to generate new address  through command line please help me . so i can build api through this.

Thankyou for advance.

**Comment by guagualvcha** [comment]
Please use ` ./geth account new  `

**Comment by lokeshratnam09** [comment]
> Please use `./geth account new `
Basically this above command used for validator address not for user new address.
After entered into geth node how to use this command ..??
