### ISSUE TITLE
Anyone else stuck on 12,286,674?

### ISSUE THREAD

**Issue by Crypto2** [binance-chain/bsc#503]
Getting this in the log:

INFO [11-01|18:35:46.849] Skip duplicated bad block                number=12,286,675 hash=3a1340..d43cff
ERROR[11-01|18:35:46.861]
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}

Number: 12286675
Hash: 0x3a1340c7655f2c194feede3cebb4872146d8eceb13e74ab9f9ee93b400d43cff
         0: cumulative: 39336 gas: 39336 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xb1256943beba35b48fcb517cd410394180bc326210c0e9ee2d4da2c416e2336e logs: [0xc0003258c0] bloom: 00008000000000000200000000000000000000000020000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
...
         380: cumulative: 67502557 gas: 161033 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x09235d26f6ebce65fd417fcc6f4babcb1f30c8d5abfba359005428838b2317d7 logs: [0xc054d789a0 0xc054d78a50 0xc054d78b00 0xc054d78bb0 0xc054d78c60 0xc054d78d10 0xc054d78dc0] bloom: 00200000000000000002000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000108000000200000100000000400000400000000000000200000800000000404000000000020000000000040000000000010000000010080800000000000000000000000000000040000000000080010004000000000000000000000000000000000000000000000000000000000000000008000400000000002000000000000000000080000000000000000001000000000000080000000000000000000000000000000000000000000000000000000000000000000 state:

Error: expected tx hash 0x268b7621590170b8a149c4d007cbabbd2c309fcf38d4b054610ebe4145df3583, get 0x698e3377ae9dc0ebb493900cd5d1c62c06b4377044521b6f8bb3a23e8d174db4, nonce 247789, to 0x0000000000000000000000000000000000001000, value 355890528761399528, gas 9223372036854775807, gasPrice 0, data f340fa0100000000000000000000000029a97c6effb8a411dabc6adeefaa84f5067c8bbe
##############################

WARN [11-01|18:35:46.864] Synchronisation failed, dropping peer    peer=cf4da38aa865f4f5e6b00571d25570a3b6c66c8b68ab1c1444528807df5283c5 err="retrieved hash chain is invalid: expected tx hash 0x268b7621590170b8a149c4d007cbabbd2c309fcf38d4b054610ebe4145df3583, get 0x698e3377ae9dc0ebb493900cd5d1c62c06b4377044521b6f8bb3a23e8d174db4, nonce 247789, to 0x0000000000000000000000000000000000001000, value 355890528761399528, gas 9223372036854775807, gasPrice 0, data f340fa0100000000000000000000000029a97c6effb8a411dabc6adeefaa84f5067c8bbe"

**Comment by khelle** [comment]
How were you able to solve this issue?

**Comment by Crypto2** [comment]
I used the debug_setHead() RPC call to roll back ~1,000 blocks, then it was able to get past it.
