### ISSUE TITLE
Is there any interest in a ethstats-like system to track node performance?

### ISSUE THREAD

**Issue by jimtje** [binance-chain/bsc#51]
Hi there,

Since this is more or less of an interest check I hope you forgive m for eschewing the template.

Out of frustration as available monitoring tools for comparison purposes to debug and diagnose issues I've forked the aleth.io set up clients to adapt it to BSC. Of course. Of course, 1 node (mine) isn't a great sample size. Is there a need in the community for this? On the eth side I've found great value for this but I literally cannot tell what the BSC lanscape is truly like since it's, frankly, not entirely transparent and albeit being a Chinese national who has been taught (brainwashed?) into thinking that the process doesn't matter, it does, and this is transparency and process at work. (And don't worry, I'm in the state with no plans to leave, have a law degree, and am thoroughly disgusted at what they do, particularly coming from a place of privilege over there that taught me that decentralized self-deployable small clusters of monitoring beats a.SAAS solution for privacy concerns.

But thre's no point in working on this if nobody care so this is an interest check really. There are bugs to be worked out and I'm admittedly much more a backend guy than a frontend guy. This is really a quick strawpoll to see what sentiments are out there. And my apologies in advance to the Chinese nationals still in China seeing this, but I don't think any of this is consider 敏感。 Comments in Chinese or English are both cool, thanks.

**Comment by huangsuyu** [comment]
I am not sure I understand you correctly. 请问能不能用中文复述一遍。

**Comment by jimtje** [comment]
因为现在好像没有什么服务可以让我从网上及时看到我的full node的情况，而且币安从来不回我的email, 也不提供任何监视办法。同时，它们尽然还通过我跟它们联系的机会来找我麻烦，把我的账户关了一周，莫名其妙，因为我在国外但是我身份证留在了国内。因为我不认为它们对辅助系统有太多兴趣我也不想多跟她们打交道，但是想问问如果我自己开了想ethstats.io一样的服务或者其他的类似系统，有没有人真的会用，还就是我一个？

**Comment by AlphaStop** [comment]
Yes, absolutely! I could definitely use this
