### ISSUE TITLE
v1.1.3 stop synchronizing blocks

### ISSUE THREAD

**Issue by KyloYang888** [binance-chain/bsc#511]
#### System information

Geth version: `1.1.3-b6035c1a`
OS & Version: Linux

#### Expected behaviour
Nodes synchronize new blocks normally

#### Actual behaviour
The node stops synchronizing new blocks at block 12327485, but the geth process runs normally.
The node starts synchronizing new blocks again after restarting

#### Backtrace

````
> eth.syncing
false
> eth.blockNumber
12327485
> eth.blockNumber
12327485
> eth.blockNumber
12327485
````

When submitting logs: please submit them as text and not screenshots.

**Comment by PanJ** [comment]
might relate with #510

**Comment by KyloYang888** [comment]
The node restarts and then stops synchronizing at block 12353014. But geth is running normally.

**Operating Environment**
Geth version: 1.1.2/1.1.3
OS & Version: c5a.4xlarge
mem: 32G
16 cores

**Start command**
sudo nohup geth --config=./config.toml --datadir=/data --cache=18000 --rpc.allow-unprotected-txs --ws --txlookuplimit=0 --diffsync --persistdiff >> nohup.out &

**Comment by yoongyy** [comment]
> I used the following resources
> 
> **Operating Environment** Geth version: 1.1.2/1.1.3 OS & Version: c5a.8xlarge mem: 64G 32vCPU
> 
> **Start command** sudo nohup geth --config=./config.toml --datadir=/data --cache=18000 --rpc.allow-unprotected-txs --ws --txlookuplimit=0 --diffsync --persistdiff >> nohup.out &

I am using the same version of Geth, my hardware is not powerful as yours.
My command same as yours except I do not have "--persistdiff", my node running good, so far no delay.
Maybe you can try to restart the node and see.

**Comment by KeefeL** [comment]
I think this is the same to #510
