### ISSUE TITLE
bsc node oom and after  bsc restart ,logs "Failed to load snapshot, regenerating" err="head doesn't match snapshot:"

### ISSUE THREAD

**Issue by wxf-kine** [binance-chain/bsc#515]
bsc node oom and after  bsc restart ,logs "Failed to load snapshot, regenerating" err="head doesn't match snapshot:"

t=2021-11-05T08:22:31+0000 lvl=info msg="Aborting state snapshot generation"     root=0x6aaa9d03840ff7ecec06ee38004bc72a17d2302c03c95f4467574a48ba793b15 at=0x170e14e5148c694b1d0340c3ae4f06ca549c29143f083d6c03cead10e2c26dab accounts=6,416,502 slots=55,884,065 storage="4.40 GiB" elapsed=11m38.946s  eta=2h51m29.33s
t=2021-11-05T08:22:31+0000 lvl=info msg="Resuming state snapshot generation"     root=0x0768e40af72c6163d1f64117e7bb26469c7bd9ce0218a88214efab8b7fb7df14 at=0x170e14e5148c694b1d0340c3ae4f06ca549c29143f083d6c03cead10e2c26dab accounts=6,416,502 slots=55,884,065 storage="4.40 GiB" elapsed=11m38.950s  eta=2h51m29.389s
t=2021-11-05T08:22:35+0000 lvl=info msg="Aborting state snapshot generation"     root=0x0768e40af72c6163d1f64117e7bb26469c7bd9ce0218a88214efab8b7fb7df14 in=0x173496395c31d28340f876f6de7c2f986798718fc6139a36310a4a9a01a4eda0 at=0xb01510999bbe8178017c0d1cd4e720d505f681a5dd01a8f7deac40d50a5197e6 accounts=6,458,663 slots=56,016,366 storage="4.41 GiB" elapsed=11m43.257s  eta=2h50m48.691s
t=2021-11-05T08:22:35+0000 lvl=info msg="Resuming state snapshot generation"     root=0x0e588b64771ccb4b13c56a29cfba9fb7a47ffd372412ab261e066a5948deec0a in=0x173496395c31d28340f876f6de7c2f986798718fc6139a36310a4a9a01a4eda0 at=0xb01510999bbe8178017c0d1cd4e720d505f681a5dd01a8f7deac40d50a5197e6 accounts=6,458,663 slots=56,016,366 storage="4.41 GiB" elapsed=11m43.258s  eta=2h50m48.706s
t=2021-11-05T08:22:36+0000 lvl=info msg="Imported new chain segment"

**Comment by wxf-kine** [comment]
./geth --config ./config.toml --gcmode archive --datadir ./node --cache 32768 --metrics --metrics.addr="0.0.0.0" --ws --ws.addr="0.0.0.0" --ws.origins="*"

**Comment by KeefeL** [comment]
Are you going to run an archive node, archive node is difficult to maintain, I will recommend you to run a full node follow tips in #502

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
