### ISSUE TITLE
What should be the proper way to run geth 1.1.4 windows version

### ISSUE THREAD

**Issue by blackerhot** [binance-chain/bsc#518]
I ran it with cmd and I found that memery usage limit at 20 gb out of 64 gb always. 
I really want to make the geth usage exceed to maximum cpu and memory.
Any proper solution to break it out 
I set data cache to around 50 gb on config already.
![image](https://user-images.githubusercontent.com/29283963/140640735-af4da423-743e-46f3-9492-7a1e6f5447d6.png)

**Comment by mjohn** [comment]
it doesn't use cpu unless needed.
no idea about memory, my node is using about ~40-50 GB. If you have given enough time to run, it should grow logarithmically.

**Comment by blackerhot** [comment]
After tried so many solution I knew how to fix it !!!
my ram usage stuck at 6gb all time. this is why i can not synce up to current block . always 100 block behide
All i did is setting a --cache 65000 (around 64gb) in my case  to command or whatever you have . after that you geth synce so smooth !!

**Comment by KeefeL** [comment]
It seems you have got your answer, I'm going to close this issue.
