### ISSUE TITLE
Fatal: ./config.toml, line 46: field 'omitempty' is not defined in node.Config

### ISSUE THREAD

**Issue by alberentsen** [binance-chain/bsc#52]
I follow the instruction to set-up a node on https://docs.binance.org/smart-chain/developer/fullnode.html and get the following fatal error:

Fatal: ./config.toml, line 46: field 'omitempty' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields

Here are the steps that I follow from the website:
## Install BSC node
git clone https://github.com/binance-chain/bsc
## Enter the folder bsc was cloned into
cd bsc
## Compile and install bsc
make geth
## mainet
wget --no-check-certificate  $(curl -s https://api.github.com/repos/binance-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip mainnet.zip
geth --datadir node init genesis.json
## start a full node
geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof
Here the error occurs.

## System information
Get Version: 1.9.24-stable
Git Commit: cc05b050df5f88e80bb26aaf6d2f339c49c2d702
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=/home/aber/go
GOROOT=/usr/local/go

**Comment by guagualvcha** [comment]
I try to follow your steps, and the version is:

```
Geth
Version: 1.0.4
Git Commit: ed10dfa6bf8d1175e6fb4d2e79997f60fb9627a5
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: darwin
GOPATH=/Users/baifudong/workspace
GOROOT=/usr/local/go
```
guess something wrong when build, the binary should under `build/bin`.

And we did have a false config in  `mainnet.zip` and correct it now.
