### ISSUE TITLE
Unclean Shutdown

### ISSUE THREAD

**Issue by CryptoDynasty** [binance-chain/bsc#521]
Linux Debian Mini

Running geth as a service, in the command console I have used systemctl stop geth to make changes and then used systemctl restart geth. When geth restarts it says it was an unclean shutdown. Is there another command I should be using?

**Comment by KeefeL** [comment]
Which binary version you are running, I think it is caused by ungraceful shutdown, maybe you can upgrade to the latest binary version.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
