### ISSUE TITLE
Market Price for Transactions and Maximum Speed of the Network

### ISSUE THREAD

**Issue by ghost** [binance-chain/bsc#522]
# Rationale

As many already noticed, the network is not working very stable recently due to high amount of tx per second. Despite the huge load on the network, base price of transactions always stands the same (5 gwei), as extremely cheap ticket for a subway train during prime time. And validators start creating blocks 600-800 tx per block sometimes, and every 5gwei tx is mined. From the client side everything is might be fine. But a lot of nodes are not able to catch up and stay in sync. OK, there are probably a few nodes that are capable to double and even tripple the speed, but since the network is decetralalized, majority of the nodes should be able to catch up, right?

# Implementation

As a solution I suggest to set a physical limitation for a network speed say 500-600 tx per block, so a validator might peak from the mempool first 500-600 high priced transactions and include them into the next block. That would be automatic market price mechanism for a unit of gas. 

In that case validators might collect more value, as clients are now motivated to pay more bnb for gas, and all off-sync nodes would be in sync.

Now imagine, we ignore that issue, and network is becoming three-four times more popular then now. Validators start putting 1000-2000 tx in every block. And only a few supercomputers conduct the whole network. Not very decentrelized. 

Thank you.

**Comment by KeefeL** [comment]
Thanks for your advice, there are some solutions developing try to resolve the sync problem, as you can see erigon #568 and fastnode #640, please stay tuned.

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
