### ISSUE TITLE
Geth not syncing with snapshot

### ISSUE THREAD

**Issue by gry** [binance-chain/bsc#523]
Hi, I downloaded the latest snapshot, geth 1.1.4, and the config.toml for the release 1.1.4 for mainnet, and following the docs it seems to get stuck without doing nothing.

I renamed the original "server" name to node in the same folder where the geth executable is, and run the following:

~~~
./geth_1.1.4 --config mainnet_1.1.3/config.toml --syncmode snap --datadir ./node --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
INFO [11-08|09:42:42.660] Starting Geth on Ethereum mainnet...                                                                                                       
INFO [11-08|09:42:42.663] Maximum peer count                       ETH=30 LES=0 total=30                                                                             
INFO [11-08|09:42:42.663] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"                                       
WARN [11-08|09:42:42.663] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable 
~~~

(And then there is silence)

Can someone help me to understand what is wrong in this setup?

Thank you!

**Comment by cgallic** [comment]
Remove the log module from the config file

**Comment by KeefeL** [comment]
I think the log has been redirected to another file, try to remove the log module as @cgallic said.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
