### ISSUE TITLE
After I restart my geth, the node stays synced and syncing all the time

### ISSUE THREAD

**Issue by pedrobonfim** [binance-chain/bsc#525]
#### System information

Geth version: `1.1.2`
OS & Version: Debian
2 TB SSD NVMe
64 GB DDR4 ECC 
Ryzen 7 3700X Octa-Core

My node was slower than usual, so I decided to stop the service and start again.
Now monitoring synchronization. I notice that it has a false status, it spends about 10 seconds back to sync. and stays there all the time. 

is anyone having this problem?

**Comment by elnem0** [comment]
Yes, same issue. Did you find the solution?

**Comment by KeefeL** [comment]
Maybe you can upgrade to the latest binary version and download the latest snapshot, follow the steps herehttps://docs.binance.org/smart-chain/developer/fullnode.html

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
