### ISSUE TITLE
Debug Trace Block: insufficient funds for transfer

### ISSUE THREAD

**Issue by quickchase** [binance-chain/bsc#526]
#### System information

Geth version: `1.1.4`
OS & Version: Linux

#### Expected behaviour
Successful trace of block number `12233666` / `0x6056d1c28d9f93af0f4fcbc569eeeba7624074cb808feb3e16ae961822c56cdf`

https://www.bscscan.com/block/12233666

#### Actual behaviour
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"insufficient funds for transfer: address 0x9bB832254BAf4E8B4cc26bD2B52B31389B56E98B"}}
```
#### Steps to reproduce the behaviour
You can try to trace by blockNumber or blockHash, same result
```
NODE=http://localhost:8545

DATA='{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByHash",
  "params": [
    "0x6056d1c28d9f93af0f4fcbc569eeeba7624074cb808feb3e16ae961822c56cdf",
    { "tracer": "callTracer" }
  ],
  "id": 1
}'

curl -s -H "Content-Type: application/json" -d "$DATA" $NODE
```

**Comment by quickchase** [comment]
I think this might be caused due to some kind of execution timeout and the error may just be misleading?

**Comment by KeefeL** [comment]
The same issue to me, but another block can return as expected.
```
curl -X POST --data '{"jsonrpc": "2.0", "id": 42, "method": "debug_traceBlockByNumber", "params":["0xBAABC2", {"tracer": "callTracer", "timeout":"120s"}]}' -H "Content-Type: application/json" https://bsc-dataseed-archive-graph.nariox.org/
{"id":0,"jsonrpc":"2.0","error":{"code":-32603,"message":"insufficient funds for transfer: address 0x9bB832254BAf4E8B4cc26bD2B52B31389B56E98B"}}%
```

**Comment by KeefeL** [comment]
I can get the debug result as expected now, and the result didn't see address 0x9bB832254BAf4E8B4cc26bD2B52B31389B56E98B, I guess maybe the block is corrupted before, anyway we can get the correct result now, you can have a try.

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
