### ISSUE TITLE
Switch sync mode from fast sync to full sync

### ISSUE THREAD

**Issue by harryweiyongjie** [binance-chain/bsc#529]
#### System information

Geth version: `1.1.3`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
I use --syncmode fast, but log tells me it sync with full mode

#### Actual behaviour
full syncmode 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.
![image](https://user-images.githubusercontent.com/43234967/140850013-16512d01-8533-4e55-a98e-db3c719200c1.png)
![image](https://user-images.githubusercontent.com/43234967/140850139-34835915-da56-4058-a0e0-f913f3424c0a.png)

**Comment by harryweiyongjie** [comment]
my node just sync 1000+ blocks through all night, it's toooooo slow, it just sync 2-4 block every time

![image](https://user-images.githubusercontent.com/43234967/140850484-d521f270-17bd-46a4-8f9c-f838bbe23c38.png)

**Comment by SnakePin** [comment]
This is not a bug, it is the intended behavior. The client will only use fast sync on the initial sync, once the node has been fully synced it will switch to the full sync.

**Comment by harryweiyongjie** [comment]
> This is not a bug, it is the intended behavior. The client will only use fast sync on the initial sync, once the node has been fully synced it will switch to the full sync.

but it sync too slow, it just sync 3 or 4 block every 8s

**Comment by mcoelho80** [comment]
> > This is not a bug, it is the intended behavior. The client will only use fast sync on the initial sync, once the node has been fully synced it will switch to the full sync.
> 
> but it sync too slow, it just sync 3 or 4 block every 8s

Same here.

**Comment by KeefeL** [comment]
Switch sync mode from fast to full is intended behavior as @SnakePin said. As the sync slow problem, there are many possible reasons, maybe you can get some tips here #502 .

**Comment by harryweiyongjie** [comment]
I've given up about bsc node, close
