### ISSUE TITLE
State heal in progress takes forever

### ISSUE THREAD

**Issue by sandcoffin** [binance-chain/bsc#530]
#### System information

Geth version: 1.1.2->1.1.4
OS & Version: Linux Ubuntu 20.04
Commit hash : (if `develop`)

#### Expected behaviour
Sync will take 1-2 day to complete

#### Actual behaviour
I was able to sync bsc 3 weeks ago, pretty smooth with 1.1.2 within more than a day, however i tried a fresh sync last week with 1.1.3, 1.1.4 and 1.1.2 (again) but always stuck at State heal in progress

#### Steps to reproduce the behaviour
This is the command i used
/root/geth --config /root/mainnet/config.toml --datadir /root/mainnet/data --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode=snap --snapshot=false

#### Backtrace
> eth.syncing
{
  currentBlock: 12497994,
  highestBlock: 12498068,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 12480257
}

bsc.log
t=2021-11-09T09:55:24+0100 lvl=info msg="State heal in progress"                 accounts=4,258,351@236.95MiB slots=18,770,353@1.35GiB    codes=3249@25.58MiB   nodes=80,038,311@20.19GiB  pending=34375
t=2021-11-09T09:55:27+0100 lvl=info msg="Imported new block headers"             count=1    elapsed=1.003ms     number=12,498,144 hash=0x81568d8d01b42e545de2a7cb9c8234d007362cf9453493e4ae2943383f5c8f82
t=2021-11-09T09:55:30+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="327.379µs" number=12,498,145 hash=0xea6c85b751567a79bad85b356abc5e2b7439de4ca87c7dec326800eb2612a9a6
t=2021-11-09T09:55:30+0100 lvl=info msg="Downloader queue stats"                 receiptTasks=0   blockTasks=0   itemSize="612.52 KiB" throttle=107
t=2021-11-09T09:55:33+0100 lvl=info msg="State heal in progress"                 accounts=4,258,351@236.95MiB slots=18,772,460@1.35GiB    codes=3249@25.58MiB   nodes=80,045,448@20.20GiB  pending=32187
t=2021-11-09T09:55:33+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="316.257µs" number=12,498,146 hash=0x0107bb7dcfa1295ffa10cbc3a75104d7eaeed3f384c9f8fdd5369ff889992556
t=2021-11-09T09:55:36+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="404.898µs" number=12,498,147 hash=0xdd8dafa39f2b46239790acd8b010fb55708c0db992a5b1d46b694a7ac2ffd5c8
t=2021-11-09T09:55:39+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="325.055µs" number=12,498,148 hash=0xfe0a16353a76029513498ed71063ada26279ad78455c24021d0e169e2b5c48f8
t=2021-11-09T09:55:41+0100 lvl=info msg="State heal in progress"                 accounts=4,258,351@236.95MiB slots=18,774,613@1.35GiB    codes=3249@25.58MiB   nodes=80,052,538@20.20GiB  pending=30646
t=2021-11-09T09:55:42+0100 lvl=info msg="Imported new block headers"             count=1    elapsed="697.438µs" number=12,498,149 hash=0xbe7035077ef4255d7b7d2e5c3698ad570d652838c433e9c6877922520f767030
t=2021-11-09T09:55:45+0100 lvl=info msg="Imported new block headers"             count=1    elapsed=1.114ms     number=12,498,150 hash=0xd330dfa4f3c8596d5cb3a22069a8eadb9b77d85281cdd3cd56381fd3f1f5603e

````
iostat -mdx
Linux 5.4.0-89-generic (Ubuntu-2004-focal-64-minimal)   11/09/2021      _x86_64_        (8 CPU)

Device            r/s     rMB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wMB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dMB/s   drqm/s  %drqm d_await dareq-sz  aqu-sz  %util
dm-0             0.87      0.00     0.00   0.00    0.27     4.07    1.23      0.00     0.00   0.00    6.72     4.00    0.00      0.00     0.00   0.00    0.00     0.00    0.01   0.26
dm-1             0.00      0.00     0.00   0.00    0.05    21.04    0.02      0.00     0.00   0.00    3.09     4.00    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.01
dm-2          4136.93     50.14     0.00   0.00    0.13    12.41  239.51     25.04     0.00   0.00    2.81   107.06    0.00      0.00     0.00   0.00    0.00     0.00    1.22  92.69
md0              0.00      0.00     0.00   0.00    0.00    11.63    0.00      0.00     0.00   0.00    0.00     0.89    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
md1           4198.44     56.10     0.00   0.00    0.00    13.68  290.28     26.88     0.00   0.00    0.00    94.83    0.00      0.00     0.00   0.00    0.00     0.00    0.00   0.00
nvme0n1       2122.70     25.50     3.88   0.18    0.14    12.30   79.87     12.85    79.79  49.98   16.08   164.74    0.00      0.00     0.00   0.00    0.00     0.00    1.22  90.62
nvme1n1       2067.47     24.64     4.40   0.21    0.13    12.21   70.09     12.13    78.05  52.69   18.74   177.19    0.00      0.00     0.00   0.00    0.00     0.00    1.25  89.78

# smartctl -a /dev/nvme0n1
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-89-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       SAMSUNG MZVKW512HMJP-00000
Serial Number:                      S316NX0J622879
Firmware Version:                   CXA7500Q
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 512,110,190,592 [512 GB]
Unallocated NVM Capacity:           0
Controller ID:                      2
Number of Namespaces:               1
Namespace 1 Size/Capacity:          512,110,190,592 [512 GB]
Namespace 1 Formatted LBA Size:     512
Namespace 1 IEEE EUI-64:            002538 c671b11d79
Local Time is:                      Tue Nov  9 09:57:48 2021 CET
Firmware Updates (0x16):            3 Slots, no Reset required
Optional Admin Commands (0x0017):   Security Format Frmw_DL Self_Test
Optional NVM Commands (0x001f):     Comp Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat
Warning  Comp. Temp. Threshold:     70 Celsius
Critical Comp. Temp. Threshold:     73 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     6.80W       -        -    0  0  0  0        0       0
 1 +     5.60W       -        -    1  1  1  1        0       0
 2 +     4.40W       -        -    2  2  2  2        0       0
 3 -   0.0400W       -        -    3  3  3  3      210    1500
 4 -   0.0050W       -        -    4  4  4  4     2200    6000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        50 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    20%
Data Units Read:                    291,643,504 [149 TB]
Data Units Written:                 189,355,300 [96.9 TB]
Host Read Commands:                 13,834,225,177
Host Write Commands:                2,611,374,835
Controller Busy Time:               43,181
Power Cycles:                       27
Power On Hours:                     26,424
Unsafe Shutdowns:                   6
Media and Data Integrity Errors:    0
Error Information Log Entries:      16
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               50 Celsius
Temperature Sensor 2:               83 Celsius

Error Information (NVMe Log 0x01, max 64 entries)
Num   ErrCount  SQId   CmdId  Status  PELoc          LBA  NSID    VS
  0         16     0  0x0011  0x4016  0x004            0     1     -
  1         15     0  0x0014  0x4004      -            0     0     -
  2         14     0  0x0016  0x4004      -            0     0     -
  3         13     0  0x000c  0x4004      -            0     0     -
  4         12     0  0x000c  0x4004      -            0     0     -
  5         11     0  0x0011  0x4016  0x004            0     1     -
  6         10     0  0x0011  0x4016  0x004            0     1     -
  7          9     0  0x0011  0x4016  0x004            0     1     -
  8          8     0  0x0011  0x4016  0x004            0     1     -
  9          7     0  0x0011  0x4016  0x004            0     1     -
 10          6     0  0x0011  0x4016  0x004            0     1     -
 11          5     0  0x0011  0x4016  0x004            0     1     -
 12          4     0  0x0011  0x4016  0x004            0     1     -
 13          3     0  0x0011  0x4016  0x004            0     1     -
 14          2     0  0x0011  0x4016  0x004            0     1     -
 15          1     0  0x0011  0x4016  0x004            0     1     -

````

When submitting logs: please submit them as text and not screenshots.

**Comment by adenine0001** [comment]
same here. It has been around 2 days and my server is still at this stage
```
t=2021-11-10T04:30:50+0100 lvl=info msg="State heal in progress"    accounts=11,811,644@694.67MiB slots=37,253,111@2.69GiB codes=7693@60.22MiB nodes=191,248,181@50.10GiB pending=109,730
```
not sure how long it will take

**Comment by sandcoffin** [comment]
it seems this stage should be quick, i consulted geth team and they say if it cant complete in a day or earlier, it will never catch up

**Comment by adenine0001** [comment]
prior to this stage I saw 
```
msg="State sync in progress"   synced=100.00% state="

200.61 GiB" accounts=75,993,218@17.58GiB slots=874,107,297@176.68GiB codes=797,763@6.35GiB
``` 
don't know if "State heal" can finish when the number of accounts reaches that value.

**Comment by KeefeL** [comment]
Maybe you can download the latest snapshot and try to run it with flag --snapshot=true not --snapshot=false

**Comment by Thrisul-K** [comment]
@adenine0001 @sandcoffin 
i'm facing the same issue now, could you please let me know if you had any luck in resolving this issue.

**Comment by roflganker** [comment]
Same issue on BNB test network. "accounts", "slots", "codes" are increasing slowly.

Also I see frequent errors like this:
```shell
########## BAD BLOCK #########
Chain config: {ChainID: 97 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 1010000, Niels: 1014369, MirrorSync: 5582500, Bruno: 13837000, Berlin: <nil>, YOLO v3: <nil>, CatalystBlock: <nil>, London: <nil>, ArrowGlacier: <nil>, MergeFork:<nil>, Euler: 19203503, Gibbs: 22800220, Nano: 23482428, Moran: 23603940, Planck: 28196022, Engine: parlia}

Number: 28929604
Hash: 0xff18b42a45c7d444ea509f81ca22974e1589c26ad53e592ad51425c42b56bfa6


Error: could not apply tx 0 [0x3a8a0552ca0436d9e0109ddf9e1db32a4040c72a3e2a06ea0c039e3e33aeafc0]: nonce too high: address 0xaa25Aa7a19f9c426E07dee59b12f944f4d9f1DD3, tx: 9594633 state: 0
##############################
```

Seems like the node is trying to apply newer blocks, but it's state is corrupted and it cannot validate them..
