### ISSUE TITLE
Impossible reorg, please file an issue

### ISSUE THREAD

**Issue by mcoelho80** [binance-chain/bsc#531]
#### System information

Geth version: 1.1.4
OS & Version: FreeBSD 13.0
Commit hash : (if `develop`)

#### Expected behaviour

Normal sync

#### Actual behaviour

Error:

t=2021-11-09T09:41:26-0300 lvl=eror msg="Impossible reorg, please file an issue" oldnum=12,502,069 oldhash=0xcd2066098442046bd9466de3244ae3fc0eaef7d5f04f0dd5f8090cb64d89ae51 newnum=12,502,069 newhash=0xcd2066098442046bd9466de3244ae3fc0eaef7d5f04f0dd5f8090cb64d89ae51

Sync age becomes older and older.

#### Steps to reproduce the behaviour

Just start geth syncmode "snap"

**Comment by KeefeL** [comment]
I think maybe your data directory has some problem, maybe you can remove your old data directory, and download the latest snapshot to run again, follow the guide here https://docs.binance.org/smart-chain/developer/fullnode.html

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
