### ISSUE TITLE
Generating state snapshot ....

### ISSUE THREAD

**Issue by berktaylan** [binance-chain/bsc#537]
Hey everyone ;

`
INFO [11-11|08:35:06.621] Generating state snapshot                root=822736..6ead1f in=23f0e5..9246ce at=3e6da3..65d6db accounts=19,915,873 slots=86,416,153 storage=7.21GiB    elapsed=18h2m7.146s   eta=110h25m34.98          6s

 INFO [11-11|08:35:14.621] Generating state snapshot                root=822736..6ead1f in=23f0e5..9246ce at=4b1158..d71840 accounts=19,915,873 slots=86,429,430 storage=7.21GiB    elapsed=18h2m15.147s  eta=110h26m23.97          4s
 
INFO [11-11|08:35:22.622] Generating state snapshot                root=822736..6ead1f in=23f0e5..9246ce at=57b37d..c0ae3e accounts=19,915,873 slots=86,442,694 storage=7.21GiB    elapsed=18h2m23.147s  eta=110h27m12.95          7s

 INFO [11-11|08:35:30.622] Generating state snapshot                root=822736..6ead1f in=23f0e5..9246ce at=647993..d1a10f accounts=19,915,873 slots=86,456,050 storage=7.21GiB    elapsed=18h2m31.148s  eta=110h28m1.945  `

Is this normal behaviour , and do i still need 110h to have my node complete ?

**Comment by psdlt** [comment]
@berktaylan it is normal. Your node should be "complete" and operational already (`geth attach --datadir /path/to/your/data/dir` and then check the output of `eth.syncing`).

**Comment by berktaylan** [comment]
@psdlt 

When i try i get this response from the first command

`Fatal: Unable to attach to remote geth: dial unix node/geth.ipc: connect: no such file or directory
`

**Comment by psdlt** [comment]
@berktaylan you can see same info by connecting to your node with web3js https://web3js.readthedocs.io/en/v1.5.2/web3-eth.html#issyncing

**Comment by psdlt** [comment]
@berktaylan your error means that you probably have `ipc` disabled in your node's config. Or you provided wrong data dir.

**Comment by berktaylan** [comment]
hey @psdlt i think i've made wrong chain on last attempt, i make a new setup, after like 24 hour now i see below at bsc.logs
Does it mean the setup , sync progress is %100 done , and node is active ( no more steps like download , sync etc )
Thanks
```
t=2021-11-12T12:13:41+0000 lvl=info msg="Imported new state entries"             count=551  elapsed=2.585ms     processed=284,657,789 pending=39797   trieretry=0    coderetry=0  duplicate=1333 unexpected=8077
t=2021-11-12T12:13:44+0000 lvl=info msg="Imported new state entries"             count=768  elapsed=3.137ms     processed=284,658,557 pending=39826   trieretry=0    coderetry=0  duplicate=1333 unexpected=8077
t=2021-11-12T12:13:46+0000 lvl=info msg="Imported new block headers"             count=2    elapsed="462.687µs" number=12,585,637 hash=0xd7226bb2fa28ba8b4d31d871545574050e7d1b752647a31a249a88350c7ef6c1
t=2021-11-12T12:13:48+0000 lvl=info msg="Imported new state entries"             count=725  elapsed=3.248ms     processed=284,659,282 pending=39804   trieretry=0    coderetry=0  duplicate=1333 unexpected=8077
t=2021-11-12T12:13:49+0000 lvl=info msg="Imported new block headers"             count=1    elapsed="331.8µs"   number=12,585,638 hash=0x1c17cbc6784553fc4f537b6abbb734875da2453caa6112a72006d16ae9d55bbf
t=2021-11-12T12:13:50+0000 lvl=info msg="Imported new state entries"             count=538  elapsed=2.925ms     processed=284,659,820 pending=39668   trieretry=0    coderetry=0  duplicate=1333 unexpected=8077
t=2021-11-12T12:13:53+0000 lvl=info msg="Imported new block headers"             count=1    elapsed="298.801µs" number=12,585,639 hash=0x03fe8e22207eb4022c0e52be7872e7e52d99aa059a44265274123e1f54661b63
```

**Comment by psdlt** [comment]
@berktaylan "Imported new state entries" suggests to me that it's still syncing, but you should check output of `eth.syncing` to be sure.

**Comment by berktaylan** [comment]
@psdlt 
im trying to enter console to see eth.syncing with
` ./geth attach /node`

but i see this 
`Fatal: Unable to attach to remote geth: dial unix ./node: connect: connection refused`

And this is my service to run geth bsc, is anything wrong ?
`ExecStart=/home/bsc/geth --config /home/bsc/config.toml --datadir /home/bsc/node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0`

**Comment by berktaylan** [comment]
I tried with
` ./geth attach ./node/geth.ipc
`
And response is
`{
  currentBlock: 12589927,
  highestBlock: 12590023,
  knownStates: 322285478,
  pulledStates: 322271005,
  startingBlock: 0
}
`

I think im still out of sync. Lets wait more. Thanks @psdlt

**Comment by voron** [comment]
As of today, I've seen these accounts/slots metrics while finishing snapshot generation
```
bsc.log.2021-12-05_02:t=2021-12-05T02:41:09+0000 lvl=info msg="Generated state snapshot"               accounts=72,959,188 slots=1,184,693,569 storage="89.31 GiB"   elapsed=107h10m25.313s
```

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by TehnobitSystems** [comment]
> I tried with `./geth attach ./node/geth.ipc` And response is `{ currentBlock: 12589927, highestBlock: 12590023, knownStates: 322285478, pulledStates: 322271005, startingBlock: 0 } `
> 
> I think im still out of sync. Lets wait more. Thanks @psdlt

try in bash: 
```
geth attach http:://127.0.0.1:8545

eth.syncing
```
