### ISSUE TITLE
Huge size chaindata folder

### ISSUE THREAD

**Issue by manefesto** [binance-chain/bsc#538]
Version:
```
NAME:
   geth - the go-ethereum command line interface

   Copyright 2013-2021 The go-ethereum Authors

USAGE:
   geth [options] [command] [command options] [arguments...]

VERSION:
   1.1.4-30972a7b
```
Run options:
```
geth --datadir /data --config /config/config.toml --syncmode fast --cache 18000 --txlookuplimit 0 --nat none --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain '*' --http.vhosts '*' --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*
```

Config:
```
[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["0.0.0.0"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 30
NoDiscovery = false
BootstrapNodes = *SKIP*
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
```

Size folders inside /data/geth:
```
2.0T	./chaindata
15M	./nodes
169M	./ethash
2.8G	./triecache
```

How decrease size of chaindata folder?

**Comment by psdlt** [comment]
@manefesto prune your node (see here https://github.com/binance-chain/bsc/issues/502). Keep in mind that to prune, you will have to take your node offline and pruning might take many hours to complete.

**Comment by mikolajsobolewski** [comment]
> @manefesto prune your node (see here #502). Keep in mind that to prune, you will have to take your node offline and pruning might take many hours to complete.
Is it really for pruning the database, need to use the full resync from snapshots? It seems to me, something in this algorithm is wrong.

**Comment by pmmasterpm** [comment]
The size of the node data is growing very quickly. From 700GB of snapshot to 2T in 10 days. What can be done to prevent them from growing so much?


And one more observation - data grows in different speed on different servers.

**Comment by blackerhot** [comment]
This happens to everyone know when chaindata + ancient is almost upto 1 TB .
I don't know why it tooks so much space to handle it. 
This chain is gonna be blow up someday :D

**Comment by gituser** [comment]
The BSC chaindata indeed grows very quickly day by day.

Pruning is not an option as it takes down the node for 5-7 hours even on fast hardware like NVME..

Any tips on this @guagualvcha ?

**Comment by chevoisiatesalvati** [comment]
> Version:
> 
> ```
> NAME:
>    geth - the go-ethereum command line interface
> 
>    Copyright 2013-2021 The go-ethereum Authors
> 
> USAGE:
>    geth [options] [command] [command options] [arguments...]
> 
> VERSION:
>    1.1.4-30972a7b
> ```
> 
> Run options:
> 
> ```
> geth --datadir /data --config /config/config.toml --syncmode fast --cache 18000 --txlookuplimit 0 --nat none --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain '*' --http.vhosts '*' --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*
> ```
> 
> Config:
> 
> ```
> [Eth]
> NetworkId = 56
> NoPruning = false
> NoPrefetch = false
> LightPeers = 100
> UltraLightFraction = 75
> TrieTimeout = 100000000000
> EnablePreimageRecording = false
> EWASMInterpreter = ""
> EVMInterpreter = ""
> 
> [Eth.Miner]
> GasFloor = 30000000
> GasCeil = 40000000
> GasPrice = 1000000000
> Recommit = 10000000000
> Noverify = false
> 
> [Eth.TxPool]
> Locals = []
> NoLocals = true
> Journal = "transactions.rlp"
> Rejournal = 3600000000000
> PriceLimit = 1000000000
> PriceBump = 10
> AccountSlots = 512
> GlobalSlots = 10000
> AccountQueue = 256
> GlobalQueue = 5000
> Lifetime = 10800000000000
> 
> [Eth.GPO]
> Blocks = 20
> Percentile = 60
> OracleThreshold = 20
> 
> [Node]
> IPCPath = "geth.ipc"
> HTTPHost = "0.0.0.0"
> NoUSB = true
> InsecureUnlockAllowed = false
> HTTPPort = 8545
> HTTPVirtualHosts = ["0.0.0.0"]
> HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
> WSPort = 8546
> WSModules = ["net", "web3", "eth"]
> 
> [Node.P2P]
> MaxPeers = 30
> NoDiscovery = false
> BootstrapNodes = *SKIP*
> ListenAddr = ":30311"
> EnableMsgEvents = false
> 
> [Node.HTTPTimeouts]
> ReadTimeout = 30000000000
> WriteTimeout = 30000000000
> IdleTimeout = 120000000000
> ```
> 
> Size folders inside /data/geth:
> 
> ```
> 2.0T	./chaindata
> 15M	./nodes
> 169M	./ethash
> 2.8G	./triecache
> ```
> 
> How decrease size of chaindata folder?

This is really annoying. I'm trying to sync from weeks, reading about performance I bought 2 wd black nvme gen 4 and make raid0, now I'm still slow and also I'm seeing storage on chaindata increase really fast. I don't think 2 TB is enough and in the documentation it says that 1 TB is the suggested space! LOL

**Comment by guagualvcha** [comment]
> 

https://github.com/binance-chain/bsc/issues/502.   Please raise the `TrieTimeout` in the config.toml, if the storage of your node increase dramatically, the exchange is that you have to tolerate with longer replaying time when the node been force killed or panic.

**Comment by gituser** [comment]
@guagualvcha I've increased `TrieTimeout` to `TrieTimeout = 10000000000000000` still doesn't help, I'm seeing +100GB per day node is synced and not behind. 

Any other tips?

**Comment by KeefeL** [comment]
> 

There are some solutions developing now, erigon #568 and fastnode #640

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
