### ISSUE TITLE
Unable to sync - too slow

### ISSUE THREAD

**Issue by NullQubit** [binance-chain/bsc#539]
I am unable to sync, the sync speed is too slow.

I am using a provisioned VM Standard F48s_v2 (48 vCPUs and 96 GiB of memory) with an attached ultra disk LRS (4072 GiB size, 160k IOPS and 4000 MB/s max throughput) on Azure. As far as I know, there's really nothing better than this supported on Azure.

This seems to be insufficient, the node fails to sync up in time (The blocks are moving faster than my node can process). The maximum observed usage is:

Disk write speed: ~120 MB/s and read speed 5 MB/s.
CPU: 10%
Memory: 26 GB
Ethernet throughput: ~1MB/s 

I am starting geth using the command:
./geth_windows.exe --config ./config.toml --datadir ./node  --cache 24000 --rpc.allow-unprotected-txs --txlookuplimit 0

MaxPeers is set to 90, and I'm using a snapshot from 7th November (Been trying to catch up for a few days now). This is what I see in the logs:

```
t=2021-11-12T15:58:33+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=711  mgas=123.641 elapsed=8.323s    mgasps=14.854 number=12,485,414 hash=0x420fb4b6c019e8d5b18a331d06d4357691b8fb8c8995b6114affdc026eb818e3 age=3d17h42m dirty="706.00 MiB"
t=2021-11-12T15:58:35+0000 lvl=info msg="Deep froze chain segment"               blocks=21 elapsed=74.485ms  number=12,395,414 hash=0x1da091f229cc770709fede1bcc1bfaaeeb831b9162ef4e5be33db4ffe27765e0
t=2021-11-12T15:58:42+0000 lvl=info msg="Imported new chain segment"             blocks=2  txs=726  mgas=124.125 elapsed=8.185s    mgasps=15.163 number=12,485,416 hash=0x9da2916fcc6789457103e4206024578917322f23abd3b7a81ee72b90dc865e88 age=3d17h42m dirty="712.83 MiB"
t=2021-11-12T15:58:51+0000 lvl=info msg="Imported new chain segment"             blocks=4  txs=1026 mgas=165.463 elapsed=9.624s    mgasps=17.192 number=12,485,420 hash=0x469f4c20ac828036b89d7daf659699c6a5fff0370a4e7324bd442fe51e6d134d age=3d17h42m dirty="720.40 MiB"
t=2021-11-12T15:58:58+0000 lvl=eror msg="diff layers too new from current"       pid=0de8ac194fb56aa879e5be5af337a4d38993cfe2b1750fb88ab68afa1ff65bb1
t=2021-11-12T15:59:01+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=1062 mgas=158.318 elapsed=9.661s    mgasps=16.387 number=12,485,423 hash=0x951d6b03f308b4fe13d9f697e121f6cc2518c16fe6620783a86983d00cdae50b age=3d17h42m dirty="729.06 MiB"
t=2021-11-12T15:59:12+0000 lvl=info msg="Persisted trie from memory database"    nodes=218,476 size="70.02 MiB" time=2.6900224s gcnodes=168,372 gcsize="66.76 MiB"  gctime=875.4069ms livenodes=1,448,023 livesize="289.26 MiB"
t=2021-11-12T15:59:12+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=759  mgas=121.110 elapsed=11.198s   mgasps=10.815 number=12,485,426 hash=0xc074ae70681d7871770540d0f492a9f34274f4219a96207dc49145419e6478bf age=3d17h42m dirty="735.37 MiB"
t=2021-11-12T15:59:21+0000 lvl=info msg="Imported new chain segment"             blocks=2  txs=739  mgas=129.830 elapsed=9.016s    mgasps=14.399 number=12,485,428 hash=0xcd785880a6da750e48006ffd149815f432e7ee737ea0dde75f7b342c56f0ae26 age=3d17h42m dirty="658.12 MiB"
t=2021-11-12T15:59:29+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=848  mgas=129.989 elapsed=8.120s    mgasps=16.008 number=12,485,431 hash=0x2a8df8b8e21f9173b8256f7f3014cd8c91e03a0e4c804443b599a9f4774e9f78 age=3d17h42m dirty="668.32 MiB"
t=2021-11-12T15:59:35+0000 lvl=info msg="Deep froze chain segment"               blocks=19 elapsed=45.209ms  number=12,395,433 hash=0x8d02681aeb061c2cd44248234324c0cb6bdb92f71756cc83a89b02c9363c42ab
t=2021-11-12T15:59:37+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=818  mgas=131.960 elapsed=8.057s    mgasps=16.377 number=12,485,434 hash=0x289b8444d5e09955f4e222f1fd6e09bf53de768f8c8de5c493dccf0665b64f50 age=3d17h42m dirty="677.16 MiB"
t=2021-11-12T15:59:46+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=800  mgas=122.562 elapsed=8.504s    mgasps=14.411 number=12,485,437 hash=0x0a2bfdd7dfcd4a7061aabfe8ecc3cda4e989fd674e062c0979c9b13252e4e6ac age=3d17h41m dirty="685.24 MiB"
t=2021-11-12T15:59:56+0000 lvl=info msg="Imported new chain segment"             blocks=3  txs=977  mgas=153.260 elapsed=10.592s   mgasps=14.469 number=12,485,440 hash=0xc6f0b8a62d2d53ed0096d915eb5569373c342f1f1d727042d25c5665e7b7ddce age=3d17h42m dirty="694.42 MiB"
```

Any ideas how I can manage to catch up to the latest block? Do I need even faster hardware (In which case I might need to settle for AWS) or something else might be causing this?

Thanks

**Comment by psdlt** [comment]
don't use snapshot, try fast sync from scratch

**Comment by imharvol** [comment]
> don't use snapshot, try fast sync from scratch

Why is that? isn't it much better to sync from snapshots?

**Comment by psdlt** [comment]
@imharvol in theory - yes, syncing from snapshot should be a better option, but read through the issues here... almost all of them are about people trying to sync from snapshot and not being able to. I never had any issues syncing from scratch, on a far lesser hardware than your spec, and that one time when I tried to do sync from snapshot - it didn't work, so... 🤷

**Comment by philzeh** [comment]
> @imharvol in theory - yes, syncing from snapshot should be a better option, but read through the issues here... almost all of them are about people trying to sync from snapshot and not being able to. I never had any issues syncing from scratch, on a far lesser hardware than your spec, and that one time when I tried to do sync from snapshot - it didn't work, so... 🤷

For testing purposes I ran two new vultr nodes last night in LA data centre - one from scratch and one from snapshot. The snapshot synced in 14 hours, and the one from scratch still is going. Currently using the snapshot one without issues (downloaded US east snapshot 11/11). I used the second NVME drive as the data drive.

**Comment by NullQubit** [comment]
Thanks everyone for your insights.

I re-downloaded the snapshot from 11 Nov and tried again the whole thing - I was able to sync in 15 hours. I honestly didn't change anything else.

The problem now is that I seem to fall behind up to 5 blocks every now and then. When this happens, I stay behind for a few seconds and then sync up to the latest block quickly. This makes my node very unreliable. This is what I see in the logs:

```
INFO [11-13|11:36:29.788] Imported new chain segment               blocks=1   txs=317   mgas=50.284   elapsed=904.029ms mgasps=55.622  number=12,612,838 hash=45bd26..d23780 dirty=1.15GiB
INFO [11-13|11:36:33.113] Imported new chain segment               blocks=1   txs=528   mgas=84.503   elapsed=1.040s    mgasps=81.251  number=12,612,839 hash=edae3a..70cda0 dirty=1.15GiB
INFO [11-13|11:36:35.861] Imported new chain segment               blocks=1   txs=367   mgas=58.048   elapsed=884.581ms mgasps=65.622  number=12,612,840 hash=65cdd7..3cc1f3 dirty=1.15GiB
INFO [11-13|11:36:52.829] Deep froze chain segment                 blocks=19  elapsed=50.869ms  number=12,522,841 hash=e6e56b..004a7e
INFO [11-13|11:36:59.440] Persisted trie from memory database      nodes=702,198   size=211.34MiB time=11.1714421s gcnodes=1,006,558 gcsize=391.88MiB gctime=6.0110221s  livenodes=2,028,092 livesize=532.30MiB
INFO [11-13|11:36:59.456] Imported new chain segment               blocks=2   txs=675   mgas=97.801   elapsed=12.917s   mgasps=7.571   number=12,612,842 hash=b127a9..8c5b8f dirty=1.15GiB
INFO [11-13|11:37:00.579] Imported new chain segment               blocks=1   txs=536   mgas=84.222   elapsed=1.110s    mgasps=75.845  number=12,612,843 hash=3753a4..8c0ef6 dirty=912.90MiB
INFO [11-13|11:37:01.252] Imported new chain segment               blocks=1   txs=333   mgas=50.559   elapsed=660.448ms mgasps=76.552  number=12,612,844 hash=56e3cc..0e7ca7 dirty=917.27MiB
INFO [11-13|11:37:03.058] Imported new chain segment               blocks=1   txs=433   mgas=76.962   elapsed=1.795s    mgasps=42.869  number=12,612,845 hash=bcd7e7..4e82e5 dirty=923.71MiB
INFO [11-13|11:37:03.500] Chain reorg detected                     number=12,612,844 hash=56e3cc..0e7ca7 drop=1 dropfrom=bcd7e7..4e82e5 add=1 addfrom=41d5f5..859514
INFO [11-13|11:37:03.515] Imported new chain segment               blocks=1   txs=447   mgas=79.811   elapsed=443.946ms mgasps=179.776 number=12,612,845 hash=41d5f5..859514 dirty=923.81MiB
INFO [11-13|11:37:03.573] Re-queue blocks                          number=12,612,846 hash=0x48b459e1d875c3903dd75de6373847d4eac2bdb6c814eaedad266cef87012e37
INFO [11-13|11:37:04.347] Imported new chain segment               blocks=1   txs=872   mgas=68.713   elapsed=817.334ms mgasps=84.069  number=12,612,846 hash=48b459..012e37 dirty=930.65MiB  ignored=1
INFO [11-13|11:37:05.418] Imported new chain segment               blocks=1   txs=375   mgas=69.759   elapsed=1.057s    mgasps=65.943  number=12,612,847 hash=ca195f..f225ad dirty=935.39MiB
INFO [11-13|11:37:06.552] Imported new chain segment               blocks=1   txs=611   mgas=84.360   elapsed=1.123s    mgasps=75.074  number=12,612,848 hash=df9503..b123d6 dirty=941.36MiB
INFO [11-13|11:37:07.378] Imported new chain segment               blocks=1   txs=433   mgas=66.146   elapsed=815.282ms mgasps=81.133  number=12,612,849 hash=c24f11..79ca8f dirty=945.43MiB
INFO [11-13|11:37:13.465] Imported new chain segment               blocks=2   txs=1195  mgas=114.254  elapsed=1.717s    mgasps=66.531  number=12,612,851 hash=ca2c22..0f6adc dirty=950.62MiB  ignored=1
INFO [11-13|11:37:15.526] Imported new chain segment               blocks=1   txs=582   mgas=76.676   elapsed=1.391s    mgasps=55.105  number=12,612,852 hash=625a34..3a0b4e dirty=956.15MiB
```

Any ideas why this might be happening now?

**Comment by mcoelho80** [comment]
> Thanks everyone for your insights.
> 
> I re-downloaded the snapshot from 11 Nov and tried again the whole thing - I was able to sync in 15 hours. I honestly didn't change anything else.
> 
> The problem now is that I seem to fall behind up to 5 blocks every now and then. When this happens, I stay behind for a few seconds and then sync up to the latest block quickly. This makes my node very unreliable. This is what I see in the logs:
> 
> ```
> INFO [11-13|11:36:29.788] Imported new chain segment               blocks=1   txs=317   mgas=50.284   elapsed=904.029ms mgasps=55.622  number=12,612,838 hash=45bd26..d23780 dirty=1.15GiB
> INFO [11-13|11:36:33.113] Imported new chain segment               blocks=1   txs=528   mgas=84.503   elapsed=1.040s    mgasps=81.251  number=12,612,839 hash=edae3a..70cda0 dirty=1.15GiB
> INFO [11-13|11:36:35.861] Imported new chain segment               blocks=1   txs=367   mgas=58.048   elapsed=884.581ms mgasps=65.622  number=12,612,840 hash=65cdd7..3cc1f3 dirty=1.15GiB
> INFO [11-13|11:36:52.829] Deep froze chain segment                 blocks=19  elapsed=50.869ms  number=12,522,841 hash=e6e56b..004a7e
> INFO [11-13|11:36:59.440] Persisted trie from memory database      nodes=702,198   size=211.34MiB time=11.1714421s gcnodes=1,006,558 gcsize=391.88MiB gctime=6.0110221s  livenodes=2,028,092 livesize=532.30MiB
> INFO [11-13|11:36:59.456] Imported new chain segment               blocks=2   txs=675   mgas=97.801   elapsed=12.917s   mgasps=7.571   number=12,612,842 hash=b127a9..8c5b8f dirty=1.15GiB
> INFO [11-13|11:37:00.579] Imported new chain segment               blocks=1   txs=536   mgas=84.222   elapsed=1.110s    mgasps=75.845  number=12,612,843 hash=3753a4..8c0ef6 dirty=912.90MiB
> INFO [11-13|11:37:01.252] Imported new chain segment               blocks=1   txs=333   mgas=50.559   elapsed=660.448ms mgasps=76.552  number=12,612,844 hash=56e3cc..0e7ca7 dirty=917.27MiB
> INFO [11-13|11:37:03.058] Imported new chain segment               blocks=1   txs=433   mgas=76.962   elapsed=1.795s    mgasps=42.869  number=12,612,845 hash=bcd7e7..4e82e5 dirty=923.71MiB
> INFO [11-13|11:37:03.500] Chain reorg detected                     number=12,612,844 hash=56e3cc..0e7ca7 drop=1 dropfrom=bcd7e7..4e82e5 add=1 addfrom=41d5f5..859514
> INFO [11-13|11:37:03.515] Imported new chain segment               blocks=1   txs=447   mgas=79.811   elapsed=443.946ms mgasps=179.776 number=12,612,845 hash=41d5f5..859514 dirty=923.81MiB
> INFO [11-13|11:37:03.573] Re-queue blocks                          number=12,612,846 hash=0x48b459e1d875c3903dd75de6373847d4eac2bdb6c814eaedad266cef87012e37
> INFO [11-13|11:37:04.347] Imported new chain segment               blocks=1   txs=872   mgas=68.713   elapsed=817.334ms mgasps=84.069  number=12,612,846 hash=48b459..012e37 dirty=930.65MiB  ignored=1
> INFO [11-13|11:37:05.418] Imported new chain segment               blocks=1   txs=375   mgas=69.759   elapsed=1.057s    mgasps=65.943  number=12,612,847 hash=ca195f..f225ad dirty=935.39MiB
> INFO [11-13|11:37:06.552] Imported new chain segment               blocks=1   txs=611   mgas=84.360   elapsed=1.123s    mgasps=75.074  number=12,612,848 hash=df9503..b123d6 dirty=941.36MiB
> INFO [11-13|11:37:07.378] Imported new chain segment               blocks=1   txs=433   mgas=66.146   elapsed=815.282ms mgasps=81.133  number=12,612,849 hash=c24f11..79ca8f dirty=945.43MiB
> INFO [11-13|11:37:13.465] Imported new chain segment               blocks=2   txs=1195  mgas=114.254  elapsed=1.717s    mgasps=66.531  number=12,612,851 hash=ca2c22..0f6adc dirty=950.62MiB  ignored=1
> INFO [11-13|11:37:15.526] Imported new chain segment               blocks=1   txs=582   mgas=76.676   elapsed=1.391s    mgasps=55.105  number=12,612,852 hash=625a34..3a0b4e dirty=956.15MiB
> ```
> 
> Any ideas why this might be happening now?

Same problem here. Using NVME, 192Gb RAM, 1.4Gbps fast Internetconnection still having many problems to sync.

Binance Smart Chain can't support heavy network usage? Solana likes that.

**Comment by updatesvc** [comment]
@philzeh

what specs is your snapshot node running?
if you are using AWS what instance type is it?

**Comment by h3k1ru** [comment]
> Thanks everyone for your insights.
> 
> I re-downloaded the snapshot from 11 Nov and tried again the whole thing - I was able to sync in 15 hours. I honestly didn't change anything else.
> 
> The problem now is that I seem to fall behind up to 5 blocks every now and then. When this happens, I stay behind for a few seconds and then sync up to the latest block quickly. This makes my node very unreliable. This is what I see in the logs:
> 
> ```
> INFO [11-13|11:36:29.788] Imported new chain segment               blocks=1   txs=317   mgas=50.284   elapsed=904.029ms mgasps=55.622  number=12,612,838 hash=45bd26..d23780 dirty=1.15GiB
> INFO [11-13|11:36:33.113] Imported new chain segment               blocks=1   txs=528   mgas=84.503   elapsed=1.040s    mgasps=81.251  number=12,612,839 hash=edae3a..70cda0 dirty=1.15GiB
> INFO [11-13|11:36:35.861] Imported new chain segment               blocks=1   txs=367   mgas=58.048   elapsed=884.581ms mgasps=65.622  number=12,612,840 hash=65cdd7..3cc1f3 dirty=1.15GiB
> INFO [11-13|11:36:52.829] Deep froze chain segment                 blocks=19  elapsed=50.869ms  number=12,522,841 hash=e6e56b..004a7e
> INFO [11-13|11:36:59.440] Persisted trie from memory database      nodes=702,198   size=211.34MiB time=11.1714421s gcnodes=1,006,558 gcsize=391.88MiB gctime=6.0110221s  livenodes=2,028,092 livesize=532.30MiB
> INFO [11-13|11:36:59.456] Imported new chain segment               blocks=2   txs=675   mgas=97.801   elapsed=12.917s   mgasps=7.571   number=12,612,842 hash=b127a9..8c5b8f dirty=1.15GiB
> INFO [11-13|11:37:00.579] Imported new chain segment               blocks=1   txs=536   mgas=84.222   elapsed=1.110s    mgasps=75.845  number=12,612,843 hash=3753a4..8c0ef6 dirty=912.90MiB
> INFO [11-13|11:37:01.252] Imported new chain segment               blocks=1   txs=333   mgas=50.559   elapsed=660.448ms mgasps=76.552  number=12,612,844 hash=56e3cc..0e7ca7 dirty=917.27MiB
> INFO [11-13|11:37:03.058] Imported new chain segment               blocks=1   txs=433   mgas=76.962   elapsed=1.795s    mgasps=42.869  number=12,612,845 hash=bcd7e7..4e82e5 dirty=923.71MiB
> INFO [11-13|11:37:03.500] Chain reorg detected                     number=12,612,844 hash=56e3cc..0e7ca7 drop=1 dropfrom=bcd7e7..4e82e5 add=1 addfrom=41d5f5..859514
> INFO [11-13|11:37:03.515] Imported new chain segment               blocks=1   txs=447   mgas=79.811   elapsed=443.946ms mgasps=179.776 number=12,612,845 hash=41d5f5..859514 dirty=923.81MiB
> INFO [11-13|11:37:03.573] Re-queue blocks                          number=12,612,846 hash=0x48b459e1d875c3903dd75de6373847d4eac2bdb6c814eaedad266cef87012e37
> INFO [11-13|11:37:04.347] Imported new chain segment               blocks=1   txs=872   mgas=68.713   elapsed=817.334ms mgasps=84.069  number=12,612,846 hash=48b459..012e37 dirty=930.65MiB  ignored=1
> INFO [11-13|11:37:05.418] Imported new chain segment               blocks=1   txs=375   mgas=69.759   elapsed=1.057s    mgasps=65.943  number=12,612,847 hash=ca195f..f225ad dirty=935.39MiB
> INFO [11-13|11:37:06.552] Imported new chain segment               blocks=1   txs=611   mgas=84.360   elapsed=1.123s    mgasps=75.074  number=12,612,848 hash=df9503..b123d6 dirty=941.36MiB
> INFO [11-13|11:37:07.378] Imported new chain segment               blocks=1   txs=433   mgas=66.146   elapsed=815.282ms mgasps=81.133  number=12,612,849 hash=c24f11..79ca8f dirty=945.43MiB
> INFO [11-13|11:37:13.465] Imported new chain segment               blocks=2   txs=1195  mgas=114.254  elapsed=1.717s    mgasps=66.531  number=12,612,851 hash=ca2c22..0f6adc dirty=950.62MiB  ignored=1
> INFO [11-13|11:37:15.526] Imported new chain segment               blocks=1   txs=582   mgas=76.676   elapsed=1.391s    mgasps=55.105  number=12,612,852 hash=625a34..3a0b4e dirty=956.15MiB
> ```
> 
> Any ideas why this might be happening now?

What is strange your 1 block elapsed takes from 1 to 2 sec, should be in range of 100-300 ms. Looks like a hardware issue for me

**Comment by NullQubit** [comment]
> > Thanks everyone for your insights.
> > I re-downloaded the snapshot from 11 Nov and tried again the whole thing - I was able to sync in 15 hours. I honestly didn't change anything else.
> > The problem now is that I seem to fall behind up to 5 blocks every now and then. When this happens, I stay behind for a few seconds and then sync up to the latest block quickly. This makes my node very unreliable. This is what I see in the logs:
> > ```
> > INFO [11-13|11:36:29.788] Imported new chain segment               blocks=1   txs=317   mgas=50.284   elapsed=904.029ms mgasps=55.622  number=12,612,838 hash=45bd26..d23780 dirty=1.15GiB
> > INFO [11-13|11:36:33.113] Imported new chain segment               blocks=1   txs=528   mgas=84.503   elapsed=1.040s    mgasps=81.251  number=12,612,839 hash=edae3a..70cda0 dirty=1.15GiB
> > INFO [11-13|11:36:35.861] Imported new chain segment               blocks=1   txs=367   mgas=58.048   elapsed=884.581ms mgasps=65.622  number=12,612,840 hash=65cdd7..3cc1f3 dirty=1.15GiB
> > INFO [11-13|11:36:52.829] Deep froze chain segment                 blocks=19  elapsed=50.869ms  number=12,522,841 hash=e6e56b..004a7e
> > INFO [11-13|11:36:59.440] Persisted trie from memory database      nodes=702,198   size=211.34MiB time=11.1714421s gcnodes=1,006,558 gcsize=391.88MiB gctime=6.0110221s  livenodes=2,028,092 livesize=532.30MiB
> > INFO [11-13|11:36:59.456] Imported new chain segment               blocks=2   txs=675   mgas=97.801   elapsed=12.917s   mgasps=7.571   number=12,612,842 hash=b127a9..8c5b8f dirty=1.15GiB
> > INFO [11-13|11:37:00.579] Imported new chain segment               blocks=1   txs=536   mgas=84.222   elapsed=1.110s    mgasps=75.845  number=12,612,843 hash=3753a4..8c0ef6 dirty=912.90MiB
> > INFO [11-13|11:37:01.252] Imported new chain segment               blocks=1   txs=333   mgas=50.559   elapsed=660.448ms mgasps=76.552  number=12,612,844 hash=56e3cc..0e7ca7 dirty=917.27MiB
> > INFO [11-13|11:37:03.058] Imported new chain segment               blocks=1   txs=433   mgas=76.962   elapsed=1.795s    mgasps=42.869  number=12,612,845 hash=bcd7e7..4e82e5 dirty=923.71MiB
> > INFO [11-13|11:37:03.500] Chain reorg detected                     number=12,612,844 hash=56e3cc..0e7ca7 drop=1 dropfrom=bcd7e7..4e82e5 add=1 addfrom=41d5f5..859514
> > INFO [11-13|11:37:03.515] Imported new chain segment               blocks=1   txs=447   mgas=79.811   elapsed=443.946ms mgasps=179.776 number=12,612,845 hash=41d5f5..859514 dirty=923.81MiB
> > INFO [11-13|11:37:03.573] Re-queue blocks                          number=12,612,846 hash=0x48b459e1d875c3903dd75de6373847d4eac2bdb6c814eaedad266cef87012e37
> > INFO [11-13|11:37:04.347] Imported new chain segment               blocks=1   txs=872   mgas=68.713   elapsed=817.334ms mgasps=84.069  number=12,612,846 hash=48b459..012e37 dirty=930.65MiB  ignored=1
> > INFO [11-13|11:37:05.418] Imported new chain segment               blocks=1   txs=375   mgas=69.759   elapsed=1.057s    mgasps=65.943  number=12,612,847 hash=ca195f..f225ad dirty=935.39MiB
> > INFO [11-13|11:37:06.552] Imported new chain segment               blocks=1   txs=611   mgas=84.360   elapsed=1.123s    mgasps=75.074  number=12,612,848 hash=df9503..b123d6 dirty=941.36MiB
> > INFO [11-13|11:37:07.378] Imported new chain segment               blocks=1   txs=433   mgas=66.146   elapsed=815.282ms mgasps=81.133  number=12,612,849 hash=c24f11..79ca8f dirty=945.43MiB
> > INFO [11-13|11:37:13.465] Imported new chain segment               blocks=2   txs=1195  mgas=114.254  elapsed=1.717s    mgasps=66.531  number=12,612,851 hash=ca2c22..0f6adc dirty=950.62MiB  ignored=1
> > INFO [11-13|11:37:15.526] Imported new chain segment               blocks=1   txs=582   mgas=76.676   elapsed=1.391s    mgasps=55.105  number=12,612,852 hash=625a34..3a0b4e dirty=956.15MiB
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any ideas why this might be happening now?
> 
> What is strange your 1 block elapsed takes from 1 to 2 sec, should be in range of 100-300 ms. Looks like a hardware issue for me Try to reduce amount of peers to 30-50 (more peers need more resources) and make sure you're connected to enough peers with net.peerCount

This seems to have worked. I see that now it takes 200-400ms for 1 block, and I'm always synced up to the latest block so far without any slowdowns. I will close this issue if this (hopefully) keeps up for at least a day. Thanks!

**Comment by AwesomeMylaugh** [comment]
which geth Releases you use? v1.1.4 or v1.1.0?

**Comment by NullQubit** [comment]
> which geth Releases you use? v1.1.4 or v1.1.0?

v1.1.4.


Unfortunately it started lagging behind again. I tracked some delay here:

```
INFO [11-15|12:11:54.364] Imported new chain segment               blocks=6  txs=4425  mgas=595.071  elapsed=8.681s    mgasps=68.547   number=12,669,003 hash=8fc90c..e20f0b dirty=1.27GiB
INFO [11-15|12:12:39.583] Deep froze chain segment                 blocks=13 elapsed=54.298ms  number=12,579,003 hash=d4dc8f..7d9d5f
INFO [11-15|12:15:36.648] Downloader queue stats                   receiptTasks=0 blockTasks=58  itemSize=210.76KiB throttle=311
INFO [11-15|12:15:41.158] Imported new chain segment               blocks=2  txs=1188  mgas=199.030  elapsed=4.481s    mgasps=44.410   number=12,669,005 hash=a0f982..3232d1 age=4m34s    dirty=1.28GiB
INFO [11-15|12:15:50.595] Imported new chain segment
```

But I don't know what could be causing it. I guess I will just retry on AWS (There's nothing better offered at Azure hardware-wise).

**Comment by izidorit** [comment]
It happens to me also, some block delay when this `Downloader queue stats` appears, but I don't know what does it mean. But after that node cathes up quickly

**Comment by dvdsim711** [comment]
Same issue. issue start a week ago. I ran the upgrade to v1.1.4 but no difference. is it possible that the current network congestion is to blame?

**Comment by mcoelho80** [comment]
> @philzeh
> 
> what specs is your snapshot node running? if you are using AWS what instance type is it?

Dell R420 with 192Gb RAM, 24 cores and a 4Tb NVME drive. Internet Speed is 1.4Gbps.

**Comment by Fillicia** [comment]
Can confirm this is not an hardware issue. I could sync pretty much any node (ETH, Polygon, even solana)  but BSC never worked. Between all the manually downloaded snapshot that ended up beeing corrupted to the lack of available nodes when you try to sync from scratch, I'm honestly wondering if someone actually synced a new node lately.

**Comment by dvdsim711** [comment]
Upgrading to 1.1.5 and setting "--diffsync" helps a bit. 
The node still falls behind every 10 minutes or so then sync's for 4-5 minutes to get back in sync.

**Comment by DryDragon10** [comment]
> Can confirm this is not an hardware issue. I could sync pretty much any node (ETH, Polygon, even solana) but BSC never worked. Between all the manually downloaded snapshot that ended up beeing corrupted to the lack of available nodes when you try to sync from scratch, I'm honestly wondering if someone actually synced a new node lately.

Good point. Seems old one can sync but not the new ones

**Comment by psdlt** [comment]
@Fillicia I have no issues catching up to latest block from genesis. Did finish syncing a new node yesterday, took around 16 hours to go from genesis to latest block. AWS `i3en.12xlarge`, `RAID0`, standard config (except `max_peers` set to 2000).

**Comment by NullQubit** [comment]
> @Fillicia I have no issues catching up to latest block from genesis. Did finish syncing a new node yesterday, took around 16 hours to go from genesis to latest block. AWS `i3en.12xlarge`, `RAID0`, standard config (except `max_peers` set to 2000).

And it stays synced without lagging behind every now and then? May I ask which region your node is located in?

**Comment by NullQubit** [comment]
I've upgraded to 1.1.5, set-up a node on US east, set max-peers to 400 and it's been working flawlessly since yesterday (Always up-to-date, no lags).

Amazing!

Closing this issue.

**Comment by updatesvc** [comment]
> I've upgraded to 1.1.5, set-up a node on US east, set max-peers to 400 and it's been working flawlessly since yesterday (Always up-to-date, no lags).
> 
> Amazing!
> 
> Closing this issue.

What instance did you use on AWS

**Comment by NullQubit** [comment]
> > I've upgraded to 1.1.5, set-up a node on US east, set max-peers to 400 and it's been working flawlessly since yesterday (Always up-to-date, no lags).
> > Amazing!
> > Closing this issue.
> 
> What instance did you use on AWS

It's not on AWS, it's on Azure.

I'm using a Standard D96ds_v5 (96 vcpus, 384 GiB memory). It's running in the temporary storage disk (local ssd, 3.6 TB available). The pricing is quite high (3,600 euro per month) but this thing doesn't even flinch. Max disk usage is ~40% at spikes.

**Comment by updatesvc** [comment]
Damn that's alot, you can checkout hetzner - was able to sync on AX61 even with gen3 nvme (about 100$/month)
was asking since I have AWS credits laying around😂

**Comment by NullQubit** [comment]
> Damn that's alot, you can checkout hetzner - was able to sync on AX61 even with gen3 nvme (about 100$/month) was asking since I have AWS credits laying around😂

I'll check it out, thanks!

**Comment by DryDragon10** [comment]
> I've upgraded to 1.1.5, set-up a node on US east, set max-peers to 400 and it's been working flawlessly since yesterday (Always up-to-date, no lags).
> 
> Amazing!
> 
> Closing this issue.

I'm out of sync a few blocks every few mins when there are lots of rpc calls. How about your node when there are rpc calls?
