### ISSUE TITLE
A large number of error messages appear:err="execution reverted: Multicall2 aggregate: call failed"

### ISSUE THREAD

**Issue by Along-WG** [binance-chain/bsc#540]
#### System information

Geth version: ` 1.1.4 `
OS & Version: Linux
Commit hash : 

oldnum=12,573,872 
oldhash=0x3bfd8d92227f5a830565833d3a91e22e3a5cb829449e31f5b11061633c8dfb5b 
newnum=12,573,872 
newhash=0x3bfd8d92227f5a830565833d3a91e22e3a5cb829449e31f5b11061633c8dfb5b
![image](https://user-images.githubusercontent.com/25116220/141601217-9299182c-7712-4d68-85c3-dd98ddc248d9.png)

#### Actual behaviour
My node was synchronizing the block, but there were a lot of error messages, and then the synchronization of the block slowed down

#### Backtrace
Start the command
````
/data/bsc/server/geth_linux --config /data/bsc/server/config.toml --datadir /data/bsc/data-seed --cache 30720  --rpc.allow-unprotected-txs --txlookuplimit 0
````

When submitting logs: please submit them as text and not screenshots.

**Comment by Along-WG** [comment]
My node configuration:
16 vCPU    32GiB    2TB SSD     100 MB

**Comment by zhongfu** [comment]
there's someone or something making a lot of `eth_call`s to your node's rpc endpoint, you'll probably have to figure out what that is and stop it for the time being

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
