### ISSUE TITLE
Can not run bsc node

### ISSUE THREAD

**Issue by 2019jack** [binance-chain/bsc#541]

**Comment by 2019jack** [comment]
./geth_linux --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0
INFO [11-13|05:30:41.282] Starting Geth on Ethereum mainnet...
INFO [11-13|05:30:41.288] Maximum peer count                       ETH=30 LES=0 total=30
WARN [11-13|05:30:41.288] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable


until it has been stuck here, there is no next step to run

**Comment by seonggwonyoon** [comment]
In my opinion, this is not stuck, it is normal.
You just need to read the log file set in config.toml Under "[Node.LogConfig]"

tail -f LOGFILE.log

**Comment by 2019jack** [comment]
ok, thanks
