### ISSUE TITLE
Nodes without save blocks

### ISSUE THREAD

**Issue by heipacker** [binance-chain/bsc#542]
# Rationale

Why should this feature exist?
What are the use-cases?
i just need get transaction and then execute in our business

# Implementation

Can i do a situation where i don't need to store blocks, or save the last 10000 blocks, because I don't want to consume too many disks, let alone maintain them regularly

Do you have ideas regarding the implementation of this feature?
This needs to be understood globally. Personally, I don't know enough about the global node, so I need to discuss it

Are you willing to implement this feature?
may need more guidance

**Comment by litebarb** [comment]
> # Rationale
> Why should this feature exist? What are the use-cases? i just need get transaction and then execute in our business
> 
> # Implementation
> Can i do a situation where i don't need to store blocks, or save the last 10000 blocks, because I don't want to consume too many disks, let alone maintain them regularly
> 
> Do you have ideas regarding the implementation of this feature? This needs to be understood globally. Personally, I don't know enough about the global node, so I need to discuss it
> 
> Are you willing to implement this feature? may need more guidance

I think what you are refering to is sort of like a 'light' node.  I too am running out of space to maintain a full node as I only have 1TB of ssd, does the community have any ideas?

**Comment by heipacker** [comment]
I'm not sure whether the light node can meet my requirements. My demand scenario is to execute all transactions and get all the information of the transaction. I don't need anything else, so I want to save only the data of the recently specified block

**Comment by heipacker** [comment]
Because the block data occupies too much disk, compression will also increase the operation and maintenance cost

**Comment by KeefeL** [comment]
This maybe a better choice #568

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
