### ISSUE TITLE
Imported new chain segment elapsed value is too high

### ISSUE THREAD

**Issue by izidorit** [binance-chain/bsc#544]
Hi everyone! I was having the ~100blocks backlog issue some days earlier, snapshot helped me, to sync. But what now I see, despite the fact, that the hardware is a beast:
```
512GB memory (8*64GB)
Intel(R) Xeon(R) W-2295 CPU @ 3.00GHz 32core
SAMSUNG MZQL23T8HCLS-00A07 3.5T nvme0n1
Geth/v1.1.4
```
Our clients experience big latency when there are bigger number of transactions in a block, it takes for seconds, which cause delays for our clients, which is a big business impact for us. 
Does anyone have a tip how to dedicate more resource to the GETH to reduce the elapsed time?
Some examples of small blocks:
```
Imported new chain segment               blocks=1  txs=0    mgas=0.000   elapsed=38.080ms    mgasps=0.000   number=12,639,461 hash=c29f2a..a8a04d dirty=336.47MiB
Imported new chain segment               blocks=1  txs=1    mgas=0.100   elapsed=4.683ms   mgasps=21.418  number=12,639,439 hash=3d6e45..101e74 dirty=187.53MiB
Imported new chain segment               blocks=1  txs=3    mgas=0.273   elapsed=5.558ms     mgasps=49.106  number=12,639,443 hash=05ac43..de6b87 dirty=204.28MiB
```
elapsed time is good. But when bigger blocks are comming:
```
Imported new chain segment               blocks=2  txs=1667 mgas=122.774 elapsed=1.582s    mgasps=77.596  number=12,639,440 hash=36542c..1d55b7 dirty=169.46MiB  ignored=2
Imported new chain segment               blocks=1  txs=603  mgas=85.444  elapsed=912.136ms   mgasps=93.675  number=12,639,466 hash=54c21b..ab380c dirty=388.93MiB
Imported new chain segment               blocks=1  txs=563  mgas=85.781  elapsed=1.121s      mgasps=76.508  number=12,639,471 hash=885656..59c080 dirty=428.46MiB
```
Relevand section of current config of geth is (from command line switches only --snapshot=false):
```
[Eth]
SyncMode = "fast"
NetworkId = 56
DisablePeerTxBroadcast = true
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 5000000000000
TrieCleanCache = 256
TrieDirtyCache = 256
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""
DatabaseCache = 10240

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
```

Thanks for the ideas and tips in advance, it's a pain in the *ss :\

**Comment by TehnobitSystems** [comment]
The same problem is with me and many guys. This is already a global problem, but the developers are not responding.

**Comment by hbtj123** [comment]
Hello All, 

Looking for a developer who can solve this is issue. Tried all the possible solution, but the blocks are delaying. Anyone here having any working solutin here?? In the past 1 week i am searching for someone but apparently no one can help!
However capable to solve i am okay to pay just send me a direct message!

**Comment by guagualvcha** [comment]
Please refer to https://github.com/binance-chain/bsc/issues/502

**Comment by guagualvcha** [comment]
From your logs, I think the performance is not bad. `mgasps`  is above 50..  The issue of your case may be the networking, try update the `StaticNodes` in the config.toml,  the the latest release: https://github.com/binance-chain/bsc/releases/download/v1.1.5/mainnet.zip have provides some different peers.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
