### ISSUE TITLE
Bad discv5 packet, invalid packet header

### ISSUE THREAD

**Issue by aisthetes** [binance-chain/bsc#546]
Trying to run a light node (v 1.1.4), example:
`geth_linux --http --http.addr 0.0.0.0 --http.port 8545 --syncmode light --allow-insecure-unlock --http.api eth,web3,personal`
and get many records like this: Bad discv5 packet id=0000000000000000 addr=18.205.198.231:30303  err="invalid packet header", what is wrong?

**Comment by Zaczero** [comment]
-> `addr=18.205.198.231:30303` -> `:30303` (ETH network port, not BSC)

It looks like you are not using the `config.toml` file which contains the proper configuration for you to connect with the BSC network. By default, you will try to connect with the ETH network nodes that are not compatible with the BSC fork of geth.

To get the node working you can follow the official guidelines here:
https://github.com/binance-chain/bsc#a-full-node-on-the-rialto-test-network

PS.
Good luck

**Comment by aisthetes** [comment]
now: lvl=info msg="Looking for peers" peercount=0 tried=25 static=25
