### ISSUE TITLE
Standard gas price just increased

### ISSUE THREAD

**Issue by billyadelphia** [binance-chain/bsc#551]
Based on this https://bscgas.info/ all of the sudden, the standard gas price just increased to 16 GWEI.
But why ?
Does it often happened ?
Because my Dapp just suddenly doesn't work. 
The hash is generated, but it just stuck and not found on bscscan. 
![gasPrice](https://user-images.githubusercontent.com/20699349/141984738-be56995d-1221-4989-9405-dfd3964e820d.PNG)

**Comment by dgdeivid** [comment]
This is not problem of BSC if problem of BSCscan. Right now it has a delay of 30 seconds (Time it takes to index the transactions in BSCscan) but I have seen it even with a delay of 2 hours from when a transaction is executed until it is shown in BSC scan.

**Comment by ratthakorn2509** [comment]
Ratthakorn99@gmail.com

**Comment by guagualvcha** [comment]
`The hash is generated, but it just stuck and not found on bscscan.` May happens when network is congested. The network has a limited tx pool, and transactions been dropped when the number of pending transaction exceed the size.
