### ISSUE TITLE
Failed to prune state

### ISSUE THREAD

**Issue by overload-ak** [binance-chain/bsc#556]
#### System information

Geth version: `1.1.4`
OS & Version:  ubuntu  
Commit hash : 541028a68a26dc1d0828b144626e8d064ac9d0b6db1ad499700ec6f62559c336

#### Expected behaviour
Compacting database   

#### Actual behaviour
INFO [11-17|04:38:55.336] Iterating state snapshot                 accounts=50,905,071 slots=562,456,750 elapsed=24m16.062s  eta=10m42.986s
INFO [11-17|04:39:03.336] Iterating state snapshot                 accounts=50,905,071 slots=563,854,559 elapsed=24m24.062s  eta=10m46.517s
INFO [11-17|04:39:11.337] Iterating state snapshot                 accounts=50,905,071 slots=565,981,980 elapsed=24m32.062s  eta=10m50.05s
ERROR[11-17|04:39:15.713] Failed to prune state                    err="invalid subroot(path b1a7f6a34c37e8b87f5d87a2b6c97bcceebbfda557eb3a65d7604ffebca5b430), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 6000caac227acb071bb787c787d6c795ee05a7c2292f37cb08b200c947f2e855"
invalid subroot(path b1a7f6a34c37e8b87f5d87a2b6c97bcceebbfda557eb3a65d7604ffebca5b430), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 6000caac227acb071bb787c787d6c795ee05a7c2292f37cb08b200c947f2e855

#### Steps to reproduce the behaviour
docker stop bsc-mainnet -t 120
nohup sudo geth --datadir ~/bsc/node snapshot prune-state > prune.log 2>&1 &
#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by overload-ak** [comment]
![image](https://user-images.githubusercontent.com/39258960/142142679-4c145018-cab1-4bf2-b01d-ba0c31000375.png)
I think I stopped the chain gracefully.

**Comment by fa-advise** [comment]
1.1.5 - same

**Comment by favealo** [comment]
Reactivate it

**Comment by overload-ak** [comment]
> Reactivate it

@favealo  It's no use

**Comment by dgdeivid** [comment]
Same problem here.

`INFO [11-26|14:25:17.295] Iterating state snapshot                 accounts=0 slots=0 elapsed="199.88µs"
INFO [11-26|14:25:25.295] Iterating state snapshot                 accounts=162,959 slots=1,427,461 elapsed=8.000s     eta=59m28.36s
INFO [11-26|14:25:33.296] Iterating state snapshot                 accounts=438,114 slots=3,191,259 elapsed=16.000s    eta=44m6.28s
INFO [11-26|14:25:41.296] Iterating state snapshot                 accounts=714,197 slots=4,592,242 elapsed=24.000s    eta=40m26.437s
INFO [11-26|14:25:49.296] Iterating state snapshot                 accounts=893,630 slots=7,993,076 elapsed=32.001s    eta=42m59.516s
INFO [11-26|14:25:57.296] Iterating state snapshot                 accounts=1,166,193 slots=10,143,591 elapsed=40.001s    eta=41m2.178s
ERROR[11-26|14:26:01.470] Failed to prune state                    err="invalid subroot(path 0499bbbabdbbd6061294e666a92077dc7ad4a890142a2345416b7bc467388ecc), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 77062efddd4dd69573535271ff8fbf291fcbccb2e9487f5fd42088916f0a0b2d"
invalid subroot(path 0499bbbabdbbd6061294e666a92077dc7ad4a890142a2345416b7bc467388ecc), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 77062efddd4dd69573535271ff8fbf291fcbccb2e9487f5fd42088916f0a0b2d
`

**Comment by updatesvc** [comment]
I solved mine by doing this:
Firstly my original geth command for syncing had --snapshot=false
and got the error 

`failed to open snapshot tree err="head doesn't match snapshot:`

I changed the command to` --snapshot=true` and let it run for a while (30mins)
Then  shut down Ctrl + C once for graceful shutdown

Then snapshot is now prunning

**Comment by guagualvcha** [comment]
FYI: https://github.com/ethereum/go-ethereum/issues/23613
The data is corrupt, a simple way is to start the node with `--snapshot=false`, run for few hours and then do prune again,
