### ISSUE TITLE
有交流群吗？能否创建一个？

### ISSUE THREAD

**Issue by baijiahei888** [binance-chain/bsc#558]
有交流群吗？能否创建一个？

**Comment by myuniswap2000** [comment]
https://t.me/joinchat/BHakxl2HJkswNmVl

**Comment by BinanceG11** [comment]
BSC Node Operator(TG) : https://t.me/c/1269469310/2133

**Comment by guagualvcha** [comment]
closing this, please goto  https://t.me/c/1269469310/2133
