### ISSUE TITLE
net.peercount cant go more than 100

### ISSUE THREAD

**Issue by berktaylan** [binance-chain/bsc#560]
Hello
`[Node.P2P]
MaxPeers = 300
`
MaxPeers setted for 300 at config, but when i check from console
net.peercount
>100
is the maximum i can see than while.
( Node still syncing not sure might be related to this or not )

**Comment by blackerhot** [comment]
trying to exceed to 10k+

**Comment by berktaylan** [comment]
@blackerhot sorry ?

**Comment by psdlt** [comment]
@berktaylan Don't ask "why" as I don't know the reason, but I noticed that `admin.peers.length` is always ~1/3 of `MaxPeers` setting. So if you want to have more peers - set your `MaxPeers` to 400 or 500 or 1000...

**Comment by blackerhot** [comment]
> @blackerhot sorry ?

yeah for my config. It reached to around 500 for me. I set it as 30k. but 1-10k should be fine

**Comment by berktaylan** [comment]
> @berktaylan Don't ask "why" as I don't know the reason, but I noticed that `admin.peers.length` is always ~1/3 of `MaxPeers` setting. So if you want to have more peers - set your `MaxPeers` to 400 or 500 or 1000...

Thanks, worked.
