### ISSUE TITLE
"Persisted trie from memory database" error in log and node becomes more than 1 minute out of sync

### ISSUE THREAD

**Issue by daica75** [binance-chain/bsc#561]
I am finding that my node is sometimes getting out of sync every 1 or 2 hours with the above error in the bsc.log showing before it becomes about 1 and half minute out of sync.

What is the cause of this error?  Why does it make the node go out of sync?

**Comment by daica75** [comment]
this is what I am seeing in my logs:

t=2021-11-18T01:38:42-0500 lvl=info msg="Persisted trie from memory database"    nodes=7,767,111 size="1.76 GiB" time=2m6.048351171s  gcnodes=12,776,067 gcsize="4.78 GiB" gctime=1m10.860520365s livenodes=2,441,524 livesize="855.78 MiB"
t=2021-11-18T01:38:42-0500 lvl=info msg="Imported new chain segment"             blocks=1   txs=555   mgas=87.351   elapsed=2m7.241s    mgasps=0.686    number=12,744,025 hash=0x7619d74c59c3ac0fcd2c6bee9ff653210f5b1bd354da274e7c972cf1073369b0 age=2m11s   dirty="3.51 GiB"

every hour or 2, the node would be out of sync by a minute or 2, and it would take a minute or so to sync back up again.

The line before it shows in the log that it is out of sync, it says "Persisted trie from memory database"

**Comment by Crypto2** [comment]
That message sounds like it's writing it to disk,  so that could take a bit and probably mutex lock the node while doing it.

**Comment by KeefeL** [comment]
I agree with @Crypto2

**Comment by daica75** [comment]
I am currently using the the Samsung 980 Pro NVME which is a gen 4 NVME and I was using geth 1.1.5 and these logs still happen but less frequent now.  I just upgraded to geth 1.1.6 and will see how it goes.

**Comment by KeefeL** [comment]
I think raising the trieTimeout value may solve your problem.

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
