### ISSUE TITLE
Sync just more and more slow!!!!!

### ISSUE THREAD

**Issue by arayalways** [binance-chain/bsc#563]
#### System information

Geth version: `geth v1.1.5`
OS & Version: Linux
Commit hash : 

#### Expected behaviour
Hundreds issues which 80% of them is synced problems. BSC guys just can't solve this little problem????

![image](https://user-images.githubusercontent.com/80883646/142353265-c2429354-e507-4ed3-8cee-e03d5fbfb9e3.png)

When I found my node is a bit slow and just update to v1.1.5, it did not catch up but much more slow.  Now it is lagged for over 5 hours and I believe it will be more in the future. What's wrong with BSC? If you can not handle this throughput then don't !

**Comment by vae520283995** [comment]
same issue

**Comment by havsar** [comment]
We created a Telegram group for BSC Node discussions, feel free to join and share experience https://t.me/joinchat/zXCza2tQN0tjYzM0

**Comment by 1106035348** [comment]
Maddening problem

**Comment by blackerhot** [comment]
I sync up really slow when I download snap shot and resync . but when I synce from 0 chain data. its really fast.
there is a bug some where

**Comment by xcuocao** [comment]
> I sync up really slow when I download snap shot and resync . but when I synce from 0 chain data. its really fast. there is a bug some where

Did you success to setup the node from Zero?

**Comment by vietthang207** [comment]
I also have a lots of problems with v1.1.5. v1.1.5 suppose to have 50-60% better syncing performance, but somehow my 1.1.5 nodes run out of sync more frequent than 1.1.4 nodes. v1.1.4 is by no mean a stable release, but at least it works most of the time.

**Comment by guagualvcha** [comment]
Reference: https://github.com/binance-chain/bsc/issues/502

**Comment by guagualvcha** [comment]
> I also have a lots of problems with v1.1.5. v1.1.5 suppose to have 50-60% better syncing performance, but somehow my 1.1.5 nodes run out of sync more frequent than 1.1.4 nodes. v1.1.4 is by no mean a stable release, but at least it works most of the time.

Does your node enable `diffsync`?

**Comment by guagualvcha** [comment]
@arayalways  Please check https://github.com/binance-chain/bsc/issues/502,  it is possible the node did not enable `diffsync` since the log shows it is doing full sync, and try prune the node.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
