### ISSUE TITLE
command to start bsc node with snapshot

### ISSUE THREAD

**Issue by lokeshratnam09** [binance-chain/bsc#565]
After downloading snapshot from bsc node. then what is the command to start the geth node through snapshot to get node synced and how much time does it takes .  please help me.

**Comment by updatesvc** [comment]
This is what i used, pasted my guide below from [here ](https://github.com/binance-chain/bsc/issues/545#issuecomment-971661245)

=================================================================
i finally synced seemed the two biggest bottlenecks are CPU and IOPS (Actual sync time about 20hrs)
Hardware Used : 

- Hetzner AX61 (128 gb ram AMD Ryzen™ 9 3900 12-Core ) 
- 2 x 1.92 TB raid 0
- Got unlucky with gen3 nvme but still synced

Process:

- download geth 1.1.5 and make it executable , optionally move it /usr/local/bin/geth
- download mainnet.zip and unzip
- generate genesis using command below, will also create a mainnet folder for blockchain data
`./geth_linux --datadir mainnet init genesis.json`
- download the  14 nov 2021 snapshot
- extract snapshot
- move snapshot data to mainnet folder
```
rm -rf mainnet/geth/chaindata
rm -rf mainnet/geth/triecache
mv server/data-seed/geth/chaindata mainnet/geth/chaindata
mv server/data-seed/geth/triecache mainnet/geth/triecache
```

Actual sync process:
[Optional] Open config.toml and delete the Node Log section, just useful for getting logs straight on the terminal or just use tail to look at the logs

[Optional] Create a service or use **screen** to run the command below, so it doesn't stop if you are using SSH,
I used **screen**

Run 
`screen `
then press enter, (anytime you lose connection via ssh, run screen -r to get back the "screen/terminal" where geth was running

### Geth Command
`geth --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=false --diffsync`

### Might be very Important 

- keep maxpeers at around 100
- syncmode full, I used fast in other servers, never synced
- snapshot false, means you won't be providing snapshots to other people, you can change it to true once you have synced and have a good server
- diffsync not sure if this helped, but probably did

**Comment by vishal2241** [comment]
Cant we simply replace the whole /mainnet/geth folder with server/data-seed/geth folder on a fresh installation.

**Comment by updatesvc** [comment]
I think it will be fine, though I just stuck with the official snapshot instructions, just in case 😂😂
I actually thought about it, I just didn't want to wait a whole day to find out my syncing didn't work.

**Comment by BinanceG11** [comment]
For BSC nodes related discussion, please join us here : https://t.me/c/1269469310/2133

**Comment by vietthang207** [comment]
> This is what i used, pasted my guide below from [here ](https://github.com/binance-chain/bsc/issues/545#issuecomment-971661245)
> 
> ================================================================= i finally synced seemed the two biggest bottlenecks are CPU and IOPS (Actual sync time about 20hrs) Hardware Used :
> 
> * Hetzner AX61 (128 gb ram AMD Ryzen™ 9 3900 12-Core )
> * 2 x 1.92 TB raid 0
> * Got unlucky with gen3 nvme but still synced
> 
> Process:
> 
> * download geth 1.1.5 and make it executable , optionally move it /usr/local/bin/geth
> * download mainnet.zip and unzip
> * generate genesis using command below, will also create a mainnet folder for blockchain data
>   `./geth_linux --datadir mainnet init genesis.json`
> * download the  14 nov 2021 snapshot
> * extract snapshot
> * move snapshot data to mainnet folder
> 
> ```
> rm -rf mainnet/geth/chaindata
> rm -rf mainnet/geth/triecache
> mv server/data-seed/geth/chaindata mainnet/geth/chaindata
> mv server/data-seed/geth/triecache mainnet/geth/triecache
> ```
> 
> Actual sync process: [Optional] Open config.toml and delete the Node Log section, just useful for getting logs straight on the terminal or just use tail to look at the logs
> 
> [Optional] Create a service or use **screen** to run the command below, so it doesn't stop if you are using SSH, I used **screen**
> 
> Run `screen ` then press enter, (anytime you lose connection via ssh, run screen -r to get back the "screen/terminal" where geth was running
> 
> ### Geth Command
> `geth --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=false --diffsync`
> 
> ### Might be very Important
> * keep maxpeers at around 100
> * syncmode full, I used fast in other servers, never synced
> * snapshot false, means you won't be providing snapshots to other people, you can change it to true once you have synced and have a good server
> * diffsync not sure if this helped, but probably did

I believe that once you set snapshot=false, change it to true has no effect, it gonna show some error like this
```Nov 17 10:55:34 kynode-geth-bsc-05 geth[5319]: WARN [11-17|10:55:34.896] Failed to load snapshot, regenerating    err="head doesn't match snapshot: have 0x8b23495b11680c95703a1d1b12081be9d0438d9bbc0c8670de716c5532a52fb1, want 0x93622fd5e4408209bbe8d0b7adb266abb236842f4a34b1ebf350178bb8b00f3f"```
This is also happened on all clients based on geth.
I think this is just a minor issue because you always want to disable snapshot anyway to save disk IO.

**Comment by hbtj123** [comment]
> For BSC nodes related discussion, please join us here : https://t.me/c/1269469310/2133

unable to join only private members!

**Comment by havsar** [comment]
We created a Telegram group for BSC Node discussions, feel free to join and share experience https://t.me/joinchat/zXCza2tQN0tjYzM0

**Comment by elnem0** [comment]
> 
> 
> This is what i used, pasted my guide below from [here ](https://github.com/binance-chain/bsc/issues/545#issuecomment-971661245)
> 
> ================================================================= i finally synced seemed the two biggest bottlenecks are CPU and IOPS (Actual sync time about 20hrs) Hardware Used :
> 
>     * Hetzner AX61 (128 gb ram AMD Ryzen™ 9 3900 12-Core )
> 
>     * 2 x 1.92 TB raid 0
> 
>     * Got unlucky with gen3 nvme but still synced
> 
> 
> Process:
> 
>     * download geth 1.1.5 and make it executable , optionally move it /usr/local/bin/geth
> 
>     * download mainnet.zip and unzip
> 
>     * generate genesis using command below, will also create a mainnet folder for blockchain data
>       `./geth_linux --datadir mainnet init genesis.json`
> 
>     * download the  14 nov 2021 snapshot
> 
>     * extract snapshot
> 
>     * move snapshot data to mainnet folder
> 
> 
> ```
> rm -rf mainnet/geth/chaindata
> rm -rf mainnet/geth/triecache
> mv server/data-seed/geth/chaindata mainnet/geth/chaindata
> mv server/data-seed/geth/triecache mainnet/geth/triecache
> ```
> 
> Actual sync process: [Optional] Open config.toml and delete the Node Log section, just useful for getting logs straight on the terminal or just use tail to look at the logs
> 
> [Optional] Create a service or use **screen** to run the command below, so it doesn't stop if you are using SSH, I used **screen**
> 
> Run `screen ` then press enter, (anytime you lose connection via ssh, run screen -r to get back the "screen/terminal" where geth was running
> ### Geth Command
> 
> `geth --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=false --diffsync`
> ### Might be very Important
> 
>     * keep maxpeers at around 100
> 
>     * syncmode full, I used fast in other servers, never synced
> 
>     * snapshot false, means you won't be providing snapshots to other people, you can change it to true once you have synced and have a good server
> 
>     * diffsync not sure if this helped, but probably did

How long did it take you to sync with full syncmode?

**Comment by updatesvc** [comment]
@elnem0 
under 20hrs using both **syncmode full** and **the snapshot**

**Comment by DreamLxq** [comment]
永远不会同步完的，即使你修改参数！

**Comment by ankneo** [comment]
> @elnem0 under 20hrs using both **syncmode full** and **the snapshot**

You mean with the 14th Nov snapshot? Did you see any ill effects of having the snapshot param set to false?

**Comment by updatesvc** [comment]
> 

So far, no side effects

**Comment by izidorit** [comment]
it took me 17 hours to sync from 19th nov. snapshot starting yesterday (2021.11.21)

**Comment by ankneo** [comment]
> it took me 17 hours to sync from 19th nov. snapshot starting yesterday (2021.11.21)

Can you please share the exact config.toml, machine specs and the command used?

**Comment by thehood1** [comment]
Guys, please help. I am losing my mind with syncing process.

Hardware:
AMD Ryzen 7 3800X 8-Core , 32GB RAM , Kingston M.2 NVMe 2TB SNVS/2000G NV1 Series(could not find IOPS for this hard disk) , 200Mbps / 80Mbps internet speed

On this NVMe disk I installed Ubuntu 20.04.3, downloaded geth_linux 1.1.5 , mainnet.zip 1.1.5. I downloaded 19th November snapshot, unpack it and start syncing 20h ago

Command line:
`./geth --config config.toml --datadir /data/bsc/node --cache 16000 --txlookuplimit 0 --http --maxpeers 100 --snapshot=true --diffsync`

config.toml:
All default values, only added DisablePeerTxBroadcast = false and DiscoveryV5 = true

Hard disk usage  - disk read values between 15k and 100k: 

![image](https://user-images.githubusercontent.com/94331274/142920410-81aa3abb-58f4-4f98-92a2-43f6b3be8aca.png)cpu and ram usage:  CPU 153% - What is this????? 



![image](https://user-images.githubusercontent.com/94331274/142920158-0d04b4ae-fdcd-4756-9a0d-8e197de3b9c8.png)




Elpsed time always around 10s...mgasps between 10 and 80, average 40

![image](https://user-images.githubusercontent.com/94331274/142918789-843a5838-0024-48e9-80fa-5381b1e6e1a1.png)

Very slow syncing, current data size 1.1TB, and still 2days behind...will this ever end? Any advice,please? Any way to speed up?

**Comment by lokeshratnam09** [comment]
By using this command 
nohup ./geth_linux --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --allow-insecure-unlock --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=false --diffsync &
it takes more than 3 days and still in syncing process and i also used snapshot.
so why its not synced..??
having any ideas to anyone please share to helped me to get node synced.
Thank you .

**Comment by lokeshratnam09** [comment]
Can I use  --syncmode=fast instead of  --syncmode=full  by using snapshot ??. because by using  --syncmode=full  it takes more than 3 days and still in syncing process...

**Comment by MarryamZulfiqar** [comment]
> Can I use --syncmode=fast instead of --syncmode=full by using snapshot ??. because by using --syncmode=full it takes more than 3 days and still in syncing process...

yes you can give it a try.

**Comment by lokeshratnam09** [comment]
> it took me 17 hours to sync from 19th nov. snapshot starting yesterday (2021.11.21)
@izidorit please  kindly share your command  to start the sync node through snapshot. 
please share hopefully its help for me.

**Comment by lokeshratnam09** [comment]
> @elnem0 under 20hrs using both **syncmode full** and **the snapshot**

@elnem0  please share your geth commands to start sync node through snapshot.
because  i am using   this command -   ./geth_linux --config ./config.toml --datadir ./mainnet --cache 100000 --rpc.allow-unprotected-txs --allow-insecure-unlock --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=full --snapshot=false --diffsync
completed 4 days but still on syncing not fully synced.
so please help with your commands hopefully its help for me .
Thank You

**Comment by webdevsmart** [comment]
could anyone please provide full doc for installing node?

**Comment by KeefeL** [comment]
Follow the guide here https://docs.binance.org/smart-chain/developer/fullnode.html, and you can get some tips from #502

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
