### ISSUE TITLE
BEP-721 aren't picked up properly by BSCScan, shown as BEP-20

### ISSUE THREAD

**Issue by SergeiInyushkin** [binance-chain/bsc#567]
The token type BEP-721 is properly seen in transaction: https://bscscan.com/tx/0x61b83b25b799912f7aaeeb8de6df7fc3125e1dc9c3153ea8c7f98e0232af8e19

But if we open the token contract it shows BEP-20 instead, and no information on transfers:
https://bscscan.com/token/0xd4f517f82a56a14dcb040d0c2d5257bab36c2475

**Comment by havsar** [comment]
I don't think this is directly related to the chain node itself.

**Comment by guagualvcha** [comment]
hi @SergeiInyushkin  Please feedback to the community of bscscan , I will close this.
