### ISSUE TITLE
Port 8545 not open to remote

### ISSUE THREAD

**Issue by mutobui** [binance-chain/bsc#571]
This is my command:

/usr/local/bin/geth --config /home/ubuntu/work/mainnet/config.toml --datadir /home/ubuntu/work/mainnet/node --syncmode snap --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcport "8545" --rpcapi "db, eth, net, web3, personal" --ws --ws.port "8546" --ws.addr "127.0.0.1" --ws.origins "*" --ws.api "web3, eth" --cache 72000 --maxpeers=100 --rpc.allow-unprotected-txs --txlookuplimit 0 --rpcvhosts=*

However port 8545 is not open to access remote

<img width="705" alt="Screen Shot 2021-11-19 at 22 50 09" src="https://user-images.githubusercontent.com/67900234/142651602-d216a030-3e3e-4209-bdb7-6469b038afc5.png">

**Comment by TehnobitSystems** [comment]
not use port settings in CLI, change settings in config file
