### ISSUE TITLE
Sync is very slow!!!

### ISSUE THREAD

**Issue by AwesomeMylaugh** [binance-chain/bsc#572]
cpu:16 core
memory:32 G
disk: nvme ssd 16K IOPS
geth:v1.1.5

start order: geth --config ./config.toml --datadir /data/server/data-seed/  --cache 20000 --rpc.allow-unprotected-txs --syncmode snap --diffsync --txlookuplimit 0

sync is very slow,what can i do,how can i do,plz help

![image](https://user-images.githubusercontent.com/48375967/142716781-14f16882-ca9a-4208-b318-88d2154469af.png)

**Comment by xcuocao** [comment]
same here, I cannot improve anything at the moment

**Comment by zhongfu** [comment]
- total space used? (have you pruned recently?)
- 16k IOPS seems rather low for an NVMe SSD, is this a directly-attached disk or a network-attached disk (eg AWS EBS, Azure managed disks, GCP persistent disks?)
  - if you're on a major cloud provider and your data is persistent, there's a significant chance you're actually on a networked disk
- are you (or your host) sharing the disk with anyone else? (you may not be able to tell if that's the case)
- what fs are you using?

**Comment by xcuocao** [comment]
> * total space used? (have you pruned recently?)
> * 16k IOPS seems rather low for an NVMe SSD, is this a directly-attached disk or a network-attached disk (eg AWS EBS, Azure managed disks, GCP persistent disks?)
>   
>   * if you're on a major cloud provider and your data is persistent, there's a significant chance you're actually on a networked disk
> * are you (or your host) sharing the disk with anyone else? (you may not be able to tell if that's the case)
> * what fs are you using?

* 1.9T
* Samsung SSD 970 EVO Plus, directly attached
* Local, no share
* fs is ext4

**Comment by zhongfu** [comment]
> * 1.9T

try pruning the state -- stop geth, then run `geth --datadir=node snapshot prune-state`

(assuming your datadir is `node`, change that if it's elsewhere)

then restart after you're done

**Comment by xcuocao** [comment]
> > * 1.9T
> 
> try pruning the state -- stop geth, then run `geth --datadir=node snapshot prune-state`
> 
> (i'm assuming your datadir is `node`, change that if it's elsewhere)
> 
> then restart after it's done

I am new to setup the node. I downloaded the snapshot data from https://github.com/binance-chain/bsc-snapshots, but my node cannot catch up the network

**Comment by zhongfu** [comment]
> I am new to setup the node. I downloaded the snapshot data from https://github.com/binance-chain/bsc-snapshots, but my node cannot catch up the network

no clue then, though it's weird that your node is already at 1.9T space **used** if you're syncing from a chaindata snapshot -- unless it's been trying to catch up for a long time

my (relatively crappy) consumer hardware works well -- i5-8500, 64GB RAM, 2TB NVMe SSD, xfs; so with the info you've given me so far, i can't tell what's up with your setup

another shot in the dark: it might be worth dropping the MaxPeers setting to something more reasonable (maybe 30-50) if you've adjusted it upwards -- i'm guessing that having a ton of peers trying to download state trie entries (plus block headers/bodies etc) from your node might be creating a bunch of i/o contention between syncing and serving data. and even if it doesn't, it's not like increasing MaxPeers to a ludicrous number would help

**Comment by xcuocao** [comment]
> > I am new to setup the node. I downloaded the snapshot data from https://github.com/binance-chain/bsc-snapshots, but my node cannot catch up the network
> 
> no clue then, though it's weird that your node is already at 1.9T space **used** if you're syncing from a chaindata snapshot -- unless it's been trying to catch up for a long time
> 
> my (relatively crappy) consumer hardware works well -- i5-8500, 64GB RAM, 2TB NVMe SSD, xfs; so with the info you've given me so far, i can't tell what's up with your setup
> 
> another shot in the dark: it might be worth dropping the MaxPeers setting to something more reasonable (maybe 30-50) if you've adjusted it upwards -- i'm guessing that having a ton of peers trying to download state trie entries (plus block headers/bodies etc) from your node might be creating a bunch of i/o contention between syncing and serving data. and even if it doesn't, it's not like increasing MaxPeers to a ludicrous number would help

'MaxPeers' is 100. 
`msg="Imported new block receipts"    count=2`
count is 2 or 3. 'age' behinds 2 days. It never reaches the mainnet.

**Comment by zhongfu** [comment]
> 'MaxPeers' is 100. `msg="Imported new block receipts" count=2` count is 2 or 3. 'age' behinds 2 days. It never reaches the mainnet.

it sounds like you may have untarred the chaindata snapshot to the wrong place; can you confirm that you've untarred it to `node/geth/chaindata`, and not `node/geth/chaindata/chaindata` or somewhere else?

**Comment by xcuocao** [comment]
> > 'MaxPeers' is 100. `msg="Imported new block receipts" count=2` count is 2 or 3. 'age' behinds 2 days. It never reaches the mainnet.
> 
> it sounds like you may have untarred the chaindata snapshot to the wrong place; can you confirm that you've untarred it to `node/geth/chaindata`, and not `node/geth/chaindata/chaindata` or somewhere else?

I removed the old chaindata
```
rm -rf node/geth/chaindata
mv server/data-seed/geth/chaindata node/geth/chaindata
mv server/data-seed/geth/triecache node/geth/triecache
```

**Comment by cellname** [comment]
vCPUs：32
Memory (GiB)：128
IOPS:16000
900MB/s

start order:/home/ubuntu/bsc/bsc/build/bin/geth --config /home/ubuntu/bsc/config.toml --datadir /home/ubuntu/bsc/bsc/node --gcmode archive --allow-insecure-unlock --pprof.addr 0.0.0.0 --metrics --pprof --diffsync --snapshot=false

the height behind more than 10000,and Growing 
![image](https://user-images.githubusercontent.com/50346972/142745502-df0c801c-5485-4477-a01a-8fadaac2f42e.png)

**Comment by cellname** [comment]
node version:geth:v1.1.5

**Comment by guagualvcha** [comment]
> vCPUs：32 Memory (GiB)：128 IOPS:16000 900MB/s
> 
> start order:/home/ubuntu/bsc/bsc/build/bin/geth --config /home/ubuntu/bsc/config.toml --datadir /home/ubuntu/bsc/bsc/node --gcmode archive --allow-insecure-unlock --pprof.addr 0.0.0.0 --metrics --pprof --diffsync --snapshot=false
> 
> the height behind more than 10000,and Growing ![image](https://user-images.githubusercontent.com/50346972/142745502-df0c801c-5485-4477-a01a-8fadaac2f42e.png)

It is strongly suggested to enable the snapshot, it will greatly impact the performance!

**Comment by guagualvcha** [comment]
> vCPUs：32 Memory (GiB)：128 IOPS:16000 900MB/s
> 
> start order:/home/ubuntu/bsc/bsc/build/bin/geth --config /home/ubuntu/bsc/config.toml --datadir /home/ubuntu/bsc/bsc/node --gcmode archive --allow-insecure-unlock --pprof.addr 0.0.0.0 --metrics --pprof --diffsync --snapshot=false
> 
> the height behind more than 10000,and Growing ![image](https://user-images.githubusercontent.com/50346972/142745502-df0c801c-5485-4477-a01a-8fadaac2f42e.png)

ok. Looks like you are running an archive node. LevelDB performance is very poor when the data size increase to TB. You need to split your archive node and use a proxy in front to route request. There's a guy already doing that, you can take a look here: https://github.com/allada/bsc-archive-snapshot/

**Comment by AwesomeMylaugh** [comment]
I can not prune the state,it report an error.

I dont know how to fix it.

The disk total space used is up to 1.7T

![image](https://user-images.githubusercontent.com/48375967/142758359-bc12ef61-14e3-458f-9bcd-30afcf5cf7d4.png)

**Comment by zhongfu** [comment]
> I can not prune the state,it report an error.

have you ever disabled state snapshots (e.g. with `--snapshot=false`)? if yes, then turn them back on again

do you have `Generating state snapshot`, or any other mention of `state snapshot` in your logs? they should show up quite frequently if your node doesn't have a complete state snapshot yet -- if that's the case, you'll need to wait until that's done

another possibility is that your state snapshot is corrupted, in which case you'd need to start geth back up again and let it regenerate the state snapshot

you will need a complete state snapshot in order to use `snapshot prune-state`

**Comment by izidorit** [comment]
I downloaded 19th of November snapshot, loaded in yesterday, restarted 18:21:24 and finished sync at12:13:40, took more than 17 hours. And started with --snapshot=false syncmode is "snap". I'm able to sync, but it always fell out of sync when requests are comming in :\

**Comment by AwesomeMylaugh** [comment]
@guagualvcha How to improve mgasps?

here is my file,plz check
[profile_60s.gz](https://github.com/binance-chain/bsc/files/7585445/profile_60s.gz)

**Comment by uniftyitadmin** [comment]
Hello, i am also getting slow sync when using snapshot.

![bsc](https://user-images.githubusercontent.com/91486835/143165670-b1898b69-8b6e-43cd-a997-5148fb7206fd.png)

Firstly, i tried to sync it from the genesis block, never succeeded. "elapsed" value was fast then (in milliseconds). Now, i downloaded latest snapshot (19 November) but "elapsed" value is much more higher (in seconds). 

Geth version:1.1.5. (added --diffsync on start command)
HW: 12 x AMD Ryzen 7 3700X , 48 GB RAM, Intel® SSD D3-S4510 (bsc node was working for a few months before on the same HW)

Also, one more problem, my node not getting highest block.

eth.isSyncing shows:
{
  currentBlock: 12807492,
  highestBlock: 12906505,
  knownStates: 297473485,
  pulledStates: 297473485,
  startingBlock: 12806605
}

Highest block (regarding BSCScan) is 12906979 at the moment. To get highest again i must restart geth service and thats just temporarily  (naturally, new blocks are added every few seconds). Highestblock value not getting updated with rest of the network.

config.toml and geth.service files are attached here:
[geth.service.txt](https://github.com/binance-chain/bsc/files/7592534/geth.service.txt)
[config.toml.txt](https://github.com/binance-chain/bsc/files/7592543/config.toml.txt)

**Comment by zhongfu** [comment]
@uniftyitadmin

hardware that was sufficient a few months before might not cut it now -- block gas limit has increased at least twice in the past few months iirc

and naturally, blocks will take longer to process now (compared to at the beginning of the chain) bc block gas limit has went up along with block utilization %


also, while you can technically run a node with a SATA drive, it's not really recommended because it'll only get harder and harder to catch up and sync requests

and indeed, your node is syncing faster than new blocks are being produced -- you would, in theory, need to be doing at least 33Mgas/s to keep up (but in practice, more than that), but that's less than the speed at which your node is processing blocks (60+Mgas/s)

but because you're using slow(er) storage, you're only syncing blocks 2x as fast as they're being produced. If you extrapolate a little, you'll still need to sync for nearly 4 more days before you can catch up

(also re highestBlock: that doesn't matter for now. when your node catches up to chain head, highestBlock will likely match what you see on bscscan)

**Comment by uniftyitadmin** [comment]
Thanks for you reply @zhongfu . So you suggest to run it on stronger hardware?

**Comment by zhongfu** [comment]
@uniftyitadmin yeah, you'd probably want to swap out the SSD for a decent NVMe one

**Comment by uniftyitadmin** [comment]
Great, what filesystem is the best to use? I am currently running it on ext4.

**Comment by zhongfu** [comment]
not sure -- I'm personally using xfs (with blocksize and sectorsize increased to at least 4096) but I reckon ext4 should be good too

**Comment by KeefeL** [comment]
It seems the same to #563 , I'm going to close this one.
