### ISSUE TITLE
Imported new states entries > bsc total tx, but still not synced ?

### ISSUE THREAD

**Issue by berktaylan** [binance-chain/bsc#575]
Hello,

I got a node which syncing almost than a week now , i was expecting it to be synced when new states entries > total bsc tx count, but somehow its still not synced. Any idea ?

`eretry=0  duplicate=218 unexpected=1713
t=2021-11-22T11:38:40+0000 lvl=info msg="Imported new state entries"             count=571  elapsed=3.937ms      processed=1,870,505,174 pending=172,924 trieretry=197  coderetry=0  duplicate=218 unexpected=1713
t=2021-11-22T11:38:40+0000 lvl=info msg="Imported new state entries"             count=384  elapsed=2.667ms      processed=1,870,505,558 pending=172,920 trieretry=0    coderetry=0  duplicate=218 unexpected=1713
t=2021-11-22T11:38:41+0000 lvl=info msg="Imported new block headers"             count=1    elapsed="563.397µs"  number=12,861,131 hash=0xddab3d46c4e9861e98ef5efec4a03fc7795fed07e38b75cdf40aed2f65185988
t=2021-11-22T11:38:41+0000 lvl=info msg="Imported new state entries"             count=384  elapsed="199.874µs"  processed=1,870,505,942 pending=173,370 trieretry=0    coderetry=0  duplicate=218 unexpected=1713
`

**Comment by berktaylan** [comment]
any idea anyone ?

**Comment by xcuocao** [comment]
> any idea anyone ?

Use snapshot data.

**Comment by psdlt** [comment]
@berktaylan if your node haven't caught up in a week, it will never catch up. Try syncing from snapshot (https://github.com/binance-chain/bsc-snapshots) or read through other issues, there are at least a couple of large threads with plenty of tips on what to do.

**Comment by realuncle** [comment]
> @berktaylan if your node haven't caught up in a week, it will never catch up. Try syncing from snapshot (https://github.com/binance-chain/bsc-snapshots) or read through other issues, there are at least a couple of large threads with plenty of tips on what to do.

Agree.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
