### ISSUE TITLE
panic: deletion not supported

### ISSUE THREAD

**Issue by wssll789** [binance-chain/bsc#576]
#### System information

Geth version: `1.1.5-8ff7d531-20211116`
OS & Version: centos7
Commit hash : (if `develop`)

panic: deletion not supported

goroutine 139237 [running]:
github.com/ethereum/go-ethereum/trie.(*StackTrie).TryUpdate(0xc8948d1110, 0xc8da82aa80, 0x20, 0x20, 0x28ba550, 0x0, 0x0, 0xca8d963698, 0xc90f4bfa80)
	github.com/ethereum/go-ethereum/trie/stacktrie.go:194 +0xd2
github.com/ethereum/go-ethereum/trie.(*StackTrie).Update(0xc8948d1110, 0xc8da82aa80, 0x20, 0x20, 0x28ba550, 0x0, 0x0)
	github.com/ethereum/go-ethereum/trie/stacktrie.go:201 +0x77
github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).processStorageResponse(0xc6f6dba780, 0xc85418f380)
	github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:1928 +0x3f4
github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).Sync(0xc6f6dba780, 0x30d54e247db8e406, 0x61b73884981166d0, 0x9a8183df351c5ce, 0x17ab8dd28ccb6d5e, 0xca304ae180, 0x0, 0x0)
	github.com/ethereum/go-ethereum/eth/protocols/snap/sync.go:653 +0xc2e
github.com/ethereum/go-ethereum/eth/downloader.(*stateSync).run(0xc6c2f28e60)
	github.com/ethereum/go-ethereum/eth/downloader/statesync.go:318 +0x87
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).runStateSync
	github.com/ethereum/go-ethereum/eth/downloader/statesync.go:114 +0x1ef

**Comment by smartins** [comment]
Getting this as well with snap sync, seems to be the culprit

**Comment by DefiDebauchery** [comment]
If you restart it, you'll continue further before hitting it again. I think I ended up with 10 such hiccups -- all relatively early on -- before it began to process mostly without issue (until hitting one snag around block 8272940.. still processing, so will continue to note any others)

**Comment by gomes7997** [comment]
Having the same problem. After multiple restarts the problem worsened and the node is no longer making sync progress. If snap sync was working it would really improve the syncing problems on BSC. So far diffsync has not improved sync times for my node.

**Comment by karalabe** [comment]
FYI https://github.com/ethereum/go-ethereum/pull/23960

**Comment by gituser** [comment]
+1 on this, any update on this issue?

**Comment by KeefeL** [comment]
Fixed by #667, please wait for next release.
