### ISSUE TITLE
err="the method miner_start does not exist/is not available"

### ISSUE THREAD

**Issue by pinswap** [binance-chain/bsc#580]
geth version 1.1.5

How to avoid this error

t=2021-11-23T15:50:27+0800 lvl=warn msg="Served miner_setEtherbase"           conn=195.123.222.16:52612 reqid=1 t="8.11µs"                 err="the method miner_setEtherbase does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:27+0800 lvl=warn msg="Served miner_setEtherbase"           conn=195.123.222.16:52612 reqid=1 t="6.606µs"                err="the method miner_setEtherbase does not exist/is not available"
t=2021-11-23T15:50:28+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:36046 reqid=1 t="7.077µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:28+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:36046 reqid=1 t="5.547µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:50:28+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:44626 reqid=1 t="4.812µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:28+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:44626 reqid=1 t="3.786µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:50:29+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:52480 reqid=1 t="5.325µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:29+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:52480 reqid=1 t="4.219µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:50:30+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:60306 reqid=1 t="5.296µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:30+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:60306 reqid=1 t="4.108µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:50:30+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:39318 reqid=1 t="6.081µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:30+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:39318 reqid=1 t="4.311µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:50:31+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:48404 reqid=1 t="5.551µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:31+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:48404 reqid=1 t="4.371µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:50:55+0800 lvl=warn msg="Served parity_netPeers"              conn=193.56.29.33:34018   reqid=3 t="6.027µs"                err="the method parity_netPeers does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:55+0800 lvl=warn msg="Served parity_netPeers"              conn=193.56.29.33:34018   reqid=3 t="4.588µs"                err="the method parity_netPeers does not exist/is not available"
t=2021-11-23T15:50:55+0800 lvl=warn msg="Served admin_peers"                  conn=193.56.29.33:34014   reqid=3 t="3.889µs"                err="the method admin_peers does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:50:55+0800 lvl=warn msg="Served admin_peers"                  conn=193.56.29.33:34014   reqid=3 t="2.96µs"                 err="the method admin_peers does not exist/is not available"
t=2021-11-23T15:51:18+0800 lvl=info msg="Imported new chain segment"          blocks=2 txs=717  mgas=99.106  elapsed=1m6.783s mgasps=1.484  number=12,812,031 hash=0x4920bf7b8b7e5cc02a2fc4b37a7b277b82b19bde86b7145e3a1d72dad423cf03 age=2d13h54m dirty="32.03 MiB"
t=2021-11-23T15:51:25+0800 lvl=warn msg="Served miner_setEtherbase"           conn=195.123.222.16:49808 reqid=1 t="6.792µs"                err="the method miner_setEtherbase does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:25+0800 lvl=warn msg="Served miner_setEtherbase"           conn=195.123.222.16:49808 reqid=1 t="5.133µs"                err="the method miner_setEtherbase does not exist/is not available"
t=2021-11-23T15:51:25+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:56854 reqid=1 t="5.344µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:25+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:56854 reqid=1 t="3.787µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:51:26+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:36510 reqid=1 t="4.719µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:26+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:36510 reqid=1 t="3.673µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:51:27+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:45772 reqid=1 t="6.618µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:27+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:45772 reqid=1 t="5.251µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:51:27+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:54712 reqid=1 t="5.277µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:27+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:54712 reqid=1 t="3.745µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:51:28+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:35380 reqid=1 t="6.996µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:28+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:35380 reqid=1 t="5.586µs"                err="the method miner_start does not exist/is not available"
t=2021-11-23T15:51:29+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:44014 reqid=1 t="7.431µs"                err="the method miner_start does not exist/is not available" X-Forwarded-For=nil
t=2021-11-23T15:51:29+0800 lvl=warn msg="Served miner_start"                  conn=195.123.222.16:44014 reqid=1 t="6.326µs"                err="the method miner_start does not exist/is not available"

**Comment by seonggwonyoon** [comment]
This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).

**Comment by acswap** [comment]
> This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> 
> e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`

Can I use this to prevent other people from making RPC calls

--nodiscover

**Comment by masayil** [comment]
> > This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> > e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`
> 
> Can I use this to prevent other people from making RPC calls
> 
> --nodiscover

Nope.

**Comment by acswap** [comment]
> > > This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> > > e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`
> > 
> > 
> > Can I use this to prevent other people from making RPC calls
> > --nodiscover
> 
> Nope.

Why not? What's wrong with that？

**Comment by masayil** [comment]
> > > > This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> > > > e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`
> > > 
> > > 
> > > Can I use this to prevent other people from making RPC calls
> > > --nodiscover
> > 
> > 
> > Nope.
> 
> Why not? What's wrong with that？

--nodiscover                        Disables the peer discovery mechanism (manual peer addition)

**Comment by acswap** [comment]
> > > > > This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> > > > > e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`
> > > > 
> > > > 
> > > > Can I use this to prevent other people from making RPC calls
> > > > --nodiscover
> > > 
> > > 
> > > Nope.
> > 
> > 
> > Why not? What's wrong with that？
> 
> --nodiscover Disables the peer discovery mechanism (manual peer addition). Your node will not find peer nodes if add --nodiscover Please set up a firewall. e.g. Block IP iptables -A INPUT -s 195.123.222.16 -j DROP

I banned one IP and then the next, and then the next, and it's kind of a bottomless pit

**Comment by seonggwonyoon** [comment]
> > > > > > This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> > > > > > e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`
> > > > > 
> > > > > 
> > > > > Can I use this to prevent other people from making RPC calls
> > > > > --nodiscover
> > > > 
> > > > 
> > > > Nope.
> > > 
> > > 
> > > Why not? What's wrong with that？
> > 
> > 
> > --nodiscover Disables the peer discovery mechanism (manual peer addition). Your node will not find peer nodes if add --nodiscover Please set up a firewall. e.g. Block IP iptables -A INPUT -s 195.123.222.16 -j DROP
> 
> I banned one IP and then the next, and then the next, and it's kind of a bottomless pit Two IP addresses are currently disabled

There are many ways to resolve this issue.
This is just an example.
If you running on cloud, you only need to allow internal IP through security group configuration.
If you're using bare metal, you can add Http authentication using a reverse proxy before geth rpc.

**Comment by acswap** [comment]
> > > > > > > This is solved by allowing only the internal IP or blocking the IP because someone is sending an rpc call to your BSC Node ( miner_start, miner_setEtherbase).
> > > > > > > e.g. Block IP `iptables -A INPUT -s 195.123.222.16 -j DROP`
> > > > > > 
> > > > > > 
> > > > > > Can I use this to prevent other people from making RPC calls
> > > > > > --nodiscover
> > > > > 
> > > > > 
> > > > > Nope.
> > > > 
> > > > 
> > > > Why not? What's wrong with that？
> > > 
> > > 
> > > --nodiscover Disables the peer discovery mechanism (manual peer addition). Your node will not find peer nodes if add --nodiscover Please set up a firewall. e.g. Block IP iptables -A INPUT -s 195.123.222.16 -j DROP
> > 
> > 
> > I banned one IP and then the next, and then the next, and it's kind of a bottomless pit Two IP addresses are currently disabled
> 
> There are many ways to resolve this issue. This is just an example. If you running on cloud, you only need to allow internal IP through security group configuration. If you're using bare metal, you can add Http authentication using a reverse proxy before geth rpc.

These are not the main ones, I am more concerned with the configuration of the primary node server. Because synchronization nodes are a real headache.
Any suggestions? My current configuration looks like this

c5d.4xlarge  
ebs gp3  2000GiB IOPS 8K 250MB/S

**Comment by realuncle** [comment]
You just need disable the external access to your RPC service.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
