### ISSUE TITLE
Cant prune state - Failed to load head block

### ISSUE THREAD

**Issue by berktaylan** [binance-chain/bsc#586]
I have 3 different node synced ( from snapshot ) , but i cant prune state any of them

`ERROR[11-24|08:05:23.709] Failed to open snapshot tree             err="Failed to load head block"
`

**Comment by realuncle** [comment]
hi @berktaylan  Does the node been gracefully shutdown?  

If not, you may start the node again and let it sync up to latest height and gracefully shutdown again.

**Comment by berktaylan** [comment]
hi @realuncle 

this is my systemctl status when i stop geth service
`Nov 24 09:55:58 ip-172-31-43-75 systemd[1]: Stopping Ethereum go client...
Nov 24 09:56:27 ip-172-31-43-75 systemd[1]: Stopped Ethereum go client.
`
And bsc.log

`t=2021-11-24T09:56:20+0000 lvl=info msg="Writing snapshot state to disk"        root=0x88f6b45f5759e095c2f2150664c517b54660b4633d74de76f83bd68a377e71b6
t=2021-11-24T09:56:20+0000 lvl=info msg="Persisted trie from memory database"   nodes=0         size="0.00 B"     time="2.371µs"      gcnodes=0         gcsize="0.00 B"      gctime=0s            livenodes=1,716,649 livesize="671.44 MiB"
t=2021-11-24T09:56:20+0000 lvl=eror msg="Dangling trie nodes after full cleanup"
t=2021-11-24T09:56:20+0000 lvl=info msg="Writing clean trie cache to disk"       path=/data/node/geth/triecache threads=16
t=2021-11-24T09:56:22+0000 lvl=info msg="Persisted the clean trie cache"         path=/data/node/geth/triecache elapsed=1.785s
t=2021-11-24T09:56:22+0000 lvl=info msg="Blockchain stopped"
`

I think its shutdown gracefully, isnt it ?

And here is my shutdown settings for systemctl 
`KillMode=process
KillSignal=SIGINT
`

**Comment by KeefeL** [comment]
> 

Yes, it has already graceful shutdown, are you still has this prune problem?

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
