### ISSUE TITLE
Dirty over 5Gb ?

### ISSUE THREAD

**Issue by DryDragon10** [binance-chain/bsc#589]
The dirty database is always over 5Gb, is that normal?

**Comment by guagualvcha** [comment]
what is the value of `--cache` when you start the node?

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.

**Comment by BinanceG11** [comment]
For any additional and support please proceed to join us : https://discord.com/invite/YPDsUqcwR8
