### ISSUE TITLE
State Sync in progress for too long

### ISSUE THREAD

**Issue by Hailiebaby16** [binance-chain/bsc#593]
State Heal in progress for almost 2 days. Does the Downloader Queue have something to do with it.

Because it was throttled too low.

 msg="Downloader queue stats"                 receiptTasks=0 blockTasks=0 itemSize="938.10 KiB"  throttle=70

**Comment by RumeelHussainbnb** [comment]
on which node you are facing issue?

Archive node or full node?

**Comment by ssl-serg** [comment]
In my case I have "State Heal in progress" for about 2 weeks !

**Comment by Hailiebaby16** [comment]
> In my case I have "State Heal in progress" for about 2 weeks !

I think that wont synced anymore

**Comment by RumeelHussainbnb** [comment]
> > on which node you are facing issue?
> > Archive node or full node?
> 
> BSC full node

Here are the tips for running a BSC full node
https://github.com/binance-chain/bsc/issues/502

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
