### ISSUE TITLE
Archive node synchronization

### ISSUE THREAD

**Issue by wbqlove** [binance-chain/bsc#595]
Development requires me to run an archive node. Currently, I have synchronized 12T of data, but it is always hundreds of thousands of blocks away from the main network node. It always stops synchronization by itself. It seems that I can never catch up. Please help.

**Comment by kgcdream2019** [comment]
You need to update your hardware feature, 
it is important to use local SSD for your archive node.
you can use aws i3 series.

**Comment by guagualvcha** [comment]
@wbqlove hi, so far it requires really really really good hardware to run archive nodes. I don't suggest personal develop to run an archive node, try use service of professional provider.

**Comment by guagualvcha** [comment]
closing this, since duplicated one. check https://github.com/binance-chain/bsc/issues/340
