### ISSUE TITLE
Newbie question about the snapshot directory

### ISSUE THREAD

**Issue by newbie715** [binance-chain/bsc#596]
I'm sorry if this is gonna be a silly question. I'm very new to linux, trying my best to learn. So i'm trying to create a Full Node in a recommended server. I have one question regarding the snapshot directory. ie., after downloading the latest bsc snapshot, where should i extract? in my case i have installed geth on /home/bsc/. So should  i place the downloaded tar file on /home/bsc/ and extract it there itself? thanks in advance.

One more question, as my server is in Europe, i have downloaded the EU endpoint file. Is that correct?

**Comment by xcuocao** [comment]
`after downloading the latest bsc snapshot, where should i extract?`
anywhere you want.
` in my case i have installed geth on /home/bsc/. So should i place the downloaded tar file on /home/bsc/ and extract it there itself? thanks in advance.`
just replace dowloaded data to your local folder. Refer step 3 here: https://github.com/binance-chain/bsc-snapshots
`One more question, as my server is in Europe, i have downloaded the EU endpoint file. Is that correct?`
Any endpoint you want, but if the server is near your node, the download speed better

**Comment by newbie715** [comment]
> 
> ` in my case i have installed geth on /home/bsc/. So should i place the downloaded tar file on /home/bsc/ and extract it there itself? thanks in advance.` ------> just replace dowloaded data to your local folder. Refer to step 3 here: https://github.com/binance-chain/bsc-snapshots.
> 


Thank you very much.. one last check.. kindly check if the following cmd is correct as per my directory..

mv server/data-seed/geth/chaindata /home/bsc/geth/chaindata; mv server/data-seed/geth/triecache /home/bsc/geth/triecache

**Comment by xcuocao** [comment]
Remove/backup the old chaindata first. Now you should check the chaindata folder: /home/bsc/node/geth/chaindata or /home/bsc/node/geth/chaindata/chaindata?

**Comment by newbie715** [comment]
> Remove/backup the old chaindata first. Now you should check the chaindata folder: /home/bsc/node/geth/chaindata or /home/bsc/node/geth/chaindata/chaindata?

Once again thank you very much for your response. 
I'm afraid if I messed it up. These are the things I had done:
- before replacing the data from downloaded snapshot to local, I already started running the geth command (starting full node). 
- then after your msg yesterday I stopped the script using kill PID. Then replaced the data using the mv cmd which I have mentioned in my prev msg. Then I again started running the full node using **geth --config ./config.toml --datadir ./node --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0**
- Now the script is running for around 8 hrs (btw I didn't remove /backup the old chain data yet). Can you kindly tell me what should I do now? I'm really sorry for these questions. I'm very new to linux. 
-

**Comment by xcuocao** [comment]
> > Remove/backup the old chaindata first. Now you should check the chaindata folder: /home/bsc/node/geth/chaindata or /home/bsc/node/geth/chaindata/chaindata?
> 
> Once again thank you very much for your response. I'm afraid if I messed it up. These are the things I had done:
> 
> * before replacing the data from downloaded snapshot to local, I already started running the geth command (starting full node).
> * then after your msg yesterday I stopped the script using kill PID. Then replaced the data using the mv cmd which I have mentioned in my prev msg. Then I again started running the full node using **geth --config ./config.toml --datadir ./node --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0**
> * Now the script is running for around 8 hrs (btw I didn't remove /backup the old chain data yet). Can you kindly tell me what should I do now? I'm really sorry for these questions. I'm very new to linux.

Please check your chaindata location.
* (1) /home/bsc/node/geth/chaindata ----> correct
* (2) /home/bsc/node/geth/chaindata/chaindata ---> incorrect

if (2), please change to (1) then start your node

**Comment by newbie715** [comment]
> > > Remove/backup the old chaindata first. Now you should check the chaindata folder: /home/bsc/node/geth/chaindata or /home/bsc/node/geth/chaindata/chaindata?
> > 
> > 
> > Once again thank you very much for your response. I'm afraid if I messed it up. These are the things I had done:
> > 
> > * before replacing the data from downloaded snapshot to local, I already started running the geth command (starting full node).
> > * then after your msg yesterday I stopped the script using kill PID. Then replaced the data using the mv cmd which I have mentioned in my prev msg. Then I again started running the full node using **geth --config ./config.toml --datadir ./node --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0**
> > * Now the script is running for around 8 hrs (btw I didn't remove /backup the old chain data yet). Can you kindly tell me what should I do now? I'm really sorry for these questions. I'm very new to linux.
> 
> Please check your chaindata location.
> 
> * (1) /home/bsc/node/geth/chaindata ----> correct
> * (2) /home/bsc/node/geth/chaindata/chaindata ---> incorrect
> 
> if (2), please change to (1) then start your node

Both the above directories are there. When i ran "ll" command, its showing logs on both. But date i can see is Nov 27 on /home/bsc/node/geth/chaindata , and Nov 22 on /home/bsc/node/geth/chaindata/chaindata. So i'm assuming chaindata location is correct.

Please check the following image n lemme know: 

![1d](https://user-images.githubusercontent.com/95102272/143684806-526cfdd7-55a6-4b82-9b3d-b1395711b291.png)

**Comment by xcuocao** [comment]
- (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
- Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).

So, you should:
* Remove (1): 
* Move (2) to (1):  
mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
rm -rf /home/bsc/node/geth/chaindata
mv /home/bsc/chaindata /home/bsc/node/geth/chaindata

**Comment by newbie715** [comment]
> * (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
> * Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).
> 
> So, you should:
> 
> * Remove (1)
> * Move (2) to (1)
>   mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
>   rm -rf /home/bsc/node/geth/chaindata
>   mv /home/bsc/chaindata /home/bsc/node/geth/chaindata

Thanks much, Understood :)

**Comment by newbie715** [comment]
> * (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
> * Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).
> 
> So, you should:
> 
> * Remove (1)
> * Move (2) to (1)
>   mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
>   rm -rf /home/bsc/node/geth/chaindata
>   mv /home/bsc/chaindata /home/bsc/node/geth/chaindata

![WhatsApp Image 2021-11-28 at 3 07 11 PM](https://user-images.githubusercontent.com/95102272/143762896-c657ea9b-ccb4-48e8-b9f7-0a8b2c9bbb7f.jpeg)

This is the log i'm getting now. Is it synced? By running eth.syncing, sometimes its showing 'false', while sometimes its showing block numbers. (you can see the above pic). And in the log, i'm getting "block 1" most of the times, but sometimes its going random like block 3, block 14 etc., 

Also do i have to change the config.toml settings? bcos initially i used Maxpeers in Node.p2p as 20. And remaining settings, i have used as per this following page:
https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node

Thanks in advance once again.

**Comment by xcuocao** [comment]
> > * (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
> > * Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).
> > 
> > So, you should:
> > 
> > * Remove (1)
> > * Move (2) to (1)
> >   mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
> >   rm -rf /home/bsc/node/geth/chaindata
> >   mv /home/bsc/chaindata /home/bsc/node/geth/chaindata
> 
> ![WhatsApp Image 2021-11-28 at 3 07 11 PM](https://user-images.githubusercontent.com/95102272/143762896-c657ea9b-ccb4-48e8-b9f7-0a8b2c9bbb7f.jpeg)
> 
> This is the log i'm getting now. Is it synced? By running eth.syncing, sometimes its showing 'false', while sometimes its showing block numbers. (you can see the above pic). And in the log, i'm getting "block 1" most of the times, but sometimes its going random like block 3, block 14 etc.,
> 
> Also do i have to change the config.toml settings? bcos initially i used Maxpeers in Node.p2p as 20. And remaining settings, i have used as per this following page: https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node
> 
> Thanks in advance once again.

Synced but unstable. Blocks=1 all the time is good, means your node got synced.

**Comment by newbie715** [comment]
> > > * (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
> > > * Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).
> > > 
> > > So, you should:
> > > 
> > > * Remove (1)
> > > * Move (2) to (1)
> > >   mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
> > >   rm -rf /home/bsc/node/geth/chaindata
> > >   mv /home/bsc/chaindata /home/bsc/node/geth/chaindata
> > 
> > 
> > ![WhatsApp Image 2021-11-28 at 3 07 11 PM](https://user-images.githubusercontent.com/95102272/143762896-c657ea9b-ccb4-48e8-b9f7-0a8b2c9bbb7f.jpeg)
> > This is the log i'm getting now. Is it synced? By running eth.syncing, sometimes its showing 'false', while sometimes its showing block numbers. (you can see the above pic). And in the log, i'm getting "block 1" most of the times, but sometimes its going random like block 3, block 14 etc.,
> > Also do i have to change the config.toml settings? bcos initially i used Maxpeers in Node.p2p as 20. And remaining settings, i have used as per this following page: https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node
> > Thanks in advance once again.
> 
> Synced but unstable. Blocks=1 all the time is good, means your node got synced.

Thanks. Btw in config.toml settings, I have Maxpeers as 25. I'm currently using the server with following config: AMD ryzen 9 3900 12 core, 128gb ddr4 ecc, 2*2TB nvme SSD.

Can you recommend MaxPeers value that I can use for my server? On doing research, most people are using between 300 to 1000. Currently my value is just at 25. 

Also if I wanna change the settings or wanna do some small changes, can I stop the full node script n resume in few mins? It won't affect syncing right? I mean it ll eventually sync soon even after those small breaks right?

**Comment by xcuocao** [comment]
> > > > * (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
> > > > * Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).
> > > > 
> > > > So, you should:
> > > > 
> > > > * Remove (1)
> > > > * Move (2) to (1)
> > > >   mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
> > > >   rm -rf /home/bsc/node/geth/chaindata
> > > >   mv /home/bsc/chaindata /home/bsc/node/geth/chaindata
> > > 
> > > 
> > > ![WhatsApp Image 2021-11-28 at 3 07 11 PM](https://user-images.githubusercontent.com/95102272/143762896-c657ea9b-ccb4-48e8-b9f7-0a8b2c9bbb7f.jpeg)
> > > This is the log i'm getting now. Is it synced? By running eth.syncing, sometimes its showing 'false', while sometimes its showing block numbers. (you can see the above pic). And in the log, i'm getting "block 1" most of the times, but sometimes its going random like block 3, block 14 etc.,
> > > Also do i have to change the config.toml settings? bcos initially i used Maxpeers in Node.p2p as 20. And remaining settings, i have used as per this following page: https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node
> > > Thanks in advance once again.
> > 
> > 
> > Synced but unstable. Blocks=1 all the time is good, means your node got synced.
> 
> Thanks. Btw in config.toml settings, I have Maxpeers as 25. I'm currently using the server with following config: AMD ryzen 9 3900 12 core, 128gb ddr4 ecc, 2*2TB nvme SSD.
> 
> Can you recommend MaxPeers value that I can use for my server? On doing research, most people are using between 300 to 1000. Currently my value is just at 25.
> 
> Also if I wanna change the settings or wanna do some small changes, can I stop the full node script n resume in few mins? It won't affect syncing right? I mean it ll eventually sync soon even after those small breaks right?

I am using the default value (30).

Sure you can stop your node, modify the settings and start again. Please use command 'pkill -INT geth' to safe kill your node.

**Comment by newbie715** [comment]
> > > > > * (2) is your fault. You should remove/backup the old chaindata first and then move the downloaded data to replace.
> > > > > * Current (1) is your 8 hours sync. You may never got synced with this data. So I prefer you delete it and use the downloaded data (2).
> > > > > 
> > > > > So, you should:
> > > > > 
> > > > > * Remove (1)
> > > > > * Move (2) to (1)
> > > > >   mv /home/bsc/node/geth/chaindata/chaindata /home/bsc
> > > > >   rm -rf /home/bsc/node/geth/chaindata
> > > > >   mv /home/bsc/chaindata /home/bsc/node/geth/chaindata
> > > > 
> > > > 
> > > > ![WhatsApp Image 2021-11-28 at 3 07 11 PM](https://user-images.githubusercontent.com/95102272/143762896-c657ea9b-ccb4-48e8-b9f7-0a8b2c9bbb7f.jpeg)
> > > > This is the log i'm getting now. Is it synced? By running eth.syncing, sometimes its showing 'false', while sometimes its showing block numbers. (you can see the above pic). And in the log, i'm getting "block 1" most of the times, but sometimes its going random like block 3, block 14 etc.,
> > > > Also do i have to change the config.toml settings? bcos initially i used Maxpeers in Node.p2p as 20. And remaining settings, i have used as per this following page: https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node
> > > > Thanks in advance once again.
> > > 
> > > 
> > > Synced but unstable. Blocks=1 all the time is good, means your node got synced.
> > 
> > 
> > Thanks. Btw in config.toml settings, I have Maxpeers as 25. I'm currently using the server with following config: AMD ryzen 9 3900 12 core, 128gb ddr4 ecc, 2*2TB nvme SSD.
> > Can you recommend MaxPeers value that I can use for my server? On doing research, most people are using between 300 to 1000. Currently my value is just at 25.
> > Also if I wanna change the settings or wanna do some small changes, can I stop the full node script n resume in few mins? It won't affect syncing right? I mean it ll eventually sync soon even after those small breaks right?
> 
> I am using the default value (30).
> 
> Sure you can stop your node, modify the settings and start again. Please use command 'pkill -INT geth' to safe kill your node.

Okay. Thanks bro. Appreciate your kindness and patience for guiding a novice like me. It means a lot.

**Comment by institutodisney** [comment]
> > > > > > * (2) é sua culpa. Você deve remover / fazer backup do chaindata antigo primeiro e, em seguida, mover os dados baixados para substituir.
> > > > > > * Atual (1) é a sua sincronização de 8 horas. Você pode nunca ter sido sincronizado com esses dados. Portanto, prefiro que você exclua e use os dados baixados (2).
> > > > > > 
> > > > > > Então você deveria:
> > > > > > 
> > > > > > * Remover (1)
> > > > > > * Mova (2) para (1) 
> > > > > >   mv / home / bsc / node / geth / chaindata / chaindata / home / bsc 
> > > > > >   rm -rf / home / bsc / node / geth / chaindata 
> > > > > >   mv / home / bsc / chaindata / home / bsc / node / geth / chaindata
> > > > > 
> > > > > 
> > > > > ![Imagem WhatsApp 2021-11-28 às 3 07 11 PM](https://user-images.githubusercontent.com/95102272/143762896-c657ea9b-ccb4-48e8-b9f7-0a8b2c9bbb7f.jpeg)
> > > > > Este é o registro que estou obtendo agora. Está sincronizado? Ao executar o eth.syncing, às vezes mostra 'false', enquanto às vezes mostra números de bloco. (você pode ver a foto acima). E no log, recebo o "bloco 1" na maioria das vezes, mas às vezes fica aleatório, como o bloco 3, bloco 14 etc., 
> > > > > também preciso alterar as configurações de config.toml? bcos inicialmente usei Maxpeers em Node.p2p como 20. E as configurações restantes, usei conforme esta página: [https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart -chain-node](https://www.quicknode.com/guides/infrastructure/how-to-run-a-binance-smart-chain-node) 
> > > > > Agradecemos antecipadamente mais uma vez.
> > > > 
> > > > 
> > > > Sincronizado, mas instável. Blocos = 1 o tempo todo é bom, significa que seu nó foi sincronizado.
> > > 
> > > 
> > > Obrigado. Btw nas configurações config.toml, tenho Maxpeers como 25. Estou usando o servidor com a seguinte configuração: AMD ryzen 9 3900 12 core, 128GB ddr4 ecc, 2 * 2TB nvme SSD. 
> > > Você pode recomendar o valor MaxPeers que posso usar para meu servidor? Ao fazer pesquisas, a maioria das pessoas está usando entre 300 a 1000. Atualmente meu valor é apenas 25. 
> > > Além disso, se eu quiser alterar as configurações ou fazer algumas pequenas alterações, posso interromper o script de nó completo e retomar em alguns minutos? Isso não afetará a sincronização, certo? Quero dizer, ele irá sincronizar em breve, mesmo após aquelas pequenas pausas, certo?
> > 
> > 
> > Estou usando o valor padrão (30).
> > Claro, você pode parar seu nó, modificar as configurações e começar novamente. Use o comando 'pkill -INT geth' para eliminar o seu nó com segurança.
> 
> OK. Obrigado mano. Agradeço sua gentileza e paciência em guiar um novato como eu. Significa muito.

Hello, good night @newbie715, just as you're starting in this world and wanting to learn, but I'm having some problems and there's no one wanting to help me, could you contact me and help me run my node please?

Thanks in advance :)

**Comment by RumeelHussainbnb** [comment]
Hi @institutodisney 
Please join the Discord channel, and discuss your problem there url is mentioned below.

https://discord.gg/WwD37ueF
