### ISSUE TITLE
PLEASE HELP, sync is CATASTROPHICALLY SLOW

### ISSUE THREAD

**Issue by thehood1** [binance-chain/bsc#599]
@guagualvcha @iakisme @ashtenhamilton @DefiDebauchery

System information: Ryzen 8-core, 32GB RAM, nvme 180k IOPS,  200/80 Gbps
Geth version: 1.1.5
OS & Version: Ubuntu Server 20.04.3 LTS
Start command : 
`./geth --config ./config.toml --datadir ./node --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0`

Guys, please help me. I tried everything that is written here...used 4 snapshots that are released in a few last weeks, tried all start commands that others use to sync, changed config file in million ways, xfs and ext4  filesystem, tried this, tried that...and I always get the same result.  Many guys here report that they successfully sync after 12h, 14h, 17h, 24h...I don't get any near last block after 24h. I just can't understand how others manage to sync so fast??? 

 As soon as I start node I get mgasps is between 100 and 200, but this lasts only up to one hour and from that point I get from 10 to 30 mgasps, with very short periods when mgasps is 70-100. Result: syncing stucked.

I checked  how my computer works when mgasps is between 100 and 200:
70% CPU usage , 50% RAM usage , 40k IOPS , 10/3 Gbps...so hardware is not a problem.

Can anybody give any advice about this...how is possible that no one knows how to solve syncing issues???

**Comment by perfectcircle2020** [comment]
@thehood1 the nework now is swimming in an endless amount of transactions, unless you have extraterrestrial hardware I guess we need to wait for the network to cool down, I had perfectly synced nodes 3 days ago, now it been hours I am trying to revive them, but no success.

**Comment by thehood1** [comment]
@perfectcircle2020 

> the nework now is swimming in an endless amount of transactions, unless you have extraterrestrial hardware I guess we need to wait for the network to cool down

I think that hardware is not a problem...CPU, RAM memory or NVME would show overload, in my case it's not the case

**Comment by technologiespro** [comment]
also cannot synchronize for a very long time(>1w), installed raid 0 with 2xNVME 2Tb on the new server to improve the speed x2, but I still cannot complete the synchronization

- RAM 64Gb ECC
- HDD SSD 2x2TB NVME on Raid 0
- CPU Intel® Xeon® Gold 6338 (32 cores)
- LAN NIC 1 Gbit/s

Has anyone finished syncing?

**Comment by ko0f** [comment]
This has nothing to do with hardware, it's an issue of block propagation. Other nodes lag too, you can't catch up if your connected peers are out of sync as well.

**Comment by thehood1** [comment]
> you can't catch up if your connected peers are out of sync as well.
@ko0f
This is the main question...how is possible that some of us can easily sync, and some of us can't at all?  Why someone always gets good peers and someone doesn't? What is the cause of this big difference? 

I had 20 fresh starts...reinstalled Linux, new snapshots, tried different commands, etc.... and I always get the same result ( after some time syncing I get 20-30 mgasps in average, impossible to sync )    

It is very strange that I never get good peers, and on the other hand there are guys here that don't have syncing problems...this is not logical.

**Comment by BrokedTV** [comment]
With 1.1.5 and the snapshot i synced in 20h and it has been running fine for almost 10 days now

**Comment by KeefeL** [comment]
Can you enable the profile funciton by -pprof,  and do the profiling by `curl -sK -v http://127.0.0.1:6060/debug/pprof/profile?seconds=60 > profile_60s.out` when syncing is slow, and attach your result here?

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
