### ISSUE TITLE
BSC light client and WS. WTF?

### ISSUE THREAD

**Issue by DamCzech** [binance-chain/bsc#600]
Hi,
What's wrong with that light node client? I had 25-37 peers a few months ago, downloading blocks on a regular date. Since October, it has been losing peers - error. Now I have 80 connected peers and a latency of 10 blocks compared to a full node. 

So much time worked great, now there is a tragedy. And it was an excellent alternative to my application. 

`--metrics --syncmode=light --maxpeers 300 --light.maxpeers 300 --ulc.onlyannounce --cache 4092 --diffsync`

Why can't I start WebSockets properly? Runs without error, does not return blocks ... Port: 8546

Ideas?

**Comment by guagualvcha** [comment]
The key problems is the light client get a latency of 10 blocks or the WebSocket of your light client can not work(can not get blocks) recently?

**Comment by RumeelHussainbnb** [comment]
Can you share the logs? And please use the business/professional language, we have to respect the community please don't use these words W**.

Thanks

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
