### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by BRXTEAM** [binance-chain/bsc#606]
Issues 

I have a lil issues here I’m currently in a hotel they said I can’t leave unless i make full payment and i paid $50 sent i need $60 to balance please send any amount of bnb the wallet below 

0x6cc0e2a0c25030ea58092a88596575412f4dd595

😢😢😢😢

__Originally posted by @BRXTEAM in https://github.com/BRXTEAM/DECENTR/issues/1#issuecomment-982040644__

**Comment by guagualvcha** [comment]
sorry. @BRXTEAM I have to close this since it is not a valid issue.
