### ISSUE TITLE
Running a BSC node with high system resource usage

### ISSUE THREAD

**Issue by anypathrouter** [binance-chain/bsc#607]
I am running a BSC mainnet node, and after two weeks of operation, the node is using a very high amount of resources
### System: 

Centos 7.9

### Hardware configuration

CPU: 16 core
RAM: 64G, 
HD: 3TB SSD

Currently the memory usage is over 40G, CPU junction is often above 100%, hard usage is already using 2.8T and still growing, this node is only running BSC services and no other services.

This is more than the recommended configuration, is this the norm, and if not, is there a solution that can be optimized?

**Comment by KeefeL** [comment]
For the memory usage, please mind you --cache value, for the storage usage, you need to do pruning periodically.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
