### ISSUE TITLE
websockets are not receiving data 

### ISSUE THREAD

**Issue by Marat00016** [binance-chain/bsc#608]
I installed everything according to the instructions. 
https://docs.binance.org/smart-chain/developer/fullnode.html

Server characteristics are as follows: 
vCPU 16
RAM 64
SSD 3.1TB

After installation and launch, the download of the missing blocks began. This process lasted a day.
But websockets still don't receive data 

Launched on command: 
`nohup ./geth_linux --syncmode fast --config ./config.toml --datadir ./node --cache 18000  --ws --ws.port=8546 --ws.api "db,eth,net,web3,personal,txpool,admin" --ws.origins="*" --txlookuplimit 0 --snapshot=false &`

Help plz

**Comment by lennybakkalian** [comment]
same issue here

**Comment by KeefeL** [comment]
I'd like to know what you client code or command is? There are some webscokets calls not supported in bsc.

**Comment by forcodedancing** [comment]
@Marat00016 @lennybakkalian Can you share more details? If not, we supposed you already find the solutions and we will close this issue. Thanks.

**Comment by lennybakkalian** [comment]
@forcodedancing i didnt receive any websocket events, because my node was not fully synchronized

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
