### ISSUE TITLE
Maintaining a node is nearly impossible. What to do?

### ISSUE THREAD

**Issue by maldiva** [binance-chain/bsc#609]
I am maintaining a BSC node for development purposes. Node is using a snap sync mode and mostly can catch up with the network but at this point I keep facing the same issues every other day which makes me always have to do something about it.
 
1. A couple times per day it completely stops syncing at some random block height. Reboot magically helps and then the node continues to sync. Is there any solution to this, e.g. config argument? I don't want to make it reboot artificially every 30-60 mins unless I really have to.  

2. Chaindata grows in size. Rapidly. Very very rapidly. 100-200+ GB everyday. I have around 3 TB of space and it is not enough to just let sync and never deal with it.
Is there any command, config or a sync mode which will allow me to maintain a synced node and not be concerned about its storage consumption every 4-5 days?

**Comment by newbie715** [comment]
> I am maintaining a BSC node for development purposes. Node is using a snap sync mode and mostly can catch up with the network but at this point I keep facing the same issues every other day which makes me always have to do something about it.
> 
> 1. A couple times per day it completely stops syncing at some random block height. Reboot magically helps and then the node continues to sync. Is there any solution to this, e.g. config argument? I don't want to make it reboot artificially every 30-60 mins unless I really have to.
> 2. Chaindata grows in size. Rapidly. Very very rapidly. 100-200+ GB everyday. I have around 3 TB of space and it is not enough to just let sync and never deal with it.
>    Is there any command, config or a sync mode which will allow me to maintain a synced node and not be concerned about its storage consumption every 4-5 days?

I would like to know this too. Thanks for asking.

**Comment by BinanceG11** [comment]
Please join Discord, #node-support subchannel for more discussion on this. https://discord.com/invite/YPDsUqcwR8.

**Comment by KeefeL** [comment]
I think Erigon would be a good choice #568 . Thanks for asking.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
