### ISSUE TITLE
1.1.6 + geth-20211129.tar.gz stuck at "Allocated cache and file handles"

### ISSUE THREAD

**Issue by viwar000** [binance-chain/bsc#610]
#### System information

Geth version: 1.1.6
OS & Version: Linux

#### Expected behaviour
t=2021-11-30T09:37:55+0300 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=48000 updated=42935
t=2021-11-30T09:37:55+0300 lvl=info msg="Set global gas cap"                 cap=25,000,000
t=2021-11-30T09:37:55+0300 lvl=info msg="Allocated trie memory caches"       clean="14.67 GiB" dirty="10.48 GiB"
t=2021-11-30T09:37:55+0300 lvl=info msg="Allocated cache and file handles"   database=/mainnet/geth/chaindata cache="16.77 GiB" handles=262,144
t=2021-11-30T09:37:57+0300 lvl=info msg="Opened ancient database"            database=/mainnet/geth/chaindata/ancient readonly=false
t=2021-11-30T09:37:57+0300 lvl=info msg="Initialised chain configuration"    config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}"
t=2021-11-30T09:37:57+0300 lvl=info msg="Unprotected transactions allowed"
t=2021-11-30T09:37:57+0300 lvl=info msg="Initialising Ethereum protocol"     network=56 dbversion=8

#### Actual behaviour
t=2021-11-30T15:12:26+0600 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=16000 updated=10704
t=2021-11-30T15:12:26+0600 lvl=info msg="Set global gas cap"                 cap=25,000,000
t=2021-11-30T15:12:26+0600 lvl=info msg="Allocated trie memory caches"       clean="3.66 GiB" dirty="2.61 GiB"
t=2021-11-30T15:12:26+0600 lvl=info msg="Allocated cache and file handles"   database=/home/bscfullnode/bsc/node/geth/chaindata cache="4.18 GiB" handles=262,144
t=2021-11-30T15:17:06+0600 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=16000 updated=10704
t=2021-11-30T15:17:06+0600 lvl=info msg="Set global gas cap"                 cap=25,000,000
t=2021-11-30T15:17:06+0600 lvl=info msg="Allocated trie memory caches"       clean="3.66 GiB" dirty="2.61 GiB"
t=2021-11-30T15:17:06+0600 lvl=info msg="Allocated cache and file handles"   database=/home/bscfullnode/bsc/node/geth/chaindata cache="4.18 GiB" handles=262,144

#### Steps to reproduce the behaviour
1.1.6 + geth-20211129.tar.gz

**Comment by blackerhot** [comment]
https://github.com/binance-chain/bsc-snapshots/issues/70

**Comment by KeefeL** [comment]
The geth-20211129.tar.gz snapshot is corrupted, please download the latest snapshot, I'm going to close this issue, thanks.
