### ISSUE TITLE
Current full block number unavailable

### ISSUE THREAD

**Issue by jlinzhou** [binance-chain/bsc#611]
error:
t=2021-11-30T06:21:55+0000 lvl=eror msg="Current full block number unavailable" hash=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b

**Comment by KeefeL** [comment]
I'd like to provide some help, could you describe your question more detail?

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
