### ISSUE TITLE
Pruning stopped working after upgrading to 1.1.5 version

### ISSUE THREAD

**Issue by rmgitting** [binance-chain/bsc#613]
#### System information

Geth version: `geth version 1.1.5`
OS & Version: Ubuntu 20.04.3

#### Expected behaviour
Before I was running on geth 1.1.4 and it was pruning just fine.
Here is the pruning command: `nohup geth_linux snapshot prune-state --datadir path/to/datadir`
After upgrading to geth 1.1.5, the pruning is no longer working. The node can sync and everything seems fine, but the issue is with the pruning.

#### Actual behaviour
Currently when I try to prune, it always gives me the following error message
406,516 slots=839,908,244 elapsed=18m56.019s eta=3m55.95s
ERROR[11-29|13:05:08.540] Failed to prune state err="invalid subroot(path d3fd9752d539043c3be027c083716a739873c9a310155ca6db7a5e68e541c2ac), want 1056ff97a2dcea00101f34d3fe33cb3d33a135037fdb8278fa76ed5ade7f9f07, have d8f64ef4cd4ec96ebf2ba5ede7ef52b196d62e3b76f92a6dc9a1dc0d9abfcbd5"
invalid subroot(path d3fd9752d539043c3be027c083716a739873c9a310155ca6db7a5e68e541c2ac), want 1056ff97a2dcea00101f34d3fe33cb3d33a135037fdb8278fa76ed5ade7f9f07, have d8f64ef4cd4ec96ebf2ba5ede7ef52b196d62e3b76f92a6dc9a1dc0d9abfcbd5

Almost between 15 and 20 minutes after the pruning starts.

#### Steps to reproduce the behaviour
I sync my node normally, the first sync I did was that I downloaded a snapshot in November and used geth 1.1.3, then I upgraded to 1.1.4 and I was pruning just fine.
But when going to 1.1.5, pruning stopped working, and giving the huge size of data that is been added everyday, there is no way to maintain the node without the pruning functionality.

This is how I usually run the command, the only difference is diffsync that I added after 1.1.5, so I am not sure if this has a relation with the pruning problem: 
geth --config config.toml --datadir /path/to/datadir  --cache 45000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http.api eth,web3,debug,txpool,net,shh,db,admin --http --http.corsdomain "*" --ws --ws.api eth,web3,debug,txpool,net,shh,db,admin  --ws.origins localhost --diffsync

Again when I run the command above, the node syncs just fine, but when I stop the node and try to prune it, it gives the error.

**Comment by guagualvcha** [comment]
@MohamadMousheimish  FYI https://github.com/ethereum/go-ethereum/issues/23613.

The data of snapshot storage is corrupt, you can do `./geth snapshot verify-state  --datadir {your data dir}` to verify it.

A quick fix is that you can start  the node again with `--snapshot=false` for one hour, and then shut it down and do prune again.

**Comment by BinanceG11** [comment]
Please join us at Discord, #node-support subchannel for more discussion https://discord.com/invite/YPDsUqcwR8

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
