### ISSUE TITLE
Light or snap mode

### ISSUE THREAD

**Issue by JohnPortreau** [binance-chain/bsc#614]
Geth: 1.1.6
OS: Ubuntu 20.04 LTS
System: 64GB, 2TB nvme ssd, 8 core

When I try to run with `--syncmode snap ` it gives me the error stated below:

```
2021/11/30 14:14:40 worker exits from a panic: runtime error: slice bounds out of range [1:0]
2021/11/30 14:14:40 worker exits from panic: goroutine 123 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1(0xc000140ab0)
	github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x17c
panic(0x15e1b80, 0xc000650030)
	runtime/panic.go:965 +0x1b9
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncNextLink(0xc00062e000, 0x1b34418, 0xc00024ea80, 0x0, 0x0)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/sync.go:124 +0x396
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncRandom(0xc00062e000, 0x1b34418, 0xc00024ea80, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/sync.go:86 +0x2d0
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).nextNode(0xc00031e380, 0x0)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/client.go:282 +0x65
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).Next(0xc00031e380, 0x42bf9b)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/client.go:261 +0x2b
github.com/ethereum/go-ethereum/p2p/enode.(*filterIter).Next(0xc000f3a318, 0x8)
	github.com/ethereum/go-ethereum/p2p/enode/iter.go:120 +0x33
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).runSource(0xc0005ce480, 0xc00004eae0, 0xc000f360e0)
	github.com/ethereum/go-ethereum/p2p/enode/iter.go:283 +0xb0
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).AddSource.func1()
	github.com/ethereum/go-ethereum/p2p/enode/iter.go:183 +0x3c
github.com/panjf2000/ants/v2.(*goWorker).run.func1(0xc000140ab0)
	github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x94
created by github.com/panjf2000/ants/v2.(*goWorker).run
	github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x4c
```

When I try to run it with `--syncmode light` it seems like it is doing the same as with fast/full.

Are these modes even supported could not find anything about it in the documentation...

**Comment by gabrielruoff** [comment]
Did you find a solution to this? I'm getting the same error but without using any mode flags.

**Comment by azimuth0x28** [comment]
same issue. 
After the panic "node cant find any peers

Devs , any tips ?

**Comment by melonux** [comment]
same issue when I starts a completely new node.

```
INFO [01-10|17:48:46.406] Initialized state bloom                  items=12356 errorrate=0.000 elapsed=152.998ms
2022/01/10 17:48:48 worker exits from a panic: runtime error: slice bounds out of range [1:0]
2022/01/10 17:48:48 worker exits from panic: goroutine 141 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1(0xc000e052c0)
	github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x177
panic(0x161cc00, 0xc000027ce0)
	runtime/panic.go:969 +0x1b9
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncNextLink(0xc0006c4000, 0x1b752e0, 0xc00011b100, 0x0, 0x0)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/sync.go:124 +0x399
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncRandom(0xc0006c4000, 0x1b752e0, 0xc00011b100, 0x0, 0x0, 0x0)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/sync.go:86 +0x2d0
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).nextNode(0xc000dfa300, 0x180d)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/client.go:282 +0x65
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).Next(0xc000dfa300, 0x1)
	github.com/ethereum/go-ethereum/p2p/dnsdisc/client.go:261 +0x2b
github.com/ethereum/go-ethereum/p2p/enode.(*filterIter).Next(0xc0003308c0, 0x14)
	github.com/ethereum/go-ethereum/p2p/enode/iter.go:120 +0x33
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).runSource(0xc00063faa0, 0xc000131b00, 0xc000d63d60)
	github.com/ethereum/go-ethereum/p2p/enode/iter.go:283 +0xb0
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).AddSource.func1()
	github.com/ethereum/go-ethereum/p2p/enode/iter.go:183 +0x3c
github.com/panjf2000/ants/v2.(*goWorker).run.func1(0xc000e052c0)
	github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x94
created by github.com/panjf2000/ants/v2.(*goWorker).run
	github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x4c
```

**Comment by davidogbiko** [comment]
Was there a resolution to this issue?

**Comment by PeaStew** [comment]
Also have this issue, would love to have an answer

**Comment by visualbasic6** [comment]
this issue is still present

**Comment by alsofter** [comment]
Confirming the problem. Can't start syncing with any sync modes. Starting from a scratch.

Client version 1.1.18
OS: Centos 8
go version: go1.18.1 

The error log:

2023/01/19 10:13:46 worker exits from a panic: runtime error: slice bounds out of range [1:0]
2023/01/19 10:13:46 worker exits from panic: goroutine 174 [running]:
github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:58 +0x10c
panic({0x16a55c0, 0xc001ba8108})
        runtime/panic.go:1038 +0x215
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncNextLink(0xc00010f140, {0x1cf5bf8, 0xc00107bd40})
        github.com/ethereum/go-ethereum/p2p/dnsdisc/sync.go:124 +0x254
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*clientTree).syncRandom(0xc00010f140, {0x1cf5bf8, 0xc00107bd40})
        github.com/ethereum/go-ethereum/p2p/dnsdisc/sync.go:86 +0x297
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).nextNode(0xc001032480)
        github.com/ethereum/go-ethereum/p2p/dnsdisc/client.go:283 +0x49
github.com/ethereum/go-ethereum/p2p/dnsdisc.(*randomIterator).Next(0xc001032480)
        github.com/ethereum/go-ethereum/p2p/dnsdisc/client.go:262 +0x1e
github.com/ethereum/go-ethereum/p2p/enode.(*filterIter).Next(0xc000111248)
        github.com/ethereum/go-ethereum/p2p/enode/iter.go:120 +0x30
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).runSource(0xc0017723c0, 0xc0012fc2a0, 0xc00011cee0)
        github.com/ethereum/go-ethereum/p2p/enode/iter.go:283 +0xbb
github.com/ethereum/go-ethereum/p2p/enode.(*FairMix).AddSource.func1()
        github.com/ethereum/go-ethereum/p2p/enode/iter.go:183 +0x25
github.com/panjf2000/ants/v2.(*goWorker).run.func1()
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:70 +0x97
created by github.com/panjf2000/ants/v2.(*goWorker).run
        github.com/panjf2000/ants/v2@v2.4.5/worker.go:48 +0x68

Any ideas how to start syncing?
