### ISSUE TITLE
1.1.6 sync is much slower than 1.1.5

### ISSUE THREAD

**Issue by lcgogo** [binance-chain/bsc#615]
I have a synced 1.1.5 node. However, after update to 1.1.6, the sync is much slower that it can not catch up the block explorer.

**Comment by m-e-r-k-l-e-root** [comment]
Nothing really has changed since 1.1.5 -> 1.1.6 of which would really effect sync speed (based on reviewal of files that have changed since 1.1.5). What sync method are you using? Full, Snap or Diff?

**Comment by lcgogo** [comment]
> Nothing really has changed since 1.1.5 -> 1.1.6 of which would really effect sync speed (based on reviewal of files that have changed since 1.1.5). What sync method are you using? Full, Snap or Diff?

use default config.toml and 
```
geth --config /data/bsc/config.toml --ws --ws.addr 0.0.0.0 --ws.api eth,net,web3,txpool,bor --ws.rpcprefix=/ --ws.origins=* --diffsync --datadir /data/bsc
```

**Comment by BinanceG11** [comment]
Please join us at Discord, #node-support subchannel for more discussion https://discord.com/invite/YPDsUqcwR8

**Comment by vae520283995** [comment]
I also found this problem. I have two nodes, one is v1.1.5 and the other is v1.1.6, but the v1.1.6 synchronization will always be slow, the startup parameters are the same, and the snapshot used for v1.1.6 Is the latest

**Comment by pr0logas** [comment]
Confirming the same behavior. The new version cannot catch-up head block.
Old version was significantly faster.

**Comment by KeefeL** [comment]
Actually there is no changes would really affect sync speed as @m-e-r-k-l-e-root said, maybe the disk usage is a little bit high, then maybe you should do pruning now?

**Comment by TehnobitSystems** [comment]
> Please join us at Discord, #node-support subchannel for more discussion https://discord.com/invite/YPDsUqcwR8

#node-support subchannel  not exist or this link expired, how to connect?

**Comment by BinanceG11** [comment]
Link does work. please try again.

**Comment by KeefeL** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
