### ISSUE TITLE
Getting more peers

### ISSUE THREAD

**Issue by kapisolec** [binance-chain/bsc#617]
Hi, I have two nodes running, in the first one I have 100 peers connected and in the second one I have over 160 peers. Both nodes were set up the same way (in both of them I changed the number of MaxPeers and LightPeer in config.toml to 300). I would like to have more peers, but I'm maxing out at 100, why is that? This is my starting command:
`~/bscfullnode/bsc/build/bin/geth --config ~/bscfullnode/bsc/config.toml --datadir ~/bscfullnode/bsc/node --pprof.addr 0.0.0.0 --rpc.allow-unprotected-txs --txlookuplimit 0 --cache 8000 --txpool.reannouncetime 5m --metrics --pprof --http --http.addr 0.0.0.0 --http.corsdomain '*' --http.api eth,net,web3,txpool,debug,admin --ws --ws.addr 0.0.0.0 --ws.origins '*' --ws.api eth,net,web3,txpool,debug,admin --nousb --diffsync --snapshot=false --maxpeers 300`

Also sometimes node feels slow, but it might be the case of the whole bsc blockchain lagging.

**My server setup:**
Processor: | Ryzen™ 9 5950X 16-Core
RAM: | 128 GB DDR4 ECC
Hard drive: | 2 x 3.84 TB NVMe SSD Datacenter Edition(software RAID 0)
Guaranteed bandwidth: | 1 GBit/s

**Comment by sbarratt** [comment]
```maxpeers``` is a misnomer. It's actually 1/3 of the peers you want to add. (I forget exactly why this is but it's somewhere in the code). So if you want 200 peers, set ```maxpeers``` to 600.

**Comment by BinanceG11** [comment]
Please join us at Discord, #node-support subchannel for more discussion https://discord.com/invite/YPDsUqcwR8

**Comment by kapisolec** [comment]
Thank you for your answers, I will close this issue then
