### ISSUE TITLE
How to upgrade fullnode version?

### ISSUE THREAD

**Issue by daron4ever** [binance-chain/bsc#618]
To upgrade new version,

Do i have to download snapshot again and resync, or just start from the following?
```
wget https://github.com/binance-chain/bsc/releases/download/v1.1.6/mainnet.zip
unzip mainnet.zip
./build/bin/geth --syncmode fast --config ./config.toml --datadir ./node --metrics --cache 31260 -verbosity 5 --ws --rpc.allow-unprotected-txs --txlookuplimit 0 --pprof.addr 0.0.0.0 --ws.origins "*" --ws.addr 0.0.0.0 --maxpeers 500
```

**Comment by guagualvcha** [comment]
No, just replace the binary and restart. You can compile the binary from source code or download from https://github.com/binance-chain/bsc/releases/download/v1.1.6/geth_linux

**Comment by BinanceG11** [comment]
Please join us at Discord, #node-support subchannel for more discussion https://discord.com/invite/YPDsUqcwR8

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
