### ISSUE TITLE
Bad block even after restoring everything.

### ISSUE THREAD

**Issue by dgdeivid** [binance-chain/bsc#619]
After being the node synchronized correctly for 3 days it has given a bad block error and has been out of sync.

`t=2021-12-01T11:07:34+0000 lvl=eror msg="\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: <nil>, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}\n\nNumber: 13082000\nHash: 0xeafc056d4cd2355235e385604eb86c9fc3da295a5ac6b292dcd518aad81c96c7\n\t 0: cumulative: 130165 gas: 130165 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xabe7acccb273e1d5c63977f184ff1c0ddf9e56a0ef1bec4681e07c443d4661db logs: [0xc0aaf80000 0xc0aaf800b0 0xc0aaf80160 0xc0aaf80210 0xc0aaf802c0] bloom: 00a0000000000000000000108.......`

This is what I have tried to try to fix it:

- I have rebooted both the server and the node multiple times. I have shutdown the node correctly waiting for the cache to be saved.
- I have started the node without using this command, and using it: "--snapshot = false --syncmode = fast"
- I have deleted all databases by deleting the entire node data directory.
- I downloaded the latest snapshot and tried to sync the node from snapshot again, just like I did the first time.

After several hours without syncing, the same bad block error occurs again and it never gets to sync even though I have deleted the entire database.

I am using 1.1.4

**Comment by seonggwonyoon** [comment]
Use geth bsc v1.1.5

**Comment by cipig** [comment]
i got this error with 1.1.6 too... 2 nodes just stopped syncing, both are showing `########## BAD BLOCK #########`

**Comment by adamiss5138** [comment]
Same error, node stopped syncing. Bad blocks error

**Comment by serfiraz21** [comment]
yes same error i getting what is the solution ? i using v.1.16

**Comment by KeefeL** [comment]
Yes, it's a bug, please refer to #628

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
