### ISSUE TITLE
BAD BLOCK cant syncing

### ISSUE THREAD

**Issue by serfiraz21** [binance-chain/bsc#625]
at 2021-12-03T15:24:32+0000 has given "########## BAD BLOCK #########" message and has been out of sync.
From 15:24 UTC to now still keep giving Bad Block message. 

i have tried these steps:

1.Used with diffsync enabled (already enabled).
2. Restated geth client. ( 3 -4 times) 
3. Restart without diffsync flag 

I use geth v1.1.6. steps above doesnt resolve.

**Comment by ko0f** [comment]
Same here, started happening on two nodes 3 hours ago.

**Comment by khelle** [comment]
Use `debug_setHead` solution mentioned in https://github.com/binance-chain/bsc/issues/507

**Comment by ko0f** [comment]
Even if that works, that's a workaround. There's a bug that causes this to occur and stop nodes from syncing.

**Comment by ascunha** [comment]
start with *diffsync disabled, rewind the chain the way @khelle suggested and it should work. 

*with diffsync on it can happen again after rewind. 

few people in the discord chats had the same bad block problem

**Comment by adamiss5138** [comment]
So diffsync is the problem here?

**Comment by overload-ak** [comment]
The same situation also appeared to me. Since version 1.14, test nodes and main network nodes are prone to sudden bad blocks and fail to synchronize.

**Comment by noirzz** [comment]
> Use `debug_setHead` solution mentioned in #507

how did we run this ?

im trying to ./geth_linux console and >debug.setHead("0xC97444")

but the block not change

**Comment by guagualvcha** [comment]
Please check https://github.com/binance-chain/bsc/pull/628 to fix
