### ISSUE TITLE
How fast should the drive be?  NVME gen 3 or gen 4?

### ISSUE THREAD

**Issue by daica75** [binance-chain/bsc#626]
I would like to ask what is the minimum or recommended storage drive that should be used?  I know an SSD is too slow, and it is recommended that an NVME be used for the storage.  I was using a gen 3 NVME and I have since upgraded to a gen 4 NVME with needed processor and motherboard to take advantage of the gen 4 speed.

However, I am not sure if the gen 4 NVME is actually improving the node or not?  When I run iotop, it shows that the disk usage is usually around 100 to 150 MB/s read and write which works out to only around 1,000 Mb/s.  The gen 3 NVME drives already offer around 2,500 Mb/s and the gen 4 goes up to 7,000 Mb/s.

Please advise.... thanks.

**Comment by bonhardt** [comment]
its not the raw speed what matters so its irrelevant if its gen3 or gen4
what matters is the "latency" of how fast the ssd can access the data and the IOPS in can produce.
and from this point it is more technical question of how the ssd is built, what type of chips are on it.
most people does not even know what is the difference between SLC/MLC/TLC/QLC ssd chips
as manufacturers tend to go cheaper for profit they use the cheaper higher capacity chips and they solve their issue with onboard cache memory, on the newer gen4 TLC/QLC based ssd, once the cache is full on a continous load its speed would degrade highly.

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
