### ISSUE TITLE
can someone release windows guide

### ISSUE THREAD

**Issue by kugimiya530** [binance-chain/bsc#627]
i saw a few people know how to build fullnode by windows
can someone release or teach me how to do that..?

**Comment by seonggwonyoon** [comment]
https://github.com/binance-chain/bsc/releases/tag/v1.1.7

geth_windows.exe has been added.

**Comment by kugimiya530** [comment]
> https://github.com/binance-chain/bsc/releases/tag/v1.1.7
> 
> geth_windows.exe has been added.

yes i know, but the guide on internet is all for linux

i don't know how to setting  like  "cache  , chain ID , allow IP  etc." and where to put the snapshot

if u know please teach me   appreciate。

**Comment by KeefeL** [comment]
The same issue to #371 , i'm gonna to close this one, we will update documents later.
