### ISSUE TITLE
Node already synced, but after several hours its not sync again.

### ISSUE THREAD

**Issue by noirzz** [binance-chain/bsc#630]
Geth version: `1.1.5`
OS & Version: Linux Ubuntu 20.04 LTS

Yesterday i'm trying to sync 2 bsc node with geth 1.1.5. After wait 20 hours, there 2 nodes are synced without issue. But after several hours the one node are not synced anymore and when I check the log. Its looking like this ? any solution ?
And the other one was working fine until now.

![image](https://user-images.githubusercontent.com/67103734/144730586-84f37794-7b8d-428e-b23d-fd2af6f1a61f.png)

**Comment by a04512** [comment]
add --snapshot=false flag

**Comment by noirzz** [comment]
> add --snapshot=false flag

im already using snapshot false since the beginning of sync

`./geth_linux --config ./config.toml --datadir ./mainnet --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=snap --snapshot=false --diffsync`

**Comment by rmgitting** [comment]
I am having the same issue, I had a node that was always in sync, but recently I started getting such an error. What is happening to this chain?

**Comment by MohamadMousheimish** [comment]
Same issue is happening here. Any idea what's going on?

**Comment by KeefeL** [comment]
Please check #628 to fix

**Comment by noirzz** [comment]
> Please check #628 to fix

on #628 say 
Start your node with --snapshot=false
but im already using false since the beginning of syncing ?
so must i set it to true then false again ?

**Comment by KeefeL** [comment]
> > Please check #628 to fix
> 
> on #628 say Start your node with --snapshot=false but im already using false since the beginning of syncing ? so must i set it to true then false again ?
I think this "BAD BLOCK" error is happened when you enabled snapshot, if you have rerun it with --snapshot=false already, maybe you can update the binary and run with --snapshot=true directly.

**Comment by yutianwu** [comment]
If you still have issue, can you try to download the latest snapshot and restart with v1.1.7

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
