### ISSUE TITLE
node out of sync?

### ISSUE THREAD

**Issue by daica75** [binance-chain/bsc#631]
I have a script that is continuously running eth.syncing to check the sync status, and every so often, it is out of sync for a few blocks, but in the bsc.log file, I don't see any log entry with age= in it.  Is the node really out of sync during these times, and if so, why does it go out of sync?

example of output of my script:
Sat Dec 4 21:51:56 EST 2021 false
Sat Dec 4 21:51:57 EST 2021 { currentBlock: 13204463, highestBlock: 13204467, knownStates: 297473485, pulledStates: 297473485, startingBlock: 13204463 }
Sat Dec 4 21:51:58 EST 2021 { currentBlock: 13204464, highestBlock: 13204467, knownStates: 297473485, pulledStates: 297473485, startingBlock: 13204463 }
Sat Dec 4 21:51:59 EST 2021 false
Sat Dec 4 21:52:00 EST 2021 false
Sat Dec 4 21:52:01 EST 2021 false
Sat Dec 4 21:52:02 EST 2021 false
Sat Dec 4 21:52:03 EST 2021 { currentBlock: 13204467, highestBlock: 13204468, knownStates: 297473485, pulledStates: 297473485, startingBlock: 13204467 }
Sat Dec 4 21:52:04 EST 2021 { currentBlock: 13204467, highestBlock: 13204469, knownStates: 297473485, pulledStates: 297473485, startingBlock: 13204467 }
Sat Dec 4 21:52:06 EST 2021 false
Sat Dec 4 21:52:07 EST 2021 false

Do these random out-of-sync cause any issues?  Is it really out of sync when it says that?  And is there any way to reduce or remove the frequency of these out-of-sync issues?

**Comment by KeefeL** [comment]
Is there any "BAD BLOCK" error in the bsc.log file, if there is please check #628 to fix

**Comment by mcf-rocks** [comment]
"Do these random out-of-sync cause any issues"

If you are using the node to query the state of the chain, then clearly it's a problem, the rest of the network has moved on and you are stuck 10 blocks back.

**Comment by RumeelHussainbnb** [comment]
https://github.com/binance-chain/bsc/issues/338

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
