### ISSUE TITLE
snapshot not old enough yet: need 120 more blocks

### ISSUE THREAD

**Issue by meligame** [binance-chain/bsc#633]
![image](https://user-images.githubusercontent.com/92240409/144812617-e19810ff-0da4-4f6f-bd9f-2b212610416d.png)

**Comment by meligame** [comment]
what should i do

**Comment by DreamLxq** [comment]
我正在修剪，看了你的问题后，我在瑟瑟发抖！

**Comment by guagualvcha** [comment]
hi @meligame What I can see from your log is that the snapshot of your node is broken and it just done repairing it, you can start the node and let it run another 128 blocks, the gracefully shut it down and do prune again.

**Comment by RumeelHussainbnb** [comment]
Snapshot is damaged please download the latest snapshot and start it gracefully.

https://github.com/binance-chain/bsc-snapshots

**Comment by meligame** [comment]
thanks everyone
