### ISSUE TITLE
Is there a corresponding Grafana monitoring configuration file?

### ISSUE THREAD

**Issue by netquery** [binance-chain/bsc#634]
Is there a corresponding Grafana monitoring configuration file?

**Comment by KeefeL** [comment]
You can refer https://ethereum.org/en/developers/tutorials/monitoring-geth-with-influxdb-and-grafana/

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
