### ISSUE TITLE
that's complete?

### ISSUE THREAD

**Issue by meligame** [binance-chain/bsc#636]
![image](https://user-images.githubusercontent.com/92240409/144846020-9603efe1-5b89-4ec5-80ad-6ca2c794b0e4.png)

**Comment by psdlt** [comment]
@meligame no, that's only half-way done. You will see `Compactin database range=0x10-0x20` next, then `0x20-0x30`, etc.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
