### ISSUE TITLE
Snapshot extension registration failed

### ISSUE THREAD

**Issue by Art-Mas** [binance-chain/bsc#637]
![image](https://user-images.githubusercontent.com/26169538/144847652-705d351d-4172-458d-a915-a79458c8ce0a.png)

`lvl=eror msg="Snapshot extension registration failed" peer=968fed87 err="peer connected on snap without compatible eth support"`

I've been getting this error for about two hours now. Everything is fine? Should I just wait?

Cmd to start: `./geth_linux --config ./config.toml --datadir ./mainnet --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --http --maxpeers 100 --ws --syncmode=snap --snapshot=true --diffsync`

VERSION: 1.1.6-0b575443

**Comment by gencero** [comment]
same issue. can anyone help?

**Comment by Art-Mas** [comment]
Still has this problem...

**Comment by RumeelHussainbnb** [comment]
Please upgrade to latest version 

https://github.com/binance-chain/bsc/releases/tag/v1.1.7

**Comment by gencero** [comment]
> Please upgrade to latest version
> 
> https://github.com/binance-chain/bsc/releases/tag/v1.1.7

Upgraded but we can't catch the curent block somehow.

**Comment by Art-Mas** [comment]
Successfully synced when i upgrade to latest geth version and use latest snapshot (20211206)

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by snail-plus** [comment]
> Successfully synced when i upgrade to latest geth version and use latest snapshot (20211206)

can you share your step？
