### ISSUE TITLE
GPO doesn't work

### ISSUE THREAD

**Issue by 1doce8** [binance-chain/bsc#638]
Reference [#559](https://github.com/binance-chain/bsc/issues/559)
I'm trying to get reasonable gas price by `eth_gasPrice` (based on the latest blocks). I have tested public binance nodes and looks like they provide the current, dynamic gas price. While my node does not exactly calculate this with the default config

#### System information

Geth version: `geth version`
```
Geth
Version: 1.1.7
Git Commit: 74f6b613a4db5cb903f98aca54dbe77d5039ffe8
Architecture: amd64
Go Version: go1.16.10
Operating System: linux
GOPATH=
GOROOT=go
```

OS & Version: Windows/Linux/OSX
```
5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### Expected behaviour
A reasonable gas price

#### Actual behaviour
1 gwei / 1000000000

#### Steps to reproduce the behaviour
Start BSC node, send request with `eth_gasPrice` method

**Comment by guagualvcha** [comment]
Can you update to the lastest config.toml, the GPO module should be:

```
[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20
```

**Comment by 1doce8** [comment]
@guagualvcha Yeah, my GPO setting similar to this

**Comment by 1doce8** [comment]
Ah hold on, looks like it works with config.toml attached to 1.1.7 release, need to test

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
