### ISSUE TITLE
What exactly will be done when running prune-state

### ISSUE THREAD

**Issue by netquery** [binance-chain/bsc#639]
https://docs.binance.org/smart-chain/developer/fullnode.html#storage

I found that after running bsc node for a period of time, the disk space increased very fast. Do we need to run prune-state?

**Comment by chenyuejie** [comment]
FYI, just finished a prune on a new node from snapshot, which take round 1.5T disk space.

INFO [12-07|08:51:00.661] Database compaction finished             elapsed=6h0m20.391s
INFO [12-07|08:51:00.662] State pruning successful                 pruned=542.32GiB elapsed=9h22m13.349s

**Comment by RumeelHussainbnb** [comment]
> https://docs.binance.org/smart-chain/developer/fullnode.html#storage
> 
> I found that after running bsc node for a period of time, the disk space increased very fast. Do we need to run prune-state?

yes, you can prune state or download another snapshot

**Comment by netquery** [comment]
> > https://docs.binance.org/smart-chain/developer/fullnode.html#storage
> > I found that after running bsc node for a period of time, the disk space increased very fast. Do we need to run prune-state?
> 
> yes, you can prune state or download another snapshot

Can prune state be made automatic? For clusters of multiple machines, the operation and maintenance cost is relatively high if it is manually operated

**Comment by yutianwu** [comment]
For now you have to prune the nodes manually, you have to stop the node before pruning. We recommend you have back up nodes running when pruning some nodes.

**Comment by jennie-bv** [comment]
> 

At the same time of pruning, whether the disk usage is gradually reduced or after pruning is completed

**Comment by mindlesscloud** [comment]
Hi, does bsc node support prune automatically now?
