### ISSUE TITLE
synchronize the node, the block height stays in place

### ISSUE THREAD

**Issue by 790228724** [binance-chain/bsc#641]
Synchronize the node, the block height stays in place, the log file prompts

"\n########## BAD BLOCK #########\nChain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}\n\nNumber: 13162754\nHash: 0x5b3ee10762a822259d51e9e0f59755e3ff69e09b0eb883891da4ff63b706e630\n\t 0: cumulative: 55477 gas: 55477 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x26696a876defe02c66f0fd34299da5b62585bea6479cd56b00697d93d72d28e3 l

**Comment by yutianwu** [comment]
you can refer to this: https://github.com/binance-chain/bsc/pull/628

**Comment by 790228724** [comment]
i have tried restarting the program, it can be solved, but after running for a period of time, there is still a probability of this situation

**Comment by 790228724** [comment]
> 你可以参考这个：#628

i have tried restarting the program, it can be solved, but after running for a period of time, there is still a probability of this situation

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
