### ISSUE TITLE
 Which block of data should I trust

### ISSUE THREAD

**Issue by meligame** [binance-chain/bsc#644]
![image](https://user-images.githubusercontent.com/92240409/145164576-630f06bc-fead-4c18-b605-4d83975aedc6.png)
I am using eth_getLogs to parse the events that occurred,
Will the situation in the picture cause me to lose some events?

**Comment by meligame** [comment]
13291827 Same block height, different hash, different number of transactions

**Comment by a04512** [comment]
Chain reorg did you see it in your logs

**Comment by psdlt** [comment]
@meligame chain reorgs are pretty common on BSC and you need to account for that. Meaning that pretty often you will see blocks with same height, but different transactions. All previously posted txs/logs should be considered invalid. Quickly checking web3js docs it doesn't seem that it reports "removed" property, but `geth` internally uses that to notify about logs that were removed.

**Comment by meligame** [comment]
> @meligame链重组在 BSC 上很常见，您需要考虑到这一点。这意味着你经常会看到高度相同但交易不同的区块。所有以前发布的交易/日志都应被视为无效。快速检查 web3js 文档，它似乎没有报告“已删除”属性，而是在`geth`内部使用它来通知已删除的日志。

Thank you for your reply
I am a novice, how can I verify that the current block data is correct for web3j

**Comment by psdlt** [comment]
@meligame depends on what you consider to be "correct". You can do same thing Binance does - wait for 10-15 blocks and only then say that "this data is correct, there is no way it will change".

**Comment by ascunha** [comment]
> > @meligame链重组在 BSC 上很常见，您需要考虑到这一点。这意味着你经常会看到高度相同但交易不同的区块。所有以前发布的交易/日志都应被视为无效。快速检查 web3js 文档，它似乎没有报告“已删除”属性，而是在`geth`内部使用它来通知已删除的日志。
> 
> Thank you for your reply I am a novice, how can I verify that the current block data is correct for web3j

I think you should wait around 12 confirmations for finality, i read somewhere that using diffsync, should be around 21.
google a little about blockchain confirmations, there is very good information around.

**Comment by meligame** [comment]
Okay, thanks for everyone's answers. I will close this issue

**Comment by meligame** [comment]
我可以通过block的 hash和parentHash 来检查吗？举个例子
block1:
{
height:1
hash：0x1,parentHash:0x00},
block2:
{
height:2
hash：0x2,parentHash:0x01}
block2:
{
height:2,
hash：0x2l,
parentHash:0x02
}

block3:{
height:3,
hash:0x3,
parentHash:0x2
}

Can I be sure that the hash: 0x2 is the correct block because the parentHash of 0x3 is 0x2
0x2L is just an uncle

**Comment by psdlt** [comment]
@meligame if that's your whole chain - then no, one block "confirmation" is not enough, chain reorg can still happen and 0x2 can be replaced by another block.

**Comment by ascunha** [comment]
> 我可以通过block的 hash和parentHash 来检查吗？举个例子

还是不行吧。。。最近的reorg都很浅但是我们不能说每个reorg有那么浅。

1 block is not enough.

**Comment by KeefeL** [comment]
You can refer the security and finality part of the whitepaper https://github.com/binance-chain/whitepaper/blob/master/WHITEPAPER.md, it need nearly ⅔*N+1 to ensure a relatively secure finality.

**Comment by meligame** [comment]
I found a better solution,
When the difference between the height of my synchronization and the latest height of the node exceeds 21, I use eth_getLogs to synchronize the event information.

Within 21 blocks
First use eth_getBlockByNumber to get transaction data
Then use eth_getTransactionReceipt
Compare the blockHash of the transaction with the Hash of the Block. If they are inconsistent, block reorganization will occur.

**Comment by meligame** [comment]
这样我就不用一直等待21个区块确认 ，导致我的数据有延迟。

**Comment by meligame** [comment]
In this way, I don't have to wait for 21 block confirmations, causing delays in my data.
