### ISSUE TITLE
getPastEvents web3 function return different results in the same input

### ISSUE THREAD

**Issue by mutobui** [binance-chain/bsc#646]
```
        const contract_transfer = new web3.eth.Contract(token_abi.abi, TOKEN_ADDRESS);
        const block_height = await web3.eth.getBlockNumber();
        const transfer_argument = {
            from: 13313155,
            to: 13317155
        }
        let transfers = await contract_transfer.getPastEvents("allEvents", transfer_argument);
        console.log("transfers: ", transfers.length);
```

with one argument but transfers show the different result when I run this code multiple times;
transfers: 1
transfers: 6
transfers: 6
transfers: 1

**Comment by NashBC** [comment]
This may caused by block reorg as #644 discuss, you can specify a historical block_height to check wether you can get the same result.

**Comment by RumeelHussainbnb** [comment]
https://github.com/binance-chain/bsc/issues/644

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
