### ISSUE TITLE
Persisted the clean trie cache

### ISSUE THREAD

**Issue by qiushaoxi** [binance-chain/bsc#649]
#### System information

Geth version: `geth version`
Version: 1.1.7
Git Commit: 74f6b613a4db5cb903f98aca54dbe77d5039ffe8

OS & Version: Windows/Linux/OSX
Linux

Commit hash : (if `develop`)

#### Expected behaviour
syncing data

#### Actual behaviour
stop syncing

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

geth is running but actually not syncing

log:

t=2021-12-09T09:39:19+0000 lvl=info msg="Writing clean trie cache to disk"       path=/data/bsc/geth/triecache threads=1
t=2021-12-09T09:39:23+0000 lvl=info msg="Persisted the clean trie cache"         path=/data/bsc/geth/triecache elapsed=4.525s

**Comment by KeefeL** [comment]
What do you mean by "geth is running but actually not syncing"? Are you doing prune here?

**Comment by qiushaoxi** [comment]
> What do you mean by "geth is running but actually not syncing"? Are you doing prune here?

geth process is running , but not receving new blocks

**Comment by RumeelHussainbnb** [comment]
https://github.com/binance-chain/bsc/issues/338

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by guiltylelouch** [comment]
same issue!! Did you solve it?
