### ISSUE TITLE
BSC full-node "possible fork" log message

### ISSUE THREAD

**Issue by marcelomorgado** [binance-chain/bsc#65]
Hi,

I've just started a BSC full-node by following this doc here https://docs.binance.org/smart-chain/developer/fullnode.html, I'm waiting for the node to sync and I'm receiving a lot of messages like that from the log:

`t=2021-01-22T11:55:53+0000 lvl=warn msg="there is a possible fork, and your client is not the majority. Please check..." nextForkHash=3f2e9ae4`

Is it normal?

Thanks

**Comment by guagualvcha** [comment]
Hi, it is normal. This is introduced recently: https://github.com/binance-chain/BEPs/blob/master/BEP89.md.
Because this feature is not upgrade in main-net yet, so if you use it in main-net, may get such warning log, it is ok.

**Comment by marcelomorgado** [comment]
OK, thanks.
