### ISSUE TITLE
Prune Failed " Resuming state snapshot generation "

### ISSUE THREAD

**Issue by jennie-bv** [binance-chain/bsc#650]
Geth  Version: `1.1.7`
Command : `nohup ./geth snapshot prune-state --datadir /bsc-data &`
nohup.out 

> INFO [12-09|10:59:33.563] Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-09|10:59:33.563] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [12-09|10:59:33.564] Set global gas cap                       cap=25,000,000
INFO [12-09|10:59:33.564] Allocated cache and file handles         database=/bsc-data/geth/chaindata cache=408.00MiB handles=32767
INFO [12-09|10:59:36.928] Opened ancient database                  database=/bsc-data/geth/chaindata/ancient readonly=false
INFO [12-09|10:59:36.950] Snapshot loaded                          diskRoot=e9d405..f7fcb4 root=9f69f4..7eb1c1
INFO [12-09|10:59:36.950] Resuming state snapshot generation       root=e9d405..f7fcb4 in=034cad..f1c556 at=1a79b8..c85a5b accounts=939,079 slots=8,040,100 storage=649.33MiB elapsed="77.797µs"
INFO [12-09|10:59:36.951] Trie missing, state snapshotting paused  root=e9d405..f7fcb4 in=034cad..f1c556 at=1a79b8..c85a5b accounts=939,079 slots=8,040,100 storage=649.33MiB elapsed="551.632µs"

**Comment by KeefeL** [comment]
It seems the bsc didn't graceful shutdown, you can try the following steps to repair:
1.Start your node with --snapshot=false
2.Wait for few minutes(it depends on how fast your nodes are), until the block height is 128 higher than where it stopped.
3.Restart the node with --snapshot=true
4.The node will continue to sync and repair the corrupt data, wait for a while the same to step2
5.Stop your node, make sure it has been graceful shutdown, do prune again

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
