### ISSUE TITLE
How exactly is TrieTimeout calculated?

### ISSUE THREAD

**Issue by nforced** [binance-chain/bsc#651]
Reading at [release v1.1.1 CHANGELOG](https://github.com/binance-chain/bsc/releases/tag/v1.1.1)

```
The default setting before release v1.1.1 is 100000000000, it will persist MPT about every 35 minutes.
We change the default setting to 2000000000000 in this release, it will persist MPT about every 12 hours.
```
But I don't understand what unit is 1 here so 100000000000 = 35min, how should one calculate this value for a given amount of time?

For example what is the value for 1hours, for 5 hours, etc.

**Comment by KeefeL** [comment]
As you can see in the source code, the TrieTimeout is used to compare with gcproc, and gcproc is the accumulated value for processing a block, the block produce time is 3s, while the process time would be much smaller than 3s. You can understand that the 35 minutes or 12 hours as an experienced value, not exactly.
![image](https://user-images.githubusercontent.com/90749943/146488680-9fe8ba7b-9255-4e6f-bcc9-7d3821bd0295.png)

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
