### ISSUE TITLE
Node stuck on 12965001 block

### ISSUE THREAD

**Issue by azimuth0x28** [binance-chain/bsc#654]
geth 1.1.7 ( tried 1.1.5- 1.1.7)
Docker container alpine:latest
Bare server 
64G Ram ,
2x2000Gb  SSD NvMe, 
Intel Xeon E3-1275v5

BSC [config.toml.txt](https://github.com/binance-chain/bsc/files/7689318/config.toml.txt)

run params
    --config=/node/config.toml \
    --syncmode snap \
    --snapshot=true \
    --diffsync \
    --cache 21000 \
    --rpc.allow-unprotected-txs \
    --txlookuplimit 0 \
    --http \
    --http.corsdomain "*" \
    --http.addr "0.0.0.0"
    
    
Issue:
6y for 2 days synced from scratch, up to block 12965001. ( it seems pivot point)
(Before sync from sratch I tried sync from latest snapshot but faled. Blocks syncing so slow I never got to head block. So I started from scratch )
Afterward snapshot generation started. New block import stopped.
    
Then ~100h snapshot was done. Node not resume importing new blocks.
[log.txt](https://github.com/binance-chain/bsc/files/7689350/log.txt)

I was waiting few hours , and got nothing new in log.
   
Then i exec command debug.setHead("0xc5d3c1")  and node started syncing from block 12964801 again up to 12965001 and stopped.
    
What i have to do?

**Comment by KeefeL** [comment]
12965001 block is 13 days ago, I think you can download the latest snapshot to start your node gain.

**Comment by azimuth0x28** [comment]
> 12965001 block is 13 days ago, I think you can download the latest snapshot to start your node gain.

I have tried. But node syncing so slow from snapshot (1 block per 10-13sec) . It will never  got head block

**Comment by LyyDandelion** [comment]
me too ,What i have to do?
![image](https://user-images.githubusercontent.com/33171640/146289960-9efdb6b5-cd27-4abb-a29e-eb8ee8be5452.png)

**Comment by RumeelHussainbnb** [comment]
https://github.com/binance-chain/bsc/issues/502 

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by pinpins** [comment]
any solution to this problem?

**Comment by GMVyLow** [comment]
any solution on these guys?

**Comment by rommzestz** [comment]
first, init from genesis. then check highest block
