### ISSUE TITLE
prune data issuse

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#655]
When I run "geth_linux snapshot prune-state --datadir /root/svc/node"  ,I got the following error.
ERROR[12-10|01:50:45.225] Failed to prune state                    err="no snapshot paired state"
![image](https://user-images.githubusercontent.com/65291464/145503872-7708a658-d756-4435-a21b-bdec8dddf388.png)

**Comment by kyrie-yl** [comment]
please add '--triesInMemory=32' when you do prune.
