### ISSUE TITLE
can't run prune-state command and always get error head doesn't match snapshot: have 0x, want 0x

### ISSUE THREAD

**Issue by nining** [binance-chain/bsc#661]
#### System information

Geth version: `1.1.7`
OS & Version: Linux

#### Expected behaviour

I have tries several times of the following process:

1. stop the node
2. start the node after 10 hours and seen there's no more  the "expected" word message in bsc.log
3. stop the node
4. execute geth with snapshot prune-state command

#### Actual behaviour
Here is the last lines in bsc.log

`t=2021-12-12T10:16:04+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=177   mgas=21.006  elapsed=189.195ms     mgasps=111.027 number=13,398,361 hash=0xe810d7794ab52626ea155a9b4f44ddd0d336b80b721ac7ca790457df0911778a dirty="675.82 MiB"
t=2021-12-12T10:16:05+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=258   mgas=24.697  elapsed=822.248ms     mgasps=30.036  number=13,398,363 hash=0x33dc32086e749a23f14c6539dce546a9362510536c563d44f6087992aa3be169 dirty="678.87 MiB"
t=2021-12-12T10:16:05+0800 lvl=info msg="Unindexed transactions"                 blocks=1   txs=219   tail=11,048,364 elapsed=4.839ms
t=2021-12-12T10:16:07+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=339   mgas=32.708  elapsed=529.195ms     mgasps=61.806  number=13,398,363 hash=0x0c9cc455f935426a800ebf73e577ccc659f6dafe98f22286cc283997bc2011f3 dirty="678.01 MiB"
t=2021-12-12T10:16:20+0800 lvl=info msg="Deep froze chain segment"               blocks=17  elapsed=244.495ms     number=13,308,363 hash=0x41472364db158602846616ada7c44c445f86f218acc0c226805fb9c0b9a983e5
t=2021-12-12T10:16:30+0800 lvl=info msg="Imported new chain segment"             blocks=5   txs=1474  mgas=239.361 elapsed=5.935s        mgasps=40.328  number=13,398,368 hash=0x8c0356e44aea67fd2205a2f2dd587b18faf3ad6332288c20d88580951c3be77e dirty="688.01 MiB"
t=2021-12-12T10:16:30+0800 lvl=info msg="Unindexed transactions"                 blocks=5   txs=1069  tail=11,048,369 elapsed=47.943ms
t=2021-12-12T10:16:32+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=284   mgas=36.886  elapsed=1.583s        mgasps=23.300  number=13,398,369 hash=0x1570acaf4602166160cf4c358721e22e6e124e7ab9ca2a554f1366f2e8d57f36 dirty="689.14 MiB"
t=2021-12-12T10:16:32+0800 lvl=info msg="Unindexed transactions"                 blocks=1   txs=257   tail=11,048,370 elapsed=6.349ms
t=2021-12-12T10:16:33+0800 lvl=info msg="Imported new chain segment"             blocks=1   txs=234   mgas=33.387  elapsed=1.242s        mgasps=26.863  number=13,398,370 hash=0x5ccea35e55b54674ea67c74c9099d769d78940c8e02d6dccba0cd29e65acd2af dirty="690.20 MiB"
t=2021-12-12T10:16:33+0800 lvl=info msg="Unindexed transactions"                 blocks=1   txs=296   tail=11,048,371 elapsed=5.837ms
t=2021-12-12T10:16:35+0800 lvl=info msg="Got interrupt, shutting down..."
t=2021-12-12T10:16:35+0800 lvl=info msg="HTTP server stopped"                    endpoint=127.0.0.1:2510
t=2021-12-12T10:16:35+0800 lvl=info msg="IPC endpoint closed"                    url=/home/bsc/mainnet/geth.ipc
t=2021-12-12T10:16:35+0800 lvl=info msg="Imported new chain segment"             blocks=2   txs=1017  mgas=59.712  elapsed=1.976s        mgasps=30.211  number=13,398,372 hash=0xc85b4e72c2bb688e4f898c5d6b813130c2622b0358f1bcbad64adfcaaf418798 dirty="691.58 MiB"  ignored=2
t=2021-12-12T10:16:35+0800 lvl=info msg="Unindexed transactions"                 blocks=2   txs=306   tail=11,048,373 elapsed=49.008ms
t=2021-12-12T10:16:41+0800 lvl=info msg="Ethereum protocol stopped"
t=2021-12-12T10:16:41+0800 lvl=info msg="Transaction pool stopped"
t=2021-12-12T10:16:41+0800 lvl=info msg="Looking for peers"                      peercount=0 tried=60 static=25
t=2021-12-12T10:16:46+0800 lvl=eror msg="Failed to journal state snapshot"       err="snapshot [0xc3891a88b22400ff10a34cf151832a96743dcb82da861478b105c8a2fcb5adf5] missing"
t=2021-12-12T10:16:46+0800 lvl=info msg="Writing cached state to disk"           block=13,398,372 hash=0xc85b4e72c2bb688e4f898c5d6b813130c2622b0358f1bcbad64adfcaaf418798 root=0xc3891a88b22400ff10a34cf151832a96743dcb82da861478b105c8a2fcb5adf5
t=2021-12-12T10:16:51+0800 lvl=info msg="Looking for peers"                      peercount=2 tried=48 static=25
t=2021-12-12T10:16:59+0800 lvl=info msg="Persisted trie from memory database"    nodes=876,701 size="246.75 MiB" time=12.96281488s  gcnodes=358,738 gcsize="140.48 MiB" gctime=2.254141643s livenodes=742,083   livesize="241.99 MiB"
t=2021-12-12T10:16:59+0800 lvl=info msg="Writing cached state to disk"           block=13,398,371 hash=0x870948c4ce25e77a7b1a9ebd3e8d90c55615e0d7485af0cb1a62871e4e346ed0 root=0xf77b0e29d7c51f75c706738b049afc4ff10b527901991f678ca3fe97b2207312
t=2021-12-12T10:16:59+0800 lvl=info msg="Persisted trie from memory database"    nodes=5556    size="2.19 MiB"   time=88.522721ms   gcnodes=0       gcsize="0.00 B"     gctime=0s           livenodes=736,527   livesize="239.80 MiB"
t=2021-12-12T10:16:59+0800 lvl=info msg="Writing cached state to disk"           block=13,398,245 hash=0x069391c7dcef83f61dca837f2b4e5eb7529a7657e0748ad3107cf013617d094e root=0xe34b1e23ee9eac1a2be382e3533389749524fd02a65cb2dce4fcead381bcab35
t=2021-12-12T10:17:01+0800 lvl=info msg="Persisted trie from memory database"    nodes=130,540 size="49.15 MiB"  time=2.084380421s  gcnodes=0       gcsize="0.00 B"     gctime=0s           livenodes=605,987   livesize="190.65 MiB"
t=2021-12-12T10:17:01+0800 lvl=eror msg="Dangling trie nodes after full cleanup"
t=2021-12-12T10:17:01+0800 lvl=info msg="Writing clean trie cache to disk"       path=/home/bsc/mainnet/geth/triecache threads=56
t=2021-12-12T10:17:01+0800 lvl=info msg="Persisted the clean trie cache"         path=/home/bsc/mainnet/geth/triecache elapsed=198.207ms
t=2021-12-12T10:17:01+0800 lvl=info msg="Blockchain stopped"
t=2021-12-12T10:17:02+0800 lvl=info msg="Looking for peers"                      peercount=0 tried=78 static=25
t=2021-12-12T10:17:46+0800 lvl=info msg="Set global gas cap" cap=25,000,000
t=2021-12-12T10:17:46+0800 lvl=info msg="Allocated cache and file handles" database=/home/bsc/mainnet/geth/chaindata cache="408.00 MiB" handles=262,144
t=2021-12-12T10:18:00+0800 lvl=info msg="Opened ancient database"          database=/home/bsc/mainnet-ancient readonly=false
t=2021-12-12T10:18:01+0800 lvl=warn msg="Loaded snapshot journal"          diskroot=0x797610c8ace4a54b514ddfcc949e85cfb1f58f0c925acd1d23134457e57a28b4 diffs=unmatched
t=2021-12-12T10:18:01+0800 lvl=eror msg="Failed to open snapshot tree"     err="head doesn't match snapshot: have 0x797610c8ace4a54b514ddfcc949e85cfb1f58f0c925acd1d23134457e57a28b4, want 0xc3891a88b22400ff10a34cf151832a96743dcb82da861478b105c8a2fcb5adf5"
` 

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by KeefeL** [comment]
This is caused by corrupted data, you may fix by these steps:
1.Stop bsc service and then run it with extra flag "--snapshot=false" for a while,
2.Stop bsc service and then run it without flag "--snapshot=false" for a while,
3.Stop bsc service and do prune again.

**Comment by nining** [comment]
> This is caused by corrupted data, you may fix by these steps: 1.Stop bsc service and then run it with extra flag "--snapshot=false" for a while, 2.Stop bsc service and then run it without flag "--snapshot=false" for a while, 3.Stop bsc service and do prune again.

now it skips this error and got a new error:
`t=2021-12-15T02:15:03+0000 lvl=info msg="Iterating state snapshot"         accounts=27,962,320 slots=326,957,591 elapsed=17m36.158s  eta=28m4.703s
t=2021-12-15T02:15:11+0000 lvl=info msg="Iterating state snapshot"         accounts=27,962,320 slots=328,022,759 elapsed=17m44.158s  eta=28m17.468s
t=2021-12-15T02:15:19+0000 lvl=info msg="Iterating state snapshot"         accounts=27,962,320 slots=328,742,073 elapsed=17m52.158s  eta=28m30.226s
t=2021-12-15T02:15:23+0000 lvl=eror msg="Failed to prune state"            err="invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2"
`

**Comment by KeefeL** [comment]
> This is caused by corrupted data, you may fix by these steps:
> 1.Stop bsc service and then run it with extra flag "--snapshot=false" for a while,
> 2.Stop bsc service and then run it without flag "--snapshot=false" for a while,
> 3.Stop bsc service and do prune again.

Step1 should ensure that the block height is 128 higher than where it stopped

**Comment by vovapwn** [comment]
> > This is caused by corrupted data, you may fix by these steps: 1.Stop bsc service and then run it with extra flag "--snapshot=false" for a while, 2.Stop bsc service and then run it without flag "--snapshot=false" for a while, 3.Stop bsc service and do prune again.
> 
> now it skips this error and got a new error: `t=2021-12-15T02:15:03+0000 lvl=info msg="Iterating state snapshot" accounts=27,962,320 slots=326,957,591 elapsed=17m36.158s eta=28m4.703s t=2021-12-15T02:15:11+0000 lvl=info msg="Iterating state snapshot" accounts=27,962,320 slots=328,022,759 elapsed=17m44.158s eta=28m17.468s t=2021-12-15T02:15:19+0000 lvl=info msg="Iterating state snapshot" accounts=27,962,320 slots=328,742,073 elapsed=17m52.158s eta=28m30.226s t=2021-12-15T02:15:23+0000 lvl=eror msg="Failed to prune state" err="invalid subroot(path 62ce31f65cc88c25073ef5023678cf3f857786f21ad935ae7f0f1468eedde8c2), want 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, have 7ab1737abe3512c9ee0646c89c2c95609596b87fbd2d86eca664aef7a39b07b2" `

Have the same error. Any luck on this one?

**Comment by RumeelHussainbnb** [comment]
This error occurs due to data corruption. You can run geth snapshot verify-state to double confirm whether the data is correct. You can download the latest snapshot from https://github.com/binance-chain/bsc-snapshots. By doing that, you don't have to prune-state in the future, save precious disk IO, it will help you keep up with syncing.

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by lcgogo** [comment]
> This error occurs due to data corruption. You can run geth snapshot verify-state to double confirm whether the data is correct. You can download the latest snapshot from https://github.com/binance-chain/bsc-snapshots. By doing that, you don't have to prune-state in the future, save precious disk IO, it will help you keep up with syncing.
> 
> Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

Why use the latest snapshot can avoid to do prune-state? My concern is I use AWS EC2 instance (type i3en.2xlarge) according to  https://github.com/binance-chain/bsc/issues/502#issuecomment-961437518 mentioned. However, it is a local SSD EC2 that can't increase disk like EBS. So I have to prune the state to recycle some disk usage before the data reach local SSD max size (4TB for i3en.2xlarge).
