### ISSUE TITLE
Why does it say VPS in node instructions 

### ISSUE THREAD

**Issue by omryr** [binance-chain/bsc#663]
Is it possible to run the node on any pc that is capable (hardware wise) or is there a reason it says vps? I want to run a witness node and I don’t want to waste my time trying to run it on a pc and discover it somehow matters..

**Comment by psdlt** [comment]
@omryr you can run "light" node on pretty much any computer, or you can run "full" (non-validator) node, but that will require computer with really good hardware. Biggest requirement is for a _really_ fast SSD, better yet - multiple SSDs in a RAID of your choice; but good CPU and a lot of RAM is also required.
Docs are outdated, don't even bother running a full node on a VPS.

**Comment by DreamLxq** [comment]
可以在裸金属机器运行!

**Comment by DreamLxq** [comment]
> @psdlt轻节点是指见证节点吗？是否有关于运行轻节点的更新文档/指南？

怎么可能.验证者是验证者,有特权的...Binance 亲自选的

**Comment by ReeganExE** [comment]
> @psdlt by light node do you mean witness node? And is there any newer documentation/guide on running a light node?

Same question.

**Comment by RumeelHussainbnb** [comment]
https://docs.binance.org/smart-chain/developer/fullnode.html

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
