### ISSUE TITLE
Switch gcmode to archive after sync from Snap

### ISSUE THREAD

**Issue by radian-rgc** [binance-chain/bsc#665]
Before i used gcmode full but now i want to switch it to archive, but i know i can't access to oldest data (a specific block).

For access to all blocks, i must Sync From Genesis Block ? if yes, can sync Geth via Snap ?

Thanks

**Comment by DreamLxq** [comment]
可以...我就是这样

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
