### ISSUE TITLE
How to get contract abi without bscscan 

### ISSUE THREAD

**Issue by Serqati** [binance-chain/bsc#666]
Hello
Can I get contract abi of a token on binance smart chain without using bscscan api (for example communicate with bsc node directly) ?
Regards

**Comment by guagualvcha** [comment]
No other method except you know what the smart contract is.

**Comment by FeurJak** [comment]
You can get the byte code of the contract and try to interpret it, difficult but not impossible.

**Comment by Serqati** [comment]
@FeurJak thanks.

**Comment by Serqati** [comment]
@FeurJak where can I find solidity decompiler (open source)

**Comment by RumeelHussainbnb** [comment]
https://github.com/ajlopez/Yasold
https://github.com/tehybel/DSol-decompiler
https://github.com/ethereum/sourcify

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
