### ISSUE TITLE
Node out of sync

### ISSUE THREAD

**Issue by uniftyitadmin** [binance-chain/bsc#669]
#### System information

Geth version: `1.1.7.`
OS & Version: Linux-Debian 11

#### Expected behaviour
node synced

#### Actual behaviour
node not synced, 5-20 and sometimes 70-100 blocks behind

Yesterday i've finally manage to sync my bsc node. i'am using Hetzner's AX51 with 2x 1 TB NVME disks in RAID 0, 64 GB RAM and AMD Ryzen 7 3700x Octa-Core. Today i checked again and my node was about 5-20 blocks behind. From time to time it  jumps to aprox. 100 blocks behind. What seems to be problem here? Maybe number of CPU's or something else?

**Comment by nilampatel-engineer** [comment]
my node is out of sync too and facing error = 


ERROR[12-16|16:27:56.982] Canonical hash missing, can't freeze     number=13,347,308

**Comment by dgdeivid** [comment]
You have very low storage. You have 1TB, and the recommended minimum is 2TB. I don't understand how you could even get to 20 blocks.

**Comment by RumeelHussainbnb** [comment]
You have 1 TB NVME Disk storage which is low. Please follow the Hardware requirement guide:

**Suggested Hardware Requirements**
**Fullnode**
VPS running recent versions of Mac OS X or Linux.
IMPORTANT 2T GB of free disk space, solid-state drive(SSD), gp3, 8k IOPS, 250MB/S throughput, read latency <1ms. (if start with snap/fast sync, it will need NVMe SSD)
16 cores of CPU and 64 gigabytes of memory (RAM).
Suggest m5zn.3xlarge instance type on AWS, c2-standard-16 on Google cloud.
A broadband Internet connection with upload/download speeds of 5 megabyte per second

**Validator**

VPS running recent versions of Mac OS X or Linux.
IMPORTANT 2T GB of free disk space, solid-state drive(SSD), gp3, 8k IOPS, 250MB/S throughput, read latency <1ms
16 cores of CPU and 64 gigabytes of memory (RAM)
Suggest m5zn.3xlarge instance type on AWS, or c2-standard-16 on Google cloud.
A broadband Internet connection with upload/download speeds of 10 megabyte per second

https://docs.binance.org/smart-chain/developer/fullnode.html

**Comment by uniftyitadmin** [comment]
I have 2 x 1TB NVME Disks in RAID 0 which means that i have 2 TB in total. That should be enough for the start.

/dev/md2 shows my disk space.
![image](https://user-images.githubusercontent.com/91486835/146939873-602f0a4b-b78c-4cf1-abff-8880f88d483a.png)

Only thing that can be the problem is number of cores since i have AMD Ryzen 7 3700X 8-Core CPU.

I will use stronger HW in the future,i just want to make sure that my problem is actually related with lack of hardware resources.

**Comment by RumeelHussainbnb** [comment]
Hi @uniftyitadmin thanks for confirming I already mentioned that its a hardware issue.  You can join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by forcodedancing** [comment]
Hello @uniftyitadmin can you follow the tips in [#502 #338] ?

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
