### ISSUE TITLE
please change your go module name

### ISSUE THREAD

**Issue by liuxh-go** [binance-chain/bsc#67]
change `github.com/ethereum/go-ethereum` to `github.com/binance-chain/bsc` in go.mod file

**Comment by guagualvcha** [comment]
hi, if do change that in `go.mod`,  need to modify most of the imports.

**Comment by liuxh-go** [comment]
You can use global replacement to modify, if you don’t modify it, I can’t directly use go moudle to reference your project in my project.

**Comment by guagualvcha** [comment]
I think you can use `replace` to solve this, like https://my.oschina.net/jsmagic/blog/2994278

**Comment by liuxh-go** [comment]
ok,tks
