### ISSUE TITLE
Can we create our blockchain and network with bsc source code ?

### ISSUE THREAD

**Issue by Serqati** [binance-chain/bsc#671]

**Comment by noXi89** [comment]
Probably. A fork could be a great thing.

**Comment by Serqati** [comment]
@noXi89 and can we access source code of tokens that random people build those on our network/blockchain ? 
(For creating a 'getabi' api method like bscscan's api)

**Comment by noXi89** [comment]
You can do whatever you want if you fork a project. But I would encourage you to dig deeper into what smart contracts are and how they are added to the chain. If you do any complex stuff while adding a tx to a block, another verifier could find another solution and be faster in publishing the block.

**Comment by RumeelHussainbnb** [comment]
Please refer to BSC whitepaper 
https://github.com/binance-chain/whitepaper/blob/master/WHITEPAPER.md

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
