### ISSUE TITLE
Tx not ordered by Gas Price anymore? 

### ISSUE THREAD

**Issue by FeurJak** [binance-chain/bsc#674]
Can someone tell me what's going on here. Spotted something strange in this block. 

Tx: (https://bscscan.com/tx/0x671828dc2de009c8dfd549f1d892ea0d2b758fe948a847c8e36175cb637cb7ee) is sitting on index 50 of block 13605757. It should be sitting on index of 1. But yet it's been pushed back to index 50 among 5 gwei txs. 

I thought Tx is ordered by Gas Price and then by time of arrival ?

**Comment by FeurJak** [comment]
similary: (https://bscscan.com/tx/0xf5697a0af2efba15a38d862e5bf86111fd79a2fd2a568217190266d5d2742343) , should be sitting on index of 1 of block 13607006, yet it's been pushed back to index of 43 among 5 gwei txs.

**Comment by FeurJak** [comment]
similary: (https://bscscan.com/tx/0xf5697a0af2efba15a38d862e5bf86111fd79a2fd2a568217190266d5d2742343) , should be sitting on index of 1 of block 13607006, yet it's been pushed back to index of 43 among 5 gwei txs.

**Comment by a04512** [comment]
because he use the same account with increased nonce,
for example,
nonce 1  gas:15
nonce 2  gas:20
your transaction 2 will be after transaction 1 which means lower gas price be front of higher gas price

**Comment by FeurJak** [comment]
> because he use the same account with increased nonce, for example, nonce 1 gas:15 nonce 2 gas:20 your transaction 2 will be after transaction 1 which means lower gas price be front of higher gas price

Thanks for the quick reply.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case .  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
