### ISSUE TITLE
Geth not writing logs

### ISSUE THREAD

**Issue by francesco-clementi-92** [binance-chain/bsc#675]
#### System information

Geth version: `1.1.7`
OS & Version: Windows

#### Expected behaviour
Finding logs in folder /node

#### Actual behaviour
After enable metrics flag, logs are no more updated/written in usual folder. My last log is at the moment I restarted geth with metrics flag (12h ago)

````
.\geth_windows.exe --metrics --metrics.addr 0.0.0.0 --config .\config.toml --datadir .\node --cache 55000 --diffsync --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode fast --http --http.api web3,eth,personal  --ws --ws.api web3,eth,personal --ws.rpcprefix /websocket
````

**Comment by RumeelHussainbnb** [comment]
`[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info" 
`
You can monitor the log from /node/bsc.log by default(tail -f -n 100 /node/bsc.log). If you wanna see log from geth cmd, Let's remove [Node.LogConfig] section.

**Comment by francesco-clementi-92** [comment]
Sorry the version is already the latest.

I have the logs splitted by hour in that folder, but after I enabled metrics, geth stopped to generate them

![Capture](https://user-images.githubusercontent.com/30288622/146730925-4e6ce0e9-4227-46af-a8f2-8d5926f124f2.PNG)

You can see from the photo that geth is still working, but it doesn't generate any more log.

The ssd have plenty of space

**Comment by francesco-clementi-92** [comment]
@guagualvcha why did you label as question? It seems to me as a bug

**Comment by forcodedancing** [comment]
@francesco-clementi-92 Can you share your config.toml for the log section?

**Comment by francesco-clementi-92** [comment]
Actually I fixed the issue by downloading again the binary file.

conif.toml:
```
[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20
Default = 5000000000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 30
NoDiscovery = false
BootstrapNodes = ["enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311","enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311","enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"]
StaticNodes = ["enode://c688c9a868374ec4fd99f3bf668bff6f1b3c4f7ef6ffa3e908897e4fdc7be99f239d9d3e698db9bc12ae41291b6d32eeaef1d5665662d84b4cf09756e54e4052@3.226.45.227:30311","enode://d61a31410c365e7fcd50e24d56a77d2d9741d4a57b295cc5070189ad90d0ec749d113b4b0432c6d795eb36597efce88d12ca45e645ec51b3a2144e1c1c41b66a@34.204.129.242:30311","enode://c753758ca72c55dd389c270d4f94dbb5ef6141649f0e3dabe515498378dde9c0363deb8614ad2568a8f020eb02de5eea41f9116eed735972be9ffa452a1ff242@54.81.254.21:30311","enode://cfbdc91fe451b4ec95b3b96a379a4b3464ca7d33fe5f0d6783c45dcfaf4431a22a176d2d8aeea6f6309d7c3153e4b307de06aac52b76e39c4146840bc4956bfb@54.236.113.206:30311","enode://bf081097931e2a5e092d6df2e903dab87551d4a6ce3b3da1b3df5c1ee705fc3e3191266e6227fea058ce4e1299cf7092f7dee80df2eadced92fd8263406b0b64@34.237.238.206:30311","enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@100.24.179.110:30311","enode://c09132e0ac4875c1b0ac2856e032875f174debc76c779b125ec2dc44e94ae42b6db4412b970f15a6e618a48a6ffff6f42230222d6e61e30fd4426a1af82b154b@54.85.57.23:30311","enode://c6ffd994c4ef130f90f8ee2fc08c1b0f02a6e9b12152092bf5a03dd7af9fd33597d4b2e2000a271cc0648d5e55242aeadd6d5061bb2e596372655ba0722cc704@54.147.151.108:30311","enode://786acbdf5a3cf91b99047a0fd8305e11e54d96ea3a72b1527050d3d6f8c9fc0278ff9ef56f3e56b3b70a283d97c309065506ea2fc3eb9b62477fd014a3ec1a96@107.23.90.162:30311","enode://d257b0f8d362161bb4a18b13253b1f6abb273a89d85fed73458f84dbf52d14ce556fd32ac07cbc49cd69d99c03ceddeccab919e10351c9d4e795a4c36404aef7@3.218.112.8:30311","enode://2aadea249d51e076060c97cbc293a2d90052d1786062f137aa8f4afe06996b674ecdbe660d3033b3d46d9cdaf2c3e3db6c031e218edc5a2613caa7f9705774f9@34.193.176.125:30311","enode://0e8b399223f64479d5022b76e8f025214183d0a01b7f044a38a1844f57e9fe89d5da1fa04071758d0c39fe6afba4d5798703b4200a5078664c488129ff8239b7@18.207.56.184:30311","enode://742a02a0d8612e6c4a3669f525a9a045e5c7b0d38ab728ca7086901c5f00b90cab8d796eff64dcfa516cff4e45591f8cb3a1e34277810f84e22ac72311c42cd8@52.21.104.255:30311","enode://9f2246671f19410e722b4f977e0f2997a95a1614fafccc2db15c9dee810bfb10628d3ecc0f6eed5c2cbc1f7fc71b5fb5eb3afcd533cba5f02a6bda673f99ce29@54.204.215.58:30311","enode://bcccac7dfbd21bd1dbbb7bf64ef7af6986520091f00320905e5919d12167fc8c94698099946933747ad2ea24745d35ebc980f9ba1475a839c83574d5ccf318d9@34.196.94.250:30311","enode://20d04257749893d7193b8e3ed619d46384d28b350508bef163b52ee9dc60efc4f562aee00c7fde5cfa83e4e9723b0e90d6422d9031b6069734bd7e24a9ed8e73@107.21.209.99:30311"]
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```
Here the steps that caused the issue:

1. started the geth with `.\geth_windows.exe --config .\config.toml --datadir .\node --cache 55000 --diffsync --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode fast --http --http.api web3,eth,personal  --ws --ws.api web3,eth,personal --ws.rpcprefix /websocket`
2. logs are generated
3. stopped geth
4. started geth with `.\geth_windows.exe --metrics --metrics.addr 0.0.0.0 --config .\config.toml --datadir .\node --cache 55000 --diffsync --rpc.allow-unprotected-txs --txlookuplimit 0 --syncmode fast --http --http.api web3,eth,personal  --ws --ws.api web3,eth,personal --ws.rpcprefix /websocket`
5. logs are no more generated
6. stopped geth
7. downloaded same geth binary exe
8. started geth with same command as 4

I don't know it is possible, but now logs are generated.

**Comment by francesco-clementi-92** [comment]
Need to reopen.

I started with a new sync as the last one was having problem.

Now it still not genereting logs.

Any debug action?

**Comment by forcodedancing** [comment]
I checked our nodes, the logs are generated correctly. 
![Screen Shot 2021-12-23 at 14 12 27](https://user-images.githubusercontent.com/61674316/147196893-a1ceac7d-2b3b-41d6-bab4-4c7d8d956b2d.png)

Can you check 1) whether the process is running with the correct permissions; 2) is there any space issue; 3) check the open files (e.g., lsof  command) ? thanks.

**Comment by francesco-clementi-92** [comment]
Ok the problem is with permissions. 
If I start the node with run as administrator it started to write the logs again.

But in windows how can I set the right permissions? 

Maybe the problem is the path where I set geth? C:\geth ?

**Comment by forcodedancing** [comment]
I am not sure of this; it could depend on the OS version you are using. [Ref from Internet](https://www.digitalcitizen.life/run-as-admin/)
You can also change the r/w permissions of the folder where logs are sitting in.

**Comment by francesco-clementi-92** [comment]
I don't think that to use geth we should "run as an administrator", but it's the only solution for now (still can't understand why during some of the test it doesn't need it), but I can close the issue as it's been resolved.
