### ISSUE TITLE
Bsc node fails

### ISSUE THREAD

**Issue by Neoblock8** [binance-chain/bsc#677]
Hi,

#### System information

Geth version: ` 1.1.7`
OS & Version: Linux
Commit hash : (if `master`)

Running private geth node in server with 1TB and 16GB RAM. But it will fails often, after restart the block will generate from the beginning. How to overcome this issue?

Running Commands:
./geth --datadir data init <path_of_genesis>/genesis.json
./geth --datadir data --networkid 1001 --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock --rpc.txfeecap 0 --cache=1024 console

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by psdlt** [comment]
@Neoblock8 1TB is not enough. You will need *at least* 2TB, preferably 3 or 4... Also consider adding more RAM, 16GB isn't that much either.

**Comment by Neoblock8** [comment]
> @Neoblock8 1TB is not enough. You will need _at least_ 2TB, preferably 3 or 4... Also consider adding more RAM, 16GB isn't that much either.

Is 1TB not enough for private network in BSC?

**Comment by psdlt** [comment]
@Neoblock8 oh, I thought you’re running a regular full node. No idea what’s wrong with your private node, sorry.

**Comment by panalyticsBsc** [comment]
Hmm hard to say..

Did you follow the guide on: [Local BSC Network](https://docs.binance.org/smart-chain/developer/deploy/local.html)

**Comment by RumeelHussainbnb** [comment]
Follow the guide here. It can bring up local BSC private network, either one node or a cluster.
https://github.com/binance-chain/bsc-docker
