### ISSUE TITLE
Miner reward 

### ISSUE THREAD

**Issue by Neoblock8** [binance-chain/bsc#678]
Hi,
 Running private node in BSC network. But miner reward is not getting added.

**Comment by psdlt** [comment]
@Neoblock8 there are no miner rewards for running a BSC node.

**Comment by Neoblock8** [comment]
@psdlt, Then what is the reward for miners?

**Comment by psdlt** [comment]
@Neoblock8 there are no miners on BSC :) do some research on how BSC works

**Comment by Neoblock8** [comment]
> @Neoblock8 there are no miners on BSC :) do some research on how BSC works

Then what about transaction fee?

**Comment by psdlt** [comment]
@Neoblock8 tx fee goes to validators. Not sure how that works in a private setup.

**Comment by Neoblock8** [comment]
> @Neoblock8 tx fee goes to validators. Not sure how that works in a private setup.

what is the block reward in BSC?

**Comment by psdlt** [comment]
@Neoblock8 it seems to me you’re not really sure what you’re trying to achieve here. Please do a research first, you can start by asking same questions on google.

**Comment by RumeelHussainbnb** [comment]
Please follow the BSC Docs you will almost get the answers here:

https://docs.binance.org/smart-chain/guides/bsc-intro.html
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by forcodedancing** [comment]
@Neoblock8 
If you are interested in the Reward and other things about BSC, the [white paper](https://github.com/binance-chain/whitepaper/blob/master/WHITEPAPER.md#reward) is a good material. All answers are there.

I will close this issue. And if you have further questions, feel free to create another one. Thanks.
