### ISSUE TITLE
BSC block reward

### ISSUE THREAD

**Issue by osiz-blockchainapp** [binance-chain/bsc#679]
Hi,
 What is the block reward in bsc?
 Which consensus algorithm used in bsc?

**Comment by dgdeivid** [comment]
Here you can read the docs: https://github.com/binance-chain/bsc

**Comment by RumeelHussainbnb** [comment]
Please follow the docs: 

https://docs.binance.org/smart-chain/guides/concepts/consensus.html
https://docs.binance.org/smart-chain/guides/concepts/genesis.html

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
