### ISSUE TITLE
Sync Issue  peer=xxxxxxxx err="peer not registered"

### ISSUE THREAD

**Issue by vovapwn** [binance-chain/bsc#681]
#### System information

Geth version: last release
OS & Version: ubuntu 20.04 LTE
AMD Ryzen 9 3900, 12 core, 128GB
4 x 2 TB NVMe raid0

#### Expected behaviour

Worked fine for a few weeks, then issue happened (2-3 days ago first, and now continues)

#### Actual behaviour

75% of all time is still working fine, but then stuck for 20-30 seconds, and that line appeares:

Sync Issue  peer=xxxxxxxx err="peer not registered"

after that catches up very fast till the last block and works for a few minutes normal until next stuck.
Then everything repeats.

**Comment by forcodedancing** [comment]
@vovapwn Hello, does the issue still exist? It looks like a network/connection issue.

**Comment by vovapwn** [comment]
@forcodedancing 
Hello,
According to my logs last 14 hours everything seems to be OK. Before that there were occasional errors, like one-two in an hour. I forgot to mention, I had two nodes with the same specs: one in Germany, another in Finland. And errors were on both. Now both are OK.

There is another error though every minute or so:

ERROR[12-23|09:20:03.405] do light process err at block            num=13,720,737 err="account storage root mismatch"

But it doesnt seem to affect node performance.

**Comment by forcodedancing** [comment]
@vovapwn Thanks for your sharing about the issue, we think "peer not registered" could be a bug, it should not be critical and we will look into it. 
For  "account storage root mismatch", it should no impact and this issue has already been fixed. You can ignore it and you can refer to #672 for more details if you are interested.

**Comment by forcodedancing** [comment]
We will close this issue. For the "peer not registered" one, it will be tracked by #220 Thanks.

**Comment by Jolly23** [comment]
#856 fixed
