### ISSUE TITLE
No snapshot paired state

### ISSUE THREAD

**Issue by JohnsonCaii** [binance-chain/bsc#683]
Hi I'm trying to prune the data state, but it always showed `no snapshot paired state`, wondering why?
```
$ /opt/bsc/geth1.1.7 snapshot prune-state --datadir /data/bsc

INFO [12-22|09:30:31.331] Maximum peer count                       ETH=50 LES=0 total=50
INFO [12-22|09:30:31.332] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [12-22|09:30:31.335] Set global gas cap                       cap=25,000,000
INFO [12-22|09:30:31.335] Allocated cache and file handles         database=/data/bsc/geth/chaindata cache=408.00MiB handles=32767
INFO [12-22|09:30:41.032] Opened ancient database                  database=/data/bsc/geth/chaindata/ancient readonly=false
INFO [12-22|09:30:41.075] Deep froze chain segment                 blocks=3 elapsed=16.440ms number=13,593,853 hash=dfa474..30af1a
INFO [12-22|09:30:41.226] Snapshot loaded                          diskRoot=a4a5d2..c62ad0 root=516556..6ee7e2
INFO [12-22|09:30:41.867] Initialized state bloom                  size=2.00GiB
ERROR[12-22|09:30:47.291] Failed to prune state                    err="no snapshot paired state"
no snapshot paired state
```

This is my start command.
```
$ /opt/bsc/geth1.1.7 --config=/opt/bsc/config.toml --syncmode=snap --datadir=/data/bsc --http --http.addr=0.0.0.0 --http.port=8545 --http.vhosts=* --nodiscover --http.corsdomain=* --diffsync --
cache=8000 --txlookuplimit 0 --txpool.reannouncetime 5m
```

And the data volume usage right now.
```
/dev/nvme1n1p1  3.5T  2.9T  596G  83% /data
```

It seems the only way to reduce the disk is to redownload the bsc snapshot and resyncing?

**Comment by forcodedancing** [comment]
Can you try the solution mentioned in [#256 ](https://github.com/binance-chain/bsc/issues/256) ?

**Comment by JohnsonCaii** [comment]
Yes I used snap sync mode but no good. I've deleted the data and redownloaded it from the bsc snapshot.

I still have 3 more bsc servers that need to prune-state periodically, so I wanna know the root cause of this issue, any input will be appreciated. Thanks!

**Comment by masayil** [comment]
I have the same problem

**Comment by forcodedancing** [comment]
@JohnsonCaii @masayil Hello, for the solution #256 , for the step 1 (resync) you need to wait for a while, usually it needs several hundreds of blocks to make sure the new snapshot has been created. Could you try it with the latest binary? thanks

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
