### ISSUE TITLE
Setting up a full node while getting err="etherbase must be explicitly specified"

### ISSUE THREAD

**Issue by ai323** [binance-chain/bsc#684]
I was trying to setup a full node and getting err="etherbase must be explicitly specified".

I followed the steps here https://docs.binance.org/smart-chain/developer/fullnode.html and syncing from snapshot, it was running for a day or two and suddenly throw me the error that etherbase is not specified.

If I understand correctly, running a full node is just acting as a witness node and no etherbase is required? Anyway, how to resolve this issue and getting my full node properly running? Should I follow the steps in the "syncing from genesis" section and init from the genesis.json?

**Comment by forcodedancing** [comment]
Can you try the steps in "Sync From Snapshot" section? 
You do not need to init genesis.json. "Sync From Snapshot"  and "Syncing From Genesis" are two options, pick one is fine.

**Comment by ai323** [comment]
> Can you try the steps in "Sync From Snapshot" section? You do not need to init genesis.json. "Sync From Snapshot" and "Syncing From Genesis" are two options, pick one is fine.

That's exactly what I did: followed the steps in the "Sync From Snapshot" section and it gave the above erros.

**Comment by forcodedancing** [comment]
Hello @ai323  can you check whether you are using the correct binary, and can you have a try with [the latest binary and config files](https://github.com/binance-chain/bsc/releases)? thanks

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by ares0x** [comment]
![image](https://user-images.githubusercontent.com/53114112/148370547-c79c0364-69c7-4470-893e-b54f5ebdc54a.png)
I ran into the same situation.
