### ISSUE TITLE
About Zero Gas

### ISSUE THREAD

**Issue by AutoBoyWinner** [binance-chain/bsc#685]
Hi, everyone.
Very sorry for bothering you.
The sweeper is attacking my wallet since a week ago.
I contacted Flash bot, but there is no answer.
I want to rescue token.
When I send BNB to my wallet,  BNB is disappeared soon.
I have just read the link below and get the word about Zero fee.
https://github.com/binance-chain/bsc/issues/658
I'm a beginner, so I'm not sure about the contents of this link. Could you please share some specific source code?
I will never use it for any bad purpose. Never misunderstand me as a scammer.
Please give me only one chance.

**Comment by forcodedancing** [comment]
Sorry for your bnb loss, it was an attack.
For the issue you mentioned, it is not related to any attack; it is kind of technical discussion/issue.

**Comment by DreamLxq** [comment]
你丢钱了?(You lost your money?)

**Comment by sleepyyypt** [comment]
could you fix anyway?
