### ISSUE TITLE
[Question] What are the exact conditions to replace an already sent transaction?

### ISSUE THREAD

**Issue by aplut** [binance-chain/bsc#689]
Hey folks,

as far as I know, there is a chance to change a sent transaction before including it in the blockchain. For example, when I send a transaction, after 100ms I send a second similar transaction with the same nonce and a higher gas price. From time to time the first transaction is replaced, I don't understand why only from time to time? My first assumption was that it depends on when a new block is created (because after block creation the transaction is removed from the mempool and cannot be changed?). I've tested this assumption, but I can't confirm that it is correct. In my tests, I've sent the first transaction and waited for the next block, after receiving the new block the second one is sent. Not always, but sometimes it happens that the first transaction is replaced. Do you know explicit conditions when and which transactions can be replaced? Thanks in advance!

Cheers,
Adrian

**Comment by psdlt** [comment]
@aplut your assumption is correct. You can replace your first tx with your second tx as long as 2nd tx reaches validator sooner than they start building next block. It's a race condition basically, not really an exact science.

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
