### ISSUE TITLE
graphql error

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#691]
![image](https://user-images.githubusercontent.com/65291464/147801036-3769bcbc-038c-4ef0-a800-3dbc3dc4ac3c.png)
![image](https://user-images.githubusercontent.com/65291464/147801277-10ce7186-8c34-4763-9e53-ba10363bef82.png)

Querying for blocks which are not present. This behavior can cause this error

**Comment by forcodedancing** [comment]
Hello @masayil the issue comes from graphql-go. Could you report the issue in their repo instead? thanks 
https://github.com/graphql-go/graphql/issues

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
