### ISSUE TITLE
Node check balance Issue

### ISSUE THREAD

**Issue by coininn-exchange** [binance-chain/bsc#692]
I have synced to the latest height, and use fast mode
`ount=2    elapsed="922.287µs" number=13,948,435 hash=0xb480083d46e82411248de58c133b8c85b96c8d43feed166c2c60bdd5733ec553
t=2021-12-31T06:17:28+0000 lvl=info msg="Imported new state entries"             count=384  elapsed="39.861µs"  processed=329,645,646 pending=49758 trieretry=0   coderetry=0 duplicate=0 unexpected=0
t=2021-12-31T06:17:29+0000 lvl=info msg="Initializing state bloom"               items=124,393,021 errorrate=0.000 elapsed=22m40.383s
t=2021-12-31T06:17:31+0000 lvl=info msg="Imported new block headers"             count=2    elapsed="739.132µs" number=13,948,437 hash=0x78da0cc59f6f26a15589ffbd1a7cec2301c0e2f3f01dab3bc30397b3ccc17e84`

curl --location --request POST 'http://127.0.0.1:8545/' \
> --header 'Content-Type: application/json' \
> --data-raw '{
> "jsonrpc":"2.0",
> "method":"eth_getBalance",
> "params":[ 
> "0xa180Fe01B906A1bE37BE6c534a3300785b20d947", 
> "latest"
> ],
> "id":1
> }'
{"jsonrpc":"2.0","id":1,"result":"0x0"}

**Comment by forcodedancing** [comment]
@coininn-exchange Tested on our node, the result is expected.
`curl  -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa180Fe01B906A1bE37BE6c534a3300785b20d947", "latest"],"id":74}' https://bsc-dataseed.binance.org/

{"jsonrpc":"2.0","id":74,"result":"0x7b16abc585cace586a7"} `

Are you running multi nodes? Can you further check the port and host you are using is correct? thanks

**Comment by coininn-exchange** [comment]
Yes, I can use other nodes to query normally, but my height is also synchronized to the latest, but the balance  cannot be queried. What could be the reason for this?

**Comment by coininn-exchange** [comment]
> @coininn-exchange Tested on our node, the result is expected.
> 
> ```
> curl  -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa180Fe01B906A1bE37BE6c534a3300785b20d947", "latest"],"id":74}' https://bsc-dataseed.binance.org/
> 
> {"jsonrpc":"2.0","id":74,"result":"0x7b16abc585cace586a7"} 
> ```
> 
> Are you running multi nodes? Can you further check the port and host you are using is correct? thanks

Yes, I can use other nodes to query normally, but my height is also synchronized to the latest, but the assets cannot be queried. What could be the reason for this?

**Comment by coininn-exchange** [comment]
![image](https://user-images.githubusercontent.com/81599843/147810798-2f159b6f-0b33-470b-9618-60f951d4d8fe.png)


> @coininn-exchange Tested on our node, the result is expected.
> 
> ```
> curl  -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa180Fe01B906A1bE37BE6c534a3300785b20d947", "latest"],"id":74}' https://bsc-dataseed.binance.org/
> 
> {"jsonrpc":"2.0","id":74,"result":"0x7b16abc585cace586a7"} 
> ```
> 
> Are you running multi nodes? Can you further check the port and host you are using is correct? thanks

![image](https://user-images.githubusercontent.com/81599843/147810810-f63e3ad1-ad89-488a-bce1-e537cdc60458.png)

**Comment by coininn-exchange** [comment]
> @coininn-exchange Tested on our node, the result is expected.
> 
> ```
> curl  -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa180Fe01B906A1bE37BE6c534a3300785b20d947", "latest"],"id":74}' https://bsc-dataseed.binance.org/
> 
> {"jsonrpc":"2.0","id":74,"result":"0x7b16abc585cace586a7"} 
> ```
> 
> Are you running multi nodes? Can you further check the port and host you are using is correct? thanks

![image](https://user-images.githubusercontent.com/81599843/147810896-cf4b3f3a-dd8d-47b2-b335-a7594ebd7a52.png)
