### ISSUE TITLE
Database compacting, degraded performance

### ISSUE THREAD

**Issue by interfuse1** [binance-chain/bsc#693]
I am running a BSC Archive node and having trouble syncing due to "Database compacting, degraded performance". This is happening a couple of times a day and lasts 2-4 hours each. Because of this, we are falling behind with our sync. Is there any way to bypass this?

**Comment by kyrie-yl** [comment]
Although bsc support no compaction by `nocompaction` flag, this will degrade performance too if you use it. While, you can run our erigon version which is storage optimized and at beta version.

**Comment by guagualvcha** [comment]
Erigon-bsc: https://github.com/binance-chain/bsc-erigon
