### ISSUE TITLE
How to make my node as fast as possible

### ISSUE THREAD

**Issue by Gerraldin** [binance-chain/bsc#695]
Hi, so i am running a node on a decent ubuntu computer, 64 GB ram, 4T of NVME SSD, 12 cores... i have encountered an issue where if i have a nodejs client running and querying the node for stuff like balance, or simple contract functions, i get very slow response times if it gets heavy on the requests, what is the best config for maximum requests capacity? i want people to be able to use my node for serious queries (the amount of responses i tested is about 100-1000 requests per second)

**Comment by RumeelHussainbnb** [comment]
https://github.com/binance-chain/bsc/issues/502 

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
