### ISSUE TITLE
 "code: -32000, message: 'header not found'"   Error when i deploy to Binance main net 

### ISSUE THREAD

**Issue by ZaidAhed-Halim** [binance-chain/bsc#698]
#### System information

truffle : v5.1.49
Web3.js v1.2.1

when ever i try to deploy my smart contract to binance testnet it works fine but with main net it throws this error always 
i even tried all the mainnet RPCs and all same issue 
i have done some research and lately lots of people can't deploy to binance main net and facing exact same issue 
any idea if its gonna be fixed or have any solution ?

**Comment by RumeelHussainbnb** [comment]
Please follow the Setting up the development environment Guide using Truffle:

```
bsc: { provider: () => new HDWalletProvider(mnemonic, https://bsc-dataseed1.binance.org`),
network_id: 56,
confirmations: 10,
timeoutBlocks: 200,
skipDryRun: true
}`
```

https://docs.binance.org/smart-chain/developer/deploy/truffle-new.html

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by ZaidAhed-Halim** [comment]
tried it  still same issue 

    On Tuesday, January 4, 2022, 02:36:00 PM GMT+2, RumeelHussainbnb ***@***.***> wrote:  
 
 


Please follow the Setting up the development environment Guide using Truffle:
bsc: { provider: () => new HDWalletProvider(mnemonic, https://bsc-dataseed1.binance.org`),
network_id: 56,
confirmations: 10,
timeoutBlocks: 200,
skipDryRun: true
}`

https://docs.binance.org/smart-chain/developer/deploy/truffle-new.html

Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZaidAhed-Halim** [comment]
i tried it same issue

**Comment by RumeelHussainbnb** [comment]
Please try to use These RPC:

https://bsc-dataseed.binance.org/
https://bsc-dataseed1.defibit.io/
https://bsc-dataseed1.ninicoin.io/

**Comment by realuncle** [comment]
The public BSC nodes do not always sync to the latest height,  I guess there are a bunch of nodes behind the endpoints. Please try our more stable RPC service: https://nodereal.io/

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
