### ISSUE TITLE
NodeReal validator is not respecting the gas ordering in block.

### ISSUE THREAD

**Issue by dgdeivid** [binance-chain/bsc#699]
**First transaction of the block** (20.112792903 Gwei)
https://bscscan.com/tx/0x5c428e03e2dccbaed407f9e44fde01afc1ef9766367fe44a6c8a8d0b72df3b7e

**Second transaction of the block** (160.05155077 Gwei)
https://bscscan.com/tx/0x11939b9664c914a1b87b8a760fc043fb0c4e7bae6623bf9a6b1ac8a414a45a24

Block:
https://bscscan.com/txs?block=14071137&p=5

This behavior is due to its own benefit, since it can be clearly seen that it is front-running on the same token to other swaps, ignoring the gas.

**Comment by imharvol** [comment]
Related: #658

**Comment by Lucienest** [comment]
NodeReal must be jailed for it's malicious behavior

**Comment by Zaczero** [comment]
Dear BSC team,

Please ensure the same, strict order (by gas price) for all transactions in blocks on the network layer. It will not solve the issue at its core but will:
1) make it more expensive to operate maliciously (by having to pay fair gas prices)
2) make the programming more 'logical'; I bet there are scenarios where people would benefit from a standardized way of ordering transactions in a block - for example, an efficient custom gas price estimator (since we are already on-route to paying higher gas prices due to full network utilization)

**Comment by DreamLxq** [comment]
说那么多有什么用呢?你看看人家Matic(polygon),人家交易就是随机排序的....
from translate.google.cn
What's the use of saying so much? Look at Matic (polygon), people's transactions are sorted randomly...

**Comment by DreamLxq** [comment]
说那么多有什么用呢?你看看人家Matic(polygon),人家交易就是随机排序的....
from translate.google.cn
What's the use of saying so much? Look at Matic (polygon), people's transactions are sorted randomly...

**Comment by dgdeivid** [comment]
> 说那么多有什么用呢?你看看人家Matic(polygon),人家交易就是随机排序的.... from translate.google.cn What's the use of saying so much? Look at Matic (polygon), people's transactions are sorted randomly...

That is not at all correct, at Polygon transactions are ordered by gas.

Look at any block: https://polygonscan.com/txs?block=23382154&p=2

If the transactions were ordered randomly, it would be useless to put less or more gas.

BSC's problem is that at least one validator bypasses gas sorting for its own benefit.

**Comment by yoongyy** [comment]
For all of your information, many of the BSC validators are from BSC itself (including NodeReal)
So it is useless to ask Binance to penalty itself???

Secondly, all other validators on BSC are doing the same things, why people staking million of BNB to become a validator? Just to receive a little transaction fee every 21 blocks???

If you have million of BNB, you can do the same lolx...
To be honest this is rich become richer game, other chains also the same...
Even if you go and talk to CZ(boss of Binance), I guess he will reply to you, if you don't like BSC, you can left it, he does not care about it...

**Comment by dgdeivid** [comment]
We have discovered that they are ignoring the gas in favor of the frontrunners and against the normal users because they have implemented that system poorly. They say that now that we have caught them, they are not going to continue behaving properly (at least in terms of gas order). They do not inspire any confidence as they can continue to cheat with the gas and the order of the transactions doing the same thing, but without being noticed due to a more complex implementation.

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild

**Comment by Lucienest** [comment]
> Please check the response from nodereal: #658

Are u favoring Nodereal? there's clearly something sketchy going around.
