### ISSUE TITLE
Sync issue with possible fork

### ISSUE THREAD

**Issue by affaxltd** [binance-chain/bsc#70]
Hello, getting this problem while running geth.
I ran all of the commands required and applied the genesis.
Is this a known issue?

![image](https://user-images.githubusercontent.com/59908257/107111573-de8b9600-6859-11eb-9668-0ed7b4bcb1bd.png)

**Comment by guagualvcha** [comment]
No worry, please refer to: https://github.com/binance-chain/bsc/issues/65

**Comment by affaxltd** [comment]
Alright, thank you @guagualvcha!
