### ISSUE TITLE
native tracer support

### ISSUE THREAD

**Issue by sjl623** [binance-chain/bsc#700]
# Rationale

Why should this feature exist?
When using RPC call in debug namespace like trace_call, a tracer could be given to customize debug behave. But only JS script is supported to be given, which run under JSVM env. It may lead to additional performance cost. Maybe native tracer should be supported.
What are the use-cases?
Write tracer in native language, which compile with geth, to improve tracer running performance.

# Implementation

Do you have ideas regarding the implementation of this feature?
Yes. The origin repository go-ethereum have supported it in [here](https://github.com/ethereum/go-ethereum/tree/master/eth/tracers). 
Are you willing to implement this feature?
Any plan to merge go-ethereum has been scheduled? If not, I could  have a try by refering the existing implementation in go-ethereum.

**Comment by guagualvcha** [comment]
Hi, BSC will support native tracer in next release, actually it is on the develop branch now, please check: https://github.com/binance-chain/bsc/pull/581
