### ISSUE TITLE
Sync from genesis and after 10mill set gcmode archive

### ISSUE THREAD

**Issue by radian-rgc** [binance-chain/bsc#703]
Hi

I started syncing from genesis by below command:

`./build/bin/geth --diffsync --config ./config.toml --snapshot=false  --syncmode fast --gcmode full --datadir ./node  --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 0  --ws`

And after fetched 10mill blocks, i changed the gcmode to **Archive**  by following command:

`./build/bin/geth --diffsync --config ./config.toml --snapshot=false  --syncmode fast --gcmode archive --datadir ./node  --cache 30000 --rpc.allow-unprotected-txs --txlookuplimit 0  --ws`

And after 30 hours, the sync is completed but now i cant access to the 12mill block for get balance...

Have I done the wrong steps?

The purpose of this is that I do not need to archive all blocks and only need archive blocks after 10 millions

**Comment by radian-rgc** [comment]
I think i must set `--syncmode full `

**Comment by kyrie-yl** [comment]
> 
yes, how is going with `--syncmode full`?

**Comment by radian-rgc** [comment]
> > 
> 
> yes, how is going with `--syncmode full`?

Nothing change ... 😕

Mean i think must set syncmode full and gcmode Archive from start (0 block).

And i resync again from genesis with syncmode full and gcmode Archive. And now im waiting to finish it...

**Comment by guagualvcha** [comment]
hi @radian-rgc You can not initial setup the node with `fastsync` mode.

**Comment by j75689** [comment]
Hi, I will close this issue first, if you still have questions, please re-open this issue or create a new issue, thanks.
