### ISSUE TITLE
Сan't sync the last 64-100 blocks(

### ISSUE THREAD

**Issue by ArtemkaMakarenko** [binance-chain/bsc#707]
I can't sync the last 64-100 blocks, what am I doing wrong?
Someone can tell me where and how I can sync the node without problems?

**list of my servers on which I am trying  sync the node** 
 vultr  Bare Metal 8 cores / 16 threads @ 3.7 GHz   RAM 128 GB       10 Gbps Network 1.9 TB NVMe SSD
 AWS m5zn.3xlarge  12 vCPUs RAM 48.0 GiB    volum gp3  IOPS 15000  Throughput (MiB/s) 950
 AWS i3.2xlarge  8 vCPUs  RAM 61.0 GiB     1900 GB NVMe SSD 
 AWS  Dedicated Hosts i3en.2xlarge 8 CPU RAM 64.0 GiB     RAID0 5000 GB (2 * 2500 GB NVMe SSD) 
DigitalOcean Memory-Optimized  16 vCPUs  RAM 128 GB  RAID0 2.34 TB 6x SSD 
DigitalOcean   8 vCPUs   RAM 16 GB Memory   RAID0 5 volume 

**Сonfig and disk tests  one of my servers ** 
(  AWS Dedicated Hosts i3en.2xlarge 8 CPU RAM 64.0 GiB     RAID0 5000 GB (2 * 2500 GB NVMe SSD) )

instance: Geth/v1.1.7-74f6b613/linux-amd64/go1.16.10
at block: 0 (Mon Apr 20 2020 13:46:54 GMT+0000 (UTC))
 modules: debug:1.0 eth:1.0 net:1.0 personal:1.0 rpc:1.0 web3:1.0

To exit, press ctrl-d
> net.peerCount
62
> eth.syncing
{
  currentBlock: 14220573,
  highestBlock: 14220648,
  knownStates: 1604080420,
  pulledStates: 1603983829,
  startingBlock: 14217784
}
> 

**Сommand to start a node** 
`--syncmode fast --http --http.addr 0.0.0.0 --http.vhosts '*' --cache 40960 --http.api 'eth,net,web3,personal,debug' --rpc.allow-unprotected-txs --allow-insecure-unlock --txlookuplimit 0 --pprof --pprof.addr=0.0.0.0 --pprof.port=6060 --metrics`

**config.toml**
`[Eth]
NetworkId = 56
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 100000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 512
GlobalSlots = 10000
AccountQueue = 256
GlobalQueue = 5000
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 20

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
NoUSB = true
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
BootstrapNodes = ["enode://1cc4534b14cfe351ab740a1418ab944a234ca2f702915eadb7e558a02010cb7c5a8c295a3b56bcefa7701c07752acd5539cb13df2aab8ae2d98934d712611443@52.71.43.172:30311","enode://28b1d16562dac280dacaaf45d54516b85bc6c994252a9825c5cc4e080d3e53446d05f63ba495ea7d44d6c316b54cd92b245c5c328c37da24605c4a93a0d099c4@34.246.65.14:30311","enode://5a7b996048d1b0a07683a949662c87c09b55247ce774aeee10bb886892e586e3c604564393292e38ef43c023ee9981e1f8b335766ec4f0f256e57f8640b079d5@35.73.137.11:30311"]
StaticNodes = ["enode://b208ecff0e78b0de84fbed72ce4a39590903ead22759dc77b560298550394dd723b232daa42c76596a6763447dc3a7951027cc5fb3f8085d42775023c9412c63@23.21.154.239:30311", "enode://bcccac7dfbd21bd1dbbb7bf64ef7af6986520091f00320905e5919d12167fc8c94698099946933747ad2ea24745d35ebc980f9ba1475a839c83574d5ccf318d9@34.196.94.250:30311", "enode://8661a9799cb9c202c87c895b06de689279fb3b9795b7a00a33be04d0651331a3f0603b1056fb2a8a9eeea76a4396f6fa8d29d03b4f3f29f34adf33fe0e96d905@44.197.67.153:30311", "enode://3fe3aca8482301a3b966e40e66b9a924ede7bb10b6f76e2c1c0aa421e293189e44d381c652d9f875ea7f865829e9a8e6a5d006e5a5e54176aa2069dd18b18ef6@23.22.69.150:30311", "enode://29af5f724433add3047a2f20b4c82ca587fe507c579531798a4bad25cbcbb0243d9da94d14f8388b80a7780568db39c1bee7a8862b8bebe7f8c6eb34246d5569@3.215.144.57:30311", "enode://82776830495703594e88b2225509a42517545ec53c3da93eea51eaa1556e3a1d56a2bd342aca5519261d40ae9ade8ff81289d7fa1a999e6e7f698aad0aa0fce6@34.236.200.111:30311", "enode://ffb8116321f8c01bc0f33852d95f8779cd2e29711c089026464907b55fdaed8d1261f49ab68f0012594633f290f005d284e4b49cb50eba7b3634f4901ec9fa7d@34.193.27.17:30311", "enode://97be405ab074c15eca1a82625f6516f08488f3c39033d72e81e98996e0f3cbc5c047e89276f953c27a08f20f41ec334e819096be543206368ae1f71c0a438b88@3.216.10.24:30311", "enode://bcdd46e1e49986d3ea31010933e7910409afcc7766dbb9335c9f27202a2361a621632a4b5a8e2bfa9bf2019a49a3658122c3e5d6e8d8a16a6984df91e7aed6c9@107.21.209.99:30311", "enode://75c5f28810dda7533bfe6dd3ba16b61c3dd2ab5198edbd8279c5e34b22615932ed826da146fdb11f62680ad238a2d961bb1c7eb6f63e2a78683584ad7e9e0103@107.20.8.154:30311"]
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
`
**Testing disk performance with utilities  ioping and  fio** 

ioping -c 100

--- test/ (ext4 /dev/md0) ioping statistics ---
99 requests completed in 32.1 ms, 396 KiB read, 3.09 k iops, 12.1 MiB/s
generated 100 requests in 1.65 min, 400 KiB, 1 iops, 4.04 KiB/s
min/avg/max/mdev = 53.7 us / 323.8 us / 2.90 ms / 747.5 us

fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=8G --readwrite=randrw --rwmixread=75

fiotest: (g=0): rw=randrw, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.16
Starting 1 process
Jobs: 1 (f=1): [m(1)][100.0%][r=424MiB/s,w=141MiB/s][r=109k,w=36.2k IOPS][eta 00m:00s]
fiotest: (groupid=0, jobs=1): err= 0: pid=12054: Sun Jan  9 17:09:39 2022
  read: IOPS=109k, BW=425MiB/s (446MB/s)(6141MiB/14446msec)
   bw (  KiB/s): min=428912, max=438360, per=100.00%, avg=435327.82, stdev=1906.74, samples=28
   iops        : min=107228, max=109590, avg=108831.93, stdev=476.70, samples=28
  write: IOPS=36.3k, BW=142MiB/s (149MB/s)(2051MiB/14446msec); 0 zone resets
   bw (  KiB/s): min=142504, max=147592, per=100.00%, avg=145367.86, stdev=1278.79, samples=28
   iops        : min=35626, max=36898, avg=36341.96, stdev=319.71, samples=28
  cpu          : usr=23.41%, sys=64.77%, ctx=424696, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=1572145,525007,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=425MiB/s (446MB/s), 425MiB/s-425MiB/s (446MB/s-446MB/s), io=6141MiB (6440MB), run=14446-14446msec
  WRITE: bw=142MiB/s (149MB/s), 142MiB/s-142MiB/s (149MB/s-149MB/s), io=2051MiB (2150MB), run=14446-14446msec

Disk stats (read/write):
    md0: ios=1566737/523226, merge=0/0, ticks=142500/10184, in_queue=152684, util=99.36%, aggrios=786072/262504, aggrmerge=0/0, aggrticks=73772/5866, aggrin_queue=79637, aggrutil=99.07%
  nvme2n1: ios=786291/262285, merge=0/0, ticks=72881/5722, in_queue=78603, util=99.06%
  nvme1n1: ios=785854/262724, merge=0/1, ticks=74663/6010, in_queue=80672, util=99.07%

fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=8G --readwrite=randread

fiotest: (g=0): rw=randread, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.16
Starting 1 process
Jobs: 1 (f=1): [r(1)][100.0%][r=605MiB/s][r=155k IOPS][eta 00m:00s]
fiotest: (groupid=0, jobs=1): err= 0: pid=12067: Sun Jan  9 17:11:00 2022
  read: IOPS=155k, BW=606MiB/s (635MB/s)(8192MiB/13518msec)
   bw (  KiB/s): min=617944, max=622664, per=100.00%, avg=620542.56, stdev=1151.26, samples=27
   iops        : min=154486, max=155666, avg=155135.63, stdev=287.61, samples=27
  cpu          : usr=32.61%, sys=67.39%, ctx=28, majf=0, minf=73
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=2097152,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: bw=606MiB/s (635MB/s), 606MiB/s-606MiB/s (635MB/s-635MB/s), io=8192MiB (8590MB), run=13518-13518msec

Disk stats (read/write):
    md0: ios=2078610/0, merge=0/0, ticks=166488/0, in_queue=166488, util=99.30%, aggrios=1048576/0, aggrmerge=0/0, aggrticks=87131/0, aggrin_queue=87131, aggrutil=99.00%
  nvme2n1: ios=1048576/0, merge=0/0, ticks=86110/0, in_queue=86110, util=98.99%
  nvme1n1: ios=1048576/0, merge=0/0, ticks=88152/0, in_queue=88152, util=99.00%
  
  fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=fiotest --bs=4k --iodepth=64 --size=8G --readwrite=randwrite
  
  fiotest: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=64
fio-3.16
Starting 1 process
Jobs: 1 (f=1): [w(1)][100.0%][w=504MiB/s][w=129k IOPS][eta 00m:00s]
fiotest: (groupid=0, jobs=1): err= 0: pid=12079: Sun Jan  9 17:12:03 2022
  write: IOPS=125k, BW=490MiB/s (513MB/s)(8192MiB/16730msec); 0 zone resets
   bw (  KiB/s): min=124064, max=517392, per=99.96%, avg=501189.06, stdev=68829.52, samples=33
   iops        : min=31016, max=129348, avg=125297.24, stdev=17207.37, samples=33
  cpu          : usr=13.24%, sys=57.40%, ctx=1033830, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued rwts: total=0,2097152,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
  WRITE: bw=490MiB/s (513MB/s), 490MiB/s-490MiB/s (513MB/s-513MB/s), io=8192MiB (8590MB), run=16730-16730msec

Disk stats (read/write):
    md0: ios=5065/2086436, merge=0/0, ticks=432/40740, in_queue=41172, util=99.46%, aggrios=2532/1048576, aggrmerge=0/0, aggrticks=226/22662, aggrin_queue=22888, aggrutil=99.22%
  nvme2n1: ios=2408/1048576, merge=0/0, ticks=192/22242, in_queue=22434, util=99.22%
  nvme1n1: ios=2657/1048576, merge=0/0, ticks=260/23082, in_queue=23343, util=99.22%

**Comment by imharvol** [comment]
I've also tried the i3en.2xlarge with the 2 NVMEs in RAID0 and I've managed to fully sync from snapshot in 10h or so

**Comment by Zaczero** [comment]
I remember having the same issue. What I did, in the end, was to trash the data and set up a completely fresh node using the snapshot provided by the BSC team: https://github.com/binance-chain/bsc-snapshots. Of course, it's not an ideal solution, but that's what helped in my case.

**Comment by imnovox** [comment]
I'm exactly same position.
I'm really, really tired. I rent AX61-NVME server, it's a excelente hardware server, but the same problem, NEVER synchronized.

Imported new state entries looks infinity, never end's.

my geth
./geth_linux --config config.toml --datadir mainnet --cache 61440 --rpc.allow-unprotected-txs --txlookuplimit 0 --ws --http

Now, i'm download geth-20220113.tar.lz4 and i will try again. 
OMG, get fullnode BSC is very dificult.

> eth.syncing
{
  currentBlock: 14344856,
  highestBlock: 14344922,
  knownStates: 1606798476,
  pulledStates: 1606743429,
  startingBlock: 14343637
}
>

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
