### ISSUE TITLE
Block data exception

### ISSUE THREAD

**Issue by shexiaoheng** [binance-chain/bsc#708]
env: "Geth/v1.1.7-99cb655f/linux-amd64/go1.16.4"

```
curl https://bsc-dataseed1.binance.org -d '{"jsonrpc": "2.0", "id": 1, "method": "eth_getTransactionByBlockHashAndIndex", "params": ["0x6b012f81a08af7d932a760d1c370a50379322cad06eb2763ffc49f364cb6814c", "0x0"]}'
```
The block hash returned by the curl command above is: "0x6b012f81a08af7d932a760d1c370a50379322cad06eb2763ffc49f364cb6814c"

The block hash on the blockchain explorer is: "0x3ec864d59aff6bb75d956e5929987960ef83d14c3fc3c72d65483a2d51803973"
https://bscscan.com/block/14237704

**Comment by Dakoan** [comment]
test

**Comment by kyrie-yl** [comment]
0x6b012f81a08af7d932a760d1c370a50379322cad06eb2763ffc49f364cb6814c this block is a forked block, while you the block height specifics a block at main chain.
