### ISSUE TITLE
eth.syncing not found

### ISSUE THREAD

**Issue by nilampatel-engineer** [binance-chain/bsc#709]
I have bsc node running and I can not do eth.syncing it says its not found pls help

**Comment by nilampatel-engineer** [comment]
I m not able to run above cmd ./getg......

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Zaczero** [comment]
With the current amount of information, I am unable to help you. Please post more details/logs/steps to reproduce.

How to get started with BSC fullnode:  
https://docs.binance.org/smart-chain/developer/fullnode.html#steps-to-run-a-fullnode

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild

**Comment by echoof** [comment]
> Unable to reproduce, please elaborate on the issue.
> 
> ![image](https://user-images.githubusercontent.com/10835147/149173128-c6dff25e-f295-4a4c-a559-0231d31c5e52.png)

亲，What does this result mean
<img width="143" alt="image" src="https://user-images.githubusercontent.com/54647766/195354022-15d12061-c755-4b63-953d-2253bff15a8c.png">
