### ISSUE TITLE
Warning: "there is a possible fork, and your client is not the majority. Please check..."

### ISSUE THREAD

**Issue by allenwq** [binance-chain/bsc#71]
Seeing this warning log all the time while running the latest released os x client (https://github.com/binance-chain/bsc/releases).

#### System information
Version: 1.0.6
Git Commit: 540ac2a1b73bacc3555b51c8d0021599684aba8a
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.7

Genesis file is from mainnet.zip

cc @guagualvcha  looks like this is related to https://github.com/binance-chain/bsc/pull/56

**Comment by guagualvcha** [comment]
No worry, please refer to https://github.com/binance-chain/bsc/issues/65

**Comment by allenwq** [comment]
@guagualvcha thanks! meaning that after other mainnet nodes updated this error will be gone?

**Comment by guagualvcha** [comment]
Yes. After the majority of validators been  upgraded.

**Comment by guagualvcha** [comment]
Also I guess other ones have the some question as yours, let's put this issue unclosed for a while.

**Comment by allenwq** [comment]
Lol yes, I just realised that this issue has been raised a few times before.

Thanks!

**Comment by VartelK** [comment]
I have seen the same message trying to run a full node on Ubuntu, thanks for clarifying this.
Guess my node is synchronizing normally no matter what that message says cause I do see a lot of the below messages:

```sh
t=2021-02-08T01:19:36+0200 lvl=info msg="Imported new chain segment"          blocks=7   txs=162  mgas=19.691  elapsed=9.362s    mgasps=2.103  number=4626884 hash=0x45e9b3d0bc6bb162574cc288fa4c4b261a3c65254a324f0b49edd7b97988c334 age=2d35m18s dirty="61.84 MiB"
```
