### ISSUE TITLE
At least 10 tx per second remain pending forever.

### ISSUE THREAD

**Issue by dgdeivid** [binance-chain/bsc#716]
I have counted how many tx remain pending for at least two hours and the result is that approximately every second about 10 transactions on average remain pending for at least two hours.

Is this behavior common?

This sample of transactions was taken approximately 2 hours ago in 1-2 seconds and is still pending.

https://bscscan.com/tx/0x353ae098c0df79cce0b7e0d59874be19d0bdbd701ff5ee694ca80836794b9d53
https://bscscan.com/tx/0xc5d478030d57b91c5d14d41fe093754703688a0b8bc78d13d17ed93b42d02e53
https://bscscan.com/tx/0xf26f1c3f88aa026fc3f0cb99e0dca296ef7d6e18ae5682a08a758dd1ddc0b8e8
https://bscscan.com/tx/0x1f6150990dd6c5bd577e1ca25f4b659871ab73a36774e7b9623f36b73e1153bf
https://bscscan.com/tx/0x58753d8bedea3ace64240d62ddafd73cef3dc5342566e2d034bb017bf83e617d
https://bscscan.com/tx/0x6c5e9cbfa8b328ecf319558b0559d116ae421a7acf07a8f899621fb943176a56
https://bscscan.com/tx/0xb0e5dbe5e4553382051c48e2c069aa490408170c0daf5a96f2007e347314758e
https://bscscan.com/tx/0x39d6f8bf6ac7be747e88a18b5df513de8a96ce44db240d974f13796067bcffbe
https://bscscan.com/tx/0xdc2b138f0dbbb2965008886c94b906894ea0274c1b93d4aead1b4e0d68b39133
https://bscscan.com/tx/0xaa7b8e25e6c880341dc4940c6dba21fc71067aaf2a009174977cdb8950e51ec1
https://bscscan.com/tx/0x1a84dbcff95f7db0938b7794fec20d97d5b2102eb6c6747ebb2cbb02db06a440
https://bscscan.com/tx/0xa2cdd0b67435b060c169bb195e6af9ac92d2b87857a6e45abbbb36c08bba9968
https://bscscan.com/tx/0x8fde9a3224fcd6fb74a614454a380b7a46d96ed9606d53e09190df6d84863648

This is how I see all this tx in bscscan:

https://i.ibb.co/BfSpRfP/tx-Pending.png

**Comment by psdlt** [comment]
All these txs are from same sender. All of them have "future" nonces. Look at the last mined tx for this account, it's nonce is 4470. All txs that you've linked have much higher nonces. I assume owner of this account either intentionally or accidentally skipped (haven't submitted yet) tx with nonce 4471, but they've submitted a lot of txs with higher nonces. All txs originating from same account must have sequential nonces, no skipping, so until they submit the missing nonce, all others will remain pending (unless they get dropped by the network if they stay pending for too long).
