### ISSUE TITLE
Synchronization node stuck at height 12965001

### ISSUE THREAD

**Issue by a411382846** [binance-chain/bsc#717]
t=2022-01-15T22:53:14+0800 lvl=warn msg="Served admin_peers"                     conn=217.12.203.122:35652 reqid=1   t="7.763µs"                err="the method admin_peers does not exist/is not available" X-Forwarded-For=nil
t=2022-01-15T22:53:14+0800 lvl=warn msg="Served admin_peers"                     conn=217.12.203.122:35652 reqid=1   t="5.525µs"                err="the method admin_peers does not exist/is not available"
t=2022-01-15T22:53:18+0800 lvl=warn msg="Served parity_netPeers"                 conn=217.12.203.122:35652 reqid=1   t="9.842µs"                err="the method parity_netPeers does not exist/is not available" X-Forwarded-For=nil
t=2022-01-15T22:53:18+0800 lvl=warn msg="Served parity_netPeers"                 conn=217.12.203.122:35652 reqid=1   t="7.35µs"                 err="the method parity_netPeers does not exist/is not available"
t=2022-01-15T22:53:51+0800 lvl=warn msg="Served admin_peers"                     conn=217.12.203.122:52424 reqid=1   t="9.787µs"                err="the method admin_peers does not exist/is not available" X-Forwarded-For=nil
t=2022-01-15T22:53:51+0800 lvl=warn msg="Served admin_peers"                     conn=217.12.203.122:52424 reqid=1   t="7.348µs"                err="the method admin_peers does not exist/is not available"
t=2022-01-15T22:53:56+0800 lvl=warn msg="Served parity_netPeers"                 conn=217.12.203.122:52424 reqid=1   t="9.572µs"                err="the method parity_netPeers does not exist/is not available" X-Forwarded-For=nil
t=2022-01-15T22:53:56+0800 lvl=warn msg="Served parity_netPeers"                 conn=217.12.203.122:52424 reqid=1   t="7.305µs"                err="the method parity_netPeers does not exist/is not available"
t=2022-01-15T22:54:39+0800 lvl=warn msg="Served admin_peers"                     conn=217.12.203.122:40650 reqid=1   t="7.082µs"                err="the method admin_peers does not exist/is not available" X-Forwarded-For=nil
t=2022-01-15T22:54:39+0800 lvl=warn msg="Served admin_peers"                     conn=217.12.203.122:40650 reqid=1   t="5.294µs"                err="the method admin_peers does not exist/is not available"
t=2022-01-15T22:54:44+0800 lvl=warn msg="Served parity_netPeers"                 conn=217.12.203.122:40650 reqid=1   t="8.718µs"                err="the method parity_netPeers does not exist/is not available" X-Forwarded-For=nil
t=2022-01-15T22:54:44+0800 lvl=warn msg="Served parity_netPeers"                 conn=217.12.203.122:40650 reqid=1   t="6.554µs"                err="the method parity_netPeers does not exist/is not available"
t=2022-01-15T22:55:08+0800 lvl=eror msg="Snapshot extension registration failed" peer=e5f21886 err="peer connected on snap without compatible eth support"

**Comment by Zaczero** [comment]
The log you have provided shows some failed requests (RPC?) to `admin_peers` and `parity_netPeers` which are disabled by default. You need to edit `HTTPModules` and `WSModules` lines to enable given modules. One more thing: `parity_netPeers` is only available on the Parity eth client. This one will not work on the geth-based BSC client. Still, you should be fine with using just `admin_peers` - just enable the "admin" module (make sure your RPC is well secured!!).

**Comment by a411382846** [comment]
What you said is related to the node stuck in 12965001?

**Comment by Zaczero** [comment]
@a411382846

I suppose not. I addressed the logs you have provided. I don't know what to say regarding the node stuck issue as I am unable to reproduce it *(my node is running fine)*. You would have to provide more information on that. Some basic troubleshooting:

1. Make sure you have enough free disk space left.
2. Make sure you are running the latest release.
3. Check for any errors/warnings inside the `bsc.log` file.

**Comment by j75689** [comment]
@a411382846 Hi, can you provide more logs?

1. Check if there are any unexpected errors
2. Confirm whether there is a correct peer connection
3. Modify log level to `debug` or `trace`, and you can get more detail.

**Comment by Zaczero** [comment]
@DryDragon10 

**How to enable:**
I talk about it in the comment you have quoted.

**What are they for:**
From https://geth.ethereum.org/docs/rpc/ns-admin#admin_peers:

> The peers administrative property can be queried for all the information known about the connected remote nodes at the networking granularity. These include general information about the nodes themselves as participants of the ÐΞVp2p P2P overlay protocol, as well as specialized information added by each of the running application protocols (e.g. eth, les, shh, bzz).

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
