### ISSUE TITLE
Geth panics on sync

### ISSUE THREAD

**Issue by affaxltd** [binance-chain/bsc#72]
I downloaded the snapshot (because it would've taken ages to sync from genesis on my won) but I get this error after syncing from the snapshot, most likely a problem in one block.
How could I go about fixing this:

`panic: expected tx hash 0x887ef2b7f0de6de806ac22c812a7ab3904fa2b781d905b57df8a2fe85b5e9a88, get 0x377b07685bf80d4375669b17423a244366a09b316e65877afdc6a8f3c0060c58`

**Comment by guagualvcha** [comment]
Sorry for the trouble, We will take time to verify the snapshot. I think sync from genesis will take one or two days, I think it will be faster than we solve this snapshot issue.

**Comment by guagualvcha** [comment]
What is the `geth` version are you using?

**Comment by affaxltd** [comment]
Using the one that the repo was on yesterday (I built geth from the repo, I just removed the warning spam from the code manually, but this occurred even before removing the fork warning spam).
Btw, I started syncing it myself from genesis and soon will finish, but other people might also stumble on this problem as well.

**Comment by tebayoso** [comment]
Hi, I've got this same issue syncing from Genesis, around block 4.9 millions.
```
panic: expected tx hash 0x824471ff03c68ac9952786708c8e45ca4abf4cf8ff30e14c263639313f53b213, get 0x450a0850c1060f0c7bf638d9f5d4464bcb322c2fcab4d6695a76dcd0d4b3184e
```

**Comment by dsbaars** [comment]
I tried to sync with three different computers, this only happens on my Mac Mini M1.

**Comment by manelio** [comment]
Same problem here.

Restarted and failed again after some minutes.

Raspberry Pi 8GB. Have been working without problems for several weeks until now.

It's a bit concerning. I should add some monitoring layer.

**Comment by tebayoso** [comment]
I found the problem, is related with the write speed of the data storage. I think the error should be more explicit.

**Comment by dsbaars** [comment]
You can use systemd to let it automatically restart when it crashes or stops. Note that this does not solve the problem but at least helps you stay in sync. 
I use this configuration (copy and use at your own risk):

````
[Unit]
Description=BSC geth
After=syslog.target network.target

[Service]
User=geth
Group=geth
Environment=HOME=/media/bscnode/bsc-node
Type=simple
ExecStart=/media/bscnode/bsc-node/geth --config /media/bscnode/bsc-node/config.toml --datadir /media/bscnode/bsc-node/node --graphql
KillMode=process
KillSignal=SIGINT
TimeoutStopSec=90
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
````

Save to `/usr/lib/systemd/system/geth.service`, then execute `systemctl enable geth` and `systemctl start geth`

**Comment by manelio** [comment]
Thanks @tebayoso, and thanks for the workaround @dsbaars.

Now I wonder how fast the storage must be. I'm using a high end 1TB SSD, but maybe I missed any tweak.

```
root@ubuntu:~# dd if=/dev/zero of=/mnt/storage/dummy bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 9.45053 s, 114 MB/s
```

But the tech specs say writing speed up to 560 MB/s

Could I know how fast are your devices?

**Comment by dsbaars** [comment]
Might be combination of speed and latency, this is the speed of my NVMe SSD in USB-C enclosure where the data directory is stored on:

````dd if=/dev/zero of=dummy bs=2G count=1 oflag=dsync
0+1 records in
0+1 records out
2147479552 bytes (2.1 GB, 2.0 GiB) copied, 6.42651 s, 334 MB/s````

**Comment by soltrac** [comment]
Hi guys, looking the minimun specs to keep a node syncing only for personal purposes. 

@manelio have u been able to keep in sync with the rp4?
@dsbaars what minimun specs does ur pc have to keep in sync?

Thanks for your help

**Comment by manelio** [comment]
Update:

I plugged the SDD drive on my desktop computer. Writing speed was improved on a factor of 3.3:

```
➜  ~ dd if=/dev/zero of=/media/manel/blockchain/bscnode/dummy bs=1G count=1 oflag=dsync                                                                                              
1+0 records in
1+0 records out
1073741824 bytes (1,1 GB, 1,0 GiB) copied, 3,23413 s, 332 MB/s
```

Also, I upgraded the BSC node client to version 1.0.7.

The problem keeps happening :(.

```
INFO [04-10|10:32:28.334] Persisted trie from memory database      nodes=48415 size=15.66MiB time=476.959863ms gcnodes=37370 gcsize=13.63MiB gctime=102.521714ms livenodes=617494 livesize=210.27MiB
INFO [04-10|10:32:34.672] Imported new chain segment               blocks=8 txs=1426 mgas=195.327 elapsed=8.249s  mgasps=23.678 number=6393617 hash=33cf88…b804d3 age=1d13h49m dirty=277.17MiB
panic: expected tx hash 0x66984b53ae4b892e8b88f17aef26062dfcf8237db3fb1dde597a13d14b5ebbfa, get 0x206a9d729af37cde3b441ebb6238bea403d7e47ba517388a6409668594374e21

goroutine 687 [running]:
github.com/ethereum/go-ethereum/consensus/parlia.(*Parlia).Finalize(0xc0000a3500, 0x1992c00, 0xc00c84e000, 0xc0d2212480, 0xc0c76e5600, 0xc0d83943e0, 0x25fe110, 0x0, 0x0, 0xc0d8394360, ...)
        /server/bsc/consensus/parlia/parlia.go:707 +0x1139
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc00024e6c0, 0xc01042fe60, 0xc0c76e5600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /server/bsc/core/state_processor.go:94 +0xa02
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00c84e000, 0xc010372000, 0xd8, 0x100, 0xc00cf49900, 0x0, 0x0, 0x0)
        /server/bsc/core/blockchain.go:1722 +0xccc
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSideChain(0xc00c84e000, 0xc00b546cf0, 0xc00cf4dd10, 0x4, 0xc00cf4dc50, 0x4)
        /server/bsc/core/blockchain.go:1942 +0x1d16
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00c84e000, 0xc00b415500, 0x2, 0x2, 0x35c7564c2b568501, 0x0, 0x0, 0x0)
        /server/bsc/core/blockchain.go:1633 +0x3d65
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00c84e000, 0xc00b415500, 0x2, 0x2, 0x0, 0x0, 0x0)
        /server/bsc/core/blockchain.go:1539 +0xcab
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc00c1b3180, 0xc00b4154f0, 0x2, 0x2, 0x2, 0x0)
        /server/bsc/eth/downloader/downloader.go:1557 +0x50c
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc00c1b3180, 0x1977500, 0xc00b3a5a40)
        /server/bsc/eth/downloader/downloader.go:1531 +0x7d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc00c1b3180, 0xc00b57df20, 0xc00b4154b0)
        /server/bsc/eth/downloader/downloader.go:534 +0x5b
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /server/bsc/eth/downloader/downloader.go:534 +0xaf
```

**Comment by dsbaars** [comment]
Did you use the pre-compiled binary or did you compile it yourself?

**Comment by manelio** [comment]
On the Raspberry I use a version cross-compiled from desktop with:

```
xgo --deps=https://gmplib.org/download/gmp/gmp-6.0.0a.tar.bz2 --targets=linux/arm64 github.com/binance-chain/bsc/cmd/geth
```

On desktop I use the pre-compiled binary:

```
wget https://github.com/binance-chain/bsc/releases/download/v1.0.7/geth_linux
```

**Comment by manelio** [comment]
This is interesting. In my case the error happens always in same tx:

```
panic: expected tx hash 0x66984b53ae4b892e8b88f17aef26062dfcf8237db3fb1dde597a13d14b5ebbfa, get 0x206a9d729af37cde3b441ebb6238bea403d7e47ba517388a6409668594374e21                                                                                                                        
```

Maybe the problem is on the stored data.

Is there any way to 'rewind' to a previous time or tx?

**Comment by dsbaars** [comment]
> Is there any way to 'rewind' to a previous time or tx?

I think you can use `debug.setHead()` for that. Note that as far as I know, it only accepts hexadecimal numbers... but it's easy to find a decimal to hex converter.

I used it once to resync a pruning node to an archival node, which was already in sync. Not sure your node needs to be in sync first. Otherwise, doing a fast sync might be the fastest alternative. The snapshot might be broken.

**Comment by manelio** [comment]
Ok. I gave up.

After a rewind with `debug.setHead("0x618D00")`, the log started complaining with:

```
INFO [04-10|20:13:44.159] Block synchronisation started 
INFO [04-10|20:13:48.103] Looking for peers                        peercount=1 tried=78 static=8
ERROR[04-10|20:13:48.566] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Engine: parlia}

Number: 6393700
Hash: 0x7b22e1cc50756e06591afd004fdb975075c13986992d272f8c999d6679fce8f8


Error: unknown ancestor
##############################
 
WARN [04-10|20:13:48.593] Synchronisation failed, dropping peer    peer=e2f7a19a12af6e48 err="retrieved hash chain is invalid"
```

So I decided to wipe all blockchain data and start a new sync.

But this is a big concern. I'm building a project that relies on the real time analysis of blockchain, including analyzing the txpool. And the possibility of having to wait several days to get synced again is something unexpected.

I'll keep subscribed to this topic in case someone finds a solution.

**Comment by guagualvcha** [comment]
@affaxltd  I will close this issue since it is stale and did not occur now. Thanks.
