### ISSUE TITLE
trace_block ?

### ISSUE THREAD

**Issue by salisbury-espinosa** [binance-chain/bsc#724]
How to get full block trace (target - internal transactions) as in parity ?
(https://openethereum.github.io/JSONRPC-trace-module#trace_block)

**Comment by j75689** [comment]
Hi, you can find a similar API from [here](https://geth.ethereum.org/docs/rpc/ns-debug#debug_traceblockbynumber)

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
