### ISSUE TITLE
Ancient directory

### ISSUE THREAD

**Issue by yo31400** [binance-chain/bsc#726]
Hello,

I see there is an option to put the ancient directory in another location (--datadir.ancient).
Does this directory need to be on the nvme ssd ?
There is no synchronization or performance problem to move the ancient directory to a HDD or SSD (no nvme) ?

**Comment by RumeelHussainbnb** [comment]
Better to Use SSD

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
