### ISSUE TITLE
stuck when running geth 

### ISSUE THREAD

**Issue by sunset1234321** [binance-chain/bsc#727]
#### System information
geth_windows.exe version
```
Geth
Version: 1.1.7
Git Commit: 74f6b613a4db5cb903f98aca54dbe77d5039ffe8
Architecture: amd64
Go Version: go1.16.10
Operating System: windows
GOPATH=
GOROOT=go
```
OS & Version: Windows10

#### what i run 
`CMD geth_windows.exe --config .\mainnet\config.toml --datadir .\node_real_datadir --diffsync --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0`

#### dir structure 
```
├───node_real_datadir
│   ├───geth
│   │   ├───chaindata
│   │   │   └───ancient
│   │   ├───les.server
│   │   ├───lightchaindata
│   │   ├───nodes
│   │   └───triecache
│   └───keystore
```
#### Expected behaviour
constantly output something in console 

#### Actual behaviour

__stuck__ after console output these 3 lines
```
INFO [01-21|06:27:23.816] Starting Geth on Ethereum mainnet...
INFO [01-21|06:27:23.820] Maximum peer count                       ETH=30 LES=0 total=30
WARN [01-21|06:27:23.823] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
```

**Comment by psdlt** [comment]
@have you checked `node_real_datadir/bsc.log`? Does it say anything?

**Comment by j75689** [comment]
Hi @sunset1234321 can you check the logs? if you enable log module in `config.toml`, and you can get more logs in the folder.

for example:
![image](https://user-images.githubusercontent.com/25412254/150714518-6a550fd3-2303-4cba-b977-e54437bc4598.png)
And you get logs by  `tail -f /tmp/bsc.log`

**Comment by sunset1234321** [comment]
thanks all                tail -f /tmp/bsc.log  works
