### ISSUE TITLE
any peer suggestions?

### ISSUE THREAD

**Issue by sunset1234321** [binance-chain/bsc#729]
I am in hong kong,  seems i cannot find any peer, 

I guess by setting  static node could solve this.

any static node recommend?

**Comment by j75689** [comment]
could you please try these peers? 

1. wget https://github.com/binance-chain/bsc/releases/download/v1.1.7/mainnet.zip
2. unzip mainnet.zip
3. you can get peers in `config.toml`

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain
