### ISSUE TITLE
Is the geth_window.exe here same as the one in go-ethereum

### ISSUE THREAD

**Issue by sunset1234321** [binance-chain/bsc#731]
(https://github.com/ethereum/go-ethereum)  also could make geth, 

could I use their client?

**Comment by Zaczero** [comment]
The short answer is that the base geth lacks features crucial to operating on a PoS (Proof-of-Stake) blockchain like BSC. So, no - you should use the BSC version of geth to host a BSC node.

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days. 
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/binancesmartchain

**Comment by Zaczero** [comment]
@RumeelHussainbnb WDYM?

> and will proceed to close the case

I don't think you have enough permissions to do so.

> as we didn't get any additional question after 3days

This issue has not even lasted for 2 full days yet.

> Please proceed to join our Discord channel for more discussion

? ? ?

This looks like some sort of malicious behavior.

**Comment by j75689** [comment]
Hi go-ethereum doesn't support the consense of BSC(parlia), and also we did a log of code change, so please use our released version to run BSC node, thanks
