### ISSUE TITLE
Is a full node a requirement to broadcast transactions?

### ISSUE THREAD

**Issue by sunset1234321** [binance-chain/bsc#734]
Sometimes I want to interact with some smart contract ( maybe a decentralized exchange like uni swap)

And I want my transaction to be confirmed the fastest.

But usually, we are relying on other full nodes to help us broadcast the transactions.

For example on uniswap trading website https://app.uniswap.org/#/swap , it use https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxx as a provider.

But the service is not guaranteed and it could delay your request to broadcast the transactions.

So I am thinking about whether building my own node will be better.

__What node could broadcast transactions to miners? Is full node the only choice?__

**Comment by Zaczero** [comment]
Full node, Light node is the way to go.

With a full node, you will boost up not only your broadcasts but also the RPC interactions (price quote, gas simulation), but this will require you to sync the blockchain, which requires quite powerful hardware these days and lots of time.

With a light node, you will not be required to download the blockchain. Thus, you will not gain many benefits in terms of RPC interactions (you can use less powerful hardware). But, to my knowledge, you will be able to broadcast transactions quickly without relying on any 3rd party.

**Comment by j75689** [comment]
Hi, if you just want to interact with smart contracts, I recommend you to use the [official rpc endpoint](https://docs.binance.org/smart-chain/developer/rpc.html) or choose some bsc network provides business.
It may be more powerful than running the node yourself.

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
