### ISSUE TITLE
【!!!!pls help!!!!】what's the [Eth.Miner] in  config.toml 

### ISSUE THREAD

**Issue by daxuanxiaoyou** [binance-chain/bsc#735]
i update some code, and i run a full node with the miner.start(), but the count of txs in my pending block is bigger than the confirmed block.

**Comment by daxuanxiaoyou** [comment]
> eth.getBlock('pending')
{
  difficulty: 1,
  extraData: "0xd883010107846765746888676f312e31332e38856c696e7578000000c3167bdf0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  gasLimit: 79565707,
  gasUsed: 78919984,
  hash: null,
  logsBloom: "0x17a2cbf27edadafb6f957bedf1473f97e2ffc7de77654eab65b617beff350da74ceeff5f3f3b7e03af62a4f717b76b928f8778ddde77eed7f2f8d7d7bfad5bee91f7f42cdaf596eec7a7b6d9acb73bee7f8716eb97deaacf97efb4fda49ffb79fbffbcbfc6bf9af56d8ffa5abffdda03c3e6d1cffefeee659eadc5f7b7d8e55dbffbefb7fcfff74f56b9b5b3fefdcfb79fff3dfd2fe3d9baa1262f69e7e72ed3c2d3ee125c19bc54712cef787bef2d76ef9ae6332bc3a9b50fcde3bb25ca3abea373f713ea1edfb6decf8f3eef9ade97fb6feffabd3e38fe555febfefcbee7a6bc79ffe25c9477db2fafdd1739c4733beeb87f6ae5de677edebbc1bdddeeff3e",
  miner: null,
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: null,
  number: 14672046,
  parentHash: "0xfcbf80544fc9dded2d5f01b54d909eb6ee067de3f37ddc7c18c8a71a0138947d",
  receiptsRoot: "0x5f8bb3a8ebd9e925137a1a77a8d9d0093784ec6dad3fc2b3524fd02ff05e3ef9",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 71033,
  stateRoot: "0x0000000000000000000000000000000000000000000000000000000000000000",
  timestamp: 1643108890,
......



and the confirmed block:
> eth.getBlock(14672046)
{
  difficulty: 2,
  extraData: "0xd883010107846765746888676f312e31332e34856c696e7578000000c3167bdf4478ebf84cef766e82b9e64ffa8889d5ad4e009680fede98e9e840ea8e4216f65ac169c59d6aa5cf67a617c3970891f23b87ddd5cc1b31b8644ef5602b10d2c600",
  gasLimit: 80000000,
  gasUsed: 27033955,
  hash: "0xc226e464d920f46002e5791c62e22a782b8f395e0c86a1d21367997cbfb40047",
  logsBloom: "0x17a2caf27cdadaf36f9579fdf1473f97e2ffc5de77654eab65b617beff350da70ceeff5f3f3bfe13af6284e717873b928f87789dde37ee57f2f8d7d7bfad5bea91f6f42ccaf5966ec7a3b2d9acb73bee7e9706eb97deaace97ef3479849ffb79fbff9cbfc6af9af56d8f7a52bf7dda23cbe6d1cffedeee659eadc5f7bfd8e55dbffbeeb7fcffe74f56b9b5b3f4fdcfa79fb71dfd2fe3d9baa1262b6967e72ef3c2d3ee125c89bc54710cef787bef2d76ed9ae6332bc3a1b40fcde3bb24ca3a9ea173f713ea1edfb6d6ca8f3eff1a5e95fb67eefabd3a38fe555febfe7cb4e7aab859fde25c947fdb0fafdd1729c473bbeeb85f6ae5de676edebbc1f5ddeeff3e",
  miner: "0xea0a6e3c511bbd10f4519ece37dc24887e11b55d",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 14672046,
  parentHash: "0xfcbf80544fc9dded2d5f01b54d909eb6ee067de3f37ddc7c18c8a71a0138947d",
  receiptsRoot: "0x26c38135e2515bc6c44b6025acd2074dc7205923d5f561b98d4aed4d86d8bfdc",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 61245,
  stateRoot: "0xd247da583c81690b4dd3b9829fd6cbb47164831b9a8cf01a2d6e1c775b15ef7c",
  timestamp: 1643108890,
  totalDifficulty: 29152736,
.....

why the two gasUsed are so different ??

**Comment by j75689** [comment]
BSC only allows 21 validators selected every day to be miners, even if the miner module is forcibly turned on, the final block will be dominated by the block produced by the validator

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild

**Comment by Codegigi** [comment]
Hey @RumeelHussainbnb can you add me to the discord link that you just mentioned in the previous message. I have a few queries regarding the voting mechanism in bsc. Thanks!

**Comment by RumeelHussainbnb** [comment]
Please proceed to join our Discord channel for more discussion at https://discord.gg/bnbchain
