### ISSUE TITLE
A question about sync block

### ISSUE THREAD

**Issue by KEY-L-LC** [binance-chain/bsc#736]
I am a developer on BSC， I build a node by myself, the version is v1.1.7,but the node has something wrong. sometimes,about 30s to 2m, the node does not sync block, then it will sync about 20 to 30 blocks. time after time, please tell me how to resolve that, thanks very much

**Comment by j75689** [comment]
Hi, can you please provide some logs?

**Comment by KEY-L-LC** [comment]
> Hi, can you please provide some logs?

t=2022-01-26T08:54:25+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=355   mgas=19.177   elapsed=166.858ms   mgasps=114.928  number=14,698,110 hash=0x3db4d8d465647c2569a4f0cb46a24259f6a442b4f5bb60349756c8977c281aa1 age=1m12s    dirty="609.01 MiB"  ignored=1
t=2022-01-26T08:54:25+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=284   mgas=24.592   elapsed=191.954ms   mgasps=128.112  number=14,698,111 hash=0x389848b8f6a46de369cf59650a0ced35de1b22a7b451e913e5dff14ebbc12793 age=1m9s     dirty="609.96 MiB"
t=2022-01-26T08:54:31+0000 lvl=info msg="Imported new chain segment"             blocks=23  txs=4466  mgas=540.425  elapsed=5.727s      mgasps=94.350   number=14,698,134 hash=0xbfa1a409c72af16a565b2b72a6729532b840c1ecb0bc24c735a611a6cdf329e7 dirty="620.36 MiB"  ignored=1
t=2022-01-26T08:54:38+0000 lvl=info msg="Imported new chain segment"             blocks=4   txs=739   mgas=93.906   elapsed=913.277ms   mgasps=102.823  number=14,698,138 hash=0x11f8cc277d2eef01933b0bb8bb766da9a95303f4183b47a9f38b662e38d8c35d dirty="623.29 MiB"
t=2022-01-26T08:54:41+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=135   mgas=16.347   elapsed=152.541ms   mgasps=107.164  number=14,698,139 hash=0x66efe8728590defafd473152d4e28a4073665d3c7acf2cf10c60412cdf558680 dirty="623.31 MiB"
t=2022-01-26T08:54:44+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=186   mgas=21.182   elapsed=192.571ms   mgasps=109.995  number=14,698,140 hash=0x8a8d3fcef8c4a889b218684339e929a3df6fe2d10fb1ff1f9277ff5e17ef5d3b dirty="623.81 MiB"
t=2022-01-26T08:54:47+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=122   mgas=18.213   elapsed=191.273ms   mgasps=95.220   number=14,698,141 hash=0x549a6bc18b848500fdd399451ce78ec7147676f3bfad327545a3249040604385 dirty="623.06 MiB"
t=2022-01-26T08:54:50+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=203   mgas=33.747   elapsed=224.478ms   mgasps=150.334  number=14,698,142 hash=0x47de515527ee9c842558718af30f58492933cd81e3cfefe618faabb2d8bb911b dirty="624.29 MiB"
t=2022-01-26T08:54:53+0000 lvl=info msg="Imported new chain segment"             blocks=1   txs=130   mgas=15.527   elapsed=157.389ms   mgasps=98.655   number=14,698,143 hash=0x70797e3520b68892f713829eb05e0b4932697102e73124d45b2ec9e86bc1600d dirty="624.58 MiB"

**Comment by KEY-L-LC** [comment]
> Hi, can you please provide some logs?

somtimes it syncs block one by one,  2022-01-26T08:54:31 it synced 23 blocks

**Comment by j75689** [comment]
Hi @KEY-L-LC I saw the ` mgas` is  a bit low.
I thought maybe you could try:
1. prune data
2. enable diffsync

Here are some tips to help you maintain your node
1. https://github.com/binance-chain/bsc/issues/686
2. https://github.com/binance-chain/bsc/issues/502

**Comment by KEY-L-LC** [comment]
@j75689 ok,thanks very much. I will try the second acvice, then I will reply for you

**Comment by j75689** [comment]
Hi @KEY-L-LC released a new version today with a new feature `--pipecommit`.
It can improve some performance, you can check the details form #668

https://github.com/binance-chain/bsc/releases/tag/v1.1.8

**Comment by RumeelHussainbnb** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.
Please proceed to join our Discord channel for more discussion at https://discord.com/invite/buildnbuild
