### ISSUE TITLE
Incorrect gas price in mainnet geth config.toml

### ISSUE THREAD

**Issue by dileepfrog** [binance-chain/bsc#74]
#### Expected behaviour
The mainnet config.toml file included in the release linked here https://docs.binance.org/smart-chain/developer/fullnode.html#steps-to-run-a-fullnode includes a minimum gas price of 20 gwei, making it reject any transactions priced lower. It appears that BSC mainnet has started using 15 gwei gas prices this past weekend, along with an extended outage of the RPC endpoint https://bsc-dataseed.binance.org/

#### Actual behaviour
Put the actual minimum gas price in config.toml. Consider additionally providing an API tool similar to EGS that provides the current gas prices

**Comment by guagualvcha** [comment]
Hi, please fetch config.toml from latest release again.
