### ISSUE TITLE
Question:Where can I find the public archive node rpc?

### ISSUE THREAD

**Issue by jin10086** [binance-chain/bsc#75]

**Comment by guagualvcha** [comment]
Hi, bsc network does not provide a public archive node, so please run your own node if you need one.

**Comment by desktable** [comment]
How to run an archive node? Would the following command work?

```
geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof --gcmode archive --syncmode full
```

Note that this is the command in the [official doc](https://docs.binance.org/smart-chain/developer/fullnode.html), plus two options: `--gcmode archive --syncmode full`.
