### ISSUE TITLE
 add  --pipecommit to the archive nodes

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#752]
Q1：Can I add `--pipecommit`  to the archive nodes in production now？
Q2：Can I run an archive node with `--diffsync`

**Comment by KeefeL** [comment]
Answer to Q1: `--pipecommit` is an experimental feature, but we have tested it fully, I think you can enable it.
Answer to Q2: Sure, `--diffsync` also works for archive node.

**Comment by masayil** [comment]
> Answer to Q1: `--pipecommit` is an experimental feature, but we have tested it fully, I think you can enable it. Answer to Q2: Sure, `--diffsync` also works for archive node.

There should be no conflict between `--pipecommit` and  `--diffsync`. And I don't need to worry about the fork issuse. 
Right?
![image](https://user-images.githubusercontent.com/65291464/153104904-b5d8ccf5-8f38-4cda-8b0f-9a01999157ce.png)

**Comment by masayil** [comment]
I know err:`account storage root mismatch` can be ignored .   How about "missing storage change in difflayer" and "missing code"?
![image](https://user-images.githubusercontent.com/65291464/153107939-efe480ed-4aaf-4a78-b727-cc361e546b4f.png)

**Comment by KeefeL** [comment]
> > Answer to Q1: `--pipecommit` is an experimental feature, but we have tested it fully, I think you can enable it. Answer to Q2: Sure, `--diffsync` also works for archive node.
> 
> There should be no conflict between `--pipecommit` and `--diffsync`. And I don't need to worry about the fork issuse. Right? ![image](https://user-images.githubusercontent.com/65291464/153104904-b5d8ccf5-8f38-4cda-8b0f-9a01999157ce.png)

When you use `--diffsync`, there is no need to enable `--pipecommit`, because pipe commit won't work in diffsync mode.
The fork issue is not existed now, you don't need to worry about it.
