### ISSUE TITLE
some err about diffsync

### ISSUE THREAD

**Issue by masayil** [binance-chain/bsc#755]
I know `err:account storage root mismatch` can be ignored . How about "missing storage change in difflayer" and "missing code"?
![image](https://user-images.githubusercontent.com/65291464/153117489-74116d8b-efd9-4411-be21-72b8ab50464a.png)

**Comment by KeefeL** [comment]
The error is because of receiving some error difflayer, these error difflayers won't be inserted into the blockchain. If the blockchain keeps growing, you can ignore it.

**Comment by masayil** [comment]
> The error is because of receiving some error difflayer, these error difflayers won't be inserted into the blockchain. If the blockchain keeps growing, you can ignore it.

`missing code, account 0xc9a63cA55eE2118EC0e3f6Ca3Fb6576da1954D36`   Also can ignore?

**Comment by KeefeL** [comment]
> > The error is because of receiving some error difflayer, these error difflayers won't be inserted into the blockchain. If the blockchain keeps growing, you can ignore it.
> 
> `missing code, account 0xc9a63cA55eE2118EC0e3f6Ca3Fb6576da1954D36` Also can ignore?

Yes, I think so.
