### ISSUE TITLE
Logger does not log to console when a logfile is set

### ISSUE THREAD

**Issue by Code0x2** [binance-chain/bsc#76]
When using the geth setup from https://docs.binance.org/smart-chain/developer/fullnode.html with the "console" command attached to the process, nothing logs. I can access data by running `net.peerCount` on the console, or look at sync stats on `eth.syncing` from the console but it will not output to console. Logs are being sent to the log file at /node/bsc.log. Is this intentional? And how can I make it output to console and file at the same time

**Comment by guagualvcha** [comment]
If you do not want to log to bsc.log but to console, you can just remove following part from config.toml
```
[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```

**Comment by Code0x2** [comment]
> If you do not want to log to bsc.log but to console, you can just remove following part from config.toml
> 
> ```
> [Node.LogConfig]
> FilePath = "bsc.log"
> MaxBytesSize = 10485760
> Level = "info"
> FileRoot = ""
> ```

I want the logs to be on the console and on the file. Is there a way to do this?

**Comment by guagualvcha** [comment]
You need to adjust the log level to `trace` to show the trace log. So far there is no way to output log to both file and console.

**Comment by Code0x2** [comment]
> You need to adjust the log level to `trace` to show the trace log. So far there is no way to output log to both file and console.

That works, but on geth doing --debug will show the line number and file the log was sent from

**Comment by WB-Expert5007** [comment]
Hi, Everyone.
First of all, I hope you are in good health.
And I have one error like below.
_Fatal: ./config.toml, line 67: field 'LogConfig' is not defined in node.Config, see https://godoc.org/github.com/ethereum/go-ethereum/node#Config for available fields
( ![image](https://user-images.githubusercontent.com/96474901/171807942-fb2fbdce-fe2d-4394-b424-d8ba6f8b1b20.png)
How can I fix this error? )_

Here is my Config.toml code base.

[Eth]
NetworkId = 97
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60


[Node]
DataDir = "node"
InsecureUnlockAllowed = false
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8575
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug","eth", "net", "web3", "txpool", "parlia"]
WSPort = 8576
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 99
NoDiscovery = false
StaticNodes = ["enode://69a90b35164ef862185d9f4d2c5eff79b92acd1360574c0edf36044055dc766d87285a820233ae5700e11c9ba06ce1cf23c1c68a4556121109776ce2a3990bba@52.199.214.252:30311","enode://330d768f6de90e7825f0ea6fe59611ce9d50712e73547306846a9304663f9912bf1611037f7f90f21606242ded7fb476c7285cb7cd792836b8c0c5ef0365855c@18.181.52.189:30311","enode://df1e8eb59e42cad3c4551b2a53e31a7e55a2fdde1287babd1e94b0836550b489ba16c40932e4dacb16cba346bd442c432265a299c4aca63ee7bb0f832b9f45eb@52.51.80.128:30311","enode://0bd566a7fd136ecd19414a601bfdc530d5de161e3014033951dd603e72b1a8959eb5b70b06c87a5a75cbf45e4055c387d2a842bd6b1bd8b5041b3a61bab615cf@34.242.33.165:30311","enode://604ed87d813c2b884ff1dc3095afeab18331f3cc361e8fb604159e844905dfa6e4c627306231d48f46a2edceffcd069264a89d99cdbf861a04e8d3d8d7282e8a@3.209.122.123:30311","enode://4d358eca87c44230a49ceaca123c89c7e77232aeae745c3a4917e607b909c4a14034b3a742960a378c3f250e0e67391276e80c7beee7770071e13f33a5b0606a@52.72.123.113:30311"]



TrustedNodes = ["enode://69a90b35164ef862185d9f4d2c5eff79b92acd1360574c0edf36044055dc766d87285a820233ae5700e11c9ba06ce1cf23c1c68a4556121109776ce2a3990bba@52.199.214.252:30311","enode://330d768f6de90e7825f0ea6fe59611ce9d50712e73547306846a9304663f9912bf1611037f7f90f21606242ded7fb476c7285cb7cd792836b8c0c5ef0365855c@18.181.52.189:30311","enode://df1e8eb59e42cad3c4551b2a53e31a7e55a2fdde1287babd1e94b0836550b489ba16c40932e4dacb16cba346bd442c432265a299c4aca63ee7bb0f832b9f45eb@52.51.80.128:30311","enode://0bd566a7fd136ecd19414a601bfdc530d5de161e3014033951dd603e72b1a8959eb5b70b06c87a5a75cbf45e4055c387d2a842bd6b1bd8b5041b3a61bab615cf@34.242.33.165:30311","enode://604ed87d813c2b884ff1dc3095afeab18331f3cc361e8fb604159e844905dfa6e4c627306231d48f46a2edceffcd069264a89d99cdbf861a04e8d3d8d7282e8a@3.209.122.123:30311","enode://4d358eca87c44230a49ceaca123c89c7e77232aeae745c3a4917e607b909c4a14034b3a742960a378c3f250e0e67391276e80c7beee7770071e13f33a5b0606a@52.72.123.113:30311"]




EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info" 

Please help me.
Best Regards.

**Comment by WB-Expert5007** [comment]
> If you do not want to log to bsc.log but to console, you can just remove following part from config.toml
> 
> ```
> [Node.LogConfig]
> FilePath = "bsc.log"
> MaxBytesSize = 10485760
> Level = "info"
> FileRoot = ""
> ```

Hi, How are you?
Please check my question above and help me.
Best Regards.
