### ISSUE TITLE
Can't get data from old block number

### ISSUE THREAD

**Issue by vuducchinh29** [binance-chain/bsc#78]
Hi there,

I'm trying to get the data in the old block number but has an issue.
This is my codes:
`const pairAddress = '0xE2D1B285d83efb935134F644d00FB7c943e84B5B'`
`const web3 = new Web3('https://bsc-dataseed.binance.org/')`
`const contract = new web3.eth.Contract(ABI, pairAddress)`
`console.log(contract);`
`const reserves = await contract.methods.getReserves().call({}, '586960')`
`console.log(reserves);`

Error: Returned error: missing trie node dd8f963b36947dc129b720bf69ff248b610931dfe51ce863507014b84e940b11 (path )

Sure the ABI includes the method getReserves().

Please check and tell me how to fix it.
Thanks a lot.

**Comment by guagualvcha** [comment]
hi @vuducchinh29.  The public endpoint does not support the query of history state. I think you have to run a archive node by yourself.

**Comment by vuducchinh29** [comment]
> hi @vuducchinh29. The public endpoint does not support the query of history state. I think you have to run an archive node by yourself.

Thank you. That means only the archive node can query the history state at the old block number.
It's a bigger issue with the storage for archive node.
