### ISSUE TITLE
Syncing won't start because of BAD BLOCK

### ISSUE THREAD

**Issue by riccardope** [binance-chain/bsc#81]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use [discord](https://discord.gg/nthXNEv) or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version v1.0.6`
OS & Version: Ubuntu  20.04
Commit hash : (if `develop`)

#### Expected behaviour

Node starts syncing

#### Actual behaviour

ERROR[02-18|20:06:02.803] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: <nil>, Engine: unknown}

Number: 1
Hash: 0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6

Error: extra-data too long: 97 > 32
##############################
 
WARN [02-18|20:06:02.804] Synchronisation failed, dropping peer    peer=4cd4232e722a2cd6 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
INFO [02-18|20:06:07.304] Looking for peers                        peercount=5 tried=123 static=8
ERROR[02-18|20:06:12.528] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: <nil>, Engine: unknown}

Number: 1
Hash: 0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6

Error: extra-data too long: 97 > 32
##############################
 
WARN [02-18|20:06:12.576] Synchronisation failed, dropping peer    peer=44487db85567dc28 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
INFO [02-18|20:06:17.608] Downloader queue stats                   receiptTasks=0 blockTasks=22528 itemSize=761.51B throttle=8192
ERROR[02-18|20:06:17.609] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: <nil>, Engine: unknown}

Number: 1
Hash: 0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6

Error: extra-data too long: 97 > 32
##############################
 
WARN [02-18|20:06:17.609] Synchronisation failed, dropping peer    peer=71fd22d8cb7e4cae err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
INFO [02-18|20:06:17.609] Looking for peers                        peercount=4 tried=117 static=8
ERROR[02-18|20:06:23.496] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: <nil>, Engine: unknown}

Number: 1
Hash: 0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6

Error: extra-data too long: 97 > 32
##############################
 
WARN [02-18|20:06:23.496] Synchronisation failed, dropping peer    peer=b84139a1ce52b6f2 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
INFO [02-18|20:06:27.987] Looking for peers                        peercount=5 tried=68  static=8
ERROR[02-18|20:06:34.668] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: <nil>, Engine: unknown}

Number: 1
Hash: 0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6

Error: extra-data too long: 97 > 32
##############################
 
WARN [02-18|20:06:34.687] Synchronisation failed, dropping peer    peer=b49a8e88f94dd286 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
INFO [02-18|20:06:37.990] Looking for peers                        peercount=4 tried=92  static=8
ERROR[02-18|20:06:45.803] 
########## BAD BLOCK #########
Chain config: {ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: <nil>, Engine: unknown}

Number: 1
Hash: 0x04055304e432294a65ff31069c4d3092ff8b58f009cdb50eba5351e0332ad0f6

Error: extra-data too long: 97 > 32
##############################
 
WARN [02-18|20:06:45.803] Synchronisation failed, dropping peer    peer=cc0a1a26d9e3f1d3 err="retrieved hash chain is invalid: extra-data too long: 97 > 32"
INFO [02-18|20:06:48.121] Looking for peers                        peercount=2 tried=112 static=8
INFO [02-18|20:06:58.303] Looking for peers                        peercount=2 tried=89  static=8

#### Backtrace

````
[backtrace]
````

**Comment by guagualvcha** [comment]
Hi, did you use the binary of this repo or build from this repo? The logs:
```
Chain config: {ChainID: 56 Homestead: 0 DAO: DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, YOLO v2: , Engine: unknown}
```
shows that the engine is unknown, I guess you are not using the bsc client.

**Comment by livenodescoin** [comment]
I think you have another version of geth in your environment. 
Try to start geth with command `./geth` and not just `geth`

**Comment by quato** [comment]
I think you have another version of geth in your environment. 
Try to start geth with command `./geth` and not just `geth`

**Comment by ceds** [comment]
I'm having the same problem.  For test purposes I built the source in Windows and then running from Windows.  First the config file did not work, so had to create a new one and migrated the settings over.  But still getting the same error messages
