### ISSUE TITLE
BSC Chain not Starting - Freezes before anything happens

### ISSUE THREAD

**Issue by ceds** [binance-chain/bsc#83]
#### System information

Geth version: 1.06
OS & Version: Ubuntu 18.04

#### Expected behaviour

As per documentation:

https://docs.binance.org/smart-chain/developer/fullnode.html

./geth_linux --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof

Starting the node should start without any problems

#### Actual behaviour

Node does not start.  Get stucks at "Starting Geth on Ethereum mainnet and then an error "Smartcard socket not found".  After that nothing happens.

#### Steps to reproduce the behaviour

Follow instructions exactly as per documentation:

https://docs.binance.org/smart-chain/developer/fullnode.html

"geth" is replaced with "./geth_linux" otherwise it does not work

root@ugogvirginia2:~/bsc# ./geth_linux --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof
INFO [02-21|01:30:55.524] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [02-21|01:30:55.524] Starting Geth on Ethereum mainnet...
INFO [02-21|01:30:55.524] Bumping default cache on mainnet         provided=1024 updated=4096
INFO [02-21|01:30:55.524] Enabling metrics collection
INFO [02-21|01:30:55.526] Maximum peer count                       ETH=200 LES=0 total=200
INFO [02-21|01:30:55.526] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"

**Comment by guagualvcha** [comment]
Hi, please check the log. It is `node/bsc.log`, the sync log is on the file, not the console.

**Comment by ceds** [comment]
> Hi, please check the log. It is `node/bsc.log`, the sync log is on the file, not the console.

Aaaah interesting... the log shows it is running as expected showing "imported new chain segment".  How can I get these messages to show in the console itself as with Ethereum GETH?  I'm used to running Ethereum GETH nodes where the messages are displayed in the console as well.

**Comment by guagualvcha** [comment]
Just edit the `config.toml`, and at the bottom of the file, delete the log config.
