### ISSUE TITLE
Fatal: Error starting protocol stack: database contains incompatible genesis

### ISSUE THREAD

**Issue by pion33r** [binance-chain/bsc#85]
Error while starting testnet node ropsten or rinkeby

Fatal: Error starting protocol stack: database contains incompatible genesis (have 6d3c66c5357ec91d5c43af47e234a939b22557cbb552dc45bebbceeed90fbe34, new 41941023680923e0fe4d74a34bdac8141f2540e3ae90623718e47d66d1ca4a2d)

**Comment by huangsuyu** [comment]
please use genesis file for Binance Smart chain testnet instead.
