### ISSUE TITLE
Problem with account after triggering EVM error

### ISSUE THREAD

**Issue by oikos1** [binance-chain/bsc#87]
Hello,

After triggering a **[evm: max code size exceeded]** error when trying to deploy a contract, my account seems to be unable to execute any contract deployment or function invocation.

The transaction that caused the issue:
[https://testnet.bscscan.com/tx/0x4928fcc277a919e12631bc4aa95de9de72fbbcfd5dbd75ebbb09fac98556a54b
](https://testnet.bscscan.com/tx/0x4928fcc277a919e12631bc4aa95de9de72fbbcfd5dbd75ebbb09fac98556a54b
)

This is the account involved:
[https://testnet.bscscan.com/address/0xcd5b38549139e4cf0d9322c4f1c802f89901227b](https://testnet.bscscan.com/address/0xcd5b38549139e4cf0d9322c4f1c802f89901227b)

**Comment by oikos1** [comment]
Experiencing the same problem with another account, this time without triggering any EVM. Example transactions that never get mined:

https://testnet.bscscan.com/tx/0xa917e21db4e686076cb94b75058a8ae41f8e19474fcb8d24e0dcba6fc8608ed9
https://testnet.bscscan.com/tx/0xe312d5024aa54b60571247435c0c9710a8b29b6a868043231342898439b523eb

**Comment by guagualvcha** [comment]
@oikos1 since it is transaction that can not seen on bscscan and never seen by us, will kindly close this issue.

**Comment by oikos1** [comment]
@guagualvcha Actually the following transaction can be seen on bscscan:

https://testnet.bscscan.com/tx/0x4928fcc277a919e12631bc4aa95de9de72fbbcfd5dbd75ebbb09fac98556a54b
