### ISSUE TITLE
Looking for docker images hub for each released tag

### ISSUE THREAD

**Issue by longhoangwkm** [binance-chain/bsc#88]
Hi there,

If possible, I would like we have dockerhub repo for each released tag like ethereum/go-ethereum which have https://hub.docker.com/r/ethereum/client-go/tags?page=1&ordering=last_updated. It more easier to upgrade k8s BSC node. Many thanks!

**Comment by guagualvcha** [comment]
@longhoangwkm  Will working on this and update here.

**Comment by corymsmith** [comment]
Any updates on this @longhoangwkm @guagualvcha?

**Comment by kozhevnikov-peter** [comment]
@guagualvcha

Our team is integrating BSC with [WAVES](https://waves.exchange/). We really need docker image. We can help create automatic configuration (for DockerHub). Please contact us.

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
