### ISSUE TITLE
[New Feature Request] Add flag for binance network

### ISSUE THREAD

**Issue by longhoangwkm** [binance-chain/bsc#92]
Hi team,

If possible I would like to have a network flag for binance smart chain testnet network like  `geth --bsctestnet` (like go-ethereum test network flags: ` geth --goerli ` or ` geth --rinkeby`). User no need to download `config.toml` and `genesis.json` files to run. We just set up it before and check flag to switch network. It is easier to run a node on docker container. 

Please comment on your thoughts. Thanks in advance!

**Comment by BinanceG11** [comment]
We have responded to the question and will proceed to close the case as we didn't get any additional question after 3days.  Please proceed to join our Discord channel for more discussion at https://discord.com/invite/YPDsUqcwR8
