### ISSUE TITLE
Purging old data from geth/free up disk space, purge specific data

### ISSUE THREAD

**Issue by Code0x2** [binance-chain/bsc#93]
Hello BSC devs, I have been running a BSC node from a few weeks ago, and I have noticed that the disk usage is rapidly increasing. Upon initial sync, geth only used up ~50gb of disk space. Today it is using over 125gb of disk space. This could be a problem if it continues expanding at this rate. Is there a way to limit this usage or purge off unneeded data?

I've also noticed lately there has been loads of CHI Gastokens being minted at ~1 gwei gas price and filling up a lot of blocks. Is there a way to make my node purge all the data at a specific contract to free up space?

**Comment by profforg** [comment]
Same problem :(
I've tried to apply this solution (https://github.com/ethereum/go-ethereum/issues/15797#issuecomment-357030043), to have fresh and clean data dir, but it's not working:
```
WARN [03-02|23:39:57.068] Synchronisation failed, dropping peer    peer=local err="retrieved hash chain is invalid"
WARN [03-02|23:39:57.068] Downloader wants to drop peer, but peerdrop-function is not set peer=local
```

**Comment by Code0x2** [comment]
> Same problem :(
> I've tried to apply this solution ([ethereum/go-ethereum#15797 (comment)](https://github.com/ethereum/go-ethereum/issues/15797#issuecomment-357030043)), to have fresh and clean data dir, but it's not working:
> 
> ```
> WARN [03-02|23:39:57.068] Synchronisation failed, dropping peer    peer=local err="retrieved hash chain is invalid"
> WARN [03-02|23:39:57.068] Downloader wants to drop peer, but peerdrop-function is not set peer=local
> ```

That stuff is for geth 1.8/1.9.  bsc-geth likely doesnt have that yet

**Comment by djtjc** [comment]
Same problem. I tried setting `--datadir.ancient` but my node directory is still filling up rapidly with hundreds of thousands of `ldb` files (I'm assuming one for each block)?

All I want to use the node for is seeing incoming pending transactions, so I really don't need to have all these files stored.

**Comment by luucasbruno** [comment]
can I get the same effect manually somehow? I'd like to shrink ancient data too.

**Comment by guagualvcha** [comment]
The latest bsc version already support prune data, will kindly close this.
