### ISSUE TITLE
Fail to connect BSC testnet node

### ISSUE THREAD

**Issue by readygo586** [binance-chain/bsc#94]
when I try to connect https://data-seed-prebsc-1-s1.binance.org:8545 by Go,  the following error happens
" Post "https://18.182.214.188:8545": x509: cannot validate certificate for 18.182.214.188 because it doesn't contain any IP SANs" 

but when I use curl to connect the same node, it works
`curl -X POST -H 'content-type:application/json'  --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'  https://data-seed-prebsc-1-s1.binance.org:8545
{"jsonrpc":"2.0","id":1,"result":"0x65f8f5"}`

What should I do to fix this problem?

**Comment by longhoangwkm** [comment]
Could you show Go code ?!

**Comment by jhonzy0928** [comment]
I met the same problem. Can you tell me how you solved it?
