### ISSUE TITLE
Readme port / sync clarification.

### ISSUE THREAD

**Issue by kutysam** [binance-chain/bsc#95]
Readme states this.
> Note: The default p2p port is 30311 and the RPC port is 8575 which is different from Ethereum.

However, i'm not too sure if this is specific for testnet?
- (testnet config.toml states 30311 and 8575)
- (mainnet config.toml states 30311 and 8545)

Writing this in issues as it needs clarity. (Though there is a header testnet right above the note, port 30311 reflects on mainnet too)

-----

Additionally under https://docs.binance.org/smart-chain/developer/fullnode.html
```
Settings
Sync Mode
Fast Sync
The default sync mode. Synchronizes a full node doing a fast synchronization by downloading the entire state database, requesting the headers first, and filling in block bodies and receipts afterward. Once the fast sync reaches the best block of the Binance Smart Chain network, it switches to full sync mode.
```

The default mode in the toml is actually `full` sync. Not sure if its intended too.

**Comment by guagualvcha** [comment]
@kutysam  Thanks for reporting this. 
1. The RPC port should be 8575, will correct this.
2. And for the sync mode in config.toml, it won't take effect actually, it looks confusing and I will delete it.

**Comment by kutysam** [comment]
Actually i think the syncmode will indeed take effect.

> @kutysam Thanks for reporting this.
> 
> 1. The RPC port should be 8575, will correct this.
> 2. And for the sync mode in config.toml, it won't take effect actually, it looks confusing and I will delete it.
> 
> Thanks again for reporting this valuable issue.

**Comment by kutysam** [comment]
Additionally, just curious, is there any reason why the following are set in the config.toml?
- txpool.nolocals
- txpool.pricelimit(1000000000) --> default is 1.

**Comment by guagualvcha** [comment]
closing this, since it is been fixed.
