### ISSUE TITLE
Can not start geth

### ISSUE THREAD

**Issue by olchaeng** [binance-chain/bsc#97]
Hi. I have a problem starting geth of bsc on testnet.(same problem at mainnet config) Installation looks find but execution is stuck. please help me. 

#### System information

Geth version:
  Version: 1.0.6
  Git Commit: b7cff76c9ade0d7eb87c090961b5fb16609df18c
  Git Commit Date: 20210225
  Architecture: amd64
  Protocol Versions: [65 64 63]
  Go Version: go1.16
  Operating System: linux

OS & Version: windows wsl2 ubuntu 20.4

#### Expected behaviour

showing log of syncing of blocks.

#### Actual behaviour

syncing block and working well.

#### Steps to reproduce the behaviour

I read installation of fullnode guide(https://docs.binance.org/smart-chain/developer/fullnode.html). I followed the indication. All process was fine till facing the error.

#### Backtrace

````
ubuntu1@DESKTOP-EBK4HLR:~/bsc$ ./build/bin/geth --config ./config.toml --datadir ./node --pprofaddr 0.0.0.0 --metrics --pprof --verbosity 5
INFO [03-02|18:19:41.831] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [03-02|18:19:41.832] Starting Geth on Ethereum mainnet...
INFO [03-02|18:19:41.832] Bumping default cache on mainnet         provided=1024 updated=4096
DEBUG[03-02|18:19:41.832] Sanitizing Go's GC trigger               percent=25
INFO [03-02|18:19:41.832] Enabling metrics collection
INFO [03-02|18:19:41.833] Maximum peer count                       ETH=50 LES=0 total=50
INFO [03-02|18:19:41.833] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
DEBUG[03-02|18:19:41.834] FS scan times                            list=11.4µs set=200ns diff=700ns
DEBUG[03-02|18:19:41.834] FS scan times                            list=5.7µs  set=200ns diff=200ns
TRACE[03-02|18:19:41.834] Started watching keystore folder         path=/home/ubuntu1/bsc/node/keystore

````

but process is not going.

**Comment by longhoangwkm** [comment]
Hi @olchaeng, Log in another place if you notice log config in `config.toml` 
```
[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info" 
```
You can monitor the log from /node/bsc.log by default. If you wanna see log from geth cmd, Let's remove `[Node.LogConfig]` section.

**Comment by hbcg0323** [comment]
OK, I have done.

**Comment by bitbd83** [comment]
better remove 
[Node.LogConfig]
FileRoot = ""
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info" 

from config.toml
